### ISSUE TITLE
建议写清楚具体版本号

### ISSUE THREAD

**Issue by parcool** [li-xiaojun/XPopup#1]
implementation 'com.lxj:xpopup:latest release'这样不支持离线模式啊，给个确定的版本号吧？

**Comment by li-xiaojun** [comment]
抱歉，不小心把版本号给删除了，具体版本号在README文件的最上方。

![image](https://user-images.githubusercontent.com/4426715/50319935-e61a4480-0504-11e9-90b2-fbc8d7da51a6.png)

**Comment by parcool** [comment]
@li-xiaojun 神速更新啊！另外有个问题：`error: resource android:attr/fontVariationSettings not found
"error: resource android:attr/ttcIndex not found."`咋回事？

**Comment by li-xiaojun** [comment]
我刚才确认了一下类库的资源引用，确保没有问题。这个问题应该是你自己项目中的问题，请检查一下。如果仍然有问题，可以将项目打包发我一下看看。我的QQ：16167479

**Comment by parcool** [comment]
找到问题了，是v4包引用的版本不同导致的，加这种
`
configurations.all {
    resolutionStrategy.force 'com.android.support:support-v4:27.1.1'
}
`
都不行。

**Comment by li-xiaojun** [comment]
可以发下你项目的Gradle中完整的依赖信息吗

**Comment by parcool** [comment]
+--- project :livenesslib
|    \--- project :basecore
|         +--- com.android.support:appcompat-v7:27.1.1
|         |    +--- com.android.support:support-annotations:27.1.1 -> 28.0.0
|         |    +--- com.android.support:support-core-utils:27.1.1 -> 28.0.0
|         |    |    +--- com.android.support:support-annotations:28.0.0
|         |    |    +--- com.android.support:support-compat:28.0.0
|         |    |    |    +--- com.android.support:support-annotations:28.0.0
|         |    |    |    +--- com.android.support:collections:28.0.0
|         |    |    |    |    \--- com.android.support:support-annotations:28.0.0
|         |    |    |    +--- android.arch.lifecycle:runtime:1.1.1
|         |    |    |    |    +--- android.arch.lifecycle:common:1.1.1
|         |    |    |    |    |    \--- com.android.support:support-annotations:26.1.0 -> 28.0.0
|         |    |    |    |    +--- android.arch.core:common:1.1.1
|         |    |    |    |    |    \--- com.android.support:support-annotations:26.1.0 -> 28.0.0
|         |    |    |    |    \--- com.android.support:support-annotations:26.1.0 -> 28.0.0
|         |    |    |    \--- com.android.support:versionedparcelable:28.0.0
|         |    |    |         +--- com.android.support:support-annotations:28.0.0
|         |    |    |         \--- com.android.support:collections:28.0.0 (*)
|         |    |    +--- com.android.support:documentfile:28.0.0
|         |    |    |    \--- com.android.support:support-annotations:28.0.0
|         |    |    +--- com.android.support:loader:28.0.0
|         |    |    |    +--- com.android.support:support-annotations:28.0.0
|         |    |    |    +--- com.android.support:support-compat:28.0.0 (*)
|         |    |    |    +--- android.arch.lifecycle:livedata:1.1.1
|         |    |    |    |    +--- android.arch.core:runtime:1.1.1
|         |    |    |    |    |    +--- com.android.support:support-annotations:26.1.0 -> 28.0.0
|         |    |    |    |    |    \--- android.arch.core:common:1.1.1 (*)
|         |    |    |    |    +--- android.arch.lifecycle:livedata-core:1.1.1
|         |    |    |    |    |    +--- android.arch.lifecycle:common:1.1.1 (*)
|         |    |    |    |    |    +--- android.arch.core:common:1.1.1 (*)
|         |    |    |    |    |    \--- android.arch.core:runtime:1.1.1 (*)
|         |    |    |    |    \--- android.arch.core:common:1.1.1 (*)
|         |    |    |    \--- android.arch.lifecycle:viewmodel:1.1.1
|         |    |    |         \--- com.android.support:support-annotations:26.1.0 -> 28.0.0
|         |    |    +--- com.android.support:localbroadcastmanager:28.0.0
|         |    |    |    \--- com.android.support:support-annotations:28.0.0
|         |    |    \--- com.android.support:print:28.0.0
|         |    |         \--- com.android.support:support-annotations:28.0.0
|         |    +--- com.android.support:support-fragment:27.1.1
|         |    |    +--- com.android.support:support-compat:27.1.1 -> 28.0.0 (*)
|         |    |    +--- com.android.support:support-core-ui:27.1.1 -> 28.0.0
|         |    |    |    +--- com.android.support:support-annotations:28.0.0
|         |    |    |    +--- com.android.support:support-compat:28.0.0 (*)
|         |    |    |    +--- com.android.support:support-core-utils:28.0.0 (*)
|         |    |    |    +--- com.android.support:customview:28.0.0
|         |    |    |    |    +--- com.android.support:support-annotations:28.0.0
|         |    |    |    |    \--- com.android.support:support-compat:28.0.0 (*)
|         |    |    |    +--- com.android.support:viewpager:28.0.0
|         |    |    |    |    +--- com.android.support:support-annotations:28.0.0
|         |    |    |    |    +--- com.android.support:support-compat:28.0.0 (*)
|         |    |    |    |    \--- com.android.support:customview:28.0.0 (*)
|         |    |    |    +--- com.android.support:coordinatorlayout:28.0.0
|         |    |    |    |    +--- com.android.support:support-annotations:28.0.0
|         |    |    |    |    +--- com.android.support:support-compat:28.0.0 (*)
|         |    |    |    |    \--- com.android.support:customview:28.0.0 (*)
|         |    |    |    +--- com.android.support:drawerlayout:28.0.0
|         |    |    |    |    +--- com.android.support:support-annotations:28.0.0
|         |    |    |    |    +--- com.android.support:support-compat:28.0.0 (*)
|         |    |    |    |    \--- com.android.support:customview:28.0.0 (*)
|         |    |    |    +--- com.android.support:slidingpanelayout:28.0.0
|         |    |    |    |    +--- com.android.support:support-annotations:28.0.0
|         |    |    |    |    +--- com.android.support:support-compat:28.0.0 (*)
|         |    |    |    |    \--- com.android.support:customview:28.0.0 (*)
|         |    |    |    +--- com.android.support:interpolator:28.0.0
|         |    |    |    |    \--- com.android.support:support-annotations:28.0.0
|         |    |    |    +--- com.android.support:swiperefreshlayout:28.0.0
|         |    |    |    |    +--- com.android.support:support-annotations:28.0.0
|         |    |    |    |    +--- com.android.support:support-compat:28.0.0 (*)
|         |    |    |    |    \--- com.android.support:interpolator:28.0.0 (*)
|         |    |    |    +--- com.android.support:asynclayoutinflater:28.0.0
|         |    |    |    |    +--- com.android.support:support-annotations:28.0.0
|         |    |    |    |    \--- com.android.support:support-compat:28.0.0 (*)
|         |    |    |    \--- com.android.support:cursoradapter:28.0.0
|         |    |    |         \--- com.android.support:support-annotations:28.0.0
|         |    |    +--- com.android.support:support-core-utils:27.1.1 -> 28.0.0 (*)
|         |    |    +--- com.android.support:support-annotations:27.1.1 -> 28.0.0
|         |    |    +--- android.arch.lifecycle:livedata-core:1.1.0 -> 1.1.1 (*)
|         |    |    \--- android.arch.lifecycle:viewmodel:1.1.0 -> 1.1.1 (*)
|         |    +--- com.android.support:support-vector-drawable:27.1.1
|         |    |    +--- com.android.support:support-annotations:27.1.1 -> 28.0.0
|         |    |    \--- com.android.support:support-compat:27.1.1 -> 28.0.0 (*)
|         |    \--- com.android.support:animated-vector-drawable:27.1.1
|         |         +--- com.android.support:support-vector-drawable:27.1.1 (*)
|         |         \--- com.android.support:support-core-ui:27.1.1 -> 28.0.0 (*)
|         +--- com.android.support:support-v4:27.1.1
|         |    +--- com.android.support:support-compat:27.1.1 -> 28.0.0 (*)
|         |    +--- com.android.support:support-media-compat:27.1.1
|         |    |    +--- com.android.support:support-annotations:27.1.1 -> 28.0.0
|         |    |    \--- com.android.support:support-compat:27.1.1 -> 28.0.0 (*)
|         |    +--- com.android.support:support-core-utils:27.1.1 -> 28.0.0 (*)
|         |    +--- com.android.support:support-core-ui:27.1.1 -> 28.0.0 (*)
|         |    \--- com.android.support:support-fragment:27.1.1 (*)
|         +--- com.android.support:design:27.1.1
|         |    +--- com.android.support:support-v4:27.1.1 (*)
|         |    +--- com.android.support:appcompat-v7:27.1.1 (*)
|         |    +--- com.android.support:recyclerview-v7:27.1.1 -> 28.0.0
|         |    |    +--- com.android.support:support-annotations:28.0.0
|         |    |    +--- com.android.support:support-compat:28.0.0 (*)
|         |    |    \--- com.android.support:support-core-ui:28.0.0 (*)
|         |    \--- com.android.support:transition:27.1.1
|         |         +--- com.android.support:support-annotations:27.1.1 -> 28.0.0
|         |         \--- com.android.support:support-compat:27.1.1 -> 28.0.0 (*)
|         +--- com.android.support:cardview-v7:27.1.1 -> 28.0.0
|         |    \--- com.android.support:support-annotations:28.0.0
|         +--- com.android.support.constraint:constraint-layout:1.1.3
|         |    \--- com.android.support.constraint:constraint-layout-solver:1.1.3
|         +--- junit:junit:4.12
|         |    \--- org.hamcrest:hamcrest-core:1.3
|         +--- io.reactivex.rxjava2:rxjava:2.1.7 -> 2.1.16
|         |    \--- org.reactivestreams:reactive-streams:1.0.2
|         +--- io.reactivex.rxjava2:rxandroid:2.0.1
|         |    \--- io.reactivex.rxjava2:rxjava:2.0.1 -> 2.1.16 (*)
|         +--- com.hwangjr.rxbus:rxbus:1.0.5
|         |    +--- io.reactivex:rxjava:1.1.9
|         |    +--- io.reactivex:rxandroid:1.2.1
|         |    |    \--- io.reactivex:rxjava:1.1.6 -> 1.1.9
|         |    +--- com.jakewharton.timber:timber:4.3.0
|         |    \--- com.android.support:support-annotations:24.2.0 -> 28.0.0
|         +--- com.trello.rxlifecycle2:rxlifecycle-components:2.0.1
|         |    +--- com.trello.rxlifecycle2:rxlifecycle-android:2.0.1
|         |    |    +--- com.trello.rxlifecycle2:rxlifecycle:2.0.1
|         |    |    |    +--- io.reactivex.rxjava2:rxjava:2.0.1 -> 2.1.16 (*)
|         |    |    |    \--- com.google.code.findbugs:jsr305:3.0.1
|         |    |    +--- io.reactivex.rxjava2:rxandroid:2.0.1 (*)
|         |    |    \--- com.android.support:support-annotations:25.0.0 -> 28.0.0
|         |    +--- io.reactivex.rxjava2:rxjava:2.0.1 -> 2.1.16 (*)
|         |    \--- com.android.support:appcompat-v7:25.0.0 -> 27.1.1 (*)
|         +--- com.jakewharton.rxbinding2:rxbinding:2.0.0
|         |    +--- io.reactivex.rxjava2:rxjava:2.0.2 -> 2.1.16 (*)
|         |    +--- io.reactivex.rxjava2:rxandroid:2.0.0 -> 2.0.1 (*)
|         |    \--- com.android.support:support-annotations:25.1.1 -> 28.0.0
|         +--- com.jakewharton.rxbinding2:rxbinding-support-v4:2.0.0
|         |    +--- com.jakewharton.rxbinding2:rxbinding:2.0.0 (*)
|         |    \--- com.android.support:support-core-ui:25.1.1 -> 28.0.0 (*)
|         +--- com.jakewharton.rxbinding2:rxbinding-appcompat-v7:2.0.0
|         |    +--- com.jakewharton.rxbinding2:rxbinding:2.0.0 (*)
|         |    \--- com.android.support:appcompat-v7:25.1.1 -> 27.1.1 (*)
|         +--- com.jakewharton.rxbinding2:rxbinding-design:2.0.0
|         |    +--- com.jakewharton.rxbinding2:rxbinding:2.0.0 (*)
|         |    \--- com.android.support:design:25.1.1 -> 27.1.1 (*)
|         +--- com.jakewharton.rxbinding2:rxbinding-recyclerview-v7:2.0.0
|         |    +--- com.jakewharton.rxbinding2:rxbinding:2.0.0 (*)
|         |    \--- com.android.support:recyclerview-v7:25.1.1 -> 28.0.0 (*)
|         +--- com.github.tbruyelle:rxpermissions:0.10.2
|         |    +--- io.reactivex.rxjava2:rxjava:2.1.16 (*)
|         |    +--- com.android.support:support-annotations:27.1.1 -> 28.0.0
|         |    \--- com.android.support:support-fragment:27.1.1 (*)
|         +--- com.squareup.retrofit2:retrofit:2.4.0
|         |    \--- com.squareup.okhttp3:okhttp:3.10.0
|         |         \--- com.squareup.okio:okio:1.14.0
|         +--- com.squareup.retrofit2:converter-gson:2.4.0
|         |    +--- com.squareup.retrofit2:retrofit:2.4.0 (*)
|         |    \--- com.google.code.gson:gson:2.8.2
|         +--- com.squareup.retrofit2:adapter-rxjava2:2.4.0
|         |    +--- com.squareup.retrofit2:retrofit:2.4.0 (*)
|         |    \--- io.reactivex.rxjava2:rxjava:2.0.0 -> 2.1.16 (*)
|         +--- com.squareup.okhttp3:logging-interceptor:3.9.1
|         |    \--- com.squareup.okhttp3:okhttp:3.9.1 -> 3.10.0 (*)
|         +--- com.github.bumptech.glide:glide:3.7.0
|         +--- com.google.code.gson:gson:2.8.0 -> 2.8.2
|         +--- com.android.support:multidex:1.0.2
|         +--- com.orhanobut:logger:2.2.0
|         |    \--- com.android.support:support-annotations:27.1.0 -> 28.0.0
|         +--- com.github.florent37:viewanimator:1.0.5
|         |    +--- com.android.support:support-v4:23.3.0 -> 27.1.1 (*)
|         |    +--- com.android.support:appcompat-v7:23.3.0 -> 27.1.1 (*)
|         |    \--- com.android.support:support-annotations:23.3.0 -> 28.0.0
|         +--- devlight.io:navigationtabbar:1.2.5
|         |    \--- com.android.support:design:23.2.1 -> 27.1.1 (*)
|         +--- com.flyco.tablayout:FlycoTabLayout_Lib:2.1.2
|         +--- com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.30
|         +--- com.contrarywind:Android-PickerView:4.1.6
|         |    \--- com.contrarywind:wheelview:4.0.8
|         +--- com.zhihu.android:matisse:0.5.1
|         |    +--- com.android.support:support-v4:27.1.1 (*)
|         |    +--- com.android.support:appcompat-v7:27.1.1 (*)
|         |    +--- com.android.support:support-annotations:27.1.1 -> 28.0.0
|         |    +--- com.android.support:recyclerview-v7:27.1.1 -> 28.0.0 (*)
|         |    \--- it.sephiroth.android.library.imagezoom:library:1.0.4
|         |         \--- it.sephiroth.android.library.easing:library:1.0.2
|         +--- cn.jzvd:jiaozivideoplayer:6.3.1
|         +--- com.github.chrisbanes:PhotoView:2.0.0
|         |    \--- com.android.support:support-core-utils:25.3.0 -> 28.0.0 (*)
|         +--- com.github.zyyoona7:EasyPopup:1.1.2
|         |    \--- com.android.support:support-compat:27.1.1 -> 28.0.0 (*)
|         +--- com.github.lzyzsd:jsbridge:1.0.4
|         +--- me.yokeyword:indexablerecyclerview:1.3.0
|         |    +--- com.github.promeg:tinypinyin:2.0.3
|         |    |    \--- org.ahocorasick:ahocorasick:0.3.0
|         |    \--- com.github.promeg:tinypinyin-lexicons-android-cncity:2.0.3
|         |         \--- com.github.promeg:tinypinyin-android-asset-lexicons:2.0.3
|         |              \--- com.github.promeg:tinypinyin:2.0.3 (*)
|         +--- com.hyman:flowlayout-lib:1.1.2
|         +--- com.github.Othershe:NiceImageView:1.0.1
|         |    \--- com.android.support:appcompat-v7:27.1.1 (*)
|         +--- org.greenrobot:greendao:3.2.0
|         |    \--- org.greenrobot:greendao-api:3.2.0
|         +--- org.greenrobot:greendao-generator:3.2.0
|         |    \--- org.freemarker:freemarker:2.3.23
|         +--- cn.yipianfengye.android:zxing-library:2.2
|         |    +--- com.android.support:appcompat-v7:25.1.1 -> 27.1.1 (*)
|         |    \--- com.android.support:support-v4:25.1.1 -> 27.1.1 (*)
|         +--- com.android.support:palette-v7:27.1.1
|         |    +--- com.android.support:support-compat:27.1.1 -> 28.0.0 (*)
|         |    \--- com.android.support:support-core-utils:27.1.1 -> 28.0.0 (*)
|         +--- com.github.promeg:tinypinyin:2.0.3 (*)
|         +--- com.github.promeg:tinypinyin-lexicons-android-cncity:2.0.3 (*)
|         +--- cn.finalteam.rxgalleryfinal:library:1.1.2
|         |    +--- io.reactivex.rxjava2:rxandroid:2.0.1 (*)
|         |    +--- io.reactivex.rxjava2:rxjava:2.1.0 -> 2.1.16 (*)
|         |    +--- com.yalantis:ucrop:2.2.0
|         |    |    +--- com.android.support:appcompat-v7:24.2.0 -> 27.1.1 (*)
|         |    |    \--- com.squareup.okhttp3:okhttp:3.4.1 -> 3.10.0 (*)
|         |    +--- com.android.support:recyclerview-v7:25.3.1 -> 28.0.0 (*)
|         |    +--- com.android.support:appcompat-v7:25.3.1 -> 27.1.1 (*)
|         |    \--- com.android.support:exifinterface:25.3.1
|         |         \--- com.android.support:support-annotations:25.3.1 -> 28.0.0
|         \--- com.lxj:xpopup:0.0.5
|              +--- com.android.support:appcompat-v7:28.0.0 -> 27.1.1 (*)
|              +--- com.android.support:cardview-v7:28.0.0 (*)
|              +--- com.android.support:recyclerview-v7:28.0.0 (*)
|              \--- com.lxj:easyadapter:0.0.8
|                   +--- com.android.support:appcompat-v7:28.0.0 -> 27.1.1 (*)
|                   \--- com.android.support:recyclerview-v7:28.0.0 (*)
+--- com.tencent.mm.opensdk:wechat-sdk-android-without-mta:1.3.4
+--- com.ruffian.library:RWidgetHelper:1.0.1
|    \--- com.android.support:appcompat-v7:26.0.0-alpha1 -> 27.1.1 (*)

**Comment by li-xiaojun** [comment]
@parcool  v4依赖一般不要写，buildToolVersion也不要写，studio会根据已经安装的sdk去选择合适的。如果写了，可能会出现冲突

**Comment by parcool** [comment]
还是贴个能用的办法：
`
implementation ('com.lxj:xpopup:0.0.5') {
        exclude group: 'support-v4'
        exclude module: 'appcompat-v7'
        exclude module: 'cardview-v7'
        exclude module: 'recyclerview-v7'
    }
`

**Comment by parcool** [comment]
@li-xiaojun 老项目，依赖这些不敢去改了。麻烦。。。

**Comment by li-xiaojun** [comment]
@parcool 理解，如果再遇到lib冲突，就直接用 `exclude xxx`大法就行。
