### ISSUE TITLE
一加手机不出滚动条

### ISSUE THREAD

**Issue by yanfulei** [li-xiaojun/XPopup#100]
'com.lxj:xpopup:1.6.5'

**Comment by yanfulei** [comment]
new XPopup.Builder(context)
                .atView(view)  // 依附于所点击的View，内部会自动判断在上方或者下方显示
                .moveUpToKeyboard(false)
                .asAttachList(strArray2, new int[]{}, (position, text) -> viewInteface.click(position, text))
                .show();
![image](https://user-images.githubusercontent.com/13723893/55337796-ea75d680-54d1-11e9-9421-9e8afddef23d.png)

**Comment by li-xiaojun** [comment]
@yanfulei 
这个弹窗高度过高时超出了window区域，导致无法点击。这个bug和滚动条的问题我下个版本修复。

**Comment by li-xiaojun** [comment]
@yanfulei 
最新版1.6.6已经修复这个问题，请更新试试。
