### ISSUE TITLE
全屏状态下不走ondissmiss方法

### ISSUE THREAD

**Issue by billdizl** [li-xiaojun/XPopup#1001]
**XPopup版本**
如2.8.12

**描述你的问题**
最好能上代码截图和问题截图
 if (!TextUtils.isEmpty(imageOfLoginSuccess)) {
            if (userSuccessDialog == null) {
                userSuccessDialog = XPopup.Builder(this)
                    .customHostLifecycle(lifecycle)
                    .dismissOnTouchOutside(false)
                    .dismissOnBackPressed(false)
                    .isViewMode(false) //开启View实现
                    .isDestroyOnDismiss(false)
                    .isLightStatusBar(true)
                    .popupAnimation(PopupAnimation.ScrollAlphaFromBottom)
                    .setPopupCallback(object : XPopupCallback{
                        override fun onCreated(popupView: BasePopupView?) {

                        }

                        override fun beforeShow(popupView: BasePopupView?) {

                        }

                        override fun onShow(popupView: BasePopupView?) {
                            KlogUtils.e("弹窗显示")
                            AmazonEventNameUtils.pitHomeShowDilaog(AmazonEventKeyConstant.APP_PUSH_CONSTANT,AmazonEventKeyConstant.HOMEPAGER_HOME_CONSTANT,AmazonEventKeyConstant.HOME_PAGER_CONCENT_CONSTANT,"", "true");
                        }

                        override fun onDismiss(popupView: BasePopupView?) {
                            KlogUtils.e("弹窗关闭")
                            AmazonEventNameUtils.pitHomeShowDilaog(AmazonEventKeyConstant.APP_PUSH_CONSTANT,AmazonEventKeyConstant.HOMEPAGER_HOME_CONSTANT,AmazonEventKeyConstant.HOME_PAGER_CONCENT_CONSTANT,"", "false");
                        }

                        override fun beforeDismiss(popupView: BasePopupView?) {

                        }

                        override fun onBackPressed(popupView: BasePopupView?): Boolean {
                            return false
                        }

                        override fun onKeyBoardStateChanged(
                            popupView: BasePopupView?,
                            height: Int
                        ) {

                        }

                        override fun onDrag(
                            popupView: BasePopupView?,
                            value: Int,
                            percent: Float,
                            upOrLeft: Boolean
                        ) {

                        }

                        override fun onClickOutside(popupView: BasePopupView?) {

                        }

                    })
                    .asCustom(
                        FullScarnOfLoginSuccessDialog(
                            this,
                            object : PopConfirmAndCancelListener {
                                override fun dialogCancel(mBasePop: BasePopupView?) {
                                    mBasePop?.dismiss()
                                    finish()
                                }

                                override fun dialogConfirm(mBasePop: BasePopupView?) {
                                    if (!UIUitls.isNotificationEnabled(this@LoginBtfeelActivity)) {
                                        UIUitls.gotoSet(this@LoginBtfeelActivity)
                                        //mBasePop?.dismiss()
                                    }
                                }
                            },imageOfLoginSuccess)
                    ) as FullScarnOfLoginSuccessDialog
            } else {
                userSuccessDialog?.setImageLoad(imageOfLoginSuccess)
            }
            userSuccessDialog?.show()
        } else {
            finish()
        }
描述:
dialogCancel()方法下dissmiss 是走onDismiss方法的,但是我在别的地方调用
 if (userSuccessDialog != null && userSuccessDialog!!.isShow) {
            userSuccessDialog?.dismiss()
            AmazonEventNameUtils.pitHomeShowDilaog(AmazonEventKeyConstant.APP_PUSH_CONSTANT,AmazonEventKeyConstant.HOMEPAGER_HOME_CONSTANT,AmazonEventKeyConstant.HOME_PAGER_CONCENT_CONSTANT,"", "false");
            finish()
        }

这时候不走onDismiss方法

**Comment by li-xiaojun** [comment]
dismiss()后activity立即finish肯定不走，来不及走就没了。你可以这样写:
```
userSuccessDialog.dismissWith {
    //do something
    finish()
}
```
