### ISSUE TITLE
底部输入法弹窗有间距

### ISSUE THREAD

**Issue by liweiGe** [li-xiaojun/XPopup#1002]
**XPopup版本**
2.8.13

**手机系统和型号**
华为Mate30 pro Android 10

**描述你的问题**
为了测试影响，单独写了一个空白activity在项目里，也是一样会出现这个问题
 <activity android:name=".ui.activity.SettingsActivity" />

![image](https://user-images.githubusercontent.com/25901728/179225116-1b7836b1-9e68-4afc-9209-7da19d943e01.png)

![WechatIMG42](https://user-images.githubusercontent.com/25901728/179224975-69cbaedd-3ee6-4936-9869-e2a32cf798a7.jpeg)

**Comment by li-xiaojun** [comment]
@liweiGe 试试demo会不会这样

**Comment by liweiGe** [comment]
> 试试demo会不会这样

demo 没这个问题，但是比较奇怪的是这个不是每次出现的，多试几次偶然出现的，感觉跟一个是键盘的计算，一个是沉浸式状态设置有关系

**Comment by li-xiaojun** [comment]
那看看是不是softMode设置的是否和demo不一样，一般也不需要特殊设置，可能你用个三方框架修改了系统的输入法行为

**Comment by liweiGe** [comment]
> 那看看是不是softMode设置的是否和demo不一样，一般也不需要特殊设置，可能你用个三方框架修改了系统的输入法行为

确实，是清单文件里设置了 android:windowSoftInputMode="adjustResize"，不设置就没问题，但唯独这个机型才有问题，其他几个机型我试了都没这个问题
