### ISSUE TITLE
View内部有EditText，如何做到键盘不自动弹起

### ISSUE THREAD

**Issue by mengchaoshen** [li-xiaojun/XPopup#1005]
**XPopup版本**
2.8.0

**手机系统和型号**
小米mix4

**描述你的问题**
View内部有EditText，如何做到键盘不自动弹起

**Comment by li-xiaojun** [comment]
看文档设置下

**Comment by mengchaoshen** [comment]
文档内的autoOpenSoftInput(false)不起作用，最后是用attachPopupView.dialog.getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_STATE_HIDDEN);解决的。需要在attachPopupView.show之后调用。
