### ISSUE TITLE
此时有个bottom弹窗在，Position弹窗设置透传事件

### ISSUE THREAD

**Issue by Dreamxhx** [li-xiaojun/XPopup#1007]
**XPopup版本**
最新版本

**手机系统和型号**
华为Mate20 Android 10

**描述你的问题**
此时有个bottom弹窗在，Position弹窗设置透传事件，为什么在Position弹窗弹出时点击bottom弹窗的控件事件直接传到了activity

**Comment by Dreamxhx** [comment]
我看内部排除了继承BasePopupView类的弹窗，难道只能自己写bottom弹窗吗

**Comment by li-xiaojun** [comment]
@Dreamxhx bottom设置enableDrag(false)应该就可以
