### ISSUE TITLE
#95006 java.lang.NullPointerException Attempt to invoke virtual method 'boolean android.view.View.getGlobalVisibleRect(android.graphics.Rect)' on a null object reference  com.lxj.xpopup.core.BasePopupView.onTouchEvent(BasePopupView.java:852)

### ISSUE THREAD

**Issue by Badwritten** [li-xiaojun/XPopup#1009]
**XPopup版本**
如2.8.3

**手机系统和型号**
Android 9,level 28  vivo/FUNTOUCH  V1813BT

**描述你的问题**
#95006 java.lang.NullPointerException Attempt to invoke virtual method 'boolean android.view.View.getGlobalVisibleRect(android.graphics.Rect)' on a null object reference  com.lxj.xpopup.core.BasePopupView.onTouchEvent(BasePopupView.java:852)

**Comment by li-xiaojun** [comment]
@Badwritten 更新到最新版本
