### ISSUE TITLE
如何在列表中显示在某一控件的正上方和正下方

### ISSUE THREAD

**Issue by woshiyizhijiao** [li-xiaojun/XPopup#101]
![55369693-381e2d80-552a-11e9-9fc8-b01fc69b29f5](https://user-images.githubusercontent.com/19473420/55379385-82fe6c00-554f-11e9-8d26-dd2ea8ea71ec.png)
![55369695-38b6c400-552a-11e9-95dd-7c15ca632182](https://user-images.githubusercontent.com/19473420/55379386-83970280-554f-11e9-8fac-5884367457fc.png)
这个是ui效果图，我试着查看api但是没有效果相关的方法。
atView 和 watchView 都达不到需求

**Comment by li-xiaojun** [comment]
@woshiyizhijiao 
弹窗的位置允许进行偏移，目前可以使用offsetX和offsetY进行偏移来达到合适的位置。

**Comment by li-xiaojun** [comment]
@woshiyizhijiao 
最新版1.6.6增加了isCenterHorizontal方法来设置与目标View水平居中对齐，更新试试。

**Comment by woshiyizhijiao** [comment]
![微信图片_20190403135448](https://user-images.githubusercontent.com/19473420/55455927-261ab880-5618-11e9-8edb-ed07305b0d31.jpg)
![微信图片_20190403135451](https://user-images.githubusercontent.com/19473420/55455928-274be580-5618-11e9-8600-e87f62e4fb64.jpg)
![微信图片_20190403135455](https://user-images.githubusercontent.com/19473420/55455930-27e47c00-5618-11e9-854b-2db4d6bc2432.jpg)
三星s9+的手机在最底下弹出的时候会出现白边的情况  虽然不是啥大问题，但是测试可能会当bug提
我记得之前用1.3版本的时候是没有的

**Comment by woshiyizhijiao** [comment]
另外有个问题，我如何知道现在是显示在控件的上方还是下方，我要标明剪头的方向

**Comment by li-xiaojun** [comment]
@woshiyizhijiao 
每个弹窗都有一个popupInfo变量，你可以通过popupInfo.popupPosition来判断。
