### ISSUE TITLE
asConfirm确认弹窗,当内容较多时底部确认按钮丢失

### ISSUE THREAD

**Issue by XiaoRanLiu3119** [li-xiaojun/XPopup#1010]
**XPopup版本**
2.8.14

**手机系统和型号**
所有型号

**描述你的问题**
[asConfirm确认弹窗,当提示文字较多(分型号,小屏手机50字,小米手机70字),底部确认按钮显示不全或不显示]
![image](https://user-images.githubusercontent.com/62411322/181412123-81f191a6-64f4-4e53-b3b5-fc4fe0b80ab0.png)
![image](https://user-images.githubusercontent.com/62411322/181411561-84793b61-3305-4360-bc03-f9ab4ffd05b8.png)

**Comment by li-xiaojun** [comment]
@XiaoRanLiu3119 更新到2.8.15即可
