### ISSUE TITLE
状态栏问题

### ISSUE THREAD

**Issue by jiaoyongzhi** [li-xiaojun/XPopup#1011]
**XPopup版本**
如2.8.14

**手机系统和型号**
华为Mate20 Android 10

**描述你的问题**
在第一个弹窗  弹起第二个弹窗 都设置的为hasStatusBar(false)   
当第二个弹窗dismiss 后 
 第一个弹窗的状态栏会显示出来

**Comment by jiaoyongzhi** [comment]
第一个弹窗是FullScreenPopupView  第二个CenterPopupView

**Comment by li-xiaojun** [comment]
@jiaoyongzhi 更新到2.8.15即可
