### ISSUE TITLE
横屏AttachPopupView位置错误的问题

### ISSUE THREAD

**Issue by Alex861** [li-xiaojun/XPopup#1013]
**XPopup版本**
如2.8.14

**手机系统和型号**
华为P30pro Android 10

横屏AttachPopupView显示错位问题，如图，最好你能调试一下全面屏“ 顶部设置”，看看横屏显示错误问题，以前我反馈过这个问题，现在在新版本上又出现了
![B6E65F3F46F171E448175C83F6979003](https://user-images.githubusercontent.com/10345635/182518833-d3585c38-0eb2-4411-accd-520a9dc1787a.jpg)
![138407181-d1a1c55e-c9ce-475e-8a7e-1722f2d4119e](https://user-images.githubusercontent.com/10345635/182518845-0d720271-2ed3-4158-83a6-d57e23fb90c7.jpg)

**Comment by zhoudaxia1990** [comment]
解决了吗？？

**Comment by Alex861** [comment]
> 解决了吗？？

最新版的2.8.15还是没有解决，以前我反馈过这个问题，在2.8.2版本解决了，后面又出现了，横屏下刘海屏适配有问题

**Comment by li-xiaojun** [comment]
@Alex861 @zhoudaxia1990 更新到2.8.16即可

**Comment by Alex861** [comment]
> @Alex861 @zhoudaxia1990 更新到2.8.16即可

去掉清单文件里的刘海屏适配，横屏状态下还是有问题（注掉  <meta-data android:name="android.max_aspect" android:value="2.4" />
        <meta-data android:name="android.notch_support" android:value="true" />）
![Uploading 537B23B3CA1A5D3C8841538F3414E93E.jpg…]()

**Comment by zhoudaxia1990** [comment]
> 确实还有问题，还是会有偏移
