### ISSUE TITLE
查看图片加载进度动画可以实现自定义修改颜色吗

### ISSUE THREAD

**Issue by xuxinjiang** [li-xiaojun/XPopup#1015]
**XPopup版本**
 版本：2.8.15
**建议更新**
1.查看图片加载动画如何修改颜色，可以不跟随App主题颜色进行加载，动态修改
2.可以自定义加载动画吗，更好处理UI自由实现功能

**Comment by li-xiaojun** [comment]
在theme中使用colorControlActived属性修改，
