### ISSUE TITLE
anim引起的native crash

### ISSUE THREAD

**Issue by tongzifang** [li-xiaojun/XPopup#1017]
**XPopup版本**
2.8.14

**手机系统和型号**
安卓tv Android 9,level 28

**描述你的问题**
pop的anim可能引起RenderThread的native crash,能否提供一个无动画的方法
下面是crash log:
1
#00 pc 0001ce72 /system/lib/libc.so (abort+61) [armeabi-v7a::0ab03097f7b50ae290834de3a56ac8a4]
2
#01 pc 00006dd5 /system/lib/liblog.so (__android_log_assert+156) [armeabi-v7a::f278633e7fc824abffbcfa008b1e9686]
3
#02 pc 00370c43 /system/lib/libhwui.so [armeabi-v7a::71173b478283866480b45f09377399c0]
4
#03 pc 000abd0f /system/lib/libhwui.so [armeabi-v7a::71173b478283866480b45f09377399c0]
5
#04 pc 0009bad5 /system/lib/libhwui.so [armeabi-v7a::71173b478283866480b45f09377399c0]
6
#05 pc 0009bfb9 /system/lib/libhwui.so [armeabi-v7a::71173b478283866480b45f09377399c0]
7
#06 pc 0009aec5 /system/lib/libhwui.so [armeabi-v7a::71173b478283866480b45f09377399c0]
8
#07 pc 00378b7b /system/lib/libhwui.so [armeabi-v7a::71173b478283866480b45f09377399c0]
9
#08 pc 0033e64f /system/lib/libhwui.so [armeabi-v7a::71173b478283866480b45f09377399c0]
10
#09 pc 000a3503 /system/lib/libhwui.so [armeabi-v7a::71173b478283866480b45f09377399c0]
11
#10 pc 0000c147 /system/lib/libutils.so (_ZN7android6Thread11_threadLoopEPv+166) [armeabi-v7a::f9589727d4d1f6f48c90d8239b66c4f9]
12
#11 pc 00063c15 /system/lib/libc.so (_ZL15__pthread_startPv+22) [armeabi-v7a::0ab03097f7b50ae290834de3a56ac8a4]
13
#12 pc 0001e065 /system/lib/libc.so (__start_thread+22) [armeabi-v7a::0ab03097f7b50ae290834de3a56ac8a4]

java:

1
android.view.ThreadedRenderer.nBuildLayer(Native Method)
2
android.view.ThreadedRenderer.buildLayer(ThreadedRenderer.java:857)
3
android.view.View.buildLayer(View.java:18893)
4
android.view.ViewPropertyAnimator$2.run(ViewPropertyAnimator.java:780)
5
android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationStart(ViewPropertyAnimator.java:1078)
6
android.animation.Animator$AnimatorListener.onAnimationStart(Animator.java:536)
7
android.animation.ValueAnimator.notifyStartListeners(ValueAnimator.java:1013)
8
android.animation.ValueAnimator.startAnimation(ValueAnimator.java:1262)
9
android.animation.ValueAnimator.start(ValueAnimator.java:1064)
10
android.animation.ValueAnimator.start(ValueAnimator.java:1088)
11
android.view.ViewPropertyAnimator.startAnimation(ViewPropertyAnimator.java:904)
12
android.view.ViewPropertyAnimator.start(ViewPropertyAnimator.java:416)
13
com.lxj.xpopup.animator.TranslateAnimator.animateShow(TranslateAnimator.java:65)
14
com.lxj.xpopup.core.BasePopupView.doShowAnimation(BasePopupView.java:514)
15
com.lxj.xpopup.impl.FullScreenPopupView.doShowAnimation(FullScreenPopupView.java:66)
16
com.lxj.xpopup.core.BasePopupView$2.run(BasePopupView.java:246)
17
android.os.Handler.handleCallback(Handler.java:873)
18
android.os.Handler.dispatchMessage(Handler.java:99)
19
android.os.Looper.loop(Looper.java:193)
20
android.app.ActivityThread.main(ActivityThread.java:6670)
21
java.lang.reflect.Method.invoke(Native Method)
22
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
23
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by tongzifang** [comment]
我看了使用NoAnimation里面还是有一个alpha动画

**Comment by li-xiaojun** [comment]
直接自定义一个Animation吧，实现方法保留空就行
