### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException Attempt to read from field 'android.graphics.PointF com.lxj.xpopup.core.PopupInfo.touchPoint' on a null object

### ISSUE THREAD

**Issue by billdizl** [li-xiaojun/XPopup#1018]
**XPopup版本**
2.8.15

**手机系统和型号**
设备
品牌：HMD Global
型号：Nokia G300
屏幕方向： 纵向
可用 RAM： 632 MB
可用磁盘空间： 25.93 GB
操作系统
版本：Android 11
屏幕方向： 纵向
是否已取得 root 权限：否

**描述你的问题**
com.lxj.xpopup.core.BubbleAttachPopupView.doAttach (BubbleAttachPopupView.java:81)
com.lxj.xpopup.core.BubbleAttachPopupView$1.run (BubbleAttachPopupView.java:63)
com.lxj.xpopup.util.XPopupUtils.lambda$null$0 (XPopupUtils.java:186)
com.lxj.xpopup.util.-$$Lambda$XPopupUtils$qS6sUHnDp6axrzd_q6LpLC0sMBA.run (未知来源:2)
android.os.Handler.handleCallback (Handler.java:938)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:223)
android.app.ActivityThread.main (ActivityThread.java:7721)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:592)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:952)

**Comment by li-xiaojun** [comment]
@billdizl 更新到2.8.16
