### ISSUE TITLE
导航栏问题

### ISSUE THREAD

**Issue by jiaoyongzhi** [li-xiaojun/XPopup#1019]
**XPopup版本**
2.8.15

**手机系统和型号**
android5.1.1

**描述你的问题**
dialog 设置的是 .hasNavigationBar(false)   一开始是隐藏导航栏的  内部有edittext  但是当软键盘弹起 然后收回后  导航栏不隐藏

**Comment by li-xiaojun** [comment]
@jiaoyongzhi 我的手机复现不出来，可能是特殊机型的问题

**Comment by jiaoyongzhi** [comment]
> @jiaoyongzhi 我的手机复现不出来，可能是特殊机型的问题

确实是特殊机型，没事 我已经改实现方式了，这样也杜绝了 不隐藏

**Comment by jiaoyongzhi** [comment]
还是这个特殊机型有个别的问题 就是 用的FullScreenPopupView  然后设置了
 .dismissOnBackPressed(false) .dismissOnTouchOutside(false)
弹窗里面有一些edittext  有一些设置enable（false） 
并且在 oncreate 方法里 设置了KeyboardUtils.hideKeyboard(dialog);
点击屏幕下方的 虚拟按钮返回按钮   它会把弹窗关闭 但是不走 setPopupCallback的onDismiss 方法
