### ISSUE TITLE
运行报错，日志如下

### ISSUE THREAD

**Issue by fansangg** [li-xiaojun/XPopup#102]
1	com.lxj.xpopup.photoview.Util.isSupportedScaleType(Util.java:29)
2	com.lxj.xpopup.photoview.PhotoViewAttacher.setScaleType(PhotoViewAttacher.java:480)
3	com.lxj.xpopup.photoview.PhotoView.setScaleType(PhotoView.java:99)

**Comment by li-xiaojun** [comment]
你的ImageView的scaleType是什么？

**Comment by li-xiaojun** [comment]
@fansangg 
最新版本1.6.7已修复此问题。

**Comment by fansangg** [comment]
> @fansangg
> 最新版本1.6.7已修复此问题。

dismissOnTouchOutside这个方法没有了？

**Comment by fansangg** [comment]
看了代码，知道了
