### ISSUE TITLE
更新最新版后BottomPopupView的margin失效问题

### ISSUE THREAD

**Issue by BreezeAndMoon** [li-xiaojun/XPopup#1021]
**XPopup版本**
如2.8.15

**描述你的问题**

`BottomPopupView的getImplLayoutId()布局如下:
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_marginHorizontal="45dp"
    android:layout_marginTop="19dp"/>`
实际展示margin无效，整个布局充满全屏,旧版可以。查看源码发现了问题所在：
XpopupUtils.java文件中:

    public static void applyPopupSize(final ViewGroup content, final int maxWidth, final int maxHeight,
                                      final int popupWidth, final int popupHeight, final Runnable afterApplySize) {
        content.post(() -> {
            ViewGroup.LayoutParams params = content.getLayoutParams();
            View implView = content.getChildAt(0);
            ViewGroup.LayoutParams implParams = implView.getLayoutParams();
            // 假设默认Content宽是match，高是wrap
            int w = content.getMeasuredWidth();
            // response impl view wrap_content params.
            if (maxWidth > 0) {
                //指定了最大宽度，就限制最大宽度
                params.width = Math.min(w, maxWidth);
                if (implParams.width==ViewGroup.LayoutParams.MATCH_PARENT){
                    implParams.width = Math.min(w, maxWidth);
                    //修复=====================
                    //源码忽略了margin,此处补上
                    if (implParams instanceof ViewGroup.MarginLayoutParams) {
                        implParams.width = implParams.width - ((ViewGroup.MarginLayoutParams) implParams).leftMargin - ((ViewGroup.MarginLayoutParams) implParams).rightMargin;
                    }
                  //修复=======================
                }
                if (popupWidth > 0) {
                    params.width = Math.min(popupWidth, maxWidth);
                    implParams.width = Math.min(popupWidth, maxWidth);
                }
            }

**Comment by li-xiaojun** [comment]
@BreezeAndMoon 感谢，稍后会更新

**Comment by li-xiaojun** [comment]
@BreezeAndMoon 更新到2.8.16即可
