### ISSUE TITLE
> @Alex861 @zhoudaxia1990 更新到2.8.16即可

### ISSUE THREAD

**Issue by zhoudaxia1990** [li-xiaojun/XPopup#1023]
> @Alex861 @zhoudaxia1990 更新到2.8.16即可

去掉清单文件里的刘海屏适配，横屏状态下还是有问题
（注掉  <meta-data android:name="android.max_aspect" 
android:value="2.4" />
        <meta-data android:name="android.notch_support" 
android:value="true" />）

![537B23B3CA1A5D3C8841538F3414E93E](https://user-images.githubusercontent.com/10345635/187873124-2e1d5642-e5bf-441f-a2f5-3cddc04583d6.jpg)

_Originally posted by @Alex861 in https://github.com/li-xiaojun/XPopup/issues/1013#issuecomment-1233958990_

**Comment by li-xiaojun** [comment]
@zhoudaxia1990 更新到2.8.17
