### ISSUE TITLE
毛玻璃效果导致view移位

### ISSUE THREAD

**Issue by SmallWinter** [li-xiaojun/XPopup#1026]
**XPopup版本**
2.1.0

**手机系统和型号**
华为Mate20 Android 10

**描述你的问题**
目前调测不止这一个机型，手头四五个测试机都存在这个问题，OPPO,VIVO等，应该不是一个指定机型的特定情况。
![1](https://user-images.githubusercontent.com/8638180/190103889-11445178-2807-4885-9ed3-48b80f06302f.png)
![2](https://user-images.githubusercontent.com/8638180/190103946-89cefe5b-ed7f-4746-b6cc-d47fc5e997ca.png)
![3](https://user-images.githubusercontent.com/8638180/190103911-814ef3c2-2ac2-4bb0-861c-a758d97264f9.png)

**Comment by SmallWinter** [comment]
抱歉，补充一下：使用版本标注错了，使用的是最新版本2.9.0。

**Comment by li-xiaojun** [comment]
@SmallWinter 使用的是哪种弹窗

**Comment by SmallWinter** [comment]
继承自：　PositionPopupView

**Comment by SmallWinter** [comment]
> @SmallWinter 使用的是哪种弹窗

继承自：　PositionPopupView

**Comment by li-xiaojun** [comment]
@SmallWinter 奇怪我手机也是mate20无法复现

**Comment by SmallWinter** [comment]
> @SmallWinter 奇怪我手机也是mate20无法复现
抱歉，取消模糊效果没这个问题，前段时间赶工期，暂时就没再关注了。

使用模糊效果：hasBlurBg(true)，就会这样；不使用则没问题；
我无法确定问题出在哪儿，可能某种特殊机制下导致这种情况出现。
大概介绍一下，被位移的view使用的是SVGAImageview，SVGAImagview依附于recyclerview的item;
另外使用了使view可超出边界的属性clipChildren=false，不知是否有影响。

**Comment by li-xiaojun** [comment]
@SmallWinter 更新到最新版本试试

**Comment by li-xiaojun** [comment]
@SmallWinter 更新到2.9.17即可
