### ISSUE TITLE
小米8 出现点击隐藏软键盘后再dismiss后软键盘重复弹出又消失

### ISSUE THREAD

**Issue by zofnk** [li-xiaojun/XPopup#103]
本库版本1.6.5

bug视频在群里有上传...

出现bug的机型参数
![image](https://user-images.githubusercontent.com/17997544/55380600-3e74cf80-5553-11e9-9e68-be9598e18562.png)

偶尔会出现软键盘弹出后距离Dialog中间会空白一段 , 出现后我又装了一次 , 就复现不出了
![image](https://user-images.githubusercontent.com/17997544/55380726-a1666680-5553-11e9-8d84-fa5bb7f8fd0b.png)

**Comment by li-xiaojun** [comment]
@zofnk 
最新版本1.6.7已修复此问题。
