### ISSUE TITLE
关于一次性关闭很多XPOPUP

### ISSUE THREAD

**Issue by DD924** [li-xiaojun/XPopup#1033]
**XPopup版本**
 2.9.0

**手机系统和型号**
华为Mate20 Android 10

**描述你的问题**
你好 我是android 初学者  用户点击购买按钮 发送网络请求 请求结束后弹出 订单信息界面  然后继续支付 发送订单信息网络请求 结束后 弹出 确认购买界面 发送网络请求 当这些操作完成后 弹出 购买成功界面 但是 我不知道如何关闭之前弹出的所有界面 已经困扰我很多天了 希望能解答 我知道这并不是一个BUG或者与xpopup相关的问题  但还是希望作者能解答一下，因为我之前用的别的dialog方式 我现在切换到Xpopup 很棒

**Comment by DD924** [comment]
public static void _login(Context context){
        popup_loading popup_loading = new popup_loading(context);
        popup_meal popup_meal = new popup_meal(context);
        new XPopup.Builder(context)
                //.hasBlurBg(true) // 是否有高斯模糊的背景，默认为false
                .dismissOnBackPressed(false) // 按返回键是否关闭弹窗，默认为true
                .dismissOnTouchOutside(false) // 点击外部是否关闭弹窗，默认为true
                .asCustom(popup_loading)
                .show();
        String data = "a="+username+"&type=login";
        PublicClient.builder()
                .addHeader(time(2),header)
                .asyncPostHandler(context, api.urlMyself, new AsyncHttpResponseHandler() {
                    @Override
                    public void onSuccess(int statusCode, Header[] headers, byte[] responseBody) {
                        String res = HexUtil.encodeHexStr(responseBody);
                        if (!StrUtil.hasEmpty(res) && !res.contains("error")){
                            Object ObJ = JSONPath.read(res, "$");
                            new XPopup.Builder(context)
                                    //.hasBlurBg(true) // 是否有高斯模糊的背景，默认为false
                                    .isLightStatusBar(true)
                                    .dismissOnBackPressed(false) // 按返回键是否关闭弹窗，默认为true
                                    .dismissOnTouchOutside(false) // 点击外部是否关闭弹窗，默认为true
                                    .asCustom(popup_meal)
                                    .show();
                        }
                    }

                    @Override
                    public void onFailure(int statusCode, Header[] headers, byte[] responseBody, Throwable error) {
                        popup_loading.smartDismiss();
                    }
                });
    }


我有很多类似上面的 代码片段 一系列操作后 弹出四五个xpopup 但是 最后 关闭 我应该怎么办

**Comment by fastenCh** [comment]
可以将popup存储起来，在关闭代码处或最后一个popup监听里面调用dismiss关闭吧

**Comment by DD924** [comment]
@fastenCh  怎么存储 能说下吗  我试过 用 类似 全局变量 形式 但是希望能给个例子 或者 部分关键代码片段 谢谢

**Comment by li-xiaojun** [comment]
用全局变量存就行，监听到操作成功后调用dismiss()，最好判空下
