### ISSUE TITLE
BottomPopupView 被输入法顶上去了，怎么设置不顶上去 

### ISSUE THREAD

**Issue by luoxiong94** [li-xiaojun/XPopup#1034]
BottomPopupView 被输入法顶上去了，怎么设置不顶上去 ？  弹窗高度是屏幕的80%高，搜索框在屏幕顶部，输入法弹起的时候，整个布局都会往上顶。。。 请问如何设置不变

**Comment by li-xiaojun** [comment]
isMoveUpToKeyboard(false)
