### ISSUE TITLE
DrawerPopupView 如果是view模式下，开启多个点击时间无法响应

### ISSUE THREAD

**Issue by WuXiaoran** [li-xiaojun/XPopup#1035]
**XPopup版本**
2.9.0

**手机系统和型号**
小米 9 android11

**描述你的问题**
DrawerPopupView 设置isViewMode(true)
主要是为了承载fragment，然后开启多个的话 点击时间就无法响应了
等待前一个关闭完后在打开，就不会出现这个问题

**Comment by li-xiaojun** [comment]
你说这个点击是弹窗内部的点击事件？还是点击透传到下层？

**Comment by WuXiaoran** [comment]
> 你说这个点击是弹窗内部的点击事件？还是点击透传到下层？

弹窗内部的点击事件

**Comment by li-xiaojun** [comment]
@WuXiaoran 我无法复现，可以提供一个最小复现的demo，加我qq：16167479 发给我我看看

**Comment by Travellingpoet** [comment]
这个问题解决了吗 我也复现了这个问题 同时弹出两个dialog时只有后开启的dialog点击事件可以响应
