### ISSUE TITLE
show无法弹出框(偶现bug)

### ISSUE THREAD

**Issue by billdizl** [li-xiaojun/XPopup#1036]
**XPopup版本**
如2.9.0

**手机系统和型号**
三星  

**描述你的问题**
偶现bug,点击show的时候会一闪,继续点击show,仍旧闪一下,返回重新进入该页面,再点的时候就正常了,偶现偶现偶现偶现偶现偶现!!!!
if(AAAADialog==null){
AAAADialog=XPopup.Builder(mContext)
                    .customHostLifecycle(mLifecycle)
                    .dismissOnTouchOutside(false)
                    .isViewMode(false) //开启View实现
                    .isDestroyOnDismiss(false)
                    .popupHeight(XPopupUtils.dp2px(mContext, 397f))
                    .setPopupCallback(object : XPopupCallback {
                        override fun onCreated(popupView: BasePopupView?) {

                        }

                        override fun beforeShow(popupView: BasePopupView?) {
                        }

                        override fun onShow(popupView: BasePopupView?) {
                        }

                        override fun onDismiss(popupView: BasePopupView?) {
                            onCommentListListener?.showLoadDialog(false)
                        }

                        override fun beforeDismiss(popupView: BasePopupView?) {
                        }

                        override fun onBackPressed(popupView: BasePopupView?): Boolean {
                            return true
                        }

                        override fun onKeyBoardStateChanged(
                            popupView: BasePopupView?,
                            height: Int
                        ) {
                        }

                        override fun onDrag(
                            popupView: BasePopupView?,
                            value: Int,
                            percent: Float,
                            upOrLeft: Boolean
                        ) {
                        }

                        override fun onClickOutside(popupView: BasePopupView?) {

                        }

                    })
                    .asCustom(
                        CommentListDialog(
                            mContext, onCommentListListener, mLifecycleOwner, showId, showingIdBean
                        )
                    )

}
if(AAAADialog!=null){
AAAADialog.show()}

注:::::
CommentListDialog extends BottomPopupView

**Comment by li-xiaojun** [comment]
@billdizl 更新到2.9.2试试
