### ISSUE TITLE
偶现闪退

### ISSUE THREAD

**Issue by crazyzjw** [li-xiaojun/XPopup#1037]
**XPopup版本**
(com.github.li-xiaojun:XPopup:2.9.0)

**手机系统和型号**
<img width="637" alt="image" src="https://user-images.githubusercontent.com/12543049/191702402-e5030408-8c74-4f86-af46-e0bdc99ba9f0.png">

**描述你的问题**
<img width="895" alt="image" src="https://user-images.githubusercontent.com/12543049/191702334-c9d30a37-800e-439d-bcd4-ec7c59897796.png">

**Comment by li-xiaojun** [comment]
更新到2.9.1即可
