### ISSUE TITLE
黑屏bug

### ISSUE THREAD

**Issue by wkbin** [li-xiaojun/XPopup#1038]
**XPopup版本**
2.9.0

**手机系统和型号**
OPPO Find X5 Pro 天玑版

**描述你的问题**
关闭全屏弹窗后黑屏

`XPopup.Builder(this.context)
   .isViewMode(false)
           .isDestroyOnDismiss(true)
           .shadowBgColor(Color.parseColor("#CC000000"))
           .customAnimator(EmptyAnimator(window.decorView,0))
           .asCustom(xxx)
           .show()
`

**Comment by wkbin** [comment]
经过测试  customAnimator(EmptyAnimator(window.decorView,0)) 是动画这一行导致的

**Comment by li-xiaojun** [comment]
别这么用，你要用内置动画 就这样：
```
.popupAnimation(PopupAnimation.NoAnimation)
```
