### ISSUE TITLE
多图浏览，如果图片加载失败，展示错误占位图时，点击屏幕无法关闭弹窗

### ISSUE THREAD

**Issue by FJLiJinYi** [li-xiaojun/XPopup#1040]
**XPopup版本**
(com.github.li-xiaojun:XPopup:2.9.0)

**手机系统和型号**
坚果pro2 Android 7

**描述你的问题**
多图浏览时，使用SmartGlideImageLoader(R.mipmap.login_logo)；
在加载错误占位图时，PhotoView 调用((PhotoView) imageView).setZoomable(false);
![image](https://user-images.githubusercontent.com/32057304/196081155-3c0a4b0f-57c4-45fb-bce3-bf2ba9afe4e7.png)

PhotoView控件setZoomable设置成false 用于PhotoViewAttacher 参数中onTouch方法拦截手势操作缩放；
点击事件也在onTouch中的调用的mGestureDetector手势检测器中触发。
![image](https://user-images.githubusercontent.com/32057304/196081677-00bf102e-7bd0-42b6-bcaa-56d19afee101.png)
![image](https://user-images.githubusercontent.com/32057304/196081876-5cd1f9c1-93e4-4139-acd7-e681a154ebcd.png)
如果setZoomable 设置为false 意味着点击事件无法被响应到。
无法关闭弹窗。

可以使用 SmartGlideImageLoader(true,R.mipmap.login_logo) 调用另一个控件使用或者重写SmartGlideImageLoader这个文件。

以上，您有空可以看下是我 个人见解，谢谢！

**Comment by li-xiaojun** [comment]
@FJLiJinYi 更新到2.9.4即可
