### ISSUE TITLE
设置后台展示，没有给权限的情况下，app在前台为什么无法弹窗呢

### ISSUE THREAD

**Issue by Andy957** [li-xiaojun/XPopup#1041]

**Comment by Andy957** [comment]
.enableShowWhenAppBackground(true)

**Comment by li-xiaojun** [comment]
没有给权限怎么弹窗呢？

**Comment by Andy957** [comment]
> Owner

我的意思，我没有在后台，app在前台打开的情况下，也谈不了

**Comment by li-xiaojun** [comment]
上代码

**Comment by Andy957** [comment]
new Handler().postDelayed(() -> {
                    popupView = new CustomFullScreenPopup(getContext());
                    new XPopup.Builder(getContext())
                            .enableShowWhenAppBackground(true)
                            .asCustom(popupView)
                            .show();
                }, 2000);
悬浮窗和后台弹出界面的权限都是没有的，demo我是打开的，在前台显示

**Comment by Andy957** [comment]
.enableShowWhenAppBackground(true)
意思就是要是设置了这个，就必须要有悬浮窗或者后台弹窗的权限，才能显示这个弹窗吗

**Comment by li-xiaojun** [comment]
@Andy957 更新到2.9.6，已修复这个问题

**Comment by Andy957** [comment]
非常感谢大佬！！！
