### ISSUE TITLE
小米商店审核隐私不合规

### ISSUE THREAD

**Issue by zcychinese** [li-xiaojun/XPopup#1042]
**XPopup版本**
如2.9.6

**手机系统和型号**
小米

**描述你的问题**
小米商店审核不通过，提示如下

APP以隐私政策弹窗的形式向用户明示收集使用规则，未经用户同意，存在收集安装列表的行为。

APP向用户明示SDK的收集使用规则，未经用户同意，SDK存在收集com.lxj.xpopup获取安装列表的行为。

这个如何解决一下。现在被卡了。

**Comment by li-xiaojun** [comment]
XPopup不存在收集安装列表的行为，可以查看代码和权限便知。检测一下你的初始化代码，可能某个SDK在用户未授权的情况下进行提前初始化了

**Comment by zcychinese** [comment]
好的，非常感谢，可能是其他第三方的问题，我仔细查看一下。
