### ISSUE TITLE
windows11 android 子系统

### ISSUE THREAD

**Issue by dearestwilson** [li-xiaojun/XPopup#1043]
**XPopup版本**
2.9.4

**手机系统和型号**
windows11 android 子系统

**描述你的问题**
bottom弹窗底部距离
![微信图片_20221025103728](https://user-images.githubusercontent.com/10183369/197669160-0c802774-6730-48a1-861e-76cae368aa4c.png)
![微信图片_20221025103733](https://user-images.githubusercontent.com/10183369/197669172-2398d83d-0025-4e33-a7e8-fece052beb52.png)
![微信图片_20221025103710](https://user-images.githubusercontent.com/10183369/197669181-d48eadf6-5f2e-408f-928d-b2c0af31f172.jpg)

**Comment by li-xiaojun** [comment]
模拟器？

**Comment by dearestwilson** [comment]
> 模拟器？

Windows Subsystem for Android

**Comment by li-xiaojun** [comment]
不是真机的就算了
