### ISSUE TITLE
PartShadowPopupView怎么回事偏移左边？

### ISSUE THREAD

**Issue by xuxinjiang** [li-xiaojun/XPopup#1044]
**XPopup版本**
2.9.7

**手机系统和型号**
小米11

**描述你的问题**
PartShadowPopupView 为什么偏移左边？之前不是好好地吗，这改了多少次一直都有偏移问题？
![0@ )NKZW G C%O(M65E9{CH](https://user-images.githubusercontent.com/41047773/199373221-12a3bd75-2ea2-4c40-a1e0-732e1cccc33e.jpg)

**Comment by xuxinjiang** [comment]
但是无法精准控制在某个View的下方

**Comment by xuxinjiang** [comment]
![3AF51E7E46C0F115473609479213DB48](https://user-images.githubusercontent.com/41047773/199637295-6df953c3-8fe5-45cd-9948-431522cfbbba.jpg)
![C239AFBCF90136ACBE1F9FCE7029383C](https://user-images.githubusercontent.com/41047773/199637302-00016990-9fdd-48e1-950a-24cef4c04a9e.jpg)
按你方案给布局外层增加一个父布局，让内部布局居右，无法精准控制下方位置

**Comment by li-xiaojun** [comment]
@xuxinjiang 需要精准控制的话，用attach弹窗吧，只需要修改下继承的类为AttachPopupView即可

**Comment by xuxinjiang** [comment]
BubbleAttachPopupView也改了吗 改完后说实话一点都不好用了

**Comment by xuxinjiang** [comment]
BubbleAttachPopupView也改了吗，也有偏移了，这次全新版本不够之前灵活了

**Comment by li-xiaojun** [comment]
如果想在正下方，Attach弹窗加上isCenterHorizontal(true)即可
