### ISSUE TITLE
你好，我依赖这个报错冲突，但不知道与那个重复，怎么解决重复问题呢？？？

### ISSUE THREAD

**Issue by gjmm123** [li-xiaojun/XPopup#1047]
Duplicate class com.davemorrissey.labs.subscaleview.BuildConfig found in modules jetified-subsampling-scale-image-view-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view:3.10.0) and jetified-subsampling-scale-image-view-androidx-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0)
Duplicate class com.davemorrissey.labs.subscaleview.ImageSource found in modules jetified-subsampling-scale-image-view-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view:3.10.0) and jetified-subsampling-scale-image-view-androidx-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0)
Duplicate class com.davemorrissey.labs.subscaleview.ImageViewState found in modules jetified-subsampling-scale-image-view-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view:3.10.0) and jetified-subsampling-scale-image-view-androidx-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0)
Duplicate class com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView found in modules jetified-subsampling-scale-image-view-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view:3.10.0) and jetified-subsampling-scale-image-view-androidx-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0)
Duplicate class com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$1 found in modules jetified-subsampling-scale-image-view-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view:3.10.0) and jetified-subsampling-scale-image-view-androidx-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0)
Duplicate class com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$2 found in modules jetified-subsampling-scale-image-view-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view:3.10.0) and jetified-subsampling-scale-image-view-androidx-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0)
Duplicate class com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$3 found in modules jetified-subsampling-scale-image-view-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view:3.10.0) and jetified-subsampling-scale-image-view-androidx-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0)
Duplicate class com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$Anim found in modules jetified-subsampling-scale-image-view-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view:3.10.0) and jetified-subsampling-scale-image-view-androidx-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0)
Duplicate class com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$AnimationBuilder found in modules jetified-subsampling-scale-image-view-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view:3.10.0) and jetified-subsampling-scale-image-view-androidx-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0)
Duplicate class com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapLoadTask found in modules jetified-subsampling-scale-image-view-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view:3.10.0) and jetified-subsampling-scale-image-view-androidx-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0)
Duplicate class com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$DefaultOnAnimationEventListener found in modules jetified-subsampling-scale-image-view-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view:3.10.0) and jetified-subsampling-scale-image-view-androidx-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0)
Duplicate class com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$DefaultOnImageEventListener found in modules jetified-subsampling-scale-image-view-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view:3.10.0) and jetified-subsampling-scale-image-view-androidx-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0)
Duplicate class com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$DefaultOnStateChangedListener found in modules jetified-subsampling-scale-image-view-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view:3.10.0) and jetified-subsampling-scale-image-view-androidx-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0)
Duplicate class com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$OnAnimationEventListener found in modules jetified-subsampling-scale-image-view-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view:3.10.0) and jetified-subsampling-scale-image-view-androidx-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0)
Duplicate class com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$OnImageEventListener found in modules jetified-subsampling-scale-image-view-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view:3.10.0) and jetified-subsampling-scale-image-view-androidx-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0)
Duplicate class com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$OnStateChangedListener found in modules jetified-subsampling-scale-image-view-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view:3.10.0) and jetified-subsampling-scale-image-view-androidx-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0)
Duplicate class com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$ScaleAndTranslate found in modules jetified-subsampling-scale-image-view-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view:3.10.0) and jetified-subsampling-scale-image-view-androidx-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0)
Duplicate class com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$Tile found in modules jetified-subsampling-scale-image-view-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view:3.10.0) and jetified-subsampling-scale-image-view-androidx-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0)
Duplicate class com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TileLoadTask found in modules jetified-subsampling-scale-image-view-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view:3.10.0) and jetified-subsampling-scale-image-view-androidx-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0)
Duplicate class com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask found in modules jetified-subsampling-scale-image-view-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view:3.10.0) and jetified-subsampling-scale-image-view-androidx-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0)
Duplicate class com.davemorrissey.labs.subscaleview.decoder.CompatDecoderFactory found in modules jetified-subsampling-scale-image-view-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view:3.10.0) and jetified-subsampling-scale-image-view-androidx-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0)
Duplicate class com.davemorrissey.labs.subscaleview.decoder.DecoderFactory found in modules jetified-subsampling-scale-image-view-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view:3.10.0) and jetified-subsampling-scale-image-view-androidx-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0)
Duplicate class com.davemorrissey.labs.subscaleview.decoder.ImageDecoder found in modules jetified-subsampling-scale-image-view-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view:3.10.0) and jetified-subsampling-scale-image-view-androidx-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0)
Duplicate class com.davemorrissey.labs.subscaleview.decoder.ImageRegionDecoder found in modules jetified-subsampling-scale-image-view-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view:3.10.0) and jetified-subsampling-scale-image-view-androidx-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0)
Duplicate class com.davemorrissey.labs.subscaleview.decoder.SkiaImageDecoder found in modules jetified-subsampling-scale-image-view-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view:3.10.0) and jetified-subsampling-scale-image-view-androidx-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0)
Duplicate class com.davemorrissey.labs.subscaleview.decoder.SkiaImageRegionDecoder found in modules jetified-subsampling-scale-image-view-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view:3.10.0) and jetified-subsampling-scale-image-view-androidx-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0)
Duplicate class com.davemorrissey.labs.subscaleview.decoder.SkiaPooledImageRegionDecoder found in modules jetified-subsampling-scale-image-view-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view:3.10.0) and jetified-subsampling-scale-image-view-androidx-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0)
Duplicate class com.davemorrissey.labs.subscaleview.decoder.SkiaPooledImageRegionDecoder$1 found in modules jetified-subsampling-scale-image-view-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view:3.10.0) and jetified-subsampling-scale-image-view-androidx-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0)
Duplicate class com.davemorrissey.labs.subscaleview.decoder.SkiaPooledImageRegionDecoder$1CpuFilter found in modules jetified-subsampling-scale-image-view-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view:3.10.0) and jetified-subsampling-scale-image-view-androidx-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0)
Duplicate class com.davemorrissey.labs.subscaleview.decoder.SkiaPooledImageRegionDecoder$DecoderPool found in modules jetified-subsampling-scale-image-view-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view:3.10.0) and jetified-subsampling-scale-image-view-androidx-3.10.0-runtime (com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0)

Go to the documentation to learn how to Fix dependency resolution errors.

**Comment by li-xiaojun** [comment]
gradle脚本进行exclude即可：
```
implementation ('com.github.li-xiaojun:XPopup:版本号看上面'){
  exclude group: "com.davemorrissey.labs", module: "subsampling-scale-image-view-androidx"
}
```

**Comment by hardgit** [comment]
> gradle脚本进行exclude即可：
> 
> ```
> implementation ('com.github.li-xiaojun:XPopup:版本号看上面'){
>   exclude group: "com.davemorrissey.labs", module: "subsampling-scale-image-view-androidx"
> }
> ```
为啥我加了没效果啊…… 糊了
 implementation ('com.github.li-xiaojun:XPopup:2.9.19'){
        exclude group: "com.davemorrissey.labs", module: "subsampling-scale-image-view-androidx"
 }
