### ISSUE TITLE
自定义弹窗无法正确显示

### ISSUE THREAD

**Issue by gaosen1023** [li-xiaojun/XPopup#105]
1.        
new XPopup.Builder(getContext())
                .popupAnimation(PopupAnimation.TranslateFromBottom)
                .asCustom(new HomeWorkPoup(getContext()))
                .show();
2.
public class HomeWorkPoup extends FullScreenPopupView {

    public HomeWorkPoup(@NonNull Context context) {
        super(context);
    }

    @Override
    protected int getImplLayoutId() {
        return R.layout.home_work_popup;
    }

    @Override
    public void init() {
        //ViewPager viewPager = findViewById(R.id.home_work_popup_viewPage);
    }
}
3.来自Demo
<?xml version="1.0" encoding="utf-8"?>
<android.support.v4.widget.NestedScrollView xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:background="#fff"
    android:layout_height="match_parent">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        android:padding="20dp">

        <TextView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="20dp"
            android:text="我是全屏弹窗，可以设置任意的动画器。我看起来就像一个从底部弹出的Activity，可以用来做一些登录，选择界面。"
            android:textColor="#333"
            android:textSize="18sp" />

        <EditText
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="15dp"
            android:hint="测试软键盘交互" />

        <View
            android:background="#ccc"
            android:layout_width="match_parent"
            android:layout_height="300dp" />

        <EditText
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="15dp"
            android:hint="测试软键盘交互" />

        <View
            android:background="#9C27B0"
            android:layout_width="match_parent"
            android:layout_height="150dp" />

        <EditText
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="85dp"
            android:hint="测试软键盘交互" />
        <View
            android:background="#AC5959"
            android:layout_width="match_parent"
            android:layout_height="150dp" />
    </LinearLayout>

</android.support.v4.widget.NestedScrollView>

问题是，执行了1代码后，从触摸反馈上可以感受到已经弹出了，但是没有显示，就像一层透明的一样，乱点也可以触发EditText弹出键盘
手机型号红米6 MIUI版本10.2 Android版本8.1

**Comment by li-xiaojun** [comment]
加群：783659607，录制个小视频我看看。
