### ISSUE TITLE
想做一个联想检索功能，但是AttachPopupView弹出后无法继续操作软键盘

### ISSUE THREAD

**Issue by hardgit** [li-xiaojun/XPopup#1050]
**XPopup版本**
如2.9.11

**手机系统和型号**
OPPO A32  Android 11

**描述你的问题**
自定义：RetrievalXpopup 继承 AttachPopupView
    xpopup = RetrievalXpopup(context)
        popupView = XPopup.Builder(context)
            .atView(holder.getView(R.id.ed_unit_manufacturer))
            .dismissOnTouchOutside(false)
            .isRequestFocus(false) //不强制焦点
            .autoFocusEditText(true)
            .moveUpToKeyboard(true)
            .hasShadowBg(true)
            .positionByWindowCenter(true)
            .popupAnimation(PopupAnimation.ScaleAlphaFromCenter)
            .asCustom(xpopup)
这个是联想检索的需求，当窗口弹出后，我无法继续操作软键盘了；
当我想设置点击穿透属性时，却发现直接触发到软键盘下方了；
我想要继续操作软键盘，需要怎么去做？

**Comment by li-xiaojun** [comment]
加上这个试试
```
.isViewMode(true)      //开启View实现
.isTouchThrough(true)
```

**Comment by hardgit** [comment]
> 加上这个试试
> 
> ```
> .isViewMode(true)      //开启View实现
> .isTouchThrough(true)
> ```
感谢回复，加上后问题已解决；
