### ISSUE TITLE
demo横屏下DrawerPopupView显示不完整

### ISSUE THREAD

**Issue by Alex861** [li-xiaojun/XPopup#1051]
**XPopup版本**
如2.9.11

**手机系统和型号**
谷歌 pixel4 XL

**描述你的问题**
如图
![Screenshot_20221110-154456](https://user-images.githubusercontent.com/10345635/201032207-37bd59b5-7f02-4f1a-9178-dbe8f9c06c82.png)

**Comment by li-xiaojun** [comment]
@Alex861 更新到2.9.12-alpha即可

**Comment by Alex861** [comment]
![image](https://user-images.githubusercontent.com/10345635/201841336-6312c96c-6a9d-4305-a5b4-30b94d7fb2a6.png)

升级到了2.9.12-alpha还是这样，左侧导航没有数据显示不全，右侧导航有数据就正常，高度计算还是有问题

**Comment by Alex861** [comment]
> @Alex861 更新到2.9.12-alpha即可



> @Alex861 更新到2.9.12-alpha即可

![image](https://user-images.githubusercontent.com/10345635/201841833-3f1d8fe5-d704-4b8d-8eef-3e37ee1e0172.png)

升级到了2.9.12-alpha还是这样，左侧导航没有数据显示不全，右侧导航有数据就正常，高度计算还是有问题

**Comment by Alex861** [comment]
> @Alex861 更新到2.9.12-alpha即可

![image](https://user-images.githubusercontent.com/10345635/201842594-b848d888-8d3d-45e7-a2f8-7108094559f0.png)

升级到了2.9.12-alpha还是这样，左侧导航没有数据显示不全，右侧导航有数据就正常，高度计算还是有问题
