### ISSUE TITLE
气泡弹窗显示异常

### ISSUE THREAD

**Issue by billdizl** [li-xiaojun/XPopup#1052]
**XPopup版本**
2.9.12

**手机系统和型号**
realme x50
荣耀8
华为mate30
.....

**描述你的问题**
更新sdk版本之后  气泡弹窗显示异常,从2.9.8 版本开始显示异常, 可能优化气泡弹窗让气泡显示在中间也许是一部分人想要的效果,但是对于有些需求还是以前的那个效果是最终效果~

代码:XPopup.Builder(mContext) //                        .isCenterHorizontal(true)
                .isDestroyOnDismiss(true) //对于只使用一次的弹窗，推荐设置这个
                .atView(mView)
                .hasShadowBg(false) // 去掉半透明背景
                //                        .offsetX(XPopupUtils.dp2px(getContext(), 20))
                .offsetY(XPopupUtils.dp2px(mContext, 6f))
                .asCustom(
                    CustomBubbleAttachPopup(
                        mContext,
                        tipText
                    ) //                                .setArrowOffset(-XPopupUtils.dp2px(getContext(), 40))  //气泡箭头偏移
                        //                                .setBubbleBgColor(Color.RED)  //气泡背景
                        .setArrowWidth(XPopupUtils.dp2px(mContext, 5f))
                        .setArrowHeight(
                            XPopupUtils.dp2px(
                                mContext,
                                6f
                            )
                        ) //                                .setBubbleRadius(100)
                        .setArrowRadius(XPopupUtils.dp2px(mContext, 3f))
                )
                .show()
![image](https://user-images.githubusercontent.com/30317994/201650859-4dd15207-5185-4b90-9d72-8ce2c9756786.png)

2.9.9版本以及之后的版本
![image](https://user-images.githubusercontent.com/30317994/201651042-c86d5acc-eb33-4161-8b2e-4e67f2c7144e.png)

2.9.8版本样式
![image](https://user-images.githubusercontent.com/30317994/201650573-d538df71-00c7-42c1-971f-495fcabd94b2.png)
2.9.8版本之前的样式

![image](https://user-images.githubusercontent.com/30317994/201653120-1bbea4d1-b9ce-4913-8114-9a25dae27aa9.png)

**Comment by li-xiaojun** [comment]
@billdizl 更新到2.9.13即可
