### ISSUE TITLE
DrawerPopupView 中 isDismissOnTouchOutside = false 没有效果

### ISSUE THREAD

**Issue by easywangzhe** [li-xiaojun/XPopup#1054]
**XPopup版本**
2.9.12-alpha

**手机系统和型号**
华为Mate20 Android 10

**描述你的问题**
最好能上代码截图和问题截图
![1668756788931](https://user-images.githubusercontent.com/9899467/202646531-7b7b8566-d111-4422-8a83-3838c00c90ed.png)
isDismissOnTouchOutside 是Boolean类型，判断时用非空判断，导致DrawerPopupView和BottomPopupView设置了false没有效果

**Comment by li-xiaojun** [comment]
@easywangzhe 更新到2.9.13即可
