### ISSUE TITLE
气泡弹窗内容显示不全

### ISSUE THREAD

**Issue by UserName-Haha** [li-xiaojun/XPopup#1056]
**XPopup版本**
2.9.13

**手机系统和型号**
小米8 MIUI12.5.2

**描述你的问题**

您好，如下图所示，气泡中文字显示不全，烦请您有空看看
![Screenshot_20221122_171420](https://user-images.githubusercontent.com/35187059/203274204-fe05ba70-2349-43a9-a4f4-2d73e8c2474a.png)

具体代码如图：
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/35187059/203274768-ca66df3b-887a-4412-943a-4ff22185fff8.png">

**Comment by li-xiaojun** [comment]
@UserName-Haha 更新到2.9.14即可
