### ISSUE TITLE
新版本根布局使用CardView时，圆角会失效，旧版本正常

### ISSUE THREAD

**Issue by licheedev** [li-xiaojun/XPopup#1057]
**XPopup版本**
2.9.15

**手机系统和型号**
小米8 MIUI12.5.2 Android 10

**描述你的问题**
旧版本：
> implementation 'com.github.li-xiaojun:XPopup:2.7.8'
![Screenshot_20221124_090650](https://user-images.githubusercontent.com/10960780/203672324-881f3bd9-f2f3-4bc8-8207-c170a99fe8e1.png)

新版本：
> implementation 'com.github.li-xiaojun:XPopup:2.9.15'
![Screenshot_20221124_090825](https://user-images.githubusercontent.com/10960780/203672327-ae0b08f4-3031-4d36-a526-222a121c6b92.png)

**Comment by li-xiaojun** [comment]
@licheedev 经测试无法复现，请贴下你的布局文件和代码

**Comment by ycsssss** [comment]
我也有这个问题

**Comment by licheedev** [comment]
@li-xiaojun https://github.com/licheedev/XpopupTest 这个demo可以复现
![截图](https://raw.githubusercontent.com/licheedev/XpopupTest/master/capture.jpg)

**Comment by li-xiaojun** [comment]
我知道了，你的宽度大于了Center弹窗默认的最大宽度，设置下getMaxWidth()返回-1

**Comment by li-xiaojun** [comment]
@licheedev @ycsssss 更新到2.9.16即可
