### ISSUE TITLE
弹出框 显示 .asCenterList 模式 如何进行多项选择

### ISSUE THREAD

**Issue by Andjdd** [li-xiaojun/XPopup#1058]
弹出框 显示 .asCenterList 模式 如何进行多项选择

**Comment by li-xiaojun** [comment]
内置弹窗没有这个功能，请自定义弹窗

**Comment by Andjdd** [comment]
收到谢谢&nbsp;


574808086
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月25日(星期五) 晚上8:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [li-xiaojun/XPopup] 弹出框 显示 .asCenterList 模式 如何进行多项选择 (Issue #1058)





 
内置弹窗没有这个功能，请自定义弹窗
