### ISSUE TITLE
isCenterHorizontal（）方法无效

### ISSUE THREAD

**Issue by dcskys** [li-xiaojun/XPopup#106]
PartShadowPopupView 类型 怎么设置都无效

**Comment by li-xiaojun** [comment]
目前只对Attach弹窗生效，可以贴下你的UI效果，我看看是否有必要添加这个功能。

**Comment by dcskys** [comment]
我继承了AttachPopupView，可以用列表呀，我还以为不能用

**Comment by li-xiaojun** [comment]
@dcskys 
继承Attach弹窗，布局可以任意实现，并没有什么限制。
