### ISSUE TITLE
isCenterHorizontal（）方法无效

### ISSUE THREAD

**Issue by Jasperben** [li-xiaojun/XPopup#1060]
new XPopup.Builder(this)
                        .hasStatusBar(false)
                        .hasNavigationBar(false)
                        .isDestroyOnDismiss(true) //对于只使用一次的弹窗，推荐设置这个
                        .popupPosition(PopupPosition.Top)//手动指定弹窗出现在目标的什么位置，对Attach和Drawer类型弹窗生效
                        .atView(mIvSwitchAlbumCalendar)
                        .isCenterHorizontal(true)
                        .hasShadowBg(false) // 去掉半透明背景
                        .asCustom(new CustomBubbleAttachPopup(this))
                        .show();

![image](https://user-images.githubusercontent.com/15630036/204259139-e56d762c-6131-4dec-b9e9-8f026a9e0f8f.png)

**Comment by li-xiaojun** [comment]
不是最新版吧

**Comment by Jasperben** [comment]
是最新的

**Comment by Jasperben** [comment]
2.9.15版本

**Comment by Jasperben** [comment]
> 不是最新版吧

是最新的

**Comment by li-xiaojun** [comment]
@Jasperben 更新到2.9.16即可
