### ISSUE TITLE
在波斯语等左右颠倒显示环境下，气泡弹窗显示异常

### ISSUE THREAD

**Issue by UserName-Haha** [li-xiaojun/XPopup#1061]
**XPopup版本**
2.9.14

**手机系统和型号**
小米8

**描述你的问题**
* 异常情况（波斯语等左右颠倒显示的情况下）：
* <img width="642" alt="image" src="https://user-images.githubusercontent.com/35187059/204430193-e31a7ce3-90a9-4e12-81d9-cc38fbed8fa1.png">

* 正常情况：
<img width="616" alt="image" src="https://user-images.githubusercontent.com/35187059/204430333-4980e7bc-50f5-407d-81ba-83b2b562b5e3.png">

* 代码：
* 
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/35187059/204431933-fac0cb8d-f59d-41c5-90a0-d8d9958ac22a.png">

盼复

**Comment by li-xiaojun** [comment]
下版本修复

**Comment by li-xiaojun** [comment]
@UserName-Haha 更新到2.9.16即可
