### ISSUE TITLE
getStatusBarHeight 获取高度有问题

### ISSUE THREAD

**Issue by Heart-Beats** [li-xiaojun/XPopup#1062]
**XPopup版本**
2.9.15

**手机系统和型号**
荣耀20Pro  Android 10（鸿蒙2.0.0）

**描述你的问题**
在使用 DrawerPopupView 作侧拉弹窗时，设置了 hasStatusBarShadow 发现无效，截图如下：
![image](https://user-images.githubusercontent.com/33248551/204954234-4e2636ae-410d-4f59-9ed8-e7f37b924601.png)
经排查发现：
```java
    @Override
    protected void dispatchDraw(Canvas canvas) {
        super.dispatchDraw(canvas);
        if (popupInfo!=null && popupInfo.hasStatusBarShadow) {
            if (shadowRect == null) {
                shadowRect = new Rect(0, 0, getMeasuredWidth(), getStatusBarHeight());
            }
            paint.setColor((Integer) argbEvaluator.evaluate(mFraction, defaultColor, getStatusBarBgColor()));
            canvas.drawRect(shadowRect, paint);
        }
    }
```
debug 运行时 `getStatusBarHeight()` 获取到的高度为 0，  所以绘制无效，因此我尝试重写了getStatusBarHeight 方法，借助ImmersionBar 实现如下：
```kotlin
override fun getStatusBarHeight(): Int {
	return ImmersionBar.getStatusBarHeight(context)
} 
```
运行时正常，截图如下：
![7fd5a3bee2728a037c1fdb344b2ab5cf](https://user-images.githubusercontent.com/33248551/204954829-5f89cf7f-c6dc-40e0-a0e8-be36ead1904a.jpg)

希望大佬有时间可以兼容修改一下

**Comment by li-xiaojun** [comment]
@Heart-Beats 更新到2.9.16即可
