### ISSUE TITLE
自定义了ImageViewerPopupView后 原来的功能都不能用了

### ISSUE THREAD

**Issue by Lucifer119119** [li-xiaojun/XPopup#1064]
**XPopup版本**
2.9.16

**手机系统和型号**
Android12

**描述你的问题**
![image](https://user-images.githubusercontent.com/35765981/205537515-b3d0fc5b-714e-4f1f-adeb-32d67def44dc.png)
![image](https://user-images.githubusercontent.com/35765981/205537539-17c5c41f-73d2-4461-8bdf-8a07334750a1.png)
![image](https://user-images.githubusercontent.com/35765981/205537561-96039894-0652-40c3-942b-90652c63f824.png)
布局直接复制的原来的布局 只是加了一个TextView 但是发现原本的功能不能用了 原来的点击保存什么的都无法使用 点击图片也不能让弹窗消失

**Comment by li-xiaojun** [comment]
demo中有自定义的例子，不要拷贝原来的布局，只需要写你的布局就行
