### ISSUE TITLE
asConfirm 我想获取确定按钮修改颜色

### ISSUE THREAD

**Issue by YQcharlse** [li-xiaojun/XPopup#1066]
**XPopup版本**
2.9.16

**手机系统和型号**
Android 11

**描述你的问题**
asConfirm 获取 确定 按钮修改字体颜色，我通过ConfirmPopupView中getConfirmTextView()方法修改text是有效的，但修改setTextColor并没有效果

**Comment by li-xiaojun** [comment]
因为被内置弹窗主题颜色覆盖了，在beforeShow回调中修改试试

**Comment by YQcharlse** [comment]
感谢大佬，我在setPopupCallback  中解决了这个问题
