### ISSUE TITLE
EditText 下使用，类似自动搜索效果，输入一半，焦点丢失了

### ISSUE THREAD

**Issue by dcskys** [li-xiaojun/XPopup#107]
![image](https://user-images.githubusercontent.com/19629224/55460416-83b50200-5624-11e9-8f32-8b68db81f296.png)  这种效果

**Comment by li-xiaojun** [comment]
@dcskys 
该问题已修复，2天内我会更新一个版本，请期待。

**Comment by dcskys** [comment]
66，厉害

**Comment by li-xiaojun** [comment]
@dcskys 
最新版本1.6.7已修复此问题。

**Comment by daleiyinsi** [comment]
怎么解决我，  我的还是edittext没有焦点

**Comment by daleiyinsi** [comment]
联想搜索如果弹出popup，edittext的焦点就没有了，无法使用
