### ISSUE TITLE
请问我们库里有那种不依靠Activity就能显示的弹窗类型吗

### ISSUE THREAD

**Issue by Yangqingchun** [li-xiaojun/XPopup#1070]
**XPopup版本**
如2.9.17

**手机系统和型号**
华为Mate20 Android 10

**描述你的问题**
我想实现一种类似与Android原生截屏缩略图展示的功能，就是截屏完成之后，出现截屏缩略图弹窗，支持倒计时关闭和手动滑动关闭此弹窗，但其实缩略图展示的时候，Activity已经关闭了，这种有方法可以实现吗，不想用addview这种方法QAQ

**Comment by li-xiaojun** [comment]
那你用WindowManager更方便
