### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by wangfens** [li-xiaojun/XPopup#1073]
**XPopup版本**
如2.9.16

**手机系统和型号**
 Android 6.0 和7.0

**描述你的问题**
空指针异常
Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.view.View.getLayoutParams()' on a null object reference
com.lxj.xpopup.util.XPopupUtils.lambda$applyPopupSize$1(XPopupUtils.java:176)

**Comment by li-xiaojun** [comment]
更新到最新版本
