### ISSUE TITLE
有没有可以在服务中启动的弹窗啊大佬，什么权限都有

### ISSUE THREAD

**Issue by Yangqingchun** [li-xiaojun/XPopup#1074]
**XPopup版本**
如2.1.0

**手机系统和型号**
华为Mate20 Android 10

**描述你的问题**
最好能上代码截图和问题截图

**Comment by li-xiaojun** [comment]
难道你的app没有一个activity吗？只要有activity，那就可以获取top activity进行弹窗啊？
