### ISSUE TITLE
底部弹窗手机适配问题

### ISSUE THREAD

**Issue by HelloJokerWord** [li-xiaojun/XPopup#1076]
**XPopup版本**
如2.9.15

**手机系统和型号**
oppo PBAM00 Android8.1.0

**描述你的问题**
底部会空出一段透明，然后打开的时候还会自己自动弹出键盘，其他手机是正常的。

![image](https://user-images.githubusercontent.com/18359626/209919033-80dec981-ac7c-44dc-b1eb-724b30f3317c.png)

其他手机是显示正常的
![image](https://user-images.githubusercontent.com/18359626/209919343-e7f2189d-0b8f-4e84-8442-0af9a6ba69e0.png)

![image](https://user-images.githubusercontent.com/18359626/209919431-ce40a8f4-be59-4a2f-aa04-5d5de3b7b67a.png)

**Comment by li-xiaojun** [comment]
@HelloJokerWord 用最新版

**Comment by HelloJokerWord** [comment]
> @HelloJokerWord 用最新版

大佬，我升级到最新的2.9.18 ， 还是会中间腾出一段空白。

![image](https://user-images.githubusercontent.com/18359626/210919538-abdb7e5f-a4d5-4742-8c65-173eeaa5b26c.png)

**Comment by li-xiaojun** [comment]
@HelloJokerWord bottom弹窗吗？布局和代码截个图

**Comment by HelloJokerWord** [comment]
> @HelloJokerWord bottom弹窗吗？布局和代码截个图

![image](https://user-images.githubusercontent.com/18359626/217754519-a19be1c2-1779-4911-abd1-457c4450fbf6.png)

使用：
 XPopup.Builder(it)
                    .asCustom(dialog)
                    .show()

**Comment by HelloJokerWord** [comment]
> > @HelloJokerWord bottom弹窗吗？布局和代码截个图
> 
> ![image](https://user-images.githubusercontent.com/18359626/217754519-a19be1c2-1779-4911-abd1-457c4450fbf6.png)
> 
> 使用： XPopup.Builder(it) .asCustom(dialog) .show()

是bottom
