### ISSUE TITLE
gradle报错，无法找到realtimeblurview库

### ISSUE THREAD

**Issue by MoonandMind** [li-xiaojun/XPopup#1077]
**XPopup版本**
2.9.17

**gradle 报错，提示无法找到com.github.mmin18:realtimeblurview:1.2.1**

gradle截图
![image](https://user-images.githubusercontent.com/5037839/209919945-e4b68cb8-2607-4605-b648-5e2b401051e6.png)

**Comment by li-xiaojun** [comment]
更新到2.9.18即可
