### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by fansangg** [li-xiaojun/XPopup#108]

**Comment by fansangg** [comment]
com.lxj.xpopup.photoview.Util.isSupportedScaleType(Util.java:29)
--
2 com.lxj.xpopup.photoview.PhotoViewAttacher.setScaleType(PhotoViewAttacher.java:480)
3 com.lxj.xpopup.photoview.PhotoView.setScaleType(PhotoView.java:99)

**Comment by li-xiaojun** [comment]
@fansangg 
最新版本1.6.7已修复此问题。
