### ISSUE TITLE
弹窗设置无阴影，底部导航栏有阴影

### ISSUE THREAD

**Issue by TwilightKHQ** [li-xiaojun/XPopup#1092]
**XPopup版本**
如2.9.19

**手机系统和型号**
Pixel 3 XL

**描述你的问题**
无弹窗时导航栏颜色
![uTools_1675326566519](https://user-images.githubusercontent.com/25874642/216271762-5f449a9e-d123-4cce-bd80-5b67c46c56be.png)
有弹窗时颜色
![uTools_1675326585289](https://user-images.githubusercontent.com/25874642/216271823-009b394f-c50a-47eb-8eb8-f4923faf7598.png)
弹窗设置无阴影时，导航栏被阴影覆盖了

Demo可以复现， Demo里的btnShowPosition2
```
case R.id.btnShowPosition2:
    new XPopup.Builder(getContext())
            .hasShadowBg(false)
            .hasBlurBg(false)
            .isDestroyOnDismiss(true) //对于只使用一次的弹窗，推荐设置这个
            .isCenterHorizontal(true)
            .offsetY(300)
            .isClickThrough(true)
            .enableDrag(false)
            .navigationBarColor(R.color.colorPrimary)
            .popupAnimation(PopupAnimation.TranslateAlphaFromTop)
            .asCustom(new QQMsgPopup(getContext()))
            .show();
```

**Comment by li-xiaojun** [comment]
@TwilightKHQ 把navigationBarColor设置为透明试试

**Comment by TwilightKHQ** [comment]
@li-xiaojun 
我理解错了参数的格式，这样就行了
`.navigationBarColor(getResources().getColor(R.color.colorAccent))`
