### ISSUE TITLE
不能设置弹窗宽高吗

### ISSUE THREAD

**Issue by LIBYER** [li-xiaojun/XPopup#11]
不能设置弹窗宽高吗

**Comment by LIBYER** [comment]
> @LIBYER
> 首先感谢您的Issue
> 对于自定的弹窗可以重写`getMaxWidth`和`getMaxHeight`方法来设置宽高；对于内置已经实现的常用弹窗，目前没有暴露方法。不过你这个建议我会采纳，我抽空加上。

能设置宽高还是蛮重要的，已经封装通用的，然后还只能去自定义设置宽高，就比较繁琐了

**Comment by li-xiaojun** [comment]
@LIBYER 
在最新版已经支持给弹窗设置宽高，但是只能对Center和Bottom类型的弹窗有效。具体使用可以看README
