### ISSUE TITLE
DrawerLayout问题，自定义阴影位置

### ISSUE THREAD

**Issue by ygeng** [li-xiaojun/XPopup#110]
如图，我想实现这样的效果，标题栏没有阴影，可以实现吗？
![image](https://user-images.githubusercontent.com/13791355/55784395-1224fa00-5ae3-11e9-9b0b-81a1e4fafbdc.png)

**Comment by li-xiaojun** [comment]
```java
ViewGroup.MarginLayoutParams params = (MarginLayoutParams) getPopupContentView().getLayoutParams();
params.topMargin = 450;
```

**Comment by sinduanan** [comment]
请问下， 这样设置topMargin后，黑色阴影顶部位置还是存在   怎么把上面得阴影也去掉
