### ISSUE TITLE
原生的elevation属性设置阴影不生效，对CardView兼容不够友好

### ISSUE THREAD

**Issue by fjyuqiang** [li-xiaojun/XPopup#111]
原生android:elevation设置阴影属性不生效，是否能增加个设置阴影的属性，另外CardView最父布局时，设置圆角属性，显示出的attachView还是矩形，边界会有圆角与底部的间隔（如下图）
![image](https://user-images.githubusercontent.com/18246136/55848211-bad46780-5b7e-11e9-9ad4-8ea5d5d80b10.png)

**Comment by li-xiaojun** [comment]
@fjyuqiang 
贴下你的布局

**Comment by fjyuqiang** [comment]
布局入之前发的图，布局代码
<?xml version="1.0" encoding="utf-8"?>
<android.support.v7.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    app:cardElevation="6dp"
    app:cardCornerRadius="4dp"
    >
    <TextView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:text="12123213"
        />

</android.support.v7.widget.CardView>

**Comment by li-xiaojun** [comment]
@fjyuqiang 
更新到1.6.9，现在弹窗自带完美的阴影，无需使用CardView。

**Comment by a1anwang** [comment]
> @fjyuqiang
> 更新到1.6.9，现在弹窗自带完美的阴影，无需使用CardView。

请问如何去掉这个自带的阴影
