### ISSUE TITLE
可不可以修改图片下载路径

### ISSUE THREAD

**Issue by meoogo** [li-xiaojun/XPopup#112]
可以不可以自定义图片下载路径,现在的路径位置是固定..

**Comment by li-xiaojun** [comment]
@meoogo 
不可以，既然保存到相册了，路径难道不是固定的？

**Comment by meoogo** [comment]
其实我的意思是可以不可以自定义文件夹..

**Comment by li-xiaojun** [comment]
@meoogo 
如果自定义文件夹，那就无法在相册中看到了。这个保存功能是保存到相册的意思，用户可以很方便的找到这张图片，如果每个人都自定义一个文件夹，用户很难找到这个图片。那保存功能还有什么意义呢？

**Comment by meoogo** [comment]
好吧.知道了.谢谢.
