### ISSUE TITLE
使用SubsamplingScaleImageView类加载图片时存在缓存

### ISSUE THREAD

**Issue by yunianshu** [li-xiaojun/XPopup#1125]
**XPopup版本**
如2.9.19

**手机系统和型号**
Pxels 3

**描述你的问题**
使用SubsamplingScaleImageView加载本地图片时候，当外部修改了图片内容，但是名字路径都没有改变时，显示的内容还是第一次加载的内容，我复制了SubsamplingScaleImageView代码，在Glide中添加了signature(new ObjectKey(System.currentTimeMillis()))，使用我自定义的类，图片就加载成功了，建议asImageViewer的时候添加设置签名的方法

**Comment by li-xiaojun** [comment]
你加了signature(new ObjectKey(System.currentTimeMillis()))缓存就没有意义了，每次都会重新获取图片，正常改图片内容一定会改图片路径，

**Comment by yunianshu** [comment]
我这个只是做个测试，实际我在ObjectKey传的是一个更新时间，如果这个更新时间不变，那就还是使用缓存的内容，只有当这个更新时间变化了，才会去更新这个图片。在所有数据列表中，其实我这边只会改变其中一条数据，其他数据还是使用缓存。当然我这个属于个例。
