### ISSUE TITLE
Android13 保存图片失败

### ISSUE THREAD

**Issue by AndroidBreathing** [li-xiaojun/XPopup#1152]
**XPopup版本**
2.9.17

**手机系统和型号**
Vivo x80 Android 13

**描述你的问题**
使用了大图预览 点击保存时 可能没有正确的授权 保存不成功
什么时候可以做一下13的权限兼容呢

**Comment by billdizl** [comment]
小伙子,你可以自己自定义布局来实现保存功能,在保存之前获取权限即可
