### ISSUE TITLE
空指针问题

### ISSUE THREAD

**Issue by m5314** [li-xiaojun/XPopup#117]
Attempt to invoke virtual method 'void android.view.ViewGroup.removeView(android.view.View)' on a null object reference
com.lxj.xpopup.XPopup$2$2.run（XPopup.java:156）
com.lxj.xpopup.core.BasePopupView$6.run（BasePopupView.java:339）

版本：1.5.2，关闭时报这个错，关闭时因为有动画导致这个时间内activity销毁后decorview为空的问题，希望能修复下

**Comment by li-xiaojun** [comment]
@m5314 
升级到最新版本吧。

**Comment by m5314** [comment]
@li-xiaojun 
我看了下最新版，dismiss的逻辑还是一样的吧，在动画结束后再去removeView，应该还是会有上面那个问题

**Comment by li-xiaojun** [comment]
@m5314 
更新到1.6.9，问题已经修复。

**Comment by m5314** [comment]
@li-xiaojun 好的，谢谢
