### ISSUE TITLE
SDK的版本必须要26及以上才可以使用吗

### ISSUE THREAD

**Issue by guizhongxiaobai** [li-xiaojun/XPopup#118]

**Comment by li-xiaojun** [comment]
@guizhongxiaobai
你自己的可以用不26，但是本地要有26以上的SDK，否则编译失败。话说现在谁的App的SDK还在26以下呢？targetSDK如果在26以下，有些应用市场都不让上。

**Comment by guizhongxiaobai** [comment]
本地有26以上的sdk，编译还是报错，targetSDK还是25，目前无权修改

**Comment by li-xiaojun** [comment]
报错截图我看看。

**Comment by guizhongxiaobai** [comment]
![image](https://user-images.githubusercontent.com/22098435/56194434-90dee180-6065-11e9-804f-371457a1a842.png)

**Comment by li-xiaojun** [comment]
@guizhongxiaobai 
你可以把compileSdkVersion改为26，targetSdkVersion保持不变。
