### ISSUE TITLE
继承了CenterPopupView，没有居中，会偏左，主要是自定义布局的宽度是固定的，就会这样

### ISSUE THREAD

**Issue by wangjiangliu0920** [li-xiaojun/XPopup#119]
自定义布局的宽度是固定的，这种现象就会出现，用match_parent就没有问题，但是这样就不叫自定义布局了

**Comment by li-xiaojun** [comment]
@wangjiangliu0920
该问题已修复，下个版本更新。

**Comment by li-xiaojun** [comment]
@wangjiangliu0920 
更新到1.6.9，问题已经修复。
