### ISSUE TITLE
何时切换成AndroidX

### ISSUE THREAD

**Issue by fairytale110** [li-xiaojun/XPopup#12]
何时切换成AndroidX？

**Comment by li-xiaojun** [comment]
@fairytale110 
如果现在切换成AndroidX，那么未迁移到AndroidX的用户(目前大多数都是)将无法使用；
对于已经迁移到AndroidX的用户，只需开启`android.enableJetifier`即可使用。
所以暂时没有这个打算，希望理解。

**Comment by fairytale110** [comment]
了解
