### ISSUE TITLE
自定义布局在点击事件中dismiss()会出现内存泄漏

### ISSUE THREAD

**Issue by wangjiangliu0920** [li-xiaojun/XPopup#120]
`protected void onCreate() {
            super.onCreate();
            findViewById(R.id.tv_close).setOnClickListener(new OnClickListener() {
                @Override
                public void onClick(View v) {
                    dismiss(); // 关闭弹窗
                }
            });
        }`

类似于这样，出现内存泄漏，提示是KeyboardUtils.onGlobalLayoutListener引用了一个activity对象一直没有释放，导致内存泄漏，可以试试在onClick执行退出activity就会报这个泄漏

**Comment by li-xiaojun** [comment]
@wangjiangliu0920 
更新到`1.7.1`，问题已修复。
