### ISSUE TITLE
1.6.9不支持圆角和背景透明问题

### ISSUE THREAD

**Issue by fjyuqiang** [li-xiaojun/XPopup#122]
更新1.6.9之后，AttachPopupView设置hasShadowBg（false）时，可以正常显示阴影，但是自定义的drawable设置的背景透明度和圆角都无法正常显示

bg代码如下 ：

### test.xml(drawable)

<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">
    <corners android:topLeftRadius="10dp"
        android:topRightRadius="10dp"
        />
    <solid android:color="@color/white80" />
</shape>

### test.xml(drawable-v21)

<?xml version="1.0" encoding="utf-8"?>
<ripple xmlns:android="http://schemas.android.com/apk/res/android"
    android:color="@color/app_common_ripple">

    <item android:drawable="@drawable/bg_white80_top_radius_10dp" />
</ripple>

**Comment by fjyuqiang** [comment]
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">
    <corners android:topLeftRadius="10dp"
        android:topRightRadius="10dp"
        />
    <solid android:color="@color/white80" />

</shape>

**Comment by fjyuqiang** [comment]
![image](https://user-images.githubusercontent.com/18246136/56278777-6c543980-6139-11e9-9369-8bdf4a7aacc3.png)
![image](https://user-images.githubusercontent.com/18246136/56278795-770ece80-6139-11e9-99bb-62032f27f6d3.png)

**Comment by li-xiaojun** [comment]
@fjyuqiang 
尝试使用getPopupContentView类似设置自定义的背景，不要在布局文件中设置。

**Comment by fjyuqiang** [comment]
![image](https://user-images.githubusercontent.com/18246136/56279565-f0f38780-613a-11e9-8095-20ae2174a21b.png)
使用getPopupContentView，还是没有生效

**Comment by li-xiaojun** [comment]
在onCreate中设置

**Comment by li-xiaojun** [comment]
@fjyuqiang 
更新到1.7.0，Attach弹窗提供了`getPopupBackground()`方法用来自定义弹窗的背景，重写这个方法，返回一个Drawable即可。
