### ISSUE TITLE
CenterPopupView弹窗宽度无法占满屏幕

### ISSUE THREAD

**Issue by fumayer** [li-xiaojun/XPopup#1226]
XPopup.Builder(requireContext())
                .isDestroyOnDismiss(true)
                .popupWidth(ScreenUtils.getScreenWidth())
                .asCustom(
                    SignInCenterDialog(requireContext())
                ).show()

    override fun getPopupWidth(): Int {
        return ScreenUtils.getScreenWidth()+1000
    }
两种方法都试了，还是无法占满屏幕宽度

**Comment by liuya891012** [comment]
我也发现这个问题，不过文档写了，可以重写getMaxWidth
![image](https://github.com/user-attachments/assets/8fe4cf15-5309-457d-bd0e-fb2dffed8ef1)
