### ISSUE TITLE
底部导航栏适配问题

### ISSUE THREAD

**Issue by chenhang19920630** [li-xiaojun/XPopup#124]
三星S8+，android9.0（One UI），导航栏设置为“全屏手势”后，底部导航栏如图所示
![Screenshot_20190418-153327_XPopup](https://user-images.githubusercontent.com/20785879/56344426-f7900680-61ef-11e9-8f6d-9be47996e1fd.jpg)
![Uploading Screenshot_20190418-153312_XPopup.jpg…]()

**Comment by li-xiaojun** [comment]
@chenhang19920630 这个切换全屏和导航栏暂时无法精确识别，而且目前是部分机型有问题，需要一些时间来解决。

**Comment by LouisShark** [comment]
@li-xiaojun 请问解决了吗

**Comment by li-xiaojun** [comment]
@LouisShark 可以试试新版本看看有没有这个问题。

**Comment by li-xiaojun** [comment]
更新到1.8.8即可。

**Comment by siyukok** [comment]
三星S8，Android9.0问题仍然存在

**Comment by siyukok** [comment]
![image](https://user-images.githubusercontent.com/21030561/64094679-0df9c180-cd8f-11e9-920b-18543e414904.png)
