### ISSUE TITLE
输入法弹起的底部多弹窗隐藏输入法后弹窗没有回弹

### ISSUE THREAD

**Issue by Zerbaoo** [li-xiaojun/XPopup#125]
![QQ截图20190418184356](https://user-images.githubusercontent.com/16794924/56355993-43e84000-620a-11e9-8533-0b5d433cd935.png)
![QQ截图20190418184419](https://user-images.githubusercontent.com/16794924/56356036-5ebab480-620a-11e9-84e0-0ec4d8f27ef9.png)

**Comment by li-xiaojun** [comment]
@Zerbaoo 
更新到1.7.0，该问题已修复。
