### ISSUE TITLE
 android.content.res.Resources$NotFoundException: Resource ID #0x0

### ISSUE THREAD

**Issue by Zerbaoo** [li-xiaojun/XPopup#126]
recycleview引用BaseQuickAdapter，点击item，自定义CenterPopupView弹窗 
报错 
android.content.res.Resources$NotFoundException: Resource ID #0x0

**Comment by li-xiaojun** [comment]
@Zerbaoo 
找不到资源和弹窗没有关系，可以贴个代码吗？

**Comment by UsingMisz** [comment]
在使用attachView的时候也会报这个错误 使用自定义的bottomView时候不会报这个错误
