### ISSUE TITLE
1.6.9版本，部分impl里的PopupView仍然使用CommonAdapter

### ISSUE THREAD

**Issue by TheStar4Fate** [li-xiaojun/XPopup#128]
Android Studio升级到3.4.0后报错，提示找不到CommonAdapter。我新增了您的另一个库implementation 'com.lxj:easyadapter:latest release'的依赖后，将CommonAdapter改为EasyAdapter，才正常通过编译。之后我发现com.lxj.xpopup.impl包里还有部分PopupView使用的还是CommonAdapter，希望您能及时修改一下，谢谢。
简单看了一下，这三个类是有问题的类AttachListPopupView,BottomListPopupView,CenterListPopupView

**Comment by TheStar4Fate** [comment]
![AttachListPopupView](https://user-images.githubusercontent.com/7358871/56419265-385d4d80-62cc-11e9-9f69-d832b28cf0b7.png)
![BottomListPopupView](https://user-images.githubusercontent.com/7358871/56419271-3b583e00-62cc-11e9-8696-820530a96029.png)
![CenterListPopupView](https://user-images.githubusercontent.com/7358871/56419275-3e532e80-62cc-11e9-97dc-8c0f46de7bdc.png)
补几张图

**Comment by li-xiaojun** [comment]
@TheStar4Fate 
好的，我改下。

**Comment by li-xiaojun** [comment]
@TheStar4Fate 
更新到1.7.0，该问题已修复。
