### ISSUE TITLE
耦合略严重

### ISSUE THREAD

**Issue by ezfantasy** [li-xiaojun/XPopup#129]
Builder PopupInfo 都不对外提供，想自定义上中下，非得自定义UI或者改你源码或者反射

**Comment by li-xiaojun** [comment]
1. popupInfo的所有参数都由你自己传入
2. 想自定义上中下指的什么，能说清楚点？
3. 弹窗的自定义设计的已经很好，你有需求尽量详细说明，如果文字描述的不够，直接上图，ok?

**Comment by ezfantasy** [comment]
老弟，你生气了。。。 asConfirm-popupType(PopupType.Center); 你让asConfirm 怎么自定义位置中下，明白了吗？当我没说吧，本来也不可能满足所有人的需求。

**Comment by li-xiaojun** [comment]
@ezfantasy 
内置弹窗的实用性很有限，无论怎么改也不可能满足所有人的需求，目前我不太愿意给内置弹窗添加额外特性，一来会增加代码量，而来实用性太小。所以更推荐自定义弹窗。
