### ISSUE TITLE
点击事件执行时间

### ISSUE THREAD

**Issue by qiushui95** [li-xiaojun/XPopup#13]
我希望点击事件触发dismiss 。dismiss动画执行完之后再执行点击逻辑。请问现有接口能否实现该想法

**Comment by qiushui95** [comment]
点了按钮就跳转界面  我感觉比较生硬

**Comment by li-xiaojun** [comment]
@qiushui95 
您可以给每个弹窗设置一个显示和隐藏的监听器，如下图：
![1545742996 1](https://user-images.githubusercontent.com/4426715/50422794-8fa46180-0888-11e9-90d4-1d27e279d7c0.jpg)
