### ISSUE TITLE
asConfirm某个方法错误

### ISSUE THREAD

**Issue by kokod21** [li-xiaojun/XPopup#131]
Xpopup类，309行
        public ConfirmPopupView asConfirm(String title, String content, OnConfirmListener confirmListener, OnCancelListener cancelListener) {
            return asConfirm(title, content, confirmListener, null, false);
        }
传了cancelListener进去，但是你方法里面调用是写了一个null，1.7.0版本还是有这个问题

**Comment by li-xiaojun** [comment]
@kokod21 严谨，感谢指正，下个版本修复。

**Comment by li-xiaojun** [comment]
@kokod21 
更新到`1.7.1`，问题已修复。
