### ISSUE TITLE
atView(view)方法传目标控件，显示位置有问题

### ISSUE THREAD

**Issue by chengmenghuiAndroid** [li-xiaojun/XPopup#132]
在已经弹出的Dialog上，标题文字下需要显示气泡popWindow，atView(view)方法传目标控件，弹出的气泡popWindow被已经存在Dialog覆盖，不是显示在目标控件下面

**Comment by li-xiaojun** [comment]
@chengmenghuiAndroid 
XPopup是附在decorView上，所以会被系统的Dialog和PopupWindow覆盖。另外你可以贴个截图，这样一目了然。

**Comment by chengmenghuiAndroid** [comment]
> @chengmenghuiAndroid
> XPopup是附在decorView上，所以会被系统的Dialog和PopupWindow覆盖。另外你可以贴个截图，这样一目了然。

我已经在邮件中回复

**Comment by li-xiaojun** [comment]
@chengmenghuiAndroid 
邮件中没有收到截图，请给个截图

**Comment by li-xiaojun** [comment]
@chengmenghuiAndroid 问题解决了吗。

**Comment by chengmenghuiAndroid** [comment]
我自定义了一个pop解决了,你不是说你的项目XPopup是附在decorView上，所以会被系统的Dialog和PopupWindow覆盖。所以就没用你的
  

  

 

 ------------------ 原始邮件 ------------------
  发件人: "李晓俊"<notifications@github.com>;
 发送时间: 2019年4月26日(星期五) 上午9:08
 收件人: "li-xiaojun/XPopup"<XPopup@noreply.github.com>;
 抄送: "Aaron"<cheng_oop@foxmail.com>; "Mention"<mention@noreply.github.com>; 
 主题: Re: [li-xiaojun/XPopup] atView(view)方法传目标控件，显示位置有问题 (#132)

 

 
@chengmenghuiAndroid 问题解决了吗。

**Comment by chengmenghuiAndroid** [comment]
> 我自定义了一个pop解决了,你不是说你的项目XPopup是附在decorView上，所以会被系统的Dialog和PopupWindow覆盖。所以就没用你的
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "李晓俊"<notifications@github.com>; 发送时间: 2019年4月26日(星期五) 上午9:08 收件人: "li-xiaojun/XPopup"<XPopup@noreply.github.com>; 抄送: "Aaron"<cheng_oop@foxmail.com>; "Mention"<mention@noreply.github.com>; 主题: Re: [li-xiaojun/XPopup] atView(view)方法传目标控件，显示位置有问题 (#132) @chengmenghuiAndroid 问题解决了吗。 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

别的地方还是用的你pop，希望以后能优化

**Comment by chengmenghuiAndroid** [comment]
别的地方弹出pop还是使用的依赖库，希望以后能优化
