### ISSUE TITLE
moveUpToKeyboard()有点问题

### ISSUE THREAD

**Issue by slgluo** [li-xiaojun/XPopup#133]
moveUpToKeyboard()默认打开，不加此方法或设置为true时，弹出输入法时，对话框下移，本来输入法不覆盖对话框，下移反而被覆盖了。应该是里面的计算逻辑有点问题，希望尽快修复

**Comment by li-xiaojun** [comment]
@slgluo 
首先确认是否是最新版本，如果是的话请加我扣扣：16167479，录制个小视频发我，这样更快定位问题。

**Comment by slgluo** [comment]
关于下面这一段代码：
```
if (pv instanceof CenterPopupView) {
            int targetY = keyboardHeight - (windowHeight - popupHeight + getStatusBarHeight()) / 2; //上移到下边贴着输入法的高度

            if (focusEt != null && focusEtTop - targetY < 0) {
                targetY += focusEtTop - targetY - getStatusBarHeight();//限制不能被状态栏遮住
            }
            dy = targetY;
 }
```
1. 如果target为负，对话框会下移。即对话框的底部是在输入法上面的
2. getStatusBarHeight()是不是可以不用加回来？我昨天测了手上的几个机型，发现不加上这个，正好不覆盖对话框

**Comment by li-xiaojun** [comment]
@slgluo 你的那个荣耀8X机型我暂时没有找到，试试最新版本有没有解决，我会继续寻找对应的机型。

**Comment by brady2037** [comment]
> 关于下面这一段代码：
> 
> ```
> if (pv instanceof CenterPopupView) {
>             int targetY = keyboardHeight - (windowHeight - popupHeight + getStatusBarHeight()) / 2; //上移到下边贴着输入法的高度
> 
>             if (focusEt != null && focusEtTop - targetY < 0) {
>                 targetY += focusEtTop - targetY - getStatusBarHeight();//限制不能被状态栏遮住
>             }
>             dy = targetY;
>  }
> ```
> 1. 如果target为负，对话框会下移。即对话框的底部是在输入法上面的
> 2. getStatusBarHeight()是不是可以不用加回来？我昨天测了手上的几个机型，发现不加上这个，正好不覆盖对话框

@li-xiaojun 
同是因为这段代码，会造成遮挡布局底部按钮问题

##### 依赖环境

com.lxj:xpopup:1.7.2
mainfest->Activity:  `android:windowSoftInputMode="adjustResize"`

##### 问题

发现原因是弹出软键盘时，窗口上移距离计算的问题
[GIF链接](https://lance-img.nos-eastchina1.126.net/nvl92-c0dxw.gif)
![问题示意](https://lance-img.nos-eastchina1.126.net/nvl92-c0dxw.gif)
##### 代码修改

![修改后代码](https://lance-img.nos-eastchina1.126.net/%E7%A4%BA%E6%84%8F%E5%9B%BE.png)

**Comment by li-xiaojun** [comment]
@brady2037 @slgluo 
检查是否在清单文件中给Activity添加`android:windowSoftInputMode="adjustResize"`了，尝试去掉试试。

**Comment by li-xiaojun** [comment]
@brady2037 你的这个机型和系统版本说下。

**Comment by li-xiaojun** [comment]
@slgluo @brady2037 更新到1.7.3试试。
