### ISSUE TITLE
请支持 AndroidX

### ISSUE THREAD

**Issue by KunMinX** [li-xiaojun/XPopup#134]
support库官方从此往后不再维护了，一切都会基于 AndroidX 继续。。

**Comment by li-xiaojun** [comment]
![9{(@_ AT7E(RQ3{@$9K S](https://user-images.githubusercontent.com/4426715/56850043-76dbb380-692f-11e9-8532-7e771da10db5.png)

**Comment by KunMinX** [comment]
@li-xiaojun get，666

**Comment by KunMinX** [comment]
@li-xiaojun 

ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not download easyadapter.aar (com.lxj:easyadapter:1.1.1)
Show Details
Affected Modules: app

疑似网络不佳，请提供maven类似以下的maven地址：
repositories {
        maven { url "https://dl.bintray.com/viabus-architecture/maven/" }
}
