### ISSUE TITLE
刘海屏图片预览不完整

### ISSUE THREAD

**Issue by lh1241698502** [li-xiaojun/XPopup#138]
测试手机小米8
预览长图，顶部区域展示不完整，有刘海屏高度的内容展示不出来

**Comment by li-xiaojun** [comment]
@lh1241698502 请截个图展示一些，这样更好定位。

**Comment by zofnk** [comment]
![微信图片_20190507103721](https://user-images.githubusercontent.com/17997544/57267850-27764f80-70b4-11e9-967f-9184c502cfb3.jpg)
这老哥应该是说这样的.... 不管怎么放大 , 被刘海屏遮住的那部分怎么都显示不出来

**Comment by li-xiaojun** [comment]
@zofnk @lh1241698502 
这个问题我想想怎么处理比较优雅。

**Comment by li-xiaojun** [comment]
@zofnk @lh1241698502 
最新版本做了优化，具体是当图片滑到顶部时，如果再往下滑就会整体移出遮挡区域；上滑时会回归原位。请更新版本或者下载Apk进行体验。

**Comment by zofnk** [comment]
@li-xiaojun 为什么不像微信那样 , 宽<高的图  , 就宽度占满屏幕 然后可以上下滑动... 即使被挡住了 , 往下拉一点 就会看到被遮挡的内容

**Comment by li-xiaojun** [comment]
@zofnk @lh1241698502 
新版本已优化成微信那样的体验，请更新1.7.6
