### ISSUE TITLE
小米8和小米8se 9.0系统自定义弹窗里面有viewpager+recyclerview+刷新框架,无法上拉刷新

### ISSUE THREAD

**Issue by lodgkk** [li-xiaojun/XPopup#141]
小米8和小米8se 9.0系统自定义弹窗里面有viewpager+recyclerview+刷新框架,无法上拉刷新,还有一个问题是全屏弹窗的时候,底部有空隙,和以前报的华为空隙一样

**Comment by lodgkk** [comment]
就是无法滑动,但是5.1的魅族没问题

**Comment by li-xiaojun** [comment]
@lodgkk 有demo工程吗，可以发我一份，加扣扣。

**Comment by lodgkk** [comment]
我的qq是44437337

**Comment by li-xiaojun** [comment]
@lodgkk 可以加QQ群：783659607。

**Comment by lodgkk** [comment]
小米8和小米8se 9.0系统自定义弹窗里面有viewpager+recyclerview+刷新框架,无法上拉刷新,这个问题已经解决,我这边的问题

**Comment by lodgkk** [comment]
全屏设置高度会有一部分空白,因为小米8和小米8se设置全面屏之后,底部导航栏还是在,但是隐藏了,可是获取到的高度却没有达到全部,所以到时底部透明

**Comment by lodgkk** [comment]
有个获取真实高度的方法,我用了,解决了
