### ISSUE TITLE
查看大图的"n/y"自带指示器不能去除

### ISSUE THREAD

**Issue by zofnk** [li-xiaojun/XPopup#142]
1.
![Z65KMB4D_`_3( N@E%@AZO5](https://user-images.githubusercontent.com/17997544/57429588-3fd69d80-725f-11e9-81f8-7ad4a9c72755.png)
需要隐藏这个, 并且能否开放showPagerIndicator方法, 当url.size()=1的时候 , 来自定义自己的指示器显示与否

2.最新的setSingleSrcView , 没有设置在多个点击的时候
![image](https://user-images.githubusercontent.com/17997544/57429677-b07dba00-725f-11e9-98ce-1586c8202d5f.png)
用这样虽然可以解决, 但在背景为半透明 , 切换图片的时候 , 该图片在它原有位置上会显示成白色

![image](https://user-images.githubusercontent.com/17997544/57429782-1c602280-7260-11e9-84d1-7b1a543ae042.png)
![image](https://user-images.githubusercontent.com/17997544/57429822-431e5900-7260-11e9-918a-31a137cb5735.png)

**Comment by zofnk** [comment]
最后那个情况视频我放在群里了..,麻烦看看~

**Comment by li-xiaojun** [comment]
@zofnk 
新版本已经支持，请更新试试。
