### ISSUE TITLE
webview加载html点击图片预览

### ISSUE THREAD

**Issue by zouwansheng** [li-xiaojun/XPopup#143]

**Comment by zouwansheng** [comment]
ImageView imageView = new ImageView(this);
new XPopup.Builder(this)
                    .asImageViewer(imageView,
                            position, imageList, new OnSrcViewUpdateListener() {
                @Override
                public void onSrcViewUpdate(ImageViewerPopupView popupView, int position) {
                    popupView.updateSrcView(imageView);
                }
            }, new MyImageLoader())
                    .show();
这是我在webview中，点击图片预览，但是会闪一下，然后点击预览图回到这个页面的时候，会再闪动一下，很明显。因为点击的是webview中的图片，没有图片控件计算位置，我new的imageview这么处理的，问下怎么回事

**Comment by li-xiaojun** [comment]
@zouwansheng 
new的ImageView并没有在View树中存在，没有坐标位置，XPopup找不到srcView的位置就显示异常。
目前框架还不支持从webview中显示大图浏览，很抱歉。
你可以更改下方案，直接开启一个Activity进行大图浏览。

**Comment by zouwansheng** [comment]
> @zouwansheng
> new的ImageView并没有在View树中存在，没有坐标位置，XPopup找不到srcView的位置就显示异常。
> 目前框架还不支持从webview中显示大图浏览，很抱歉。
> 你可以更改下方案，直接开启一个Activity进行大图浏览。
在看源码，我试着去在webview中覆盖一个imageview试图设置他的windowLocation，还是有卡顿，可以试下你这个方案，谢谢
