### ISSUE TITLE
PartShadowPopupView 列表筛选的下拉弹问题

### ISSUE THREAD

**Issue by zbore** [li-xiaojun/XPopup#144]
demo 中的例子是弹出后，再点击就收回了，看上去并没有什么问题
但是我这边业务情况是，弹出后，再选择其他的弹出项，继续弹出，

于是我就先关掉已打开弹窗，然后继续打开新窗口， 这时候会产生抖动不流畅的现象
个人估计是由于先关闭再打开导致动画问题，希望可以探讨下! 目前暂无解决方案

**Comment by li-xiaojun** [comment]
@zbore 
这个我思考下如何优雅的解决。

**Comment by li-xiaojun** [comment]
@zbore 
要想流畅的根本手段就是动画不要同时进行，dismiss动画完了再show，给你个代码示例，这个是可以流程运行的：
```java
private void showPartShadow(final View v){
        //如果处于显示中就return
        if(popupView!=null && popupView.isShow())return;
        popupView = (CustomPartShadowPopupView) new XPopup.Builder(getContext())
                .atView(v)
                .setPopupCallback(new XPopupCallback() {
                    @Override
                    public void onShow() {
                        toast("显示了");
                    }
                    @Override
                    public void onDismiss() {
                        popupView = null;
                        showPartShadow(v); //消失之后再显示
                    }
                })
                .asCustom(new CustomPartShadowPopupView(getContext()));
        popupView.show();
    }
```

**Comment by zbore** [comment]
@li-xiaojun 我用dismissWith方案，但是这个方案缓存存了Runnable, 点返回或者取消的时候都会调用一次, 要是api能动态改变dismissWithRunnable就好了，比如设置为空
`
private void showQFPopDialog(boolean show, final int position) {
        if (selectPos != -1 && selectPos != position) {
            // 清除选中状态
            popupViews.get(selectPos).dismissWith(new Runnable() {
                @Override
                public void run() {
                    doShowPop(show, position);
                }
            });
        } else {
            doShowPop(show, position);
        }
    }

    private void doShowPop(boolean show, int position) {
        if (show) {
            popupViews.get(position).show();

        } else {
            popupViews.get(position).dismiss();
        }
    }
`

**Comment by li-xiaojun** [comment]
@zbore 
这个缓存新版本已修复，请更新1.7.6

**Comment by zbore** [comment]
厉害！！！速度惊人

**Comment by li-xiaojun** [comment]
@zbore 
觉得好用，可以给自己的朋友推荐一波。
