### ISSUE TITLE
确认弹窗在没有取消监听时仍然有取消按钮！

### ISSUE THREAD

**Issue by Moonkan** [li-xiaojun/XPopup#145]
public ConfirmPopupView asConfirm(String title, String content, OnConfirmListener confirmListener) {
            return asConfirm(title, content, null, null, confirmListener, null, false);
        }

个人认为最后一个参数应该是true

**Comment by li-xiaojun** [comment]
@Moonkan 
我的考虑是这样的：这个参数的设计其实和有没有取消监听器没有太大关系，大部分情况都不需要取消监听器；但大部分时候是需要取消按钮的。
所以，目前可能不会进行更改。

**Comment by zhaoxiuyu** [comment]
这个类ConfirmPopupView，isHideCancel属性能不能开放出来，我想动态改变
