### ISSUE TITLE
asLoading能否像安卓的progressDialog一样有title和message？

### ISSUE THREAD

**Issue by zhihaofans** [li-xiaojun/XPopup#15]
如果有的话就可以显示loading时的状态了

**Comment by zhihaofans** [comment]
还有asLoading()有时dismiss()无效，但setPopupCallback监听到dismiss事件

**Comment by li-xiaojun** [comment]
@zhihaofans 
好想法，我抽空加上哈

**Comment by li-xiaojun** [comment]
@zhihaofans 
感谢您的建议和想法。
在最新的`1.0.4`版本中，已经支持给Loading弹窗设置标题。另外dismiss无效的情况我还没有遇到过，我会继续关注这个问题。
