### ISSUE TITLE
xpopup 如果不是activity ，无法弹出窗口

### ISSUE THREAD

**Issue by zhujunjun** [li-xiaojun/XPopup#151]
趣键盘：我们是做输入法开发的项目。目前正在采用您的库。发现以下问题：
1.在键盘上 点击按钮，无法弹出窗口。因为键盘的context 是InputMethodService ，所以service 是无法弹出窗口。这个是否有办法解决？
2.弹窗没有显示在键盘输入法之上，反而是被键盘给覆盖了。

**Comment by li-xiaojun** [comment]
@zhujunjun 
目前的弹窗需要依赖Activity的，否则很多测量和计算无法进行，如果是Service的话目前是不能用的。

**Comment by dary123** [comment]
我是全局保存了当前activity，传的是当前的activity,但是仍然不弹出

**Comment by li-xiaojun** [comment]
@zhujunjun 您可以通过保存你的Activity引用，只要这个Activity在显示，就能弹出弹窗。
