### ISSUE TITLE
【建议】图片预览长图看不清

### ISSUE THREAD

**Issue by dragon-y** [li-xiaojun/XPopup#152]

**Comment by li-xiaojun** [comment]
@dragon-y 
请截个图，不然不知道你那边是什么样的，我测试的长图都没有问题，能给出长图的url地址更好。

**Comment by dragon-y** [comment]
@li-xiaojun    这是长图的地址 ，请您看下  http://218.56.110.189:14189/admin/file/filedownload?filename=3gq2l6mk1x1557923362338fjjfu.png&oldfilename=oldfilename

**Comment by li-xiaojun** [comment]
@dragon-y 
我这边显示非常清晰：
![image](https://user-images.githubusercontent.com/4426715/57834189-55fbd500-77ee-11e9-80d2-f60f8ba0c097.png)

**Comment by li-xiaojun** [comment]
@dragon-y 你用的是最新版本吗？

**Comment by dragon-y** [comment]
我再测试一下 @li-xiaojun

**Comment by li-xiaojun** [comment]
@dragon-y 
另外给你提个醒，你们的图片是http连接，在Android9.0系统上所有不是`https`的请求都会失败；可以尽快适配这个问题。

**Comment by dragon-y** [comment]
@dragon-y    好的，谢谢大神

**Comment by dragon-y** [comment]
@li-xiaojun   忘记了设置 override(Target.SIZE_ORIGINAL)

**Comment by li-xiaojun** [comment]
@dragon-y 
你那个图片最好让服务器压缩下，现在是2M多，在低端机上容易内存溢出的。

**Comment by dragon-y** [comment]
@li-xiaojun   好的
