### ISSUE TITLE
如果我在fragmentdialog上show，则会被这个fragmentdialog所遮挡

### ISSUE THREAD

**Issue by fansangg** [li-xiaojun/XPopup#153]

**Comment by fansangg** [comment]
popup无法在最上层显示

**Comment by li-xiaojun** [comment]
@fansangg 
是这样的，XPopup本质上是在decorView上盖一个临时的View，所以无法处于系统的Dialog之上。您可以选择使用XPopup替代之前的FragmentDialog。

**Comment by li-xiaojun** [comment]
@fansangg 
最新版本已经支付覆盖到dialog上面，请更新到最新版本
