### ISSUE TITLE
自定义弹框不显示

### ISSUE THREAD

**Issue by dary123** [li-xiaojun/XPopup#155]
是在小米推送里的BroadcastReceiver：
Log.e("33","弹出来了11");
                    new XPopup.Builder(context)
                            .asCustom(new FilmReceiveInvationPopup(context,json.optString("userAvatar"),json.optString("userName"),json.optString("filmImg"),json.optString("filmTit"),json.optString("filmUrl"),json.optString("roomName")))
                            .show();
                    Log.e("33","弹出来了22");

package com.vc.app.ui.PopupWindow;

import android.content.Context;
import android.content.Intent;
import android.net.Uri;
import android.view.View;
import android.widget.TextView;

import androidx.annotation.NonNull;

import com.facebook.drawee.view.SimpleDraweeView;
import com.lxj.xpopup.animator.PopupAnimator;
import com.lxj.xpopup.core.CenterPopupView;
import com.vc.app.R;
import com.vc.app.activity.FilmActivity.FilmPlayerAudienceActivity;

import java.util.ArrayList;
import java.util.Arrays;

/**
 * Created by zy on 2019/5/16.
 */
public class FilmReceiveInvationPopup extends CenterPopupView {
    //自定义弹窗本质是一个自定义View，但是只需重写这个构造，其他的不用重写
    private Context mContext;
    private String userAvatar;
    private String userName;
    private String filmImg;
    private String filmTit;
    private String filmUrl;
    private String watchId;
    public FilmReceiveInvationPopup(@NonNull Context context,String userAvatar,String userName,String filmImg,String filmTit,String filmUrl,String watchId) {
        super(context);
        this.mContext = context;
        this.userAvatar = userAvatar;
        this.userName = userName;
        this.filmImg = filmImg;
        this.filmTit = filmTit;
        this.filmUrl = filmUrl;
        this.watchId = watchId;
    }
    // 返回自定义弹窗的布局
    @Override
    protected int getImplLayoutId() {
        return R.layout.dialog_receive_filminvation;
    }
    // 执行初始化操作，比如：findView，设置点击，或者任何你弹窗内的业务逻辑
    @Override
    protected void onCreate() {
        super.onCreate();
        SimpleDraweeView join_blur_bg = findViewById(R.id.join_blur_bg);
        join_blur_bg.setImageURI(Uri.parse(filmImg));
        TextView join_des = findViewById(R.id.join_des);
        SimpleDraweeView join_avatar = findViewById(R.id.join_avatar);
        join_avatar.setImageURI(Uri.parse(userAvatar));
        TextView join_name = findViewById(R.id.join_name);
        join_name.setText(userName);
        join_des.setText(userName+"邀请你一起看《"+filmTit+"》");
        findViewById(R.id.invitation_container).setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                dismiss(); // 关闭弹窗
                Intent intent = new Intent();
                intent.setClass(mContext, FilmPlayerAudienceActivity.class);
                intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK );
                intent.putExtra("image",filmImg);
                intent.putExtra("title",filmTit);
                String[] filmUrls = filmUrl.split(";");
                ArrayList<String> filmUrlsList = new ArrayList<>(Arrays.asList(filmUrls));
                intent.putStringArrayListExtra("urls",filmUrlsList);
                intent.putExtra("watchId",watchId);
                mContext.startActivity(intent);
            }
        });
    }
    // 设置最大宽度，看需要而定
    @Override
    protected int getMaxWidth() {
        return super.getMaxWidth();
    }
    // 设置最大高度，看需要而定
    @Override
    protected int getMaxHeight() {
        return super.getMaxHeight();
    }
    // 设置自定义动画器，看需要而定
    @Override
    protected PopupAnimator getPopupAnimator() {
        return super.getPopupAnimator();
    }
    /**
     * 弹窗的宽度，用来动态设定当前弹窗的宽度，受getMaxWidth()限制
     *
     * @return
     */
    protected int getPopupWidth() {
        return 0;
    }

    /**
     * 弹窗的高度，用来动态设定当前弹窗的高度，受getMaxHeight()限制
     *
     * @return
     */
    protected int getPopupHeight() {
        return 0;
    }
}

**Comment by dary123** [comment]
log日志只打印出：弹出来了11

**Comment by dary123** [comment]
好像是上下文context的问题，我在fragment里是可以显示的

**Comment by li-xiaojun** [comment]
@dary123 
目前不支持Application上下文，Service类型上下文和广播中的上下文，只支持Activity上下文，Fragment的上下文，View的上下文。

**Comment by dary123** [comment]
![image](https://user-images.githubusercontent.com/12826258/57897592-24cfe300-7888-11e9-8f64-8d219332651b.png)
我把每次进入的Activity都存入栈里，传入的就是当前Activity，按理来说应该是可以的呀，为什么还是不显示

**Comment by li-xiaojun** [comment]
可以换个思路啊，你接收到广播后用EventBus发个事件通知Activity显示弹窗，这样也解耦了。在Activity中订阅显示弹窗的事件。

**Comment by dary123** [comment]
我刚开始也是这样想的，但是第一工作量太大，虽然每个页面都是继承的同一个父类Activity，但是有些Activity我已经加了EventBus，如果在通用的父类Activity中再注册一个EventBus我怕出问题，第二，这样每个页面都需要监听事件，是不是会影响性能，本来有些页面完全不需要监听任何事件的

**Comment by dary123** [comment]
希望这个库还是支持下广播上下文，毕竟我也仅仅是因为这个需求才找到这个库的

**Comment by dary123** [comment]
解决了，(Context) AppManager.AppManager.currentActivity()，这样强制转换下就可以了，嘿嘿

**Comment by dary123** [comment]
但是好像还有个问题， 如果在应用在后台运行弹出的话，进入前台只显示背景暗掉的遮罩，弹框却没有显示

**Comment by li-xiaojun** [comment]
@dary123 应用在后台肯定是无法显示的，这时候activity都没有窗体，无法挂载弹窗。

**Comment by dary123** [comment]
那能不能加个判断，在后台的话，不要显示背景遮罩，直接不弹出弹框，现在是有有个暗色的背景遮罩的

**Comment by li-xiaojun** [comment]
@dary123 
这个判断你完全可以自己加，我是没法加的，因为我不知道你的应用什么时候进入后台，你可以在广播中进行判断，如果在后台就return。
