### ISSUE TITLE
android 横屏，弹窗没有铺满屏幕，左侧有空白。请看附件。

### ISSUE THREAD

**Issue by 1395881288** [li-xiaojun/XPopup#156]
![1](https://user-images.githubusercontent.com/24973451/57963406-5c0cc580-7956-11e9-959a-ebde0a240656.png)

**Comment by 1395881288** [comment]
手机不是水滴屏，普通的四四方方的屏幕， 华为 努比亚手机 都是这样。

**Comment by li-xiaojun** [comment]
@1395881288 
最新版本已经发布，更新下试试。

**Comment by 1395881288** [comment]
测试 已经正常了，这个bug 你一会儿时间就修复了，神速，祝这个项目越来越火。

**Comment by Elaine666** [comment]
什么原因呀？作者
