### ISSUE TITLE
类似微博超长图显示不出

### ISSUE THREAD

**Issue by zofnk** [li-xiaojun/XPopup#157]
特别长的 , 类似漫画的超长图 , 无法显现 , 日志为
```
W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (870x19710, max=8192x8192)
```

**Comment by zofnk** [comment]
机型 : 华为Honor 9 Lite

**Comment by li-xiaojun** [comment]
@zofnk 
这是Glide本身存在的问题，和XPopup无关，XPopup本身不提供加载图片的功能，请看：https://github.com/bumptech/glide/issues/2313

从上述连接中可以找到解决方案。
