### ISSUE TITLE
activity不可见时请求弹出对话框的时候无法显示，只显示了后面的半透明背景

### ISSUE THREAD

**Issue by wangjiangliu0920** [li-xiaojun/XPopup#158]
new XPopup.Builder(this)
                .hasShadowBg(true)
                .dismissOnTouchOutside(false)
                .dismissOnBackPressed(true)
                .asCustom(new AuthorizeRequestPopup(this)
                .setContentMsg(content)
                .setConfirmListener(new DialogConfirmListener() {
                    @Override
                    public void onConfirm(String text) {
                        //同意设备请求，调用同意请求的接口
                        if (mPresenter != null) {
                            mPresenter.agreeRequestAuthorize(fromUuid);
                        }
                    }
                }))
                .show();
这是我的弹框代码，看是否还有其他show方法可解决这个问题的呢
类似于：dialogFragment的commitAllowingStateLoss的策略

**Comment by wangjiangliu0920** [comment]
看到别的issue,这个功能貌似框架不支持，只能自己代码控制了

**Comment by li-xiaojun** [comment]
@wangjiangliu0920 
目前不支持在应用退到后台时弹出弹窗。
