### ISSUE TITLE
多图预览的时候，会卡顿  （图片很大的）

### ISSUE THREAD

**Issue by heimaxiaobo** [li-xiaojun/XPopup#159]

**Comment by heimaxiaobo** [comment]
“”http://app.xiangshujiaoyu.com/upload/images/8b/a_1558352979105914.jpg",
                "http://app.xiangshujiaoyu.com/upload/images/78/a_1558352971173576.jpg",
                "http://app.xiangshujiaoyu.com/upload/images/0b/a_1558352962186903.jpg",
                "http://app.xiangshujiaoyu.com/upload/images/0b/a_1558352953147276.jpg",
                "http://app.xiangshujiaoyu.com/upload/images/83/a_1558352945351899.jpg"

这些是图片地址 @li-xiaojun  你可以试试

**Comment by heimaxiaobo** [comment]
一张图6-7m的

**Comment by li-xiaojun** [comment]
@heimaxiaobo 
这么大肯定会卡顿，有3M就会卡顿了，问题是这么大的图不应该丢给客户端显示的。你们没有对图片进行压缩吗？

**Comment by heimaxiaobo** [comment]
客户要高清的的

**Comment by li-xiaojun** [comment]
@heimaxiaobo 高清的也没有这么大的，你见哪个app搞这么大的图。app显示的图片一般不会超过1M，1M已经可以很清楚了，除非你们是做离线地图才需要这么大的图。
