### ISSUE TITLE
图片预览建议增加对facebook库SimpleDraweeView的支持

### ISSUE THREAD

**Issue by Resmic** [li-xiaojun/XPopup#160]

**Comment by li-xiaojun** [comment]
@Resmic 
我不负责加载图片，如果你用的是Freso，请保证你的图片没有被裁剪过就行，本身XPopup不限制任何的图片加载类库，都可以使用。

**Comment by Resmic** [comment]
我说的是那个场景动画的支持

**Comment by li-xiaojun** [comment]
@Resmic 请看demo使用，支持所有图片加载类库，只是Demo中用了Glide。

**Comment by Resmic** [comment]
@Override
        public void loadImage(int position, @NonNull Object url, @NonNull ImageView imageView) {
            //必须指定Target.SIZE_ORIGINAL，否则无法拿到原图，就无法享用天衣无缝的动画
            Glide.with(imageView).load(url).apply(new RequestOptions().placeholder(R.mipmap.ic_launcher_round).override(Target.SIZE_ORIGINAL)).into(imageView);
        }

Target.SIZE_ORIGINAL，这个在SimpleDraweeView好像不能用

**Comment by li-xiaojun** [comment]
@Resmic 
这个设置是让Glide不对图片进行裁剪，如果你用的是Fresco，请按照Fresco用法来配置，让Fresco不裁剪
