### ISSUE TITLE
Demo中DrawerPopupView设置hasShadowBg(false)不起作用 

### ISSUE THREAD

**Issue by rch0903** [li-xiaojun/XPopup#163]
首先，感谢作者的这个xPopup，在实际开发中给了很大的帮助！
遇到了一个小问题，设置hasShadowBg(false)不起作用，demo中修改btnShowDrawRight事件，添加hasShadowBg(false)，一样不起作用，麻烦作者看下
AS：3.4.1
xPopup：1.7.10

**Comment by li-xiaojun** [comment]
@rch0903 
最新版本已修复，请更新试试。

**Comment by rch0903** [comment]
已修复，谢谢！
