### ISSUE TITLE
新增选项

### ISSUE THREAD

**Issue by qiushui95** [li-xiaojun/XPopup#166]
弹窗内容未填满activity的时候，新增设置项，设置是否添加背景拦截底部activity点击事件

**Comment by li-xiaojun** [comment]
@qiushui95 
这个功能不是很好实现，在设计上弹窗应当是独立的一层，事件是应该被弹窗所阻断的。这个功能近期可能不会添加。

**Comment by qiushui95** [comment]
@li-xiaojun 弹出的时候  好像底层会添加一个背景View，如果不添加那个背景view，应该可以吧

**Comment by li-xiaojun** [comment]
我猜你说的是Attach类型弹窗，请参考文档：
![image](https://user-images.githubusercontent.com/4426715/58699127-593ab780-83cf-11e9-9aa8-1fb32890284d.png)
