### ISSUE TITLE
更新版本弹窗调用下载链接

### ISSUE THREAD

**Issue by chocozhao** [li-xiaojun/XPopup#167]
需求：弹出更新版本自定义弹窗，点击更新，获取下载链接，显示下载进度条。这个如何完成？需要调用什么方法达到这种效果呢？谢谢

**Comment by li-xiaojun** [comment]
@chocozhao 
你可以自定一个带下载进度条的弹窗，当开始下载时显示这个弹出，下载完毕就关闭这个弹窗，然后再弹一个提示安装的弹窗。
