### ISSUE TITLE
动画问题

### ISSUE THREAD

**Issue by qiushui95** [li-xiaojun/XPopup#17]
`XPopup.get(context)
				.popupAnimation(PopupAnimation.TranslateAlphaFromBottom)
				.asCustom(SheetPopup(context,buildConfig()))`

SheetPopup继承BottomPopupView
显示没有动画  内容也不见了

**Comment by li-xiaojun** [comment]
@qiushui95 最新版的BottomPopupView是增加了手势交互和嵌套滚动，动画由跟随手势而变，不能自定义动画了，你把自定义动画去掉试试。默认的手势动画就是从下往上滚动，这是符合Bottom类型弹窗风格的。

**Comment by li-xiaojun** [comment]
@qiushui95  感谢您的建议和想法。
在`1.0.4`版本中，Bottom弹窗增加关闭手势交互的开关，默认带手势交互；手势交互模式下无法设置动画器；如果不想要可以在显示Bottom弹窗时传入enableGesture参数为false，此时会禁用手势交互，允许设置动画器

**Comment by qiushui95** [comment]
@qiushui95 谢谢，你更新真快

**Comment by qiushui95** [comment]
@li-xiaojun 我是自定义弹窗，继承BottomPopupView，没有相关接口关闭手势，不能执行自定义动画

**Comment by li-xiaojun** [comment]
@qiushui95 
`BottomPopupView`自带一个`enableGesture`方法，在`initPopupContent`方法中调用一下，传入false即可。

**Comment by qiushui95** [comment]
之前没调用super.initPopupContent()，调用之后可以了
