### ISSUE TITLE
MinSDKVersion能降到14么？

### ISSUE THREAD

**Issue by qr973440230** [li-xiaojun/XPopup#172]

**Comment by li-xiaojun** [comment]
@qr973440230 
完全没有必要，现在最低都19了。

**Comment by qr973440230** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    我这边有些工程机用的14-16的，如果我将这个MinSDKVersion降低到14会有很大的影响么？
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                覃锐
                                    软件工程师
                            
                    
                        
                            
                                    通号万全信号设备有限公司
                                    18340876860
                                    973440230@qq.com
                                    杭州市上城区赞成中心东7楼
                                    
                                    
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2019年6月6日 12:44，李晓俊<notifications@github.com> 写道： 


@qr973440230

完全没有必要，现在最低都19了。



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by qr973440230** [comment]
我这边有些老的工程机是14-16的，我这边手动降级影响大么？

**Comment by li-xiaojun** [comment]
@qr973440230 你可以升级一下，降级真的没有必要
