### ISSUE TITLE
Bottom弹窗键盘收起太慢

### ISSUE THREAD

**Issue by gaosen1023** [li-xiaojun/XPopup#173]
我在弹窗中request 
response 做其他弹窗操作就会导致键盘无法收起，所以这里键盘收起一定要快

**Comment by li-xiaojun** [comment]
@gaosen1023 
新版本已经解决了该问题，更新试试看。

**Comment by wuzhaohui026** [comment]
你是怎么解决的啊？我感觉弹出显示的时候先显示再出输入框，有点慢，但是想不到在哪里解决。
