### ISSUE TITLE
低系统版本崩溃

### ISSUE THREAD

**Issue by 345127607** [li-xiaojun/XPopup#174]
Matrix scale type is not supported
荣耀4.4.2系统 报错 是这个方法里面的Util.isSupportedScaleType

**Comment by li-xiaojun** [comment]
@345127607 日志说的很清楚，你肯定给ImageView设置scaleType为Matrix了。

**Comment by 345127607** [comment]
> @345127607 日志说的很清楚，你肯定给ImageView设置scaleType为Matrix了。

我没给ImageView 做过任何scaleType设置 Util.isSupportedScaleType 我看着你这里面的switch判断 只要设置了scaleType为Matrix 就会抛异常  但是其他高版本的手机 可以正常使用 。我手动给ImageView 设置
 android:scaleType="fitCenter" 后试了下 还是一样抛出这个异常了。所有有点疑惑

**Comment by li-xiaojun** [comment]
@345127607 
最低支持14版本，在几乎所有主流机型测试过，14以下的没有测试过。你跑我的Demo崩溃吗？如果Demo也崩溃那就是我的问题。

**Comment by 345127607** [comment]
> @345127607
> 最低支持14版本，在几乎所有主流机型测试过，14以下的没有测试过。你跑我的Demo崩溃吗？如果Demo也崩溃那就是我的问题。
感谢您的解答，你的DEMO没问题 ，我之前用的是1.6.4版本 我升级到最新1.8.0版本低版本系统崩溃问题自动解决了。
