### ISSUE TITLE
ImageView scaleType属性

### ISSUE THREAD

**Issue by lovechenghao** [li-xiaojun/XPopup#176]
设置android:scaleType="fitXY"属性，图片浏览退出后属性失效

**Comment by li-xiaojun** [comment]
@lovechenghao 
经过我的测试，并没有失效。如果你有这个问题，可以加XPopup交流群，在群里发个能复现的小视频，我来帮你看看。

**Comment by MiracleChen001** [comment]
我也遇到这个问题了，老哥怎么解决的？
