### ISSUE TITLE
SrcView为空

### ISSUE THREAD

**Issue by cwl1992** [li-xiaojun/XPopup#178]
//2. 设置点击
            imageView3.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    new XPopup.Builder(MyNameBeautifulActivity.this).asImageViewer(imageView3, position, photoList, new OnSrcViewUpdateListener() {
                        @Override
                        public void onSrcViewUpdate(ImageViewerPopupView popupView, int position) {
                            popupView.updateSrcView(imageView3);
                            //popupView.updateSrcView((ImageView) recyclerView0.getChildAt(position));
                        }
                    }, new ImageLoader())
                            .show();
                }
            });

**Comment by li-xiaojun** [comment]
@cwl1992 
看看我的Demo怎么写的。
