### ISSUE TITLE
自定义动画问题

### ISSUE THREAD

**Issue by qiushui95** [li-xiaojun/XPopup#18]
我使用PopupAnimator，在initAnimator内设置 animateDuration=5000，背景的变化动画不是按照我设置5000来进行的。另外，我的show和dismiss动画时间不一样，能否animateDuration分成两个

**Comment by li-xiaojun** [comment]
@qiushui95 
背景渐变动画不同步，这应该是一个bug。duration分割我考虑一下是否加上。

**Comment by qiushui95** [comment]
我的动画比较复杂，是多个view的组合动画，有同步，也有动画链
