### ISSUE TITLE
能否加入i18N

### ISSUE THREAD

**Issue by yeqiling** [li-xiaojun/XPopup#183]
目前在英文环境下,dialog的确定与取消按钮文字,依旧为中文.能够添加一下英文支持.

**Comment by yeqiling** [comment]
目前在_xpopup_center_impl_confirm.xml里面硬编码进去的.可以新建一个values-en,做国际化支持.

**Comment by yeqiling** [comment]
目前看到代码中是支持设置确定和取消文案的.不过如果默认的就支持国际化的话,会比较便捷.辛苦作者大大了

**Comment by li-xiaojun** [comment]
@yeqiling ok，这个需求我收下了，下版本更新。

**Comment by li-xiaojun** [comment]
@yeqiling @joker-fu 更新到1.8.3，该问题已修复。

**Comment by yeqiling** [comment]
@li-xiaojun 感谢作者，已更新学习
