### ISSUE TITLE
 XPopup 保存数据状态问题

### ISSUE THREAD

**Issue by fc-dream** [li-xiaojun/XPopup#184]
CustomImageViewerPopup viewerPopup = new CustomImageViewerPopup(getContext());

private void showPopup(){
new XPopup.Builder(getContext())
     .asCustom(viewerPopup)
     .show();
}

viewerPopup 是全局的，第二次执行show。 viewerPopup中的内容显示不出来。内容试图应该都存在，应该是有位置移动

**Comment by li-xiaojun** [comment]
@fc-dream 经过我的测试没有任何问题，代码截个图，就这点代码判断不出来。

**Comment by fc-dream** [comment]
@li-xiaojun 代码已经修改，就是CustomImageViewerPopup全局只有一个，sho wPopup方法除了第一次调用能正常显示，其他调用都出现的是半透明阴影

**Comment by li-xiaojun** [comment]
@fc-dream 问题解决了？

**Comment by DuShuYuan** [comment]
同问题

**Comment by LiverpoolDX** [comment]
同问题
