### ISSUE TITLE
能否对将现有的asConfirm之类的简单弹窗 设置布局文件的接口暴露出来呢

### ISSUE THREAD

**Issue by Leelion96** [li-xiaojun/XPopup#185]
首先感觉这个库真的很好，准备替换掉项目中我自己封装的popup库了。不过如果要将现有的集成，只能自己去修改库中的布局文件，后续作者你这边更新我就很麻烦。
想问下能否放开更多可自定义性的借口呢？比如将confirm弹窗 这些简单的 设置布局文件的借口暴露出来。
我了解可以用asCustom来实现，但是我觉得直接这样不够简单优雅。不知道作者你是怎么看待的，毕竟很多项目有自己的一套ui嘛。

**Comment by li-xiaojun** [comment]
@Leelion96 常用对话框暴漏布局这个想法很好，下个版本加下这个功能。

**Comment by Leelion96** [comment]
> @Leelion96 常用对话框暴漏布局这个想法很好，下个版本加下这个功能。

谢谢作者大大～ 那这样到时候就能无痛接入了。不过希望能注意到一些细节，比如现在的confrimPopupView，内部把两个按键的颜色也固定为主题色了，这些如果需要适应布局添加的话，也应该是要修改到的。期待更新～

**Comment by li-xiaojun** [comment]
@Leelion96  最新版本1.8.4已支持，更新试试。
