### ISSUE TITLE
PartShadowPopupView中，toggle方法无效

### ISSUE THREAD

**Issue by wuzhaohui026** [li-xiaojun/XPopup#186]
private LabelPopView mLabelPopView;
    private LabelPopView labelPopView;
----------
  labelPopView = new LabelPopView(getContext());
        if (mLabelPopView == null) {
            mLabelPopView = (LabelPopView) new XPopup.Builder(getContext())
                    .atView(mPerfectLabelLineView)
                    .asCustom(labelPopView);
        }
-----------------
  @OnClick(R.id.expand_iv)
    public void onViewClicked() {
        mLabelPopView.toggle();
    }
---------------
之前1.7.3的版本这样写能控制pop的显示与隐藏，但是更新到1.8.3的版本就只能第一次显示，隐藏后就不显示了。

**Comment by li-xiaojun** [comment]
@wuzhaohui026 最新版本1.8.4已修复此问题。

**Comment by wuzhaohui026** [comment]
NB,效率真高
