### ISSUE TITLE
图片预览Viewpager使用场景，循环一遍点击保存异常

### ISSUE THREAD

**Issue by 123xuan456** [li-xiaojun/XPopup#187]
![image](https://user-images.githubusercontent.com/21234200/59827816-27809500-936c-11e9-9071-4bf9ebbf4c3f.png)
``

**Comment by li-xiaojun** [comment]
你的ViewPager需要设置pageLimit，参考我的Demo。
```java
pager.setOffscreenPageLimit(list.size());
```

**Comment by 123xuan456** [comment]
我就是运行的你的demo，报错原因是因为viewpager的onPageSelected在循环滑动时position会无限增加，然后在点击保存图片的时候使用urls.get(position) 就会报数组越界异常。
![image](https://user-images.githubusercontent.com/21234200/59910108-cfb55d00-9443-11e9-8c3e-559219fff9f5.png)

**Comment by 123xuan456** [comment]
在图片保存方法中改下就可以了
![image](https://user-images.githubusercontent.com/21234200/59911614-e3ae8e00-9446-11e9-95dc-5cb87cc03359.png)

**Comment by li-xiaojun** [comment]
@123xuan456 
你确定运行的是最新Demo，这个本来就做了求模计算的。

**Comment by 123xuan456** [comment]
你可以看下代码，现在还没改

**Comment by li-xiaojun** [comment]
@123xuan456 我这里是不崩溃的。

**Comment by 123xuan456** [comment]
我用的是oppoR11手机测试的，会有崩溃异常

**Comment by li-xiaojun** [comment]
@123xuan456 
我仔细检查了下确实有问题，感谢你的指正。
