### ISSUE TITLE
停靠在view顶部的 自动间隔

### ISSUE THREAD

**Issue by anaivez** [li-xiaojun/XPopup#188]
停靠在view顶部的 有自动间隔怎么去掉呢

**Comment by li-xiaojun** [comment]
@anaivez 截图，不然不知道你说的是哪种弹窗的效果。

**Comment by anaivez** [comment]
![20190620_180143](https://user-images.githubusercontent.com/37996697/59840753-90283b80-9385-11e9-9e3b-bb25f9392e6c.jpg)

**Comment by anaivez** [comment]
@li-xiaojun  圈内这个
   new XPopup.Builder(getContext())
                .atView(v)
                .asCustom(new FareWindows(getContext(), freightBean))
                .show();

**Comment by li-xiaojun** [comment]
你用的应该是Bottom弹窗吧。看看我的Demo在你手机上下面是否有空隙

**Comment by anaivez** [comment]
@li-xiaojun 继承AttachPopupView写的  我看到demo上那个依靠在view附近的好像都有间隔。

**Comment by li-xiaojun** [comment]
既然你希望下面对齐没有空隙，那应该用Bottom弹窗。Attach弹窗默认不会去对齐，不过你可以设置offsetY来平移弹窗，也能达到效果。

**Comment by anaivez** [comment]
可是buttom的atView似乎无效 如果不行 那我就平移弹窗了

**Comment by anaivez** [comment]
谢谢你的帮助

**Comment by li-xiaojun** [comment]
@anaivez Bottom弹窗不支持atView，你是希望贴在立即购买上面是吗？那这个场景可以使用Attach弹窗或者PartShadow弹窗

**Comment by anaivez** [comment]
PartShadowPopupView  可以不设置offsetY 贴上去了  谢谢
