### ISSUE TITLE
bindLayout 缺少 bindLayout（view）

### ISSUE THREAD

**Issue by joker-fu** [li-xiaojun/XPopup#190]
bindLayout 缺少 bindLayout（view）,实际使用时需要对View进行操作，没有提供获得相关View的方法，也没有提供bindLayout（view）List的可以把ItemView的也暴露出来 (补充 好像看到了个getPopupContentView)

**Comment by joker-fu** [comment]
还有另一个问题 提供了maxWidth 却没有minWidth 实际使用有需要，高度类似，望支持

**Comment by li-xiaojun** [comment]
@joker-fu 
第一个问题，show方法返回的弹窗对象就是一个View对象，你可找到任何一个子View进行操作；
第二个问题，如果需要minWidth，可以直接在弹窗的根布局指定即可；Android没有提供maxWidth相关功能，所以才加的。

**Comment by joker-fu** [comment]
不好意 我已经验证了 确实返回了一个View对象 但是这个时候是去find子控件 还是null的 必须要监听Layout完成再去获取 个人认为这样 没有 bindLayout（view）方便，还有现在我的 底部List 文字需要居右 好像没办法呢，是不是可以把ItemView的也暴露出来

**Comment by li-xiaojun** [comment]
@joker-fu 
这个版本bindLayout只支持Confirm弹窗，Loading弹窗，还不支持列表弹窗，下个版本加下。
子控件为空的话可以监听onCreated方法，弹窗创建完才能去find到子控件。

**Comment by joker-fu** [comment]
我提的问题在不直接依赖源码的情况下都解决了，只是不够灵活。还发现些许不足，比如实际我使用的时候想用它替换系统dialog，但是发现并不能...
