### ISSUE TITLE
请教一个关于图片滑动后的问题

### ISSUE THREAD

**Issue by 957919019** [li-xiaojun/XPopup#197]
![Snipaste_2019-06-25_14-34-31](https://user-images.githubusercontent.com/19183142/60075784-ab65c300-9758-11e9-8528-f1d74fc3fce0.png)
如图所示，item跟结点是一个ConstraintLayout，这样子的话，我再重写
` onSrcViewUpdate(ImageViewerPopupView popupView, int position)
{popupView.updateSrcView(iv);}
`
的时候，该如何才能保证滑动后回缩的位置是正确的？
源码是这样写的：
`RecyclerView rv = (RecyclerView) holder.itemView.getParent();
                            popupView.updateSrcView((ImageView)rv.getChildAt(position));`

**Comment by 957919019** [comment]
附上我的item
`<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical">

    <ImageView
        android:id="@+id/iv_add"
        android:layout_width="match_parent"
        android:layout_height="100dp"
        android:background="?attr/selectableItemBackground"
        android:padding="4dp"
        android:scaleType="centerCrop"
        android:src="@mipmap/ic_add_pic"
        app:layout_constraintBottom_toBottomOf="@id/pb_bar"
        app:layout_constraintTop_toTopOf="parent" />

    <ImageView
        android:id="@+id/iv_delete"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:paddingEnd="4dp"
        android:src="@mipmap/ic_del_pic"
        app:layout_constraintEnd_toEndOf="@+id/iv_add"
        app:layout_constraintTop_toTopOf="@+id/iv_add" />

    <ProgressBar
        android:id="@+id/pb_bar"
        style="?android:attr/progressBarStyleHorizontal"
        android:layout_width="match_parent"
        android:layout_height="10dp"
        android:indeterminate="true"
        android:max="100"
        android:paddingStart="5dp"
        android:paddingEnd="5dp"
        android:visibility="invisible"
        app:layout_constraintBottom_toBottomOf="parent" />
</android.support.constraint.ConstraintLayout>`

**Comment by li-xiaojun** [comment]
先拿到你的根节点，然后在找你的ImageView：
```java
rv.getChildAt(position).findViewById(R.id.iv_add)
```

**Comment by 957919019** [comment]
多谢大侠相救，我们江湖再见
