### ISSUE TITLE
max_aspect冲突

### ISSUE THREAD

**Issue by zii4914** [li-xiaojun/XPopup#198]
项目中已经设置了max_aspect，跟库内的xpermission库的清单中max_aspect配置冲突。能否做一下判断，如果项目已经配置，则不要重复添加该属性

**Comment by li-xiaojun** [comment]
下版本去掉这个

**Comment by zii4914** [comment]
那我现在想用的话应该怎么处理呢？

**Comment by li-xiaojun** [comment]
@zii4914 
刚刚发新版本了，升级到1.8.5就行。

**Comment by zii4914** [comment]
ok
