### ISSUE TITLE
setDismissOnTouchOutside(false)无效

### ISSUE THREAD

**Issue by qiushui95** [li-xiaojun/XPopup#20]
我是继承至BottomPopupView，关闭了手势。

**Comment by li-xiaojun** [comment]
@qiushui95 
感谢您的建议，这个bug在最新版本`1.0.5`版本已经解决。

**Comment by qiushui95** [comment]
@li-xiaojun 请问是没有看到我的回复么？还是新的bug需要提交一个新的issue

**Comment by li-xiaojun** [comment]
@qiushui95
看到了，我抽空改下哈

**Comment by li-xiaojun** [comment]
@qiushui95 
您反映的问题在最新版`1.0.6`已经解决，可以更新试试看。
