### ISSUE TITLE
如何点击弹窗外部不进行dismiss，并且响应点击位置的点击事件

### ISSUE THREAD

**Issue by wuyang2000** [li-xiaojun/XPopup#200]
感谢大神

遇到一个问题：
就是收到推送消息时弹出一个
MessagePopup extends PositionPopupView
的弹框，并且只显示弹框两秒钟。

而我不关心弹框的dismiss，因为两秒钟后它会自动dismiss。
并且我在弹框显示的时候是可以正常的进行我之前的操作。

现在的情况是，弹框弹出后，必须点一下让弹框消失，然后我才能进行之前的操作。

不知道描述的是否清楚，望大神指导！

**Comment by li-xiaojun** [comment]
@wuyang2000 
show方法会返回弹窗对象，你演示两秒让弹窗消失就行：
```
popup.dismiss()
```

**Comment by wuyang2000** [comment]
@li-xiaojun 
大神您好，延时两秒弹框消失已经实现了。
现在的问题是：
1、在弹框展示的两秒种之内，点击弹框外部弹框会消失。
2、而需要的效果是点击弹框外部弹框不消失（因为固定展示2秒会自动消失），并且点击事件可以穿透到弹框下层的布局，不会影响下层布局的操作。

**Comment by li-xiaojun** [comment]
第一个：可以设置dismissOnTouchOutsize(false)
第二个：目前不支持点击事件穿透

**Comment by wuyang2000** [comment]
@li-xiaojun 
感谢大神答疑

**Comment by ygeng** [comment]
@wuyang2000 可以重写onTouchEvent方法，不拦截对话框以外的点击事件

**Comment by threedeer** [comment]
@ygeng 我重写了这个方法，但是只有双击才能响应，单击无法响应事件。
