### ISSUE TITLE
局部阴影功能消失时，有明显卡顿现象

### ISSUE THREAD

**Issue by yecal** [li-xiaojun/XPopup#201]
1.局部阴影功能再次点击消失时，有明显卡顿现象
2.版本运行后，弹出更新提示，点击升级后，下载的app无法正常安装。android手机提示：应用未安装。（首页扫码下载后也无法安装。）

**Comment by li-xiaojun** [comment]
@yecal 版本重新上传了

**Comment by yecal** [comment]
![image](https://user-images.githubusercontent.com/16286109/60167596-f86b9700-9835-11e9-874a-97cb48e13e66.png)
依然无法安装，并且打开好多次都没提示更新。（第一次提示了，不小心点了返回，die第二三四五次都没提示更新，第六次才提示。我这边网络应该没啥问题。）

**Comment by li-xiaojun** [comment]
可以扫描二维码下载，卡顿的话检查下图片是否过大，超过300K就算很大了。
