### ISSUE TITLE
生命周期与数据设置问题

### ISSUE THREAD

**Issue by DuShuYuan** [li-xiaojun/XPopup#203]
代码：
========================
activity中：

    private ChapterCommentDialog commentDialog;
private void setDialogData(){
    commentDialog.setData("123456");
}

    private void showPopup() {
        new XPopup.Builder(this)
                .asCustom(commentDialog)
                .show();
    }
==================================
public class ChapterCommentDialog extends BottomPopupView {

    @Override
    protected void onCreate() {
        super.onCreate();
        tvBookComment.setText(str);
    }

    private String str;
    
    public void setData(String data){
        str=data;
    }

}

commentDialog在setDialogData方法中设置了数据，然后智行showPopup()，首次展示数据正常显示，执行了 onCreate和onShow；当dismiss后再执行showPopup()，只走了onShow，并且commentDialog设置的数据全部无效了，回到了初始状态

**Comment by li-xiaojun** [comment]
对于同一个弹窗对象，onCreate就和activity的onCreate类似，只执行一次，也没有必要执行多次。
如果你下次开启的还是上一个弹窗对象，那么它的数据肯定不会丢失。
检查下你是否又new了一个弹窗。

**Comment by DuShuYuan** [comment]
ChapterCommentDialog  只new了一次
但是xpopup这里是每次都new一个的

private void showPopup() {
    new XPopup.Builder(this)
            .asCustom(commentDialog)
            .show();
}

**Comment by li-xiaojun** [comment]
最新版本已修复
