### ISSUE TITLE
三星手机弹窗底部留白

### ISSUE THREAD

**Issue by meanhan** [li-xiaojun/XPopup#204]
三星S9+ 开启全面屏功能时  弹窗弹出时，手机底部留白  弹窗背景未全屏
使用自定义布局的弹窗
`XPopup.Builder(getContext())
                .dismissOnTouchOutside(true)
                .asCustom(new CourseDetailDialog(getContext(), item))
                .show();`

**Comment by Terran-Marine** [comment]
在使用asImageViewer 大图浏览时也会遇到同样的问题.  应该是全屏模式的问题

**Comment by Terran-Marine** [comment]
[
![Screenshot_20190702-103436_katimes 1](https://user-images.githubusercontent.com/20888254/60478443-4d376380-9cb5-11e9-9f03-04fafcb85b90.jpg)
](url)

**Comment by li-xiaojun** [comment]
这个应该只有在动态切换全屏和导航模式时才会出现，如果是切换完模式，重新进入应该没有问题。

**Comment by li-xiaojun** [comment]
更新到1.8.8即可。
