### ISSUE TITLE
加载大图卡顿问题

### ISSUE THREAD

**Issue by yaojunqi** [li-xiaojun/XPopup#205]
你好，在使用9宫格显示大图的时候，左右切换图片的时候会很飘，不流畅，（每张图的大小是在2-3M的样子把）
还有一个问题是，拖拽关闭大图的时候，拖拽的灵敏度可以加大一丢丢吗，向微信那样，一拖就关闭了

**Comment by yaojunqi** [comment]
我没有对图进行压缩，所以就有点飘，我做了压缩好了

**Comment by li-xiaojun** [comment]
@yaojunqi 
国际惯例，列表中加载的图片不能超过300K的，你们怎么可以加载2M的图片，什么手机也扛不住。。。

**Comment by yaojunqi** [comment]
大佬，打扰一下，想请教个问题：


在recycleview中 写了圆角不显示，有办法吗？


图中代码是我在你git上最新代码试的
