### ISSUE TITLE
关于自定义 Animator 的问题

### ISSUE THREAD

**Issue by linzhengloser** [li-xiaojun/XPopup#206]
在 PopupAnimator 这个类中提供了 getDuration() 方法，但是通过阅读 BasePopupView 的源码发现并没有调用这个方法，虽然可以通过 XPopup.setAnimationDuration() 方法来控制动画的执行时间，不过总感觉怪怪的。希望能改下这个。 

XPopup 的版本是 ```com.lxj:xpopup:1.8.6-x```

**Comment by li-xiaojun** [comment]
@linzhengloser 所有的Animator内部都调用了这个方法啊。

**Comment by linzhengloser** [comment]
谢谢回复，难道不应该是每个 Animator 的 duration 都是独立的吗？我现在遇到一个问题就是，在animateDismiss() 中的动画还没有执行完，View 就被移除了，通过调用 XPopup.setAnimationDuration() 解决了这个问题，但是我发现了 Animator 有 getDuration() 可以重写，但是我发现重写这个方法没有作用。

**Comment by li-xiaojun** [comment]
@linzhengloser 
如果自定义动画逻辑的话，时间可以自己控制，XPopup的setDuration只是为空统一控制动画器的时间，如果你想要特殊的逻辑，可以自己控制时间。
