### ISSUE TITLE
内存泄漏，调用 dismiss()以后，直接 finish()当前界面会出现

### ISSUE THREAD

**Issue by KiWiLss** [li-xiaojun/XPopup#207]

**Comment by zzm123456** [comment]
我也遇到类似的问题.... popupview在显示的时候 直接finish Activity 这样写会内存泄漏....
`@Override
    protected void onDestroy() {
        super.onDestroy();
        if(mPopupView!=null)
        {
            mPopupView.dismiss();
            mPopupView = null;
        }
    }`

**Comment by KiWiLss** [comment]
应该是因为 dismiss 时有个 360ms延迟操作，设置成不用动画就不会泄漏了。

**Comment by zzm123456** [comment]
@KiWiLss 尴尬....设置不用动画我还是会....

**Comment by KiWiLss** [comment]
用的是最新的吗，我看最新的默认是 10
return  popupInfo.popupAnimation == NoAnimation ? 10 : XPopup.getAnimationDuration();
或者试试这个方法有没有用XPopup.setAnimationDuration(20)

**Comment by li-xiaojun** [comment]
@KiWiLss @zzm123456 这个问题下版本修复。

**Comment by zzm123456** [comment]
@KiWiLss 是的，用的1.8.6-x这个版本，我这样解决了
###  
    @OnClick(R.id.linActionbarClose)
    public void close() {
        if(mPopupView!=null && mPopupView.isShow())
        {
            mPopupView.dismiss();
            mPopupView = null;
            mRootActionbar.postDelayed(new Runnable() {
                @Override
                public void run() {
                    finish();
                }
            },360);
        }else {
            finish();
        }
    }

**Comment by wushange** [comment]
写一个Base类 里面释放context 也可以 我这面用这个解决得	
@Override
	public void dismiss() {
		super.dismiss();
		if (compositeDisposable != null) {
			compositeDisposable.clear();
			compositeDisposable = null;
		}
		if (context != null) {
			context = null;
		}
		KeyboardUtils.hideSoftInput(this);
	}

	@Override
	protected void onDetachedFromWindow() {
		super.onDetachedFromWindow();
		if (compositeDisposable != null) {
			compositeDisposable.clear();
			compositeDisposable = null;
		}
		if (context != null) {
			context = null;
		}
	}

**Comment by li-xiaojun** [comment]
最新版本已经修复这个内存泄露的问题。

**Comment by 18300072348** [comment]
这个问题并没有在新版本被修复，在不同的设备上依然经常出现dismiss之后，调用finish造成内存泄漏，在ondismiss()回调里finish就不会

**Comment by zhourenjun** [comment]
我现在百分百重现内存泄漏
