### ISSUE TITLE
小技巧--如果你想改变图片弹出的主题背景颜色的话

### ISSUE THREAD

**Issue by checkming** [li-xiaojun/XPopup#208]
有时候我们的图片可能是含有文字，并且字的颜色是黑色时，当使用原主题时查看图片可能就会有点不太明显，如下
![image](https://user-images.githubusercontent.com/24811745/60408778-e2255880-9bf2-11e9-843b-6aa9815d44c9.png)

这里可以使用Glide提供的[Target](https://muyangmin.github.io/glide-docs-cn/doc/targets.html)，比如 SimpleTarget对imageview进行更改背景颜色即可：

`

GlideApp.with(imageview)
.......
.into(new SimpleTarget<Drawable>() {
                            @Override
                            public void onResourceReady(@NonNull Drawable resource, @Nullable Transition<? super Drawable> transition) {
                                imageView.setBackgroundColor(0xffe2e2e2);
                                imageView.setImageDrawable(resource);
                            }
                        });

`

**Comment by li-xiaojun** [comment]
@checkming 也可以自定义ImageViewer弹窗，设置任意背景。

**Comment by checkming** [comment]
@li-xiaojun  yeah~
