### ISSUE TITLE
键盘无法自动收起

### ISSUE THREAD

**Issue by Joehaivo** [li-xiaojun/XPopup#209]
代码： 使用CustomPopup extends CenterPopupView时，在onCreate（）中设置popupInfo.autoOpenSoftInput = true， 
场景： 如果在弹框弹出期间， 并且键盘自动呼出后，当PopView被其他界面覆盖后， 那么键盘就不会被收起了，会一直停留在界面上

**Comment by li-xiaojun** [comment]
弹窗不关闭，是不会自动关闭输入法的。对于你的这个需求，可以不让弹窗自动弹，自己手动弹出输入法，什么时候开启什么时候关闭自己来控制很灵活。
