### ISSUE TITLE
不能在一个对话框结束后立马开启另一个对话框

### ISSUE THREAD

**Issue by AdamTaurus** [li-xiaojun/XPopup#21]
试了下大概在sleep几百毫秒后可以出来，猜测可能是动画执行时间

例如这样的代码，loading框不会出来，在show前加上dismiss也不行：
XPopup.get(this).asInputConfirm("登录", "请输入账号", new OnInputConfirmListener() {
                    @Override
                    public void onConfirm(String text) {
                        XPopup.get(MainActivity.this).asLoading().show();
                    }
                }).show();

使用dismiss监听，这样也不会出来，偶尔还会卡住：
XPopup.get(this).asInputConfirm("登录", "请输入账号", new OnInputConfirmListener() {
                    @Override
                    public void onConfirm(final String text) {
                        XPopup.get(MainActivity.this)
                                .setPopupCallback(new XPopupCallback() {
                                    @Override
                                    public void onShow() {

                                    }

                                    @Override
                                    public void onDismiss() {
                                        XPopup.get(MainActivity.this).asLoading().show();
                                    }
                                });
                    }
                }).show();

**Comment by li-xiaojun** [comment]
@AdamTaurus 
感谢您的建议，您的这个问题确实存在，我抽空解决下。

**Comment by li-xiaojun** [comment]
@AdamTaurus 
你反馈的问题在最新版本`1.0.7`已经修复，请更新下看看。
