### ISSUE TITLE
找不到类

### ISSUE THREAD

**Issue by wlingf** [li-xiaojun/XPopup#210]
按照文档集成 集成centerpopview 提示找不到该类

**Comment by wlingf** [comment]
<img width="816" alt="WX20190703-144446@2x" src="https://user-images.githubusercontent.com/19945512/60569160-3d954900-9da1-11e9-87d8-829556f9baac.png">
<img width="581" alt="WX20190703-144509@2x" src="https://user-images.githubusercontent.com/19945512/60569186-48e87480-9da1-11e9-95e3-73d4ab6945fc.png">
<img width="477" alt="WX20190703-144522@2x" src="https://user-images.githubusercontent.com/19945512/60569192-4c7bfb80-9da1-11e9-9322-014baa828b47.png">

**Comment by wlingf** [comment]
<img width="629" alt="WX20190703-144748@2x" src="https://user-images.githubusercontent.com/19945512/60569293-9369f100-9da1-11e9-87ef-f1502479ba82.png">

**Comment by li-xiaojun** [comment]
@wlingf 
查看build日志，会有说明的。
