### ISSUE TITLE
底部弹框，虚拟导航栏适配问题

### ISSUE THREAD

**Issue by heyi0123** [li-xiaojun/XPopup#211]
场景一、
虚拟导航栏显示，弹出框是从导航栏的顶部向上弹出，弹出后，隐藏导航栏，弹框没有跟着下移，导航栏部分透明，会显示出当前界面的内容。

场景二、
虚拟导航栏隐藏，弹出框从屏幕底部弹出，这时滑出导航栏，弹框没有上移，导航栏遮住了弹框。

运行作者Demo，也是同样问题，1.8.5,   1.8.4.  1.8.6都存在此问题。
测试机型华为P9，华为Mate10 Pro。这应该都属于常用机型。

**Comment by li-xiaojun** [comment]
这种动态切换导航栏的场景目前没法识别，页面从新打开是没问题的。

**Comment by li-xiaojun** [comment]
更新到1.8.8即可。
