### ISSUE TITLE
CenterPopupView 设置 动画不显示弹窗；

### ISSUE THREAD

**Issue by wushange** [li-xiaojun/XPopup#214]
你好 我自定义得CenterPopupView 设置了动画以后 不显示了  只显示黑色半透明背景  动画去掉就可以？
return new XPopup.Builder(context)
					//.popupAnimation(PopupAnimation.TranslateFromBottom)
					.dismissOnTouchOutside(canCancel)
					.autoDismiss(autoDismiss)
					.asCustom( this.build())
					.show();

**Comment by li-xiaojun** [comment]
最新版本吗？

**Comment by li-xiaojun** [comment]
最新版本吗？

**Comment by wushange** [comment]
是的 1.8.6

**Comment by wushange** [comment]
@li-xiaojun  好使了
