### ISSUE TITLE
自定义全屏popuwindow 中带editText 拦截不到返回事件

### ISSUE THREAD

**Issue by wushange** [li-xiaojun/XPopup#215]
你好，我的自定义全屏布局中有个Edittext 显示的时候默认我设置EditText .setEnable(false)
导致返回事件拦截不到，如果我点击EditText .setEnable(true) 就可以 显示之前我也调用了isRequestFocus（true） 还是没效果请问有解决办法吗？下面是我的布局 和 页面代码
.....
   <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="60dp"
            android:layout_marginTop="10dp"
            android:background="@color/white"
            android:gravity="center_vertical"
            android:orientation="vertical">

            <EditText
                android:id="@+id/et_group_name"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:background="@color/white"
                android:gravity="center|left"
                android:paddingLeft="20dp"
                android:paddingRight="20dp"
                tools:text="分组名称"
                />
        </LinearLayout>
.....

.....	
public void show() {
			new XPopup.Builder(context)
					.popupAnimation(PopupAnimation.TranslateFromBottom)
					.isRequestFocus(true)
					.asCustom(this.build())
					.show();
		}

......

	mEtGroupName.setEnabled(isEditMode);这里设置是否允许编辑

**Comment by li-xiaojun** [comment]
你怎么拦截的返回事件？

**Comment by wushange** [comment]
@li-xiaojun  setPopupCallback 的 back事件拦截不到， 其实我并不想拦截 我只是需要按返回键 关闭dismiss 而不是关闭我的activity，，，

**Comment by li-xiaojun** [comment]
默认情况下是按返回键是可以关闭弹窗的，可以看demo中的例子。估计是EditText.setEnable(false)影响了。

**Comment by wushange** [comment]
@li-xiaojun  嗯是的 不设置这个就没问题 我试着在EditText.setEnable(false) 之后 调用popuwindow的 requestFocus 不过还是没有生效。 对了还有个问题就是我怎么动态刷线popuwindow的高度呢？

**Comment by li-xiaojun** [comment]
新版本增加了一个autoFocusEditText的选项，可以解决你的问题。

**Comment by wushange** [comment]
是的 Thanks
