### ISSUE TITLE
EditText默认抢占焦点

### ISSUE THREAD

**Issue by AnnXZ** [li-xiaojun/XPopup#216]
原因BasePopupView的focusAndProcessBackPress方法里面存在遍历视图循环查找EditText去设置焦点
遍历的代码是XPopupUtils.findAllEditText(list, (ViewGroup) getPopupContentView());
此处为了设置返回监听，强制获取了焦点。
解决办法：添加一个判断让该方法由用户去设置这个是否获取焦点

**Comment by AnnXZ** [comment]
虽然这样处理有可能让你的返回键失效，让用户自行在onKeyDown里面去处理这个问题

**Comment by wushange** [comment]
谢谢你的建议

**Comment by li-xiaojun** [comment]
最新版本增加了一个方法来控制是否让输入框获取焦点:`autoFocusEditText`
