### ISSUE TITLE
有些时候，bottom弹窗手势下滑隐藏，无法完全关闭

### ISSUE THREAD

**Issue by xiagea** [li-xiaojun/XPopup#217]
在demo里也复现了，不过很难复现，没有关闭时，最底部会有pop布局漏在外面，导致再次点击屏幕会进行隐藏，而不会响应点击事件

**Comment by li-xiaojun** [comment]
哪种类型的弹窗？

**Comment by wangmingjob** [comment]
> 我试试

我也遇见了，bottom弹出窗，drag是enable情况下，手势下滑，界面是下滑收起来了，但是没有完全触发dismiss，并且bottomPopupContainer依然有焦点，这个复现概率不太高，但还是会出现，多用手快速下滑几次，还是可以出现的

**Comment by shenqiwen** [comment]
@li-xiaojun   仔细看了下源码 感觉是SmartDragLayout 里的 scrollTo 坐标计算有问题 导致的Bottom弹窗无法完全关闭

**Comment by li-xiaojun** [comment]
是最新版本吗，老版本曾经出现过这个问题。

**Comment by shenqiwen** [comment]
最新版1.8.8 还是有这个问题 
![Uploading Screenshot_20190805_093418.jpg…]()

**Comment by shenqiwen** [comment]
最新版1.8.8的Demo 还是有这个问题
![Screenshot_20190805_093418](https://user-images.githubusercontent.com/31466883/62432900-9a02d400-b764-11e9-8ade-8e34d3e79706.jpg)

**Comment by MakeCodeFly** [comment]
这个问题修复，能告知下，具体修复的代码在哪里吗？  麻烦告知下  谢谢

**Comment by missu263** [comment]
出现同样的问题

**Comment by missu263** [comment]
> 出现同样的问题

1.8.17版本
