### ISSUE TITLE
带软键盘的弹窗出后，activity中的布局会被顶上去，里面的RecyclerView会调用滑动事件

### ISSUE THREAD

**Issue by yangfeng1994** [li-xiaojun/XPopup#225]
带软键盘的弹窗出后，activity里面的RecyclerView会调用滑动事件，然后造成RecyclerView的notifyItemChanged调用无法生效

**Comment by li-xiaojun** [comment]
软键盘弹出导致activity布局顶上去，这个貌似和弹出没有什么关系。你不用弹窗也是会顶上去，可以考虑从softMode入手解决。

**Comment by yangfeng1994** [comment]
如果activity设置为adjustNothing的话，dialog中的输入框是不会弹出的。

**Comment by li-xiaojun** [comment]
RecyclerView的notifyItemChanged应该不会无效，有可能刷新了UI，需要滑动一下才能看到，此时可以手动scrollTo来解决。

**Comment by yy1033733525** [comment]
我使用的问题是第一次弹出,然后收回时,recyclerview第一个条目会滚上去,目前不知道怎么解决

**Comment by yy1033733525** [comment]
android:focusable="true"
            android:focusableInTouchMode="true"
已解决
