### ISSUE TITLE
优化问题

### ISSUE THREAD

**Issue by hongyanfengzi** [li-xiaojun/XPopup#226]
new XPopup.Builder(getContext()).asImageViewer(imageView, position, list, new OnSrcViewUpdateListener() {
            @Override
            public void onSrcViewUpdate(ImageViewerPopupView popupView, int position) {
                // 作用是当Pager切换了图片，需要更新源View
                popupView.updateSrcView((ImageView) recyclerView.getChildAt(position));
            }
        }, new ImageLoader())
        .show();

recyclerView 的 childView 不一定是imageView,  这个有点误导

**Comment by li-xiaojun** [comment]
demo是告诉你找到你的ImageView，item中总得有，如果跟view不是就find到

**Comment by hongyanfengzi** [comment]
嗯,只是写的时候,没有注意到, 崩溃了,  所以来提醒下, 不用在意
