### ISSUE TITLE
发现两个问题

### ISSUE THREAD

**Issue by LiaoYuqiangzz** [li-xiaojun/XPopup#23]
1.自定义view继承PartShadowPopupView时候，如果自定义的view布局高度是match_parent的话，虚拟键会挡住一部分布局内容，应该是计算布局高度的时候没有计算是否存在虚拟键。
2.我使用Leaks的时候显示KeyboardUtils的onGlobalLayoutListener存在内存泄漏，是否应该提供一个remove方法来移除监听或者在view消失的时候自动移除监听呢

**Comment by li-xiaojun** [comment]
@LiaoYuqiangzz 
感觉您的建议，我会抽空修复下。

**Comment by li-xiaojun** [comment]
@LiaoYuqiangzz 
您提出的两个问题在最新版`1.0.6`已经修复，可以下载新版本看看。
