### ISSUE TITLE
PositionPopupView弹窗在输入法隐藏后被顶上去无法复原

### ISSUE THREAD

**Issue by TIIEHenry** [li-xiaojun/XPopup#230]
![Screenshot_AndroCode_20190722-233053](https://user-images.githubusercontent.com/14892799/61645394-144d4600-acd9-11e9-8e52-a27f8fbc5265.png)
![Screenshot_AndroCode_20190722-233050](https://user-images.githubusercontent.com/14892799/61645407-1b745400-acd9-11e9-8b30-2ee516b176f4.png)

**Comment by li-xiaojun** [comment]
已修复，下个版本更新。

**Comment by TIIEHenry** [comment]
非常感谢
