### ISSUE TITLE
遇到一个和 LiveData 相关的问题

### ISSUE THREAD

**Issue by linzhengloser** [li-xiaojun/XPopup#232]
在 LiveData 的 Observer 中弹出 XPopup 会让 XPopup 的 back 失效，按下 back 键会直接退出 Activity 而不是关闭 XPopup，并且 Activity 还会出现内存泄漏。大致代码如下：

``` kotlin
class MainActivity{

    private val mLiveData = LiveData()

    fun onCreate(){
        mLiveData.observer(this, Observer{
            XPopup.show()
        })
    }
}
```
将 observer 中的逻辑拿到一般的主线程中执行就不会有问题。具体是不是 LiveData 的原因，我还要验证一下。

设备信息:

Android 9.0 三星A60

**Comment by linzhengloser** [comment]
![image](https://user-images.githubusercontent.com/12724989/61770779-a3b14100-ae20-11e9-84e4-8729fa934ca5.png)

**Comment by linzhengloser** [comment]
结果验证，发现问题在于 LoadingPopupView 上，在 LiveData 获取数据前会先显示 LoadingPopupView，然后当获取成功后，会调用 LoadingPopupView 的 dismiss() 方法，让后在弹出具体要展示数据的 PopupView，可能是弹的快还是什么原因。两个 XPopupView 冲突了。

**Comment by li-xiaojun** [comment]
这个用例测试过，LiveData的observer本身就是主线程，这个我抽空测试下。

**Comment by linzhengloser** [comment]
补充下完整的代码。

``` kotlin
class Repository{
    fun getData() = NetworkData().apply{
        Api.getData()
            .doOnSubscribe{ networkStatus.postValue("Loading") }
            .doFinally{ networkStatus.postValue("Dismiss") }
            .subscribe(
                Consumer{ data.postValue(data) },
                Consumer{ networkStatus.postValue("Error") }
            )
    }
}

class MainActivity{
    fun onCreate(){
        viewModel.networkData.netWorkStatus.observer(this, Observer{
            when(it){
                "Loading" -> showLoadingPopup()
                "Dismiss" -> dismissLoadingPopup()
                else -> "Error"
            }
        })
    }
}

class MyViewModel: ViewModel(){

    val networkData: MutableLiveData = MutableLiveData<NetworkData>()

    fun getData(){
        networkData.value = repository.getData()
    }
}

data class NetworkData<T> private constructor(
    val data: MutableLiveData<T>,
    val networkStatus: MutableLiveData<NetworkStatus>
)
```

**Comment by linzhengloser** [comment]
补充一下，LoadingPopup 设置了 dismissOnBackPressed(false) 方法，可能和这个有关联？!

**Comment by linzhengloser** [comment]
最近在使用的时候，遇到了一个比较蛋疼的地方，就是 XPopup 提供的 asXXX() 方法重载过多，在使用的时候有点不方便，建议可以将参数封装成对象，让后通过 Builder 模式来创建这些参数，这样要比现在的重载方便不少。

ps: kotlin 有默认参数，比重载好用啊~

**Comment by li-xiaojun** [comment]
有Build的，asXXX是开箱即用的封装，相当于Build的常用封装。
当时考虑的是Java选手调用的方便就用Java写了，如果你用Kotlin，可以试试我的：https://github.com/li-xiaojun/AndroidKTX
