### ISSUE TITLE
华为honor 7X，asInputConfirm无法弹出软键盘

### ISSUE THREAD

**Issue by kokod21** [li-xiaojun/XPopup#233]
代码如下：
 fun showVerifyCodePop(context: Context?, listener: OnConfirmClickListener){
        //输入收货码
        XPopup.Builder(context).asInputConfirm("提示","请输入收货码") {
            //开始效验收货码
            if (TextUtils.isEmpty(it) || it.length != 4) {
                listener.notValid("不是有效的验证码")
            } else {
                listener.onConfirm(it)
            }
        }.show()
    }
![微信图片_20190725094945](https://user-images.githubusercontent.com/5299774/61839912-f55dd800-aec1-11e9-8696-a60834fa1775.jpg)

**Comment by li-xiaojun** [comment]
是最新版本吗

**Comment by kokod21** [comment]
> 是最新版本吗

不是哦，是1.7.1-x版本的

**Comment by li-xiaojun** [comment]
用最新版本吧，你这个版本和最新的差了10几个版本了。
