### ISSUE TITLE
建议增加一个弹框拦截器

### ISSUE THREAD

**Issue by vihuela** [li-xiaojun/XPopup#235]
现在弹框会存在多个覆盖的情况，比如：强更和活动弹框，需要控制优先级。现在做法只能业务来控制，希望框架提供拦截器

**Comment by li-xiaojun** [comment]
这个我考虑下，看看怎么实现比较合适。

**Comment by li-xiaojun** [comment]
这个还是业务区控制比较好，由框架控制不太合适。
