### ISSUE TITLE
自定义布局能不能更简洁

### ISSUE THREAD

**Issue by Joslyn-Chen** [li-xiaojun/XPopup#239]
popup只做弹窗，把自定义布局抛出来，逻辑外面写。不需要去继承，一个很小的布局就要去自定义。

**Comment by li-xiaojun** [comment]
逻辑放外面并不是一个好的设计，继承的方式可以封装相同的逻辑功能。
XPopup目前支持绑定外部布局，你可以将写好的布局绑定给XPopup，不用定义类了；这样弹窗的UI由你决定，弹窗的逻辑XPopup帮你实现了。

**Comment by Joslyn-Chen** [comment]
我自己再简单封装了一层，复杂的还是的继承
