### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by chuwe1** [li-xiaojun/XPopup#24]
对于list类型的 不管是 bootom 还是 center 弹出 如果不重写 getMaxHeight 内容太多会充满整个屏幕 高度。如果重写了 getMaxHeight 如果内容太少 高度又并不是自适应的 而是 getMaxHeight的高度，多余的部分会留白。我看了源码 这是因为现在的 getMaxWidth 和 getMaxHeight 并没有用来作为界限值而是 给 弹窗设置了固定值。

因此我建议对于宽高的重写方法设计余下：
1：getMinWidth getMinHeight
2：getWidth getHeight
3：getMaxWidth getMaxHeight

如果重写了 2，那么就取固定宽高。否则 宽高 则在 1,3直接自适应变化

**Comment by li-xiaojun** [comment]
@chuwe1 
感谢您的建议，这个想法很合理。我抽个空改下。

**Comment by li-xiaojun** [comment]
@chuwe1 
您反映的问题在最新版`1.0.6`已经解决，现在是弹窗的宽高默认是自适应。在设置最大宽高的情况下，弹窗的宽高最多为max的值，如果实际宽高不足max的值，则还是以实际宽高为准；如果强行设置为max的值，会造成布局留白。

**Comment by chuwe1** [comment]
@li-xiaojun 
对于局部阴影的弹出 就 demo 而言 在弹出已经弹出的情况下 能否支持在弹出未消失时也能够响应到 “综合”、“价格”、“销量”三个View的click事件呢？
产品闲选另外一个筛选条件时，非得先关了弹窗在重新打开 麻烦

**Comment by li-xiaojun** [comment]
@chuwe1 
您反映的问题在最新的`1.1.0`已经修复，请更新看看。
