### ISSUE TITLE
关于带输入法得界面关闭页面抖动

### ISSUE THREAD

**Issue by wushange** [li-xiaojun/XPopup#240]
hello，在使用中发现这样一个现象， 在其中一个页面我输入文字弹出了输入法， 这个时候我点击按钮dismiss，如果输入法弹出状态页面会抖动一下在消失， 如果输入法已经消失 在dismiss就没有问题 。

**Comment by li-xiaojun** [comment]
什么类型的弹窗，是最新版吗

**Comment by wushange** [comment]
是的 全屏弹窗，并且有输入法弹出的情况下，输入法不弹出没有这个问题

**Comment by li-xiaojun** [comment]
看我的Demo有增问题吗。
