### ISSUE TITLE
QuickStart方式调用，Popup列表边框阴影丢失

### ISSUE THREAD

**Issue by fairytale110** [li-xiaojun/XPopup#244]
demo运行效果带阴影，但是按文档方法调用，popup无阴影，不知道哪里还需要配置，请赐教：

demo 效果：
![image](https://user-images.githubusercontent.com/30248926/62119711-b630ec00-b2f2-11e9-81d0-7ee06de6b9a7.png)

我的运行效果：
![image](https://user-images.githubusercontent.com/30248926/62119683-ad401a80-b2f2-11e9-9c12-63dbf0260ced.png)

XPopup：1.8.7 aar
设备：小米8 （Android 8.1），华为 EVA-AL10 （Android 6.0）
调用方式：
![image](https://user-images.githubusercontent.com/30248926/62119067-656cc380-b2f1-11e9-922d-a7c2ddec08ac.png)
调用位置：自定义的Toolbar右上角ImageView控件
我的manifest：
![image](https://user-images.githubusercontent.com/30248926/62119258-c1374c80-b2f1-11e9-9d4f-6530fe8aaf0c.png)
App style：
![image](https://user-images.githubusercontent.com/30248926/62119324-e3c96580-b2f1-11e9-8453-c765cfc4e619.png)

如果可以提供修改背景样式的API，想必可以规避此问题😄

**Comment by chenxiaofei910714** [comment]
> 演示运行效果带阴影，但是按文档方法调用，弹出无阴影，不知道哪里还需要配置，请赐教：
> 
> 演示效果：
> ![图片](https://user-images.githubusercontent.com/30248926/62119711-b630ec00-b2f2-11e9-81d0-7ee06de6b9a7.png)
> 
> 我的运行效果：
> ![图片](https://user-images.githubusercontent.com/30248926/62119683-ad401a80-b2f2-11e9-9c12-63dbf0260ced.png)
> 
> XPopup：1.8.7 aar 
> 设备：小米8（Android 8.1），华为EVA-AL10（Android 6.0）
> 调用方式： 调用位置：自定义的工具栏右上角ImageView控件 我的清单： App风格：
> ![图片](https://user-images.githubusercontent.com/30248926/62119067-656cc380-b2f1-11e9-922d-a7c2ddec08ac.png)
> 
> 
> ![图片](https://user-images.githubusercontent.com/30248926/62119258-c1374c80-b2f1-11e9-9d4f-6530fe8aaf0c.png)
> 
> ![图片](https://user-images.githubusercontent.com/30248926/62119324-e3c96580-b2f1-11e9-8453-c765cfc4e619.png)
> 
> 如果可以提供修改背景样式的API，想必可以规避此问题😄

你说的阴影是弹窗后的背景色？是的画，我到你代码理有个hasShadowbg(false)，应该设置为true可以显示出来

**Comment by li-xiaojun** [comment]
吧Demo中有阴影的写法复制到你项目中试试

**Comment by fairytale110** [comment]
> > 演示运行效果带阴影，但是按文档方法调用，弹出无阴影，不知道哪里还需要配置，请赐教：
> > 演示效果：
> > ![图片](https://user-images.githubusercontent.com/30248926/62119711-b630ec00-b2f2-11e9-81d0-7ee06de6b9a7.png)
> > 我的运行效果：
> > ![图片](https://user-images.githubusercontent.com/30248926/62119683-ad401a80-b2f2-11e9-9c12-63dbf0260ced.png)
> > XPopup：1.8.7 aar
> > 设备：小米8（Android 8.1），华为EVA-AL10（Android 6.0）
> > 调用方式： 调用位置：自定义的工具栏右上角ImageView控件 我的清单： App风格：
> > ![图片](https://user-images.githubusercontent.com/30248926/62119067-656cc380-b2f1-11e9-922d-a7c2ddec08ac.png)
> > ![图片](https://user-images.githubusercontent.com/30248926/62119258-c1374c80-b2f1-11e9-9d4f-6530fe8aaf0c.png)
> > ![图片](https://user-images.githubusercontent.com/30248926/62119324-e3c96580-b2f1-11e9-8453-c765cfc4e619.png)
> > 如果可以提供修改背景样式的API，想必可以规避此问题😄
> 
> 你说的阴影是弹窗后的背景色？是的画，我到你代码理有个hasShadowbg(false)，应该设置为true可以显示出来

你好，我说的是弹出popup的边框阴影，

**Comment by li-xiaojun** [comment]
你的问题解决没？
