### ISSUE TITLE
希望可以加入一项功能

### ISSUE THREAD

**Issue by kscMaster** [li-xiaojun/XPopup#248]
希望asLoading时传入的String希望可以随时修改。比如传入进度显示，再比如后台执行多个任务，可以在loading时显示当前正在执行哪个任务

**Comment by kscMaster** [comment]
目前，我可以使用一些曲折的方法实现该功能，
```java 
((TextView)loadingPopup.getPopupImplView().findViewById(R.id.tv_title)).setText("加载完毕");
```
但有一个问题很严重，在修改String之前，tv_title的长度为1，当我改变它的长度时，文字会被布局遮挡显示不全

**Comment by kscMaster** [comment]
另外有一个奇怪的地方，有人之前提过issue希望加一个Title，最后的样子应该是一个Title一个菊花转一个Content，但是你的布局和代码似乎只是把API加入了一个setTitle()改了一个，效果还是没变动

**Comment by li-xiaojun** [comment]
ok，下版本更新，setTitle可以直接修改内容。

**Comment by kscMaster** [comment]
那么有考虑加入随时改变loading展示的内容吗？

**Comment by li-xiaojun** [comment]
对，就是随时改变loading内容。

**Comment by li-xiaojun** [comment]
更新到1.8.8即可。

**Comment by kscMaster** [comment]
可否把gradle/wrapper删掉，我家里网速慢，clone不下来，嘿嘿，每次到百分之10的时候就不动了

**Comment by kscMaster** [comment]
> https://github.com/li-xiaojun/XPopup/issues/248#issuecomment-517585438
这个问题还存在，我再做一些描述吧，第二次展示的字符长度大于第一次展示字符长度时，文字会显示不全,可能是由于 android:ellipsize="end"这个属性造成的，另外在我手机上每行只能显示5个长度的字，很奇怪，我把多余的属性都去掉了，但仍然只能显示5个字，
```java
    <TextView
        android:id="@+id/tv_title"
        android:visibility="gone"
        android:textSize="15sp"
        android:textColor="#DDDDDD"
        android:layout_marginLeft="8dp"
        android:layout_marginRight="10dp"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content" />
```

如果找到问题，还请告知我一下，谢谢
