### ISSUE TITLE
fragment+XPopup，一个很难的问题

### ISSUE THREAD

**Issue by Joslyn-Chen** [li-xiaojun/XPopup#249]
我的需求：layout+viewpager+fragment+评论Popup。
刚开始用BottomPopup+评论Popup，发现BottomPopup里用不了viewpager+fragment，后来换成DialogFragment+评论Popup，结果评论Popup被dialog遮挡

**Comment by li-xiaojun** [comment]
用不了ViewPager + Fragment？？当然可以用，弹窗就是一个自定义View。

**Comment by Joslyn-Chen** [comment]
@li-xiaojun 会报这个错：
java.lang.IllegalArgumentException: No view found for id 0x7f090466 (viewpager id) for fragment DetailsFragment{b3cbc72 #1 id=0x7f090466 android:switcher:2131297382:0}

**Comment by li-xiaojun** [comment]
找不到id这种错误好好检查下布局吧，XPopup绝对可以的。

**Comment by Joslyn-Chen** [comment]
使用了childFragmentManager，但是Viewpager在Popup布局里面，所有找不到。
有demo可以参考吗？

**Comment by Joslyn-Chen** [comment]
@li-xiaojun 解决了，直接使用fragmentManager就可以了。
评论Popup里我把EditText包了两层才能实现demo效果，不然输入内容后EditText会下移。
这个库非常好，我会继续支持。
