### ISSUE TITLE
图片预览能不能设置隐藏保存按钮

### ISSUE THREAD

**Issue by daijunsheng** [li-xiaojun/XPopup#252]
图片预览能不能设置隐藏保存按钮

**Comment by li-xiaojun** [comment]
有个参数可以隐藏

**Comment by daijunsheng** [comment]
能不能说下这个参数在哪设置，我在常用设置里面没有找到，谢谢了


------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>;
发送时间: 2019年8月6日(星期二) 上午9:57
收件人: "li-xiaojun/XPopup"<XPopup@noreply.github.com>;
抄送: "519161480"<519161480@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [li-xiaojun/XPopup] 图片预览能不能设置隐藏保存按钮 (#252)




有个参数可以隐藏

**Comment by daijunsheng** [comment]
找到了，拜谢大神

**Comment by 4what2do** [comment]
能不能修改保存按钮的字体颜色啊

**Comment by li-xiaojun** [comment]
这个特殊的需求可以自定义一个预览弹窗，上面所有的 布局都可以自定义。
