### ISSUE TITLE
NavigationBarObserver 内存泄露

### ISSUE THREAD

**Issue by franticn** [li-xiaojun/XPopup#253]
![image](https://user-images.githubusercontent.com/21286570/62604002-adab6780-b929-11e9-89cf-dc78c4b8320c.png)
如图，个人认为是因为在`NavigationBarObserver::register`中注册了`ContentObserver`，却没有在合适的时机反注册

**Comment by li-xiaojun** [comment]
下版本更新

**Comment by skytang168** [comment]
直接将Context 替换成application的context

**Comment by skytang168** [comment]
关于这个问题 我把这个库下下来后改成  this.context = context.getApplicationContext();经过测试，发现不会出现这个问题的内存泄漏了

**Comment by li-xiaojun** [comment]
更新到1.8.9即可。
