### ISSUE TITLE
切换中英文输入法，会遮挡布局

### ISSUE THREAD

**Issue by MakeCodeFly** [li-xiaojun/XPopup#257]
华为手机：ALP-AL00    android版本：9       系统版本：9.0.0
![image](https://user-images.githubusercontent.com/24836213/62847206-aad4bc00-bd07-11e9-9cb9-5f01a5d1f655.png)

**Comment by MakeCodeFly** [comment]
找到问题所在了   是在xpoputils类里面计算上移dy的距离计算有误

**Comment by li-xiaojun** [comment]
这个问题我暂时无法复现，切换中英文，按道理是不会引起输入法整体移动的，可否录个视频发到群里面。
