### ISSUE TITLE
查看大图功能，动画过程中原ImageView位置显示白色背景

### ISSUE THREAD

**Issue by hubLius** [li-xiaojun/XPopup#258]
1.8.8版本查看大图功能，动画过程中原ImageView位置显示为白色方框，当父布局背景色为其他颜色时会特别显眼

**Comment by hubLius** [comment]
![image](https://user-images.githubusercontent.com/26226387/63014749-cb487600-bec1-11e9-9cc8-8733b361f3e0.png)

**Comment by li-xiaojun** [comment]
更新到1.8.9即可。
