### ISSUE TITLE
【建议】position的建议

### ISSUE THREAD

**Issue by 164738777** [li-xiaojun/XPopup#26]
由于不想多一层空白FrameLayout, 所以打算继承BasePopupView,  但是无法修改Xpopup的position

**Comment by li-xiaojun** [comment]
@164738777 这个建议很合理，我抽空改下。

**Comment by li-xiaojun** [comment]
@164738777 
在最新版本`1.0.8`已经公开设置position的API，可以更新看看。

**Comment by 164738777** [comment]
非常感谢, 已更新使用.
