### ISSUE TITLE
BottomPopupView 怎么显示背景遮罩

### ISSUE THREAD

**Issue by nirvana72** [li-xiaojun/XPopup#260]
![image](https://user-images.githubusercontent.com/15214079/63206705-370e2700-c0ec-11e9-9164-984238d42d9f.png)

我弹出BottomPopupView没有背景， 要怎么才能显示

**Comment by li-xiaojun** [comment]
看文档了吗？有个hasShadowBg选项

**Comment by nirvana72** [comment]
谢谢啊，手上事有点多，一个问题卡住了就放一边继续做别的事了，文档没太仔细看

**Comment by nirvana72** [comment]
大哥， 还是不行啊， 白天有事， 晚上回来试一下， 还是没有背景遮罩层， 代码如下
