### ISSUE TITLE
实体按键返回

### ISSUE THREAD

**Issue by rcj60560** [li-xiaojun/XPopup#261]
你好，点击手机返回按钮能设置不让弹窗消失吗 
谢谢: )
@li-xiaojun

**Comment by li-xiaojun** [comment]
看文档

**Comment by rcj60560** [comment]
看到了 谢谢




------------------ 原始邮件 ------------------
发件人: "Jun"<notifications@github.com>;
发送时间: 2019年8月19日(星期一) 晚上11:14
收件人: "li-xiaojun/XPopup"<XPopup@noreply.github.com>;
抄送: "C.O.B"<289759379@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [li-xiaojun/XPopup] 实体按键返回 (#261)




看文档
