### ISSUE TITLE
AttachListPopupView增加自定义的横向列表时遇到疑惑

### ISSUE THREAD

**Issue by XpxDeveloper** [li-xiaojun/XPopup#262]
我测试的代码是这样的，最后的测试结果仍然是纵向列表，而不是横向列表：
AttachListPopupView popupView = new AttachListPopupView(mContext)
                    .setStringData(new String[]{"分享", "编辑", "不带icon"},
                            new int[]{R.mipmap.ic_launcher_round, R.mipmap.ic_launcher_round, R.mipmap.ic_launcher_round})
                    .setOffsetXAndY(0, 0)
                    .bindItemLayout(R.layout.recycle_popup_item_text)
                    .bindLayout(R.layout.recycle_popup_item_attach_impl_list)
                    .setOnSelectListener(new OnSelectListener() {
                        @Override
                        public void onSelect(int position, String text) {
                            ToastUtils.showLong(text);
                        }
                    });
            popupView.popupInfo=new PopupInfo();
            popupView.popupInfo.hasShadowBg=false;
            popupView.popupInfo.atView=v;
            popupView.popupInfo.popupType= PopupType.AttachView;

            popupView.show();

我在自己的项目里增加了2个布局：recycle_popup_item_text、recycle_popup_item_attach_impl_list；
以及HorizontalRecyclerView类。但是测试的时候，代码并没有执行到HorizontalRecyclerView里面，而是执行到了VerticalRecyclerView类里面，我暂时没搞懂是为什么

**Comment by XpxDeveloper** [comment]
知道原因了。getImplLayoutId()方法是在AttachPopupView构造方法中调用的，而new AttachListPopupView(mContext)时压根就还没调用方法bindLayout(R.layout.recycle_popup_item_attach_impl_list)，所以这个源码上逻辑有缺陷，期待作者早点修复这个BUG

**Comment by li-xiaojun** [comment]
不要自己new PopupInfo()，这个用法我没有写过，请按照文档的方法来使用。

**Comment by XpxDeveloper** [comment]
> 不要自己new PopupInfo()，这个用法我没有写过，请按照文档的方法来使用。

我就是因为文档中没有横向列表的写法，我才这么写呀。你的PopupInfo是在Builder里面实例化的，但是Builder里面提供的方法并不支持横向列表，我当然就只能自己写了，这还不对了？
