### ISSUE TITLE
PartShadowPopupView下拉框列表的问题

### ISSUE THREAD

**Issue by lixins** [li-xiaojun/XPopup#263]
你好，继承了PartShadowPopupView的下拉框我里面放RecyclerView，就这个RecyclerView   Item的点击事件和点击获取item的值怎么回传给fragment？

**Comment by li-xiaojun** [comment]
把弹窗当做一个Fragment用就行。
可以用接口回调，或者EventBus传递。

**Comment by lixins** [comment]
谢谢楼主，还有一个问题，就是我想用这个下拉框跟随CoordinatorLayout折叠移动怎么弄啊？昨天试了他只在刚开始的位置，不会跟随滑动

**Comment by li-xiaojun** [comment]
不会跟随移动的话可能需要重新new一个弹窗，因为之前的弹窗会缓存位置，所以当目标滚动的话，需要重新new一个弹窗。
