### ISSUE TITLE
#248 这个问题依然存在

### ISSUE THREAD

**Issue by kscMaster** [li-xiaojun/XPopup#265]
[https://github.com/li-xiaojun/XPopup/issues/248](url)
1.Loading的时候，后面展示的文字长度大于首次展示文字的长度时，文字会显示不全；
2.不论显示多少个字，屏幕展示的文字永远小于等于5

**Comment by li-xiaojun** [comment]
这个下版本更新，问题已经修复。

**Comment by li-xiaojun** [comment]
更新到1.8.9即可。

**Comment by kscMaster** [comment]
检验合格，在场响起了热烈的掌声
