### ISSUE TITLE
内存泄漏问题

### ISSUE THREAD

**Issue by austenyad** [li-xiaojun/XPopup#266]
![](https://ae01.alicdn.com/kf/Hb13709a0a1744915bf49eaabe65b9feft.png)
现在我的应用每个页面 基本都由于这个单例类引用到 页面 的 Context 对象，导致页面无法正常销毁。
![](https://ae01.alicdn.com/kf/H5c671cfaec90417ebc00d70d1dae1fa12.png)
com.lxj:xpopup:1.8.8 版本号

**Comment by li-xiaojun** [comment]
更新到1.8.9即可。
