### ISSUE TITLE
关于功能上的一个建议

### ISSUE THREAD

**Issue by 211885646** [li-xiaojun/XPopup#268]
这个库挺好的,基本上囊括了业务常见的所有弹窗,但是有一种弹窗希望可以加进来,就是新手引导的蒙层弹窗,其实demo中的局部阴影有点像  但是局部阴影的功能貌似实现不了新手引导的效果,所以在此提出建议  嘿嘿

**Comment by li-xiaojun** [comment]
试试弘扬的库把：https://github.com/hongyangAndroid/Highlight

这个功能有点特殊了，不是很通用
