### ISSUE TITLE
三星S4显示内存溢出

### ISSUE THREAD

**Issue by IFeelIFeel** [li-xiaojun/XPopup#27]
是否兼容低端性能的机型

**Comment by li-xiaojun** [comment]
@IFeelIFeel 
是我的Demo内存溢出，还是你在项目中用我的类库内存溢出。可以详细一点，另外最好能贴上日志。
我的类库连图片都没有，就算在低端设备上也运行流畅的。

**Comment by IFeelIFeel** [comment]
@li-xiaojun 
我是直接下载的demo的apk，在点出左边或者右边的drawer弹窗，上下滑动弹窗之后，在主页面再点击confirm弹窗会有明显的卡顿。日志的话，我并没有运行起来，leaks也没有具体的原因，只是报内存溢出

**Comment by IFeelIFeel** [comment]
@li-xiaojun 
![image](https://user-images.githubusercontent.com/28013103/50744973-7f19c100-1262-11e9-945a-933b29b18faa.png)

**Comment by li-xiaojun** [comment]
@IFeelIFeel 
你是什么时候下载的APK，Demo中的APK解决过一次内存泄露，你重新下载一个看看。
