### ISSUE TITLE
内存泄漏问题

### ISSUE THREAD

**Issue by skytang168** [li-xiaojun/XPopup#272]
1.8.9内存依然存在
将context换成application的context就可以了 本来单例模式就是静态的，生命周期是和应用的生命周期是一样的

**Comment by gdmec07140644** [comment]
是的，还存在
![image](https://user-images.githubusercontent.com/14285067/64092915-13eca400-cd89-11e9-9ebd-c0a0602ff8f1.png)

**Comment by li-xiaojun** [comment]
最新版本1.8.10已经解决。
