### ISSUE TITLE
内存泄漏的问题

### ISSUE THREAD

**Issue by linzhengloser** [li-xiaojun/XPopup#273]
在升级 1.8.9 版本之前，出现过内存泄漏，大部分都是有 XPopup 类里面静态的 statck 导致的。我猜原因可能是我的代码中 finish() 的调用在 BasePopupView 的 dismiss() 之前，不知道是不是这个原因？

在升级了 1.8.9 之后，普通的弹出关闭都会导致内存泄漏，具体泄漏的类如下图:
![image](https://user-images.githubusercontent.com/12724989/64096675-d3932300-cd94-11e9-823d-9569199301ee.png)

里面 SettingActivity 是我定义的 Activity，而 ReportFragment 是 Lifecycle 库里面的。

**Comment by skytang168** [comment]
这个问题就是因为单例模式持有非application的context造成的，提醒过作者很多遍了，不知道他为什么不按我的思路去改，我这边把库下下来依赖以后改成application的context就不会出现这个问题了 很纳闷

**Comment by li-xiaojun** [comment]
泄露的问题主要是没有及时清除引用，用application的context只是一个表面上看起来解决了的方案，不报泄露了，但内存仍然没有释放。我这两天优化下，把这个问题彻底解决掉。

**Comment by li-xiaojun** [comment]
最新版本1.8.10已经解决。

**Comment by linzhengloser** [comment]
@li-xiaojun 我升级到了 1.9.10-x 版本，但是内存泄漏还是存在。具体如下图：
![image](https://user-images.githubusercontent.com/12724989/65059660-f9c9dd00-d9a8-11e9-83ed-f4d8312ad150.png)
请问哪个版本可以规避掉这个 NavigationBarObserver 类？

**Comment by linzhengloser** [comment]
奇怪的是，这个泄漏没法百分之百复现出来。

**Comment by zhourenjun** [comment]
1.8.10-x 版本，内存泄漏还是存在
