### ISSUE TITLE
升级到1.8.9报 Cannot access 'init': it is protected/*protected and package*/ in 'BasePopupView'

### ISSUE THREAD

**Issue by BoyYangyang** [li-xiaojun/XPopup#274]
请问升级到1.8.9报 Cannot access 'init': it is protected/*protected and package*/ in 'BasePopupView'错误

**Comment by li-xiaojun** [comment]
编译能通过吗？

**Comment by BoyYangyang** [comment]
不能编译通过

**Comment by li-xiaojun** [comment]
你是不是自己调用init方法了？

**Comment by BoyYangyang** [comment]
是的,因为我用的是InputConfirmPopuoView,我需要设置里面EditText的属性,所以要手动调用init(),方法,1.8.8调用正常,但1.8.9报错,看了你的源码,init()方法是public的啊,应该能手动调用吧?

**Comment by li-xiaojun** [comment]
1.8.9改为protect了，为了不让外界调用init等一些内置的方法，你可以getEditText()来获取EditText进行一些设置。

**Comment by BoyYangyang** [comment]
没有调用init,直接getEditText(),直接报空指针异常  java.lang.IllegalStateException: inputConfirmPopupView.editText must not be null

**Comment by li-xiaojun** [comment]
调用时机可能不对，需要在弹窗执行完onCreate之后才不为空，具体可以看看文档

**Comment by BoyYangyang** [comment]
好的,谢谢
