### ISSUE TITLE
更新到1.8.9版本 asCenterList方法 点列表最后一栏点击范围变小

### ISSUE THREAD

**Issue by zzm123456** [li-xiaojun/XPopup#275]
更新到1.8.9版本 使用asCenterList方法 点列表最后一栏点击范围变小，其他栏点击整栏有效

**Comment by zzm123456** [comment]
Demo也有这个问题，最后一列点文字周围有效，点空白无效

**Comment by AltriaTT** [comment]
asBottomList列表最后一栏点击范围变小（仅文字周围有效），asCenterList使用正常，另外Demo的asBottomList方法没有问题。

**Comment by zzm123456** [comment]
emmm。。我这里都会

**Comment by KeqingLI** [comment]
BottomList也有这情况

**Comment by clj12081103** [comment]
我也是

**Comment by li-xiaojun** [comment]
最新版本1.8.10已经解决。

**Comment by KeqingLI** [comment]
老哥，你修复了最后一排宽度，把选中状态的勾搞掉了

**Comment by li-xiaojun** [comment]
@KeqingLI 
是的，😜，下版本修复。
