### ISSUE TITLE
loadingView可否封装一下

### ISSUE THREAD

**Issue by kscMaster** [li-xiaojun/XPopup#279]
想使用LoadingView封装一个全局的加载视图,但发现在跳转到第二个页面的时候就不显示了

**Comment by kscMaster** [comment]
`
public class AlertDialogView
{
    private static final AlertDialogView mDialogView = new AlertDialogView();

    public static AlertDialogView getInstance()
    {
        return mDialogView;
    }

    private static LoadingPopupView loading;

    public void showLoading(Context cxt, String tip)
    {
        if (loading == null)
        {
            if (tip.equals("")) tip = "请稍后...";
            loading = (LoadingPopupView) new XPopup.Builder(cxt).dismissOnBackPressed(false).dismissOnTouchOutside(false).asLoading(tip).show();
        } else
        {
            loading.setTitle(tip).show();
        }
    }

    public void dismiss()
    {
        if (loading != null) loading.dismiss();
    }
}

`
- 调用：` AlertDialogView.getInstance().showLoading(App.getCtx(), "loading");
`
 - 取消：`AlertDialogView.getInstance().dismiss();
`

以上是我准备封装到项目中的代码，但是发现只能传入Activity，而且就算传入Activity，在跳转到第二个Activity的时候，loading就不显示了，能帮我排查一下原因吗？不胜感激

 - 另外，希望可以传入Application的实例，这样调用的时候，只需要传一个字符串就可以了，但目前不支持

**Comment by li-xiaojun** [comment]
如果你第一页界面的dismiss操作在第二个界面的show之后就会造成这个情况，建议试下delayDismiss，加个1秒的延时来看看。

**Comment by kscMaster** [comment]
试了，也不行，我用系统的Dialog测试，跳转到第二个页面，也不显示，打断点看了，方法走了，但是就是不显示，
```java
public class AlertDialogView
{
    private static final AlertDialogView mDialogView = new AlertDialogView();

    public static AlertDialogView getInstance()
    {
        return mDialogView;
    }
    private Dialog progressDialog;

    public void showLoading(Activity aty, String txt)
    {
        if (progressDialog == null)
        {
                progressDialog = new Dialog(aty, R.style.progress_dialog);
                progressDialog.setContentView(R.layout.view_loading);
                progressDialog.setCancelable(false);
                progressDialog.getWindow().setBackgroundDrawableResource(android.R.color.transparent);
                TextView msg = progressDialog.findViewById(R.id.tv_msg);
               msg.setText(txt);
               progressDialog.show();
        } else
        {
            ((TextView)progressDialog.findViewById(R.id.tv_msg)).setText(txt);
            progressDialog.show();
        }
    }

    public void dismissLoading()
    {
        if (progressDialog != null)
        {
            progressDialog.dismiss();
        }
    }
}
```

问题可能出在我这里
