### ISSUE TITLE
带选择效果的列表展示功能，不能默认记住上次选择的position，position一开始就被写死了

### ISSUE THREAD

**Issue by zjJunZhu** [li-xiaojun/XPopup#28]
谢谢作者提供这么方便易用的弹窗库

**Comment by li-xiaojun** [comment]
如果框架提供默认记住上次功能的话，每次show都会显示上次的位置，有时候也不好。在功能上的考虑是框架更多的是负责显示，不去侵入逻辑。所以，记住这个功能需要你用一个变量来存储。

**Comment by zjJunZhu** [comment]
明白了，谢谢
