### ISSUE TITLE
PartShadowPopupView的遮盖问题

### ISSUE THREAD

**Issue by franticn** [li-xiaojun/XPopup#280]
项目中使用的`PartShadowPopupView`吸附的底部控件使用了```android:clipChildren="false"
    android:clipToPadding="false"```属性，导致对应的`PartShadowPopupView#show`的时候遮盖了本来应该超出父View的部分。这样的有啥思路嘛？

预期结果
![image](https://user-images.githubusercontent.com/21286570/64417056-f55d1480-d0ca-11e9-8b07-8746aa72e5ae.png)

实际使用
![image](https://user-images.githubusercontent.com/21286570/64417087-03ab3080-d0cb-11e9-9f6f-255c4bdf6496.png)

感觉这样的效果用`BottomSheet`更好实现一点

**Comment by li-xiaojun** [comment]
这个效果建议用动画做吧，弹窗是位于所有View顶层的，遮盖无法避免，还是用View+Translation动画来实现比较好。
