### ISSUE TITLE
viewPager 点击查看大图  返回位置不正确 demo 同样有此问题

### ISSUE THREAD

**Issue by dxclass** [li-xiaojun/XPopup#284]
场景：点击查看大图后  左或者右滑动多次，在返回 图会返回到屏幕之外

最后2张图 以上  不包含两张图  去进行测试。

很容易出发

**Comment by cbuemc** [comment]
我同样有这个问题，返回的动画没有了，就viewpager左右滑动，下拉返回，就一闪就没了
