### ISSUE TITLE
S10 在底部有导航的时候无法充满屏幕，继承自PartShadowPopupView

### ISSUE THREAD

**Issue by WangStormstout** [li-xiaojun/XPopup#288]
![image](https://user-images.githubusercontent.com/21374546/64681949-33837b00-d4b3-11e9-9321-59ec0be9bb69.png)
感谢开源。
这就是我的问题。

**Comment by WangStormstout** [comment]
![image](https://user-images.githubusercontent.com/21374546/64682106-76455300-d4b3-11e9-8fce-270e00121d44.png)
全面屏时无问题
--------ScreenInfo--------
Screen Width : 1440px
Screen RealWidth :1440px
Screen Height: 2838px
Screen RealHeight: 3040px
Screen StatusBar Height: 150px
Screen ActionBar Height: 196px
Screen NavigationBar Height: 168px
Screen Dpi: 560
Screen Density: 3.5
--------------------------
这是我用工具类获得屏幕想信息
如果需要，我贴出工具类

**Comment by WangStormstout** [comment]
作者你好 
我可能发现问题了。
三星S10上 当全面屏开启手势提示和非全面屏传统导航条的时候。导航栏高度都是168。
其实全面屏开启手势提示的高度根本不足168，这就导致了底部留白。

**Comment by hyx0804xiaokeai** [comment]
不仅仅只是S10，测试的所有三星机带全面屏手势的切换到全面屏的时候，都会有留白现象。我这边也有这个现象，我想应该是需要适配三星的全面屏

**Comment by fansangg** [comment]
google pixel 一样有这个问题

**Comment by li-xiaojun** [comment]
@fansangg  @WangStormstout  @hyx0804xiaokeai 
试试1.9.3，修复了这个问题
