### ISSUE TITLE
BottomPopup位置问题

### ISSUE THREAD

**Issue by parcool** [li-xiaojun/XPopup#29]
图1(手机上 小米mix2s)
![image](https://user-images.githubusercontent.com/12092478/50879389-b1b7eb00-1415-11e9-8517-e7f77eccd1e6.png)

图2(模拟器上)
![image](https://user-images.githubusercontent.com/12092478/50879419-cac09c00-1415-11e9-940d-354eee13b1ec.png)

注意底部，发现手机和模拟器出现的位置不同，一个像是针对decorationView，一个像是触发按钮的View？

**Comment by li-xiaojun** [comment]
@parcool 
这个问题在最新版`1.0.8`已经修复，请更新看看。
