### ISSUE TITLE
当 Activity 处于非 resume 状态时显示对话框仅是一个透明的背景没有内容 (复现率100%，任何机型)

### ISSUE THREAD

**Issue by kaku2015** [li-xiaojun/XPopup#290]
如题，复现率100%，任何机型

**Comment by li-xiaojun** [comment]
show me your code.

**Comment by shenqiwen** [comment]
我也碰到了这个问题,就是当app处于前台但是手机处于熄屏状态时创建弹窗,只会有一个透明背景没有布局

**Comment by kaku2015** [comment]
示例代码即可复现，测试步骤：在B界面向A界面发送事件显示对话框，返回到A界面。

**Comment by gengyan2011302978** [comment]
解决了没，同问

**Comment by HystrixWong** [comment]
弹出的时候手动判断下app在前台还是后台，是否息屏就可以了，虽然这样不太优雅

**Comment by li-xiaojun** [comment]
本质上弹窗依赖于当前Activity的界面，如果要显示弹窗的Activity是不可见的，那么弹窗就无法计算宽高了。可以加点小技巧，比如等Activity显示的时候再弹出，而不是立即弹出

**Comment by xiaolingcong** [comment]
popup?.dialog?.dismiss()
可以在dismiss 之后调用diaglog 的dismiss方法。测试可以解决这个问题
