### ISSUE TITLE
设置enableDrag(false),底部弹出dialog默认动画会消失

### ISSUE THREAD

**Issue by lodgkk** [li-xiaojun/XPopup#291]
设置enableDrag(false),底部弹出dialog默认动画会消失

**Comment by lodgkk** [comment]
添加自定义动画没有消失

**Comment by li-xiaojun** [comment]
试试1.9.3，修复了这个问题

**Comment by Fomovet** [comment]
最新版2.6.6还是存在这个问题，设置enableDrag(false),底部弹出的Dialog默认动画会消失

**Comment by li-xiaojun** [comment]
@Fomovet 更新到2.6.7即可
