### ISSUE TITLE
CenterList选中后面的对勾没了

### ISSUE THREAD

**Issue by shuigesuntao** [li-xiaojun/XPopup#292]

**Comment by senyung** [comment]
I try v1.8.8 in API 29 both CenterList & ButtomList with Check do not show the check but ok in API 28,  
@shuigesuntao  is your API 29 too ?

**Comment by senyung** [comment]
@li-xiaojun could you update the CenterList & ButtomList with Check for API 29 too ?

**Comment by mrMengZhen** [comment]
我下载的是最新的v1.8.10的代码，运行之后，CenterList & ButtomList也不显示对勾了，体验的v1.8.8版本的app可以显示对勾

**Comment by SheepYang1993** [comment]
新建个布局，然后bindItemLayout。

    new XPopup.Builder(getContext())
            .asCenterList("请选择格子大小", sizeArrays,
                    null, index,
                    new OnSelectListener() {
                        @Override
                        public void onSelect(int position, String text) {
                            
                        }
                    })
            .bindItemLayout(R.layout.item_size_change)
            .show();

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:background="?android:attr/selectableItemBackground"
    android:orientation="vertical"
    tools:background="#FFD5D5">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:gravity="center_vertical"
        android:orientation="horizontal"
        android:paddingLeft="18dp"
        android:paddingTop="12dp"
        android:paddingRight="18dp"
        android:paddingBottom="12dp">

        <ImageView
            android:id="@+id/iv_image"
            android:layout_width="22dp"
            android:layout_height="22dp"
            android:layout_marginRight="6dp"
            tools:background="#B9FFB0"
            tools:visibility="visible" />

        <TextView
            android:id="@+id/tv_text"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_marginRight="6dp"
            android:layout_weight="1"
            android:ellipsize="end"
            android:lines="1"
            android:textColor="@color/_xpopup_title_color"
            android:textSize="15sp"
            tools:background="#B9FFB0"
            tools:text="测试测试测试测试测试测试" />

        <FrameLayout
            android:id="@+id/flRight"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            tools:background="#B9FFB0">

            <com.lxj.xpopup.widget.CheckView
                android:id="@+id/check_view"
                android:layout_width="30dp"
                android:layout_height="30dp"
                android:layout_gravity="center_vertical"
                android:visibility="gone"
                tools:visibility="visible" />
        </FrameLayout>
    </LinearLayout>

    <include layout="@layout/_xpopup_divider" />
</LinearLayout>

**Comment by li-xiaojun** [comment]
已经修复最新版
