### ISSUE TITLE
自定义布局问题

### ISSUE THREAD

**Issue by qiangzengli** [li-xiaojun/XPopup#293]
请问自定义布局的  popup   中的控件的点击事件  必须在Popup中的onCreate中设置吗   ，请问能在activity或者fragment中通过findviewByid来设置吗

**Comment by li-xiaojun** [comment]
可以，弹窗的本质就是当前Activity的一个View对象。

**Comment by qiangzengli** [comment]
为什么我总是的到空指针，弹窗显示出来不就代表已经走过onCreate了吗

**Comment by qiangzengli** [comment]
今天又试了一下，在  show之后  设置  100毫秒的延迟  就不会报nullpointerexception了   ，应该就是这100毫秒的时间  才让弹窗有机会执行onCreate

**Comment by li-xiaojun** [comment]
你可以把代码放到onCreated中，当onCreated执行的时候，就不会报空指针了
