### ISSUE TITLE
在华为全面屏，当我的弹框高度是全屏的时候的问题

### ISSUE THREAD

**Issue by scorpiokara** [li-xiaojun/XPopup#295]
弹框中是个recyclerview，撑满屏幕的
发现最终计算的高度少了状态栏的高度，
代码在 AttachPopupView 中183行
if (getPopupContentView().getMeasuredHeight() + rect.bottom > XPopupUtils.getWindowHeight(getContext())) {
                    ViewGroup.LayoutParams params = getPopupContentView().getLayoutParams();
                    params.height = XPopupUtils.getWindowHeight(getContext()) - rect.bottom;
                    getPopupContentView().setLayoutParams(params);
                }

XPopupUtils.getWindowHeight(getContext()) 的高度并不是真正的屏幕高度
我改成 ：
if (ImmersionBar.hasNotchScreen(getPopupContentView())){
                        params.height = XPopupUtils.getWindowHeight(getContext()) - rect.bottom + XPopupUtils.getStatusBarHeight();
                    }else {
                        params.height = XPopupUtils.getWindowHeight(getContext()) - rect.bottom;
                    }
就正确了
是bug还是我使用的姿势不正确？？

**Comment by li-xiaojun** [comment]
试试1.9.3，修复了这个问题
