### ISSUE TITLE
重新show 的时候如何 改变弹窗内容

### ISSUE THREAD

**Issue by zhaoxiuyu** [li-xiaojun/XPopup#296]
xPopup = XPopup.Builder(this).asConfirm(title, content, cancelBtnText, confirmBtnText, confirmListener, cancelListener, isHideCancel).show()

xPopup .dismiss 之后

重新 xPopup.show() 的时候如何改变弹窗内容

**Comment by li-xiaojun** [comment]
内置弹窗的话，你可以重新new；
获取可以find到子View来修改，弹窗就是View对象。
