### ISSUE TITLE
Google pixel 开启全屏幕手势后，底部留白

### ISSUE THREAD

**Issue by fansangg** [li-xiaojun/XPopup#299]
Android 10，Google pixel

**Comment by fansangg** [comment]
xpopup是1.8.10

**Comment by fansangg** [comment]
![image](https://user-images.githubusercontent.com/17351112/65407271-94e10d80-de14-11e9-8b22-4ed488c000e2.png)

**Comment by lovemianhuatang** [comment]
三星也会

**Comment by loperSeven** [comment]
一加也会

**Comment by zhourenjun** [comment]
各位麻烦测一下啊
 public static boolean isShowNavBar(Context context) {
        if (null == context) {
            return false;
        }
        /**
         * 获取应用区域高度
         */
        Rect outRect1 = new Rect();
        try {
            ((Activity) context).getWindow().getDecorView().getWindowVisibleDisplayFrame(outRect1);
        } catch (ClassCastException e) {
            e.printStackTrace();
            return false;
        }
        int activityHeight = outRect1.height();

        Log.e("zrj", "状态栏高度:"+ getStatusBarHeight() );
        Log.e("zrj", "应用区域高度:"+ activityHeight );
        Log.e("zrj", "导航栏高度:"+ getNavBarHeight() );
        Log.e("zrj", "屏幕物理高度:"+ getRealHeight(context) );
        /**
         * 屏幕物理高度 - 状态栏高度  导航栏高度 = 导航栏存在时的应用实际高度
         */
        int remainHeight = getRealHeight(context) - getStatusBarHeight() - getNavBarHeight();

        Log.e("zrj", "remainHeight:"+ remainHeight );
        /**
         * 剩余高度跟应用区域高度相等 说明导航栏存在
         */
        if (activityHeight == remainHeight) {
            return true;
        } else {
            return false;
        }
    }


    public static int getRealHeight(Context context) {
        WindowManager   wm = ((WindowManager) context.getSystemService(Context.WINDOW_SERVICE));
        Point point = new Point();
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
            wm.getDefaultDisplay().getRealSize(point);
        } else {
            wm.getDefaultDisplay().getSize(point);
        }
        return point.y;
    }

**Comment by zhourenjun** [comment]
源码里面判断导航栏是否显示时的，想请各位用不同机型测试一下，如果可以希望作者更新一下依赖版本，我只有一种测试机是非小米，华为的

**Comment by li-xiaojun** [comment]
@zhourenjun  @loperSeven @fansangg @lovemianhuatang 
试试1.9.3，修复了这个问题
