### ISSUE TITLE
建议添加取消和显示的事件回调

### ISSUE THREAD

**Issue by hanlin19900610** [li-xiaojun/XPopup#3]
建议添加取消和显示的事件回调,方便做一些自定义的处理

**Comment by li-xiaojun** [comment]
好想法，我抽个空加下。

**Comment by hanlin19900610** [comment]
最近搭个框架开始用你的这个库, 实际情况是要用到一些回调事件的

**Comment by li-xiaojun** [comment]
@hanlin19900610  
感谢您的建议和想法，我已经在新版本`0.0.8`中增加了该功能，具体看README的screenshot演示和说明。
