### ISSUE TITLE
DrawerPopupView布局recycleview notify出现问题

### ISSUE THREAD

**Issue by LailaiMaster** [li-xiaojun/XPopup#30]
如果抽屉类型弹窗布局包含RecyclerView，当我调用notifyDataSetChanged的时候 ，会导致内容消失，只留一个半透明的背景。点击也无法取消

**Comment by li-xiaojun** [comment]
@LailaiMaster 
感谢你的建议，我看看这个问题。

**Comment by li-xiaojun** [comment]
@LailaiMaster 
这个问题在最新版`1.0.8`已经修复，请更新看看。
