### ISSUE TITLE
android x 版本的 xpopup 所依赖的 easyadapter 和 xpermission 都是support版本，导致现在编译出错。

### ISSUE THREAD

**Issue by ZQ173** [li-xiaojun/XPopup#301]
如题，希望尽快修复，依赖分析如下：

+--- com.lxj:xpopup:1.8.10-x
|    +--- androidx.appcompat:appcompat:1.0.0-beta01 -> 1.0.0 (*)
|    +--- androidx.recyclerview:recyclerview:1.0.0-beta01
|    |    +--- androidx.annotation:annotation:1.0.0-beta01 -> 1.0.0
|    |    +--- androidx.core:core:1.0.0-beta01 -> 1.0.0 (*)
|    |    \--- androidx.legacy:legacy-support-core-ui:1.0.0-beta01 -> 1.0.0 (*)
|    +--- com.google.android.material:material:1.0.0-beta01
|    |    +--- androidx.annotation:annotation:1.0.0-beta01 -> 1.0.0
|    |    +--- androidx.core:core:1.0.0-beta01 -> 1.0.0 (*)
|    |    +--- androidx.legacy:legacy-support-core-ui:1.0.0-beta01 -> 1.0.0 (*)
|    |    +--- androidx.legacy:legacy-support-core-utils:1.0.0-beta01 -> 1.0.0 (*)
|    |    +--- androidx.fragment:fragment:1.0.0-beta01 -> 1.0.0 (*)
|    |    +--- androidx.transition:transition:1.0.0-beta01
|    |    |    +--- androidx.annotation:annotation:1.0.0-beta01 -> 1.0.0
|    |    |    \--- androidx.core:core:1.0.0-beta01 -> 1.0.0 (*)
|    |    +--- androidx.appcompat:appcompat:1.0.0-beta01 -> 1.0.0 (*)
|    |    +--- androidx.cardview:cardview:1.0.0-beta01 -> 1.0.0
|    |    |    \--- androidx.annotation:annotation:1.0.0
|    |    \--- androidx.recyclerview:recyclerview:1.0.0-beta01 (*)
|    +--- com.lxj:easyadapter:1.1.1
|    |    +--- com.android.support:appcompat-v7:26.0.0
|    |    |    +--- com.android.support:support-annotations:26.0.0
|    |    |    +--- com.android.support:support-v4:26.0.0
|    |    |    |    +--- com.android.support:support-compat:26.0.0
|    |    |    |    |    \--- com.android.support:support-annotations:26.0.0
|    |    |    |    +--- com.android.support:support-media-compat:26.0.0
|    |    |    |    |    +--- com.android.support:support-annotations:26.0.0
|    |    |    |    |    \--- com.android.support:support-compat:26.0.0 (*)
|    |    |    |    +--- com.android.support:support-core-utils:26.0.0
|    |    |    |    |    +--- com.android.support:support-annotations:26.0.0
|    |    |    |    |    \--- com.android.support:support-compat:26.0.0 (*)
|    |    |    |    +--- com.android.support:support-core-ui:26.0.0
|    |    |    |    |    +--- com.android.support:support-annotations:26.0.0
|    |    |    |    |    \--- com.android.support:support-compat:26.0.0 (*)
|    |    |    |    \--- com.android.support:support-fragment:26.0.0
|    |    |    |         +--- com.android.support:support-compat:26.0.0 (*)
|    |    |    |         +--- com.android.support:support-core-ui:26.0.0 (*)
|    |    |    |         \--- com.android.support:support-core-utils:26.0.0 (*)
|    |    |    +--- com.android.support:support-vector-drawable:26.0.0
|    |    |    |    +--- com.android.support:support-annotations:26.0.0
|    |    |    |    \--- com.android.support:support-compat:26.0.0 (*)
|    |    |    \--- com.android.support:animated-vector-drawable:26.0.0
|    |    |         +--- com.android.support:support-vector-drawable:26.0.0 (*)
|    |    |         \--- com.android.support:support-core-ui:26.0.0 (*)
|    |    +--- com.android.support:recyclerview-v7:26.0.0
|    |    |    +--- com.android.support:support-annotations:26.0.0
|    |    |    +--- com.android.support:support-compat:26.0.0 (*)
|    |    |    \--- com.android.support:support-core-ui:26.0.0 (*)
|    |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.21
|    |         \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.21
|    |              +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.3.21
|    |              \--- org.jetbrains:annotations:13.0
|    \--- com.lxj:xpermission:1.0.1
|         \--- com.android.support:appcompat-v7:26.0.0 (*)

**Comment by lodgkk** [comment]
其实很简单,不用androidx的版本就好了

**Comment by li-xiaojun** [comment]
Studio启用androidx配置即可。
