### ISSUE TITLE
有没有谁遇到过dissmissdialog的时候整个屏幕都无法点击,什么操作都进行不了

### ISSUE THREAD

**Issue by lodgkk** [li-xiaojun/XPopup#303]
有没有谁遇到过dissmissdialog的时候整个屏幕都无法点击,什么操作都进行不了,这个情况是偶尔出现的,我怀疑有个什么挡住整个屏幕了,所以什么都点击不了

**Comment by benxin123** [comment]
我遇到了，解决了吗？

**Comment by fushengguoban** [comment]
我也遇到了。你是怎么解决的

**Comment by fushengguoban** [comment]
> 我遇到了，解决了吗？

你好，你现在的问题解决了吗

**Comment by lodgkk** [comment]
我有时候也遇到过,不知道是什么原因,感觉有个遮罩挡住了
