### ISSUE TITLE
设置 不让让输入框自动获取焦点，弹窗不强制抢占焦点后，弹窗弹出时，键盘无法弹起

### ISSUE THREAD

**Issue by JiayuanChan** [li-xiaojun/XPopup#304]
### 设置 不让让输入框自动获取焦点，弹窗不强制抢占焦点后，弹窗弹出时，键盘无法弹起###
![image](https://user-images.githubusercontent.com/18372409/65827987-783b4e80-e2c8-11e9-8da1-c3e96b52313d.png)

**Comment by JiayuanChan** [comment]
我的弹窗内容中有多个EditText，需要根据需要设置对应的某个EditText获取焦点

**Comment by JiayuanChan** [comment]
当设置 不让让输入框自动获取焦点，弹窗不强制抢占焦点后。根据需要设置对应的EditText获取焦点后，键盘就不能弹出

**Comment by JiayuanChan** [comment]
弹窗布局为 RecyclerView

**Comment by li-xiaojun** [comment]
你可以主动弹起键盘的
