### ISSUE TITLE
自定义BottomPopupView弹窗布局显示不全

### ISSUE THREAD

**Issue by Lucifer119119** [li-xiaojun/XPopup#305]
布局中有一个含有RecyclerView     弹出有的时候下面有一部分无法弹出来 需要向上拖拽才能显示完整，最后我将enableDrag改成false 才每次都弹出完整

版本 1.8.10
手机 一加6T Android 9.0

**Comment by 50kg** [comment]
版本 1.8.10
手机 一加7 pri Android 10.0
一样的问题，需要拉一下才展示全部

**Comment by Lucifer119119** [comment]
@li-xiaojun 能给看一下什么情况吗
![Screenshot_20191016-113141](https://user-images.githubusercontent.com/35765981/66886243-500e5800-f009-11e9-95f6-883ddb6981a5.jpg)
![Screenshot_20191016-113207](https://user-images.githubusercontent.com/35765981/66886247-51d81b80-f009-11e9-908f-658c3dfc998c.jpg)
大概就是图上演示的这样弹窗会出现一般隐藏在下面  ，需要往上拽一下才显示完全  ，布局主要就是用了一个RecyclerView  当把enbleDrag 设置为false之后就不会出现这种情况
