### ISSUE TITLE
在联想平板上竖屏时无法全屏

### ISSUE THREAD

**Issue by 18300072348** [li-xiaojun/XPopup#308]
![Screenshot_20191008-214656](https://user-images.githubusercontent.com/18573453/66401452-c4e3ff80-ea15-11e9-899a-388b61cab9fd.png)

在联想 TB3-X70F Android6.0上竖屏时无法全屏，右边有空白

**Comment by 18300072348** [comment]
修改com.lxj.xpopup.core.BasePopupView 下的applySize方法里面设置bottommargin或rightmargin方法可暂时解决问题，作者可留意一下 @li-xiaojun

**Comment by 18300072348** [comment]
我发现是该平板在竖屏的时候返回的rotation是1或者3， 

        if (rotation == 0) {
            params.leftMargin = 0;
            params.rightMargin = 0;
//            params.bottomMargin = isNavBarShown ? XPopupUtils.getNavBarHeight() : 0;
            params.bottomMargin = 0;
        } else if (rotation == 1) {
            params.bottomMargin = 0;
//            params.rightMargin = isNavBarShown ? XPopupUtils.getNavBarHeight() : 0;
            params.rightMargin = 0;
            params.leftMargin = 0;
        } else if (rotation == 3) {
            params.bottomMargin = 0;
            params.leftMargin = 0;
//            params.rightMargin = isNavBarShown ? XPopupUtils.getNavBarHeight() : 0;
            params.rightMargin = 0;
        }

**Comment by AceInAndroid** [comment]
小米k20p android 10 也是同样问题

**Comment by li-xiaojun** [comment]
@AceInAndroid  @18300072348 
试试1.9.3，修复了这个问题
