### ISSUE TITLE
嵌套调用会报内存泄漏

### ISSUE THREAD

**Issue by zzm123456** [li-xiaojun/XPopup#309]
![image](https://user-images.githubusercontent.com/13730768/66454898-cf48dc80-ea9b-11e9-8d50-583eee01e0e9.png)
![image](https://user-images.githubusercontent.com/13730768/66455090-539b5f80-ea9c-11e9-9ed3-eb1bdc9a22f0.png)

**Comment by li-xiaojun** [comment]
这是demo的泄漏，但你用到自己的项目不会有xpopup引发的内存泄漏。demo的泄漏暂时没有精力去修复了。

**Comment by zzm123456** [comment]
emmm...我就是项目里这样调用会报泄漏 所以跑到demo里来试一下，结果也是报泄漏

**Comment by zzm123456** [comment]
@li-xiaojun

**Comment by li-xiaojun** [comment]
是最新版本吗，不是的更新到最新。

**Comment by zzm123456** [comment]
对 是最新的 1.8.10版本
