### ISSUE TITLE
Margin的设置问题

### ISSUE THREAD

**Issue by 164738777** [li-xiaojun/XPopup#31]
继承BaseBottomPop后, 怎么修改bottomMarin? 默认的是贴边的.

尝试过在`initPopupContent()`里
`
FrameLayout.LayoutParams lp = (FrameLayout.LayoutParams) getPopupImplView().getLayoutParams();
        lp.bottomMargin = ScreenUtils.dp2px(20);
        getPopupImplView().setLayoutParams(lp);
`
没有效果,

也尝试过在`getImplLayoutId`的布局加marginBottom也是无效

**Comment by li-xiaojun** [comment]
@164738777 
我试了下没有问题啊，如果你是直接继承BasePopupView，`getImplLayoutId`方法不用实现。
我刚更新了代码，里面有直接继承BasePopupView的示例。

**Comment by 164738777** [comment]
好的, 谢谢, 我再看看.
