### ISSUE TITLE
自定义AttachPopupView时，设置背景，可以看到后面还有一层背景

### ISSUE THREAD

**Issue by amosxb** [li-xiaojun/XPopup#313]

**Comment by li-xiaojun** [comment]
![image](https://user-images.githubusercontent.com/4426715/66694019-d3fed200-ece1-11e9-87d0-6c343e47c148.png)

**Comment by amosxb** [comment]
重写了那个getPopupBackground()方法啊，布局的最外层布局也没有设置任何背景


------------------ 原始邮件 ------------------
发件人: "Jun"<notifications@github.com>;
发送时间: 2019年10月12日(星期六) 中午11:17
收件人: "li-xiaojun/XPopup"<XPopup@noreply.github.com>;
抄送: "643654597"<643654597@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [li-xiaojun/XPopup] 自定义AttachPopupView时，设置背景，可以看到后面还有一层背景 (#313)

**Comment by li-xiaojun** [comment]
截图看看效果

**Comment by dengqiudq** [comment]
背景有半透明的黑色背景，是怎么去掉呢

**Comment by No8blackball** [comment]
解决了吗

**Comment by gzpaiwxc** [comment]
@li-xiaojun  现在都没有getPopupBackground() 的方法 , 怎么重写?

**Comment by gzpaiwxc** [comment]
重写了背景后默认的动画就有问题了
