### ISSUE TITLE
atview(view)之后，不显示弹窗

### ISSUE THREAD

**Issue by kokod21** [li-xiaojun/XPopup#314]
Xpopup版本 1.8.9-x
手机
![微信图片_20191012130829](https://user-images.githubusercontent.com/5299774/66695219-7c686280-ecf1-11e9-9358-4c01d0928ff9.jpg)
调用代码如下：
`XPopup.Builder(this)
            .atView(tv_shop)
            .asAttachList(resources.getStringArray(R.array.shop_type), null)
            { position, _ ->
                when (position) {
                    0 -> {
                        startActivity(ShopManageActivity::class.java)
                    }
                    1 -> {
                          startActivity(ShopManageActivity::class.java)
                    }
                }
            }
            .show()`

然后没有显示弹窗列表，只显示了透明黑色背景，代码中的tv_shop就是底部中间的那个按钮
![image](https://user-images.githubusercontent.com/5299774/66695241-c9e4cf80-ecf1-11e9-8aeb-8a8da49b4359.png)

**Comment by JsJeffDeveloper** [comment]
![image](https://user-images.githubusercontent.com/54256682/67082707-44b75a00-f1cc-11e9-80c1-c0ab00c8be97.png)
我定位到，当页面不显示的时候，是因为这个宽度w计算为0，导致的

**Comment by li-xiaojun** [comment]
页面都不显示了，还需要显示弹窗吗？你是什么场景

**Comment by austenyad** [comment]
> 页面都不显示了，还需要显示弹窗吗？你是什么场景
这需求要的！！

**Comment by kokod21** [comment]
> 页面都不显示了，还需要显示弹窗吗？你是什么场景

不是不显示页面，是在页面中点击底部的一个按钮，然后atview(view).asAttachList()来显示一个列表，但是这个pop不显示。
最近另一个用户发了另一个视频过来，pop列表有显示，但是一闪之后就消失了。
因为都是用户手机，且机型比较奇葩，比如我第一次提问的魅族M1E这种，我这边没法复现，或者您方便邮箱联系吗？我发个视频给您看看，视频比较清楚，我的邮箱
275648572@qq.com

**Comment by danyunliuhen** [comment]
这个问题最新的issue里好几个提到 有必现步骤

**Comment by kokod21** [comment]
> 这个问题最新的issue里好几个提到 有必现步骤

有发现问题根源吗？

**Comment by kokod21** [comment]
> 这个问题最新的issue里好几个提到 有必现步骤

刚才看了一下issue，他们的是跳转去到另一个页面不显示，我这个当前页面点击按钮用atview(view).asAttachList()在部分机型不显示，asCenterList等其他方法正常

**Comment by danyunliuhen** [comment]
就这个原因 未激活不可见的时候 宽高获取不到

**Comment by danyunliuhen** [comment]
> > 这个问题最新的issue里好几个提到 有必现步骤
> 
> 刚才看了一下issue，他们的是跳转去到另一个页面不显示，我这个当前页面点击按钮用atview(view).asAttachList()在部分机型不显示，asCenterList等其他方法正常

问题原因都是这个 一模一样

**Comment by lhl652github** [comment]
请问这个问题解决了吗？我也是这个问题

**Comment by kokod21** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"luhl"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月16日(星期四) 中午11:32
收件人:&nbsp;"li-xiaojun/XPopup"<XPopup@noreply.github.com&gt;;
抄送:&nbsp;"人者后卫"<275648572@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [li-xiaojun/XPopup] atview(view)之后，不显示弹窗 (#314)




请问这个问题解决了吗？我也是这个问题
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.




没有啊，大佬4个月没有更新了版本了，不知道是不是放弃这个库了。。。

**Comment by kokod21** [comment]
是的，直接用centerList，居中显示，这个没问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"luhl"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月16日(星期四) 下午3:55
收件人:&nbsp;"li-xiaojun/XPopup"<XPopup@noreply.github.com&gt;;
抄送:&nbsp;"人者后卫"<275648572@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [li-xiaojun/XPopup] atview(view)之后，不显示弹窗 (#314)



那你这个问题怎么处理的？不用asAttachList 这种方式吗？ 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"sky"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年1月16日(星期四) 下午3:52 
 收件人:&amp;nbsp;"li-xiaojun/XPopup"<XPopup@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"○o佑手邊ㄨ"<399651609@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [li-xiaojun/XPopup] atview(view)之后，不显示弹窗 (#314) 
 
 
 
 ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:&amp;amp;nbsp;"luhl"<notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年1月16日(星期四) 中午11:32  
  收件人:&amp;amp;nbsp;"li-xiaojun/XPopup"<XPopup@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"人者后卫"<275648572@qq.com&amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [li-xiaojun/XPopup] atview(view)之后，不显示弹窗 (#314)  
   
   
   
   
  请问这个问题解决了吗？我也是这个问题  
     
  —  
  You are receiving this because you authored the thread.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
   
   
   
   
  没有啊，大佬4个月没有更新了版本了，不知道是不是放弃这个库了。。。

**Comment by EternalPlan** [comment]
请问这个问题解决了吗？我也是这个问题

必现机型:  
![$}@EA9Z5GF ~YOEA_C3(OZC](https://user-images.githubusercontent.com/18061136/72511396-10644000-3886-11ea-8996-53f1a39ec3b0.jpg)
![WYRGT6HN0K55J15R Z}@A{3](https://user-images.githubusercontent.com/18061136/72511406-1528f400-3886-11ea-89e9-c201cc503345.jpg)

**Comment by kokod21** [comment]
没有解决啊，那位大佬不更新了，我不用这个方法，直接用centerlist代替了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Hypotension"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月16日(星期四) 下午5:32
收件人:&nbsp;"li-xiaojun/XPopup"<XPopup@noreply.github.com&gt;;
抄送:&nbsp;"人者后卫"<275648572@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [li-xiaojun/XPopup] atview(view)之后，不显示弹窗 (#314)




请问这个问题解决了吗？我也是这个问题
 
必现机型:

**Comment by JsJeffDeveloper** [comment]
> 页面都不显示了，还需要显示弹窗吗？你是什么场景

场景是：
App有用户登录失效，需要弹窗阻止用户做操作和友好提示用户登录失效。有可能是，用户把App切到后台的时候，用户登录失效的，这时候App就会在页面不显示的时候触发弹出登录失效弹窗

**Comment by li-xiaojun** [comment]
考虑在Activity可见的时候去显示弹窗
