### ISSUE TITLE
状态栏与FullScreenPopupView相互遮挡问题

### ISSUE THREAD

**Issue by 121104115wyb** [li-xiaojun/XPopup#316]
我是自定义的FullScreenPopupView，当显示出来时，会与状态栏发生重叠遮挡，我的解决办法是，在全屏的布局的根布局加上 android:layout_marginTop="@dimen/dp_20dp"属性，但是这种方法并不能适配所有机型，于是我找到了这个方法 
XPopup.Builder(getContext()).offsetY(-10)   //设置y轴偏移量

设置结果如下：
XPopup.Builder(getContext()).offsetY(BarUtils.getStatusBarHeight())  
完美解决；

**Comment by 121104115wyb** [comment]
当我设置好后，发现底部导航栏的也被偏移了，所以我又重新计算了下状态栏的px为72，而我的屏幕的分辨率为1080，所以就是1dp = 3px，所以我就设置了根布局的android:layout_marginTop=“24dp”，但是设置好后，还是还有一断距离显示不对，想到布局的可能有默认的间距于是修改为layout_marginTop=“16dp”，暂时解决

**Comment by v1ncent9527** [comment]
(binding.title.layoutParams as MarginLayoutParams).apply {
            setMargins(0, BarUtils.getStatusBarHeight(), 0, 0)
        }
