### ISSUE TITLE
当 Activity 处于不可见状态时，显示对话框仅是一个透明的背景，没有内容，比现

### ISSUE THREAD

**Issue by gengyan2011302978** [li-xiaojun/XPopup#321]
当当前的Activity 不可见时，如果触发弹框，会显示透明背景，不显示dialog。
比如 当前页面网络请求成功后弹框，请求过程中关闭屏幕就会显示，或者A跳转到B页面，在B页面触发A页面弹框，A页面此时不可见，返回时就会复现

**Comment by franticn** [comment]
可以参见此issue #290 ;我的做法是在需要维护一个队列，在当前Activity可见的时候进行show操作

**Comment by li-xiaojun** [comment]
可以通过生命周期来检测弹窗的展示逻辑。
