### ISSUE TITLE
请问怎么和DataBinding结合使用

### ISSUE THREAD

**Issue by Tang3210** [li-xiaojun/XPopup#322]

**Comment by xiaoshubin** [comment]
重写initPopupContent方法，在其中绑定view即可

**Comment by li-xiaojun** [comment]
在onCreate方法中绑定不行吗

**Comment by zhangxu2814** [comment]
应该很多人想用这个功能。 
我是在 onCreate 调用
 binding = DataBindingUtil.bind(getPopupImplView());

**Comment by zqlq4ever** [comment]
> 应该很多人想用这个功能。
> 我是在 onCreate 调用
> binding = DataBindingUtil.bind(getPopupImplView());

为什么我的需要给个泛型.
binding = DataBindingUtil.bind<T extends ViewDataBinding>(getPopupImplView());

**Comment by DaWenXxi** [comment]
> > 应该很多人想用这个功能。
> > 我是在 onCreate 调用
> > binding = DataBindingUtil.bind(getPopupImplView());
> 
> 为什么我的需要给个泛型.
> bind<>后面 ViewDataBinding

这个泛型就是你布局的ViewDataBinding呀
