### ISSUE TITLE
easyAdapter哪里去了

### ISSUE THREAD

**Issue by AlvinQiang** [li-xiaojun/XPopup#325]

**Comment by chocozhao** [comment]
同问。没有找到easyAdapter

**Comment by AlvinQiang** [comment]
之前是有的，估计是后来作者去掉了吧，自己写适配器就行




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"chocozhao"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月13日(星期三) 下午2:54
收件人:&nbsp;"li-xiaojun/XPopup"<XPopup@noreply.github.com&gt;;
抄送:&nbsp;"搁浅爱"<854381366@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [li-xiaojun/XPopup] easyAdapter哪里去了 (#325)




同问。没有找到easyAdapter

**Comment by chocozhao** [comment]
已解决，作者将这个抽出来了，在作者的仓库可以找到，implementation 'com.lxj:easyadapter:latest release'
