### ISSUE TITLE
关于图片数据过多OOM的问题

### ISSUE THREAD

**Issue by HolyShot** [li-xiaojun/XPopup#329]
每次点击查看大图，会把所有的图片一次性都加载一遍，返回在点击又回加载一遍，反复几次 内存就被占用完了。这个怎么解决？

**Comment by HolyShot** [comment]
在ImageViewerPopupView 中 pager.setOffscreenPageLimit(url.size()); 这个导致oom ，可以不用缓存这么多

**Comment by li-xiaojun** [comment]
内存占完说明你Glide用的有问题
