### ISSUE TITLE
华为手机弹出位置有问题

### ISSUE THREAD

**Issue by 1060591156** [li-xiaojun/XPopup#33]
华为畅享9，不是从最底部弹出的，距离底部有个几十个像素吧。
这个手机是刘海屏，是不是这几十个像素是状态栏的高度？

**Comment by 1060591156** [comment]
![screenshot_20190122-211200](https://user-images.githubusercontent.com/45003083/51537796-7a702200-1e8a-11e9-9005-367f872d5ffb.jpg)

**Comment by li-xiaojun** [comment]
@1060591156 这个问题我抽空看看。

**Comment by li-xiaojun** [comment]
@1060591156 
该问题在最新的`1.2.0`版本已经修复，在最新版已经适配市面上所有主流全面屏手机，请尝试更新看看。

**Comment by 1060591156** [comment]
赞
