### ISSUE TITLE
弹窗外部点击事件问题

### ISSUE THREAD

**Issue by ouyangsl** [li-xiaojun/XPopup#333]
在 com.lxj.xpopup.core.BasePopupView 中，onTouchEvent 重载方法拦截了所有的点击事件，判断点击事件是否在弹框内，如果在弹框外的点击事件则 dimiss 弹窗，但是当用户设置了 popupInfo.isDismissOnTouchOutside 为 false ，既点击外部不关闭弹窗，且 popupInfo.shadowBgAnimator 也为 false 时，此时弹窗没有阴影背景，点击外部也不关闭，按理说外部的点击事件应该要能穿透下去，但是实际上点击事件还是被消费掉了，此时点击弹窗外部也是无效的，应该判断当触摸事件发生在弹框外部的时候，不消费掉触摸事件，既：
`if (!XPopupUtils.isInRect(event.getX(), event.getY(), rect)) {`
`    // 省略掉判断及操作部分`
`     return true;`
`}else{`
`    return false;`
`}`

**Comment by liangliangliang** [comment]
对啊 点击外部事件没法用

**Comment by threedeer** [comment]
请问怎么解决这个问题

**Comment by li-xiaojun** [comment]
这个问题暂时不支持，因为会引发很多问题
