### ISSUE TITLE
当设置activity的Theme背景颜色后,popup弹窗背景颜色异常

### ISSUE THREAD

**Issue by Roben1016** [li-xiaojun/XPopup#335]
在AndroidManifest中设置activity的style, style中设置了background为白色或其它颜色, 再弹出普通的popup弹窗时, 背景颜色异常. 如图: 
![微信图片_20191107214323](https://user-images.githubusercontent.com/15700182/68393791-b0775c00-01a7-11ea-8b08-075ba4ffba75.jpg)

**Comment by Roben1016** [comment]
补上说明, 在demo里面的Theme中加上background颜色, 都会有问题

**Comment by li-xiaojun** [comment]
试试1.9.3，应该修复了这个问题

**Comment by LnLooFa** [comment]
当Activity的Theme设置一个图片后，自定义的Popup有问题，会把Theme的背景图带到弹框中
