### ISSUE TITLE
Android10全面屏开启底部手势横条，弹窗留白问题

### ISSUE THREAD

**Issue by loperSeven** [li-xiaojun/XPopup#337]
如同标题
不论是  1.8.8-x 还是1.8.10-x依旧存在这样的问题
下面是截图
![@JFBVGVFA7714(OTVQ39C_M](https://user-images.githubusercontent.com/20430552/68575281-ace51d00-04a6-11ea-88db-fc26e8d108d7.png)
![57AD763B3ED63A2BFEC7C84ABA24FADC](https://user-images.githubusercontent.com/20430552/68575285-afe00d80-04a6-11ea-8e6e-03a724e36eba.jpg)

**Comment by li-xiaojun** [comment]
什么机型，三星的？

**Comment by HubertYoung** [comment]
这个问题暂时无解，我查源码发现是获取导航条高度的问题，索性直接不用此项目了

**Comment by HubertYoung** [comment]
> 什么机型，三星的？

所有的支持全面屏手势的手机，都会出现此问题

**Comment by loperSeven** [comment]
@li-xiaojun  一加等众多机型都存在，不开启底部横条没有问题，开启之后就会存在导航条高度计算错误

**Comment by loperSeven** [comment]
@li-xiaojun  同问题 #299  当开启底部小横条的时候

**Comment by bluejuzz** [comment]
> 什么机型，三星的？

1加的也会

**Comment by lovemianhuatang** [comment]
> 这个问题暂时无解，我查源码发现是获取导航条高度的问题，索性直接不用此项目了

怎么解决这个，， 有什么其他好用的弹窗库吗？

**Comment by zhourenjun** [comment]
public static boolean isShowNavBar(Context context) {
        if (null == context) {
            return false;
        }
        /**
         * 获取应用区域高度
         */
        Rect outRect1 = new Rect();
        try {
            ((Activity) context).getWindow().getDecorView().getWindowVisibleDisplayFrame(outRect1);
        } catch (ClassCastException e) {
            e.printStackTrace();
            return false;
        }
        int activityHeight = outRect1.height();

        Log.e("zrj", "状态栏高度:"+ getStatusBarHeight() );
        Log.e("zrj", "应用区域高度:"+ activityHeight );
        Log.e("zrj", "导航栏高度:"+ getNavBarHeight() );
        Log.e("zrj", "屏幕物理高度:"+ getRealHeight(context) );
        /**
         * 屏幕物理高度 - 状态栏高度  导航栏高度 = 导航栏存在时的应用实际高度
         */
        int remainHeight = getRealHeight(context) - getStatusBarHeight() - getNavBarHeight();

        Log.e("zrj", "remainHeight:"+ remainHeight );
        /**
         * 剩余高度跟应用区域高度相等 说明导航栏存在
         */
        if (activityHeight == remainHeight) {
            return true;
        } else {
            return false;
        }
    }

**Comment by zhourenjun** [comment]
帮忙测试一下，我的pixel 手势可以正常

**Comment by zhourenjun** [comment]
public static int getRealHeight(Context context) {
        WindowManager   wm = ((WindowManager) context.getSystemService(Context.WINDOW_SERVICE));
        Point point = new Point();
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
            wm.getDefaultDisplay().getRealSize(point);
        } else {
            wm.getDefaultDisplay().getSize(point);
        }
        return point.y;
    }

**Comment by lovemianhuatang** [comment]
@zhourenjun 加源码里？

**Comment by zhourenjun** [comment]
是的

**Comment by zhourenjun** [comment]
源码里面判断导航栏是否显示时的，想请各位用不同机型测试一下，如果可以希望作者更新一下依赖版本，我只有一种测试机是非小米，华为的

**Comment by lovemianhuatang** [comment]
我的是三星S8  用isShowNavBar(context) 可以区分是否全屏手势。  牛逼

**Comment by li-xiaojun** [comment]
> public static boolean isShowNavBar(Context context) {
> if (null == context) {
> return false;
> }
> /**
> * 获取应用区域高度
> */
> Rect outRect1 = new Rect();
> try {
> ((Activity) context).getWindow().getDecorView().getWindowVisibleDisplayFrame(outRect1);
> } catch (ClassCastException e) {
> e.printStackTrace();
> return false;
> }
> int activityHeight = outRect1.height();
> 
> ```
>     Log.e("zrj", "状态栏高度:"+ getStatusBarHeight() );
>     Log.e("zrj", "应用区域高度:"+ activityHeight );
>     Log.e("zrj", "导航栏高度:"+ getNavBarHeight() );
>     Log.e("zrj", "屏幕物理高度:"+ getRealHeight(context) );
>     /**
>      * 屏幕物理高度 - 状态栏高度  导航栏高度 = 导航栏存在时的应用实际高度
>      */
>     int remainHeight = getRealHeight(context) - getStatusBarHeight() - getNavBarHeight();
> 
>     Log.e("zrj", "remainHeight:"+ remainHeight );
>     /**
>      * 剩余高度跟应用区域高度相等 说明导航栏存在
>      */
>     if (activityHeight == remainHeight) {
>         return true;
>     } else {
>         return false;
>     }
> }
> ```

如果有效，可以提个PR。我没有三星手机，不知道测试效果

**Comment by fishballzzz** [comment]
> 
> 
> > public static boolean isShowNavBar(Context context) {
> > if (null == context) {
> > return false;
> > }
> > /**
> > 
> > * 获取应用区域高度
> >   */
> >   Rect outRect1 = new Rect();
> >   try {
> >   ((Activity) context).getWindow().getDecorView().getWindowVisibleDisplayFrame(outRect1);
> >   } catch (ClassCastException e) {
> >   e.printStackTrace();
> >   return false;
> >   }
> >   int activityHeight = outRect1.height();
> > 
> > ```
> >     Log.e("zrj", "状态栏高度:"+ getStatusBarHeight() );
> >     Log.e("zrj", "应用区域高度:"+ activityHeight );
> >     Log.e("zrj", "导航栏高度:"+ getNavBarHeight() );
> >     Log.e("zrj", "屏幕物理高度:"+ getRealHeight(context) );
> >     /**
> >      * 屏幕物理高度 - 状态栏高度  导航栏高度 = 导航栏存在时的应用实际高度
> >      */
> >     int remainHeight = getRealHeight(context) - getStatusBarHeight() - getNavBarHeight();
> > 
> >     Log.e("zrj", "remainHeight:"+ remainHeight );
> >     /**
> >      * 剩余高度跟应用区域高度相等 说明导航栏存在
> >      */
> >     if (activityHeight == remainHeight) {
> >         return true;
> >     } else {
> >         return false;
> >     }
> > }
> > ```
> 
> 如果有效，可以提个PR。我没有三星手机，不知道测试效果

@li-xiaojun 请问这个有打算采用吗？我试了pixel没有问题

**Comment by li-xiaojun** [comment]
@zhourenjun  @loperSeven  @bluejuzz  @HubertYoung 

试试1.9.3，修复了这个问题

**Comment by hcyAndroid** [comment]
那个横条会遮在popwindow上，何解
