### ISSUE TITLE
图片浏览器内存炸裂,100多m暴涨至0.6G

### ISSUE THREAD

**Issue by 211885646** [li-xiaojun/XPopup#338]
多图片浏览类ImageViewerPopupView的104行的setOffscreenPageLimit方法设置的是url的长度,这导致一个很恐怖的问题,当我的url集合长度多达几十上百的时候,会同时加载全部图片  内存直接炸裂,建议此地方修改下,还有就是图片保存按钮的点击逻辑  最好判断下文件是否存在或者说是否下载完成,不然会蹦,最好再处理下重复点击的问题,坑逼测试疯狂点击保存导致也会蹦~反馈至此,感谢作者大大的辛勤付出

**Comment by li-xiaojun** [comment]
可以做个简单处理，加载图片的时候不设置originalSize，文档说明这个问题了
