### ISSUE TITLE
倒计时结束后 pop无法显示

### ISSUE THREAD

**Issue by sangsais** [li-xiaojun/XPopup#341]
private void startCountdown() {
        countdownView.start(5 * 1000);
        countdownView.setOnCountdownEndListener(new CountdownView.OnCountdownEndListener() {
            @Override
            public void onEnd(CountdownView cv) {
                LogUtils.i(cv.getSecond(), cv.getRemainTime());
                showBottomInviteSendGifsView(2);
            }
        });
    }

private void showBottomInviteSendGifsView(int sex) {
        if (null == basePopupInviteSendGifsView) {
            basePopupInviteSendGifsView = new XPopup.Builder(ActivityUtils.getTopActivity().getApplicationContext())
                    .enableDrag(true)
                    .popupAnimation(PopupAnimation.TranslateFromBottom) // 设置内置的动画
                    .moveUpToKeyboard(false) //如果不加这个，评论弹窗会移动到软键盘上面
                    .asCustom(new DatingShowBottomInviteSendGifsPop(ActivityUtils.getTopActivity(), datingShowP, sex));
            basePopupInviteSendGifsView.show();
        } else {
            basePopupInviteSendGifsView.show();
        }
    }
public class DatingShowBottomInviteSendGifsPop extends BottomPopupView {}

**Comment by li-xiaojun** [comment]
试试1.9.3，应该修复了这个问题
