### ISSUE TITLE
在大屏设备上输入框的文字会移位

### ISSUE THREAD

**Issue by zhoujia456888** [li-xiaojun/XPopup#344]
测试机器是19寸的广告展示机，分辨率为1080*1920 ,160dpi,Android6.0系统，竖屏，显示效果如下
![image](https://user-images.githubusercontent.com/7905253/69303987-f5949700-0c59-11ea-8479-cbb4cd722821.png)

**Comment by zhoujia456888** [comment]
测试发现注释掉设置et_input背景那一行就不会出现这种情况，这一行的作用是什么？
![image](https://user-images.githubusercontent.com/7905253/69312386-bcfcb980-0c69-11ea-9046-f683d88314a3.png)
![image](https://user-images.githubusercontent.com/7905253/69312433-e1589600-0c69-11ea-9f03-f6d0157b251e.png)

**Comment by li-xiaojun** [comment]
图片挂了
