### ISSUE TITLE
经常报这个错

### ISSUE THREAD

**Issue by wayneleo** [li-xiaojun/XPopup#347]
#1304 java.lang.NullPointerException

Attempt to invoke virtual method 'void android.widget.TextView.setOnClickListener(android.view.View$OnClickListener)' on a null object reference

com.lxj.xpopup.impl.ConfirmPopupView.initPopupContent(ConfirmPopupView.java:55)

出错堆栈

1	com.lxj.xpopup.impl.ConfirmPopupView.initPopupContent(ConfirmPopupView.java:55)
2	com.lxj.xpopup.core.BasePopupView.init(BasePopupView.java:83)
3	com.lxj.xpopup.core.BasePopupView$3.run(BasePopupView.java:209)
4	android.os.Handler.handleCallback(Handler.java:907)
5	android.os.Handler.dispatchMessage(Handler.java:105)
6	android.os.Looper.loop(Looper.java:216)
7	android.app.ActivityThread.main(ActivityThread.java:7625)
8	java.lang.reflect.Method.invoke(Native Method)
9	com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
10	com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by zhourenjun** [comment]
有一个很容易犯错的地方，你可能会这样写：

CustomPopup customPopup = new CustomPopup(getContext());
customPopup.setContent("这样写错了");
new XPopup.Builder(getContext())
          .asCustom(customPopup)
          .show();
这种写法会直接空指针，为什么呢？

记住，弹窗是有生命周期的，分别表现为onCreate()，onShow()，onDismiss()方法。当你new出弹窗对象时，onCreate方法还没有走，这意味着textView还是空的，所以调用setContent方法会导致空指针。

你有2种方法来给调用设置数据的方法，先看第一种：

final CustomPopup customPopup = new CustomPopup(getContext());
new XPopup.Builder(getContext())
          .setPopupCallback(new SimpleCallback(){  //监听弹窗create完毕
                 @Override
                 public void onCreated() {
                     customPopup.setContent("这样写就对了");
                 }
           })
          .asCustom(customPopup)
          .show();
第二种方法是，修改setContent方法只用来给弹窗设置数据，而弹窗内部在onCreate中拿View去使用这些数据：

public static class CustomPopup extends CenterPopupView {
        public CustomPopup(@NonNull Context context) {
            super(context);
        }

        @Override
        protected int getImplLayoutId() {
            return R.layout.custom_popup;
        }
        TextView textView;
        @Override
        protected void onCreate() {
            super.onCreate();
            textView = findViewById(R.id.text);
            textView.setText(data);
        }
        String data;
        public void setContent(String s){
            data = s; //只记录数据，不再操作View
        }
    }
第二种方式的写法好处是，你再也不用担心调用setContent方法会出问题，可以在任何地方调用它。我推荐第二种方式，内置弹窗的设置数据的方式都是采用第二种方式。 如果你经常需要修改弹窗的数据，可以这样做，将上面的setContent方法修改为如下：

String data;
public void setContent(String s){
     data = s; //只记录数据，不再操作View
     if(textView!=null){
         textView.setText(data); 
     }
}
当需要更新数据的时候，只需要调用setContent方法即可

**Comment by wayneleo** [comment]
> 有一个很容易犯错的地方，你可能会这样写：
> 
> CustomPopup customPopup = new CustomPopup(getContext());
> customPopup.setContent("这样写错了");
> new XPopup.Builder(getContext())
> .asCustom(customPopup)
> .show();
> 这种写法会直接空指针，为什么呢？
> 
> 记住，弹窗是有生命周期的，分别表现为onCreate()，onShow()，onDismiss()方法。当你new出弹窗对象时，onCreate方法还没有走，这意味着textView还是空的，所以调用setContent方法会导致空指针。
> 
> 你有2种方法来给调用设置数据的方法，先看第一种：
> 
> final CustomPopup customPopup = new CustomPopup(getContext());
> new XPopup.Builder(getContext())
> .setPopupCallback(new SimpleCallback(){ //监听弹窗create完毕
> @override
> public void onCreated() {
> customPopup.setContent("这样写就对了");
> }
> })
> .asCustom(customPopup)
> .show();
> 第二种方法是，修改setContent方法只用来给弹窗设置数据，而弹窗内部在onCreate中拿View去使用这些数据：
> 
> public static class CustomPopup extends CenterPopupView {
> public CustomPopup(@nonnull Context context) {
> super(context);
> }
> 
> ```
>     @Override
>     protected int getImplLayoutId() {
>         return R.layout.custom_popup;
>     }
>     TextView textView;
>     @Override
>     protected void onCreate() {
>         super.onCreate();
>         textView = findViewById(R.id.text);
>         textView.setText(data);
>     }
>     String data;
>     public void setContent(String s){
>         data = s; //只记录数据，不再操作View
>     }
> }
> ```
> 
> 第二种方式的写法好处是，你再也不用担心调用setContent方法会出问题，可以在任何地方调用它。我推荐第二种方式，内置弹窗的设置数据的方式都是采用第二种方式。 如果你经常需要修改弹窗的数据，可以这样做，将上面的setContent方法修改为如下：
> 
> String data;
> public void setContent(String s){
> data = s; //只记录数据，不再操作View
> if(textView!=null){
> textView.setText(data);
> }
> }
> 当需要更新数据的时候，只需要调用setContent方法即可


没有设置数据，就是类似这样调用了：
new XPopup.Builder(getContext())
          .asConfirm(null, "您可以复用项目已有布局，来使用XPopup强大的交互能力和逻辑封装，弹窗的布局完全由你自己控制。\n" +
                                "需要注意的是：你自己的布局必须提供一些控件Id，否则XPopup找不到View。\n具体需要提供哪些Id，请查看WIKI[内置弹窗]一章。",
                        "关闭", "XPopup牛逼",
                        new OnConfirmListener() {
                            @Override
                            public void onConfirm() {
                                toast("click confirm");
                            }
                        }, null, false)
            .bindLayout(R.layout.my_confim_popup) //绑定已有布局
            .show();
