### ISSUE TITLE
虚拟导航键切换为全屏手势模式   弹窗底部高度计算未适配

### ISSUE THREAD

**Issue by AnnXZ** [li-xiaojun/XPopup#349]
弹窗悬浮于 虚拟导航之上。目前因修改为全屏手势模式的情况下弹窗会直接空出  底部栏的高度

**Comment by zhourenjun** [comment]
public static boolean isShowNavBar(Context context) {
        if (null == context) {
            return false;
        }
        /**
         * 获取应用区域高度
         */
        Rect outRect1 = new Rect();
        try {
            ((Activity) context).getWindow().getDecorView().getWindowVisibleDisplayFrame(outRect1);
        } catch (ClassCastException e) {
            e.printStackTrace();
            return false;
        }
        int activityHeight = outRect1.height();

        Log.e("zrj", "状态栏高度:"+ getStatusBarHeight() );
        Log.e("zrj", "应用区域高度:"+ activityHeight );
        Log.e("zrj", "导航栏高度:"+ getNavBarHeight() );
        Log.e("zrj", "屏幕物理高度:"+ getRealHeight(context) );
        /**
         * 屏幕物理高度 - 状态栏高度  导航栏高度 = 导航栏存在时的应用实际高度
         */
        int remainHeight = getRealHeight(context) - getStatusBarHeight() - getNavBarHeight();

        Log.e("zrj", "remainHeight:"+ remainHeight );
        /**
         * 剩余高度跟应用区域高度相等 说明导航栏存在
         */
        if (activityHeight == remainHeight) {
            return true;
        } else {
            return false;
        }
    }

**Comment by zhourenjun** [comment]
public static int getRealHeight(Context context) {
        WindowManager   wm = ((WindowManager) context.getSystemService(Context.WINDOW_SERVICE));
        Point point = new Point();
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
            wm.getDefaultDisplay().getRealSize(point);
        } else {
            wm.getDefaultDisplay().getSize(point);
        }
        return point.y;
    }

**Comment by zhourenjun** [comment]
源码里面判断导航栏是否显示时的，想请各位用不同机型测试一下，如果可以希望作者更新一下依赖版本，我只有一种测试机是非小米，华为的

**Comment by honaf** [comment]
这个问题还导致输入框被遮挡

**Comment by li-xiaojun** [comment]
试试1.9.3，应该修复了这个问题
