### ISSUE TITLE
同一个activity中打开xpopup超过100次后发现打开缓慢

### ISSUE THREAD

**Issue by jumplee** [li-xiaojun/XPopup#351]
xPopup平时没事，但是长期操作后发现xPopup打开变得缓慢，特别是在低配置机器上。
---测试环境----
商米t2mini  android7.1
----场景重现----
打开一个activity，反复打开一个centerPopup实例，达到100次以上会发现明显的延迟，大概1s左右，内存稳定，cpu会有10%的浮动，而普通dialog几乎没有cpu执行。

==========
---测试环境----
华为平板m5青春版  xPopup项目demo 
-----场景重现----
反复执行100+次，会有内存泄漏。点击打开xPopup发现明显延迟

**Comment by LG12300** [comment]
这个库内存泄漏很严重，我用到弹窗的几个地方都报内存泄漏，打开多了内存吃不消

**Comment by jumplee** [comment]
@LG12300 已经连夜改为原生dialog了，项目对性能要求高，坑住自己了

**Comment by LG12300** [comment]
用的时候挺方便的，就是检测到有内存泄漏，不知道是不是我代码的问题。我用小米note3测试的倒不卡

**Comment by li-xiaojun** [comment]
试试1.9.3，应该修复了这个问题
