### ISSUE TITLE
显示框添设置offsetY 偏移量过后有个问题

### ISSUE THREAD

**Issue by niehuaming** [li-xiaojun/XPopup#354]
显示框添设置offsetY 偏移量过后有个问题，看图。当我们添加了这个偏移量过后，底部展示不全。
![image](https://user-images.githubusercontent.com/12639114/70697060-d1c7ec80-1cff-11ea-8388-e5789fd319c2.png)

**Comment by li-xiaojun** [comment]
图片挂了
