### ISSUE TITLE
drawer侧边栏弹出键盘时显示有问题

### ISSUE THREAD

**Issue by HQLIE2018** [li-xiaojun/XPopup#355]
![1 8 10](https://user-images.githubusercontent.com/45163143/70894137-647dc980-2027-11ea-86f5-dd315e1e5cf0.png)
![1 8 7](https://user-images.githubusercontent.com/45163143/70894139-65166000-2027-11ea-8b5c-54f6463e3e74.png)
1.8.10的侧边栏，当输入框靠近屏幕底部时，点击弹出键盘，显示有bug，如上图显示，1.8.7没有出现这个问题

**Comment by li-xiaojun** [comment]
试试1.9.3，修复了这个问题
