### ISSUE TITLE
建议:增加一个对话框类型，带三个按钮的对话框，感觉用处还是挺多的

### ISSUE THREAD

**Issue by zhanghw96** [li-xiaojun/XPopup#357]
如图，类似这样的，虽然可以自定义，还是希望可以内置https://files.jb51.net/file_images/article/201710/201710250936205.png

**Comment by li-xiaojun** [comment]
这个属于特殊需求了，需要你自己实现，XPopup实现很多特殊需求的话会变得很臃肿
