### ISSUE TITLE
自定义DrawerPopupView之后报setMovementMethod异常

### ISSUE THREAD

**Issue by threedeer** [li-xiaojun/XPopup#360]
private void previewOriginal(String html) {
        if (drawerPopupView == null) {
            drawerPopupView = new CustomSubjectPop(HomeWorkCorrectActivity.this);
        }
        if (popupView == null) {
            popupView = new XPopup.Builder(HomeWorkCorrectActivity.this).setPopupCallback(new SimpleCallback() {
                @Override
                public void onCreated() {
                    drawerPopupView.setHtmlValue(html);
                }
            })
                    .popupPosition(PopupPosition.Right)//右边
                    .hasStatusBarShadow(true) //启用状态栏阴影
                    .asCustom(drawerPopupView);
        }
        if (popupView.isDismiss()) {

            popupView.show();
            drawerPopupView.setHtmlValue(html);
        }
    }

第二行再次重复设置值的时候回报异常

**Comment by li-xiaojun** [comment]
具体的空指针代码是啥
