### ISSUE TITLE
AttachPopupView宽度全屏如何实现？

### ISSUE THREAD

**Issue by guozhiqiang123** [li-xiaojun/XPopup#364]
如题，我使用AttachListPopupView和自定义都不行

**Comment by guozhiqiang123** [comment]
设计图长这样，红色的区域是个弹窗
![QQ截图20191227151309](https://user-images.githubusercontent.com/20378988/71506319-72e7a300-28bb-11ea-8a87-5b96b5f32960.png)

**Comment by wenbinAndroid** [comment]
如果布局里面是rv的话,直接设置rv宽度就可以
