### ISSUE TITLE
开启全屏幕手势后，底部留白

### ISSUE THREAD

**Issue by Jasperben** [li-xiaojun/XPopup#366]
#看图片下面（机型：一加7T    Android10）

![avatar](https://gitout.oss-cn-shanghai.aliyuncs.com/content/WechatIMG301.jpeg)

![avatar](https://gitout.oss-cn-shanghai.aliyuncs.com/content/WechatIMG302.jpeg)

![avatar](https://gitout.oss-cn-shanghai.aliyuncs.com/content/WechatIMG303.jpeg)

**Comment by lianaini** [comment]
我们也遇到了，大哥怎么解决的？可否提供下思路

**Comment by alone-wolf** [comment]
小米8 类原生Android10，开启全面屏手势（底部小白条）后，也遇到了这种问题，猜测是检测导航栏高度的时候读取数据有误（开启显示布局边界后，小白条的边界仍然和经典的三大金刚高度齐平，对其的时候应该选取的是那个数据）

**Comment by DaveBoy** [comment]
+1

**Comment by li-xiaojun** [comment]
@lianaini  @alone-wolf @Jasperben @DaveBoy 

试试1.9.3，应该修复了这个问题
