### ISSUE TITLE
无法显示在DialogFragment之上

### ISSUE THREAD

**Issue by littletreezlx** [li-xiaojun/XPopup#367]
popup是通过activity的addview来操作，没法兼容DialogFragment，有什么别的解决办法吗？
（无法抛弃DialogFragment）

**Comment by yizuochengchi** [comment]
@littletreezlx 你好 请问你后来是怎么处理的 dialogfragment是比较特殊

**Comment by yizuochengchi** [comment]
我还在找原因  https://github.com/stfalcon-studio/StfalconImageViewer 这个库是可以的

**Comment by zwt-ss** [comment]
同样遇到了这个问题
