### ISSUE TITLE
同一页面打开多个PartShadowPopupView返回键有bug

### ISSUE THREAD

**Issue by Masksam** [li-xiaojun/XPopup#368]
点击viewA弹出PartShadowPopupView1，（PartShadowPopupView2未dismiss()情况下）再点击viewB弹出PartShadowPopupView2，按返回键页面直接退出，PartShadowPopupView2未dismiss

**Comment by li-xiaojun** [comment]
上具体代码

**Comment by luorou** [comment]
在PopupA 中再打开PopupB ,这时候弹出两个Popup  ,按返回键  PopupA  关掉了,  PopupB 没有关掉

**Comment by li-xiaojun** [comment]
你需要按两次，一次只能关闭一个弹窗
