### ISSUE TITLE
【bugly在线统计到的】java.lang.IllegalArgumentException parameter must be a descendant of this view  com.lxj.xpopup.core.BasePopupView$6.run(BasePopupView.java:526)

### ISSUE THREAD

**Issue by LatoAndroid** [li-xiaojun/XPopup#369]
不太清楚问题出在哪里，自己使用没有复现过，但在线统计出现了很多次这个崩溃
详细日志：

android.view.ViewGroup.offsetRectBetweenParentAndChild(ViewGroup.java:4935)
2 android.view.ViewGroup.offsetDescendantRectToMyCoords(ViewGroup.java:4872)
3 android.view.ViewGroup$ViewLocationHolder.init(ViewGroup.java:7288)
4 android.view.ViewGroup$ViewLocationHolder.obtain(ViewGroup.java:7222)
5 android.view.ViewGroup$ChildListForAccessibility.init(ViewGroup.java:7157)
6 android.view.ViewGroup$ChildListForAccessibility.obtain(ViewGroup.java:7125)
7 android.view.ViewGroup.dispatchPopulateAccessibilityEventInternal(ViewGroup.java:2721)
8 android.view.View.dispatchPopulateAccessibilityEvent(View.java:5385)
9 android.view.ViewGroup.dispatchPopulateAccessibilityEventInternal(ViewGroup.java:2727)
10 android.view.View.dispatchPopulateAccessibilityEvent(View.java:5385)
11 android.widget.RelativeLayout.dispatchPopulateAccessibilityEvent(RelativeLayout.java:1119)
12 android.view.ViewGroup.dispatchPopulateAccessibilityEventInternal(ViewGroup.java:2727)
13 android.view.View.dispatchPopulateAccessibilityEvent(View.java:5385)
14 android.view.View.sendAccessibilityEventUncheckedInternal(View.java:5350)
15 android.view.View.sendAccessibilityEventUnchecked(View.java:5334)
16 android.view.View.sendAccessibilityEventInternal(View.java:5311)
17 android.view.View.sendAccessibilityEvent(View.java:5280)
18 android.view.View.onFocusChanged(View.java:5217)
19 android.view.View.handleFocusGainInternal(View.java:4997)
20 android.view.ViewGroup.handleFocusGainInternal(ViewGroup.java:638)
21 android.view.View.requestFocusNoSearch(View.java:7722)
22 android.view.View.requestFocus(View.java:7701)
23 android.view.ViewGroup.requestFocus(ViewGroup.java:2599)
24 android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2644)
25 android.view.ViewGroup.requestFocus(ViewGroup.java:2600)
26 android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2644)
27 android.view.ViewGroup.requestFocus(ViewGroup.java:2600)
28 android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2644)
29 android.view.ViewGroup.requestFocus(ViewGroup.java:2600)
30 android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2644)
31 android.view.ViewGroup.requestFocus(ViewGroup.java:2603)
32 android.view.View.requestFocus(View.java:7668)
33 android.view.View.requestFocus(View.java:7647)
34 android.view.View.rootViewRequestFocus(View.java:5141)
35 android.view.ViewGroup.removeViewInternal(ViewGroup.java:4233)
36 android.view.ViewGroup.removeViewInternal(ViewGroup.java:4193)
37 android.view.ViewGroup.removeView(ViewGroup.java:4124)
38 com.lxj.xpopup.core.BasePopupView$6.run(BasePopupView.java:526)
39 android.os.Handler.handleCallback(Handler.java:739)
40 android.os.Handler.dispatchMessage(Handler.java:95)
41 android.os.Looper.loop(Looper.java:135)
42 android.app.ActivityThread.main(ActivityThread.java:5280)
43 java.lang.reflect.Method.invoke(Native Method)
44 java.lang.reflect.Method.invoke(Method.java:372)
45 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
46 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)

**Comment by dary123** [comment]
同问

**Comment by li-xiaojun** [comment]
最新版已经修复这个可能出现的问题
