### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by qiushui95** [li-xiaojun/XPopup#37]
离职了一个月，今晚来看看github   发现您更新了很多内容，新增的很多新的功能。
这很赞，但是，您新增的功能我可能用不到，能否拆分成几个库，按需引用，就行SmartRefresh一样，基础功能一个库地址，扩展header一个库地址。

**Comment by li-xiaojun** [comment]
@qiushui95 
首先感谢你的建议，基于几个原因目前不太适合这样做：
1. 本库的代码量目前很少，如果弄多个库，反而增加类库的管理成本
2. SmartRefresh的header库效果太炫酷，正式项目不太可能用到；而目前本库的效果都是项目中很可能用到的。

当本库代码量上去之后，我可能会采用您的建议，敬请谅解。

**Comment by qiushui95** [comment]
没事  只是建议。感谢回复
