### ISSUE TITLE
继承 CenterPopupView 实现自定义 ui 的弹窗背景怎么自己设置 ? 

### ISSUE THREAD

**Issue by gzpaiwxc** [li-xiaojun/XPopup#370]
继承 CenterPopupView 实现自定义 ui 的弹窗背景怎么自己设置 ? 我翻看了 issues , 没有找到设置背景的方法 , 背景半透明我希望能设置为更深黑一点的背景色 , 查看源码 好像是在设置动画的地方设置的背景色 ? #77000000 ? 不能提供方法改这个颜色吗?

**Comment by isyue** [comment]
可以试着将弹窗视图全屏，自己设置背景

**Comment by li-xiaojun** [comment]
所有的弹窗基类包括CenterPopupView默认都是没有背景色的，你自定义UI的时候是什么颜色就是什么颜色。
