### ISSUE TITLE
能不能加个全局可以去掉提示框显示的时候不要任何动画

### ISSUE THREAD

**Issue by dary123** [li-xiaojun/XPopup#371]
单独加可以加，但是没找到全局去掉动画的方法，用到的地方太多了，总不能一个个去加.popupAnimation(PopupAnimation.NoAnimation)吧，根本不想用动画啊，loading时间短的话，加上动画，根本来不及显示全dialog，太丑了

**Comment by li-xiaojun** [comment]
你应该使用dismissDelay，能保证动画的完整

**Comment by liyuxuanAdoreLi** [comment]
我觉得，动画是有点儿突兀，当接口请求快的时候，loading还要从小变大，动画根本完不成，显得很突兀。dismissDelay 设置太短或者是0，看起来像卡顿。设置成100，显示loading太小就消失了
