### ISSUE TITLE
FullScreenPopupView全屏弹窗再次打开会闪退

### ISSUE THREAD

**Issue by clank520** [li-xiaojun/XPopup#372]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Paint.setColor(int)' on a null object reference
at com.lxj.xpopup.impl.FullScreenPopupView.dispatchDraw(FullScreenPopupView.java:77)

        if(popupView==null){
            popupView = (BillFilePopupView) new XPopup.Builder(this)
                    .hasStatusBarShadow(true)
                    .autoOpenSoftInput(true)
                    .setPopupCallback(new SimpleCallback() {
                        @Override
                        public void onCreated() {
                            super.onCreated();
                            popupView.initData(billAttach,item);

                        }
                        @Override
                        public void onShow() {
                        }
                        @Override
                        public void onDismiss() {
                        }
                    })
                    .asCustom(new BillFilePopupView(this));
        }
        popupView.show(); 我的使用

**Comment by Zhangxd77** [comment]
我第一次就会这样，请问您解决了吗

**Comment by clank520** [comment]
> 我第一次就会这样，请问您解决了吗

换了一个实现没事 没有使用FullScreenPopupView
