### ISSUE TITLE
建议把title和content等本文传值的类型从String 改为 CharSequence 以便兼容Span 和Html

### ISSUE THREAD

**Issue by BergenWang** [li-xiaojun/XPopup#373]
如题：
主要是库已经提供的方法，比如
![图片](https://user-images.githubusercontent.com/18643187/71876665-49076980-3162-11ea-9284-4c273247c273.png)

**Comment by basillee** [comment]
+1

**Comment by li-xiaojun** [comment]
最新版已经支持 @BergenWang  @basillee
