### ISSUE TITLE
当设备横屏时,屏幕邮编会有部分空白

### ISSUE THREAD

**Issue by cainanqi** [li-xiaojun/XPopup#376]
![image](https://user-images.githubusercontent.com/17824522/72244833-11009a80-362a-11ea-9a90-389264bf0d5c.png)[这是问题]

相关代码:
![image](https://user-images.githubusercontent.com/17824522/72244873-25dd2e00-362a-11ea-8cde-9efb4320f0c3.png)

![image](https://user-images.githubusercontent.com/17824522/72244781-f4646280-3629-11ea-87ab-f48c033ebe7c.png)[这是修复后的]

**Comment by li-xiaojun** [comment]
试试1.9.3，修复了这个问题
