### ISSUE TITLE
pad横屏状态底部弹窗被挡住的问题

### ISSUE THREAD

**Issue by clank520** [li-xiaojun/XPopup#378]
![2F462E21C919CA5979A8BE64974E21A3](https://user-images.githubusercontent.com/26299156/72674479-0cb50100-3ab2-11ea-82c7-ad020e5e251d.jpg)
![2FE9CF4E255B047341D5CCB6074E0D30](https://user-images.githubusercontent.com/26299156/72674481-150d3c00-3ab2-11ea-9cfc-77b46088983f.jpg)
pad横屏状态下右边显示不全， 底部会被挡住，底部状态栏没有发生改变

**Comment by li-xiaojun** [comment]
试试1.9.3，修复了这个问题
