### ISSUE TITLE
如何设置一个activity最多显示一个BottomPopupView，后面显示的会覆盖前面

### ISSUE THREAD

**Issue by dary123** [li-xiaojun/XPopup#380]
意思就是说如果有新的BottomPopupView弹出，将当前已经显示的BottomPopupView dismiss

**Comment by li-xiaojun** [comment]
@dary123 
弹窗只负责显示逻辑。其他的需要自己做处理。过多的业务容易导致臃肿，就像Dialog一样，如果你要最多显示一个Dialog，也只能自己处理。
