### ISSUE TITLE
开放可以设置Shadow background color

### ISSUE THREAD

**Issue by leanderli** [li-xiaojun/XPopup#381]
我在Xpopup主类中找到了shadowBgColor属性，这个属性是用于设置弹窗背景色的。但目前该属性是固定的数值，建议开放设置背景色。

**Comment by huangruiLearn** [comment]
XPopup.setShadowBgColor(xxx);

**Comment by leanderli** [comment]
OK，我可能是大多数都是用new Xpopup.Builder()去构建。
