### ISSUE TITLE
存在过度绘制的隐患

### ISSUE THREAD

**Issue by KunMinX** [li-xiaojun/XPopup#383]
创建 dialog 时，使用 View，而不是 Window，在 dialog 出场时容易出现掉帧。
尤其当 dialog 的内容包含毛玻璃的情况，容易因过度绘制而出场掉帧。

**Comment by jumplee** [comment]
额，有什么方法改进吗？我已经测试出来这个问题了，操作200次左右就会出现性能下降，特别是设备性能一般的情况

**Comment by KunMinX** [comment]
@jumplee 很简单，通过 DialogFragment 来实现，就能享受 Dialog 持有的 Window 独立完成渲染。

我只是搞不懂，作者为什么放着 DialogFragment 不用，另外设计一套实际上实现方式更为复杂的浮窗。

**Comment by li-xiaojun** [comment]
@KunMinX 弹窗本是临时性的展示，消失后就移除了。
@jumplee   200次的测试我没有测试过，你试试打开Dialog 200次看会不会有性能问题。弹窗本身已经修复了内存泄漏问题，关键是弹窗内的代码有可能泄漏。
Window等其他方式很不灵活，有很多需要解决的问题，状态栏，输入法交互，全面屏适配。而View依赖于Activity，很多东西不用太处理。

**Comment by KunMinX** [comment]
> @KunMinX 弹窗本是临时性的展示，消失后就移除了。
> 
> @jumplee   200次的测试我没有测试过，你试试打开Dialog 200次看会不会有性能问题。弹窗本身已经修复了内存泄漏问题，关键是弹窗内的代码有可能泄漏。
> 
> Window等其他方式很不灵活，有很多需要解决的问题，状态栏，输入法交互，全面屏适配。而View依赖于Activity，很多东西不用太处理。

你忽略了 blur 的情况，事实上，只要在该库方案下使用毛玻璃，100%必现出场掉帧。

**Comment by jumplee** [comment]
@li-xiaojun Dialog没有任何问题，当时解决方法就是全部用Dialog重写了。

**Comment by fishballzzz** [comment]
> 
> 
> @li-xiaojun Dialog没有任何问题，当时解决方法就是全部用Dialog重写了。

请问你这个dialog上面还有popup吗？有的话是如何解决的呢？还有这个dialog你有保存他的数据吗？有的话是如何实现的呢？我之前尝试了用dialog做一些弹窗，就碰到了在dialog不能继续创建popup和不好保存数据的问题，方便分享一下经验吗？
