### ISSUE TITLE
AttachPopupView设置最大宽度失效

### ISSUE THREAD

**Issue by maxrco** [li-xiaojun/XPopup#384]
XPopup
            .Builder(context)
            .atView(bottomLayout)
            .asCustom(object : AttachPopupView(context!!) {
                override fun getImplLayoutId(): Int {
                    return R.layout.popup_add_fund_more
                }

                override fun getMaxWidth(): Int {
                    return 0
                }

                override fun onCreate() {
                    super.onCreate()
                    findViewById<RecyclerView>(R.id.rv_more).apply {
                        layoutManager = GridLayoutManager(context, 3)
                        if (itemDecorationCount == 0) {
                            addItemDecoration(
                                GridSpacingItemDecoration(
                                    3,
                                    QMUIDisplayHelper.dp2px(context, 21),
                                    true
                                )
                            )
                        }
                        adapter = moreSelectionAdapter.apply {
                            setNewData(moreDateList)
                            setOnItemChildClickListener { adapter, view, position ->
                                val selectDate = adapter.data[position] as MoreDate
                                when (view.id) {
                                    R.id.tv_date -> {
                                        moreDateList.forEach {
                                            it.isSelect = selectDate === it
                                            notifyDataSetChanged()
                                        }
                                        when (position) {
                                            0 -> choosetype = "5"
                                            1 -> choosetype = "6"
                                            2 -> choosetype = "7"
                                            3 -> choosetype = "8"
                                            4 -> choosetype = "9"
                                            5 -> choosetype = "10"
                                        }
                                        presenter.start()
                                    }
                                }
                            }
                        }
                    }
                }
            })
            .show()

重写getMaxWidth()设置0并没有达到屏幕最大宽度的效果

**Comment by li-xiaojun** [comment]
为0相当于没有设置，默认就是0，你应该return整个屏幕的宽度啊
