### ISSUE TITLE
点击按钮后能不能不关闭dialog?

### ISSUE THREAD

**Issue by VincentYD** [li-xiaojun/XPopup#39]
能否暴露一个方法去控制当前dialog不关闭?例如输入对话框,在我输入的内容提交后服务器返回修改不成功,就不关闭当前对话框

**Comment by li-xiaojun** [comment]
@VincentYD 
在最新的`1.3.6`版本增加了`autoDismiss`设置，设置为false后，在操作完毕后弹窗不再自动关闭。
```
XPopup.get(this).autoDismiss(false)...
```

**Comment by VincentYD** [comment]
> @VincentYD
> 在最新的`1.3.6`版本增加了`autoDismiss`设置，设置为false后，在操作完毕后弹窗不再自动关闭。
> 
> ```
> XPopup.get(this).autoDismiss(false)...
> ```

版本1.3.6bug  设置了autoDismiss(false)后,输入对话框的取消按钮失效

**Comment by li-xiaojun** [comment]
@VincentYD 
在最新版本`1.3.9`已经修复，请更新看看。
