### ISSUE TITLE
kotlin场景下，出现NoClassDefFoundError and ClassNotFoundException

### ISSUE THREAD

**Issue by WengHaobin** [li-xiaojun/XPopup#391]
AndroidStudio 3.6.1  
minSdk 19
targetSdk 28
gradle 5.6.4
![image](https://user-images.githubusercontent.com/16800049/75938945-f75e2f80-5ec3-11ea-92f7-d9f8a01ec559.png)
![image](https://user-images.githubusercontent.com/16800049/75939090-41dfac00-5ec4-11ea-91d8-095fc9a65b19.png)

**Comment by li-xiaojun** [comment]
适配到androidx
