### ISSUE TITLE
InputConfirmPopupView#initPopupContent()有误

### ISSUE THREAD

**Issue by Vicent9920** [li-xiaojun/XPopup#394]
`InputConfirmPopupView`在自定义弹窗的时候应该删除`applyPrimaryColor()`方法，因为父类已经判断后调用了这个方法了。而当前没有判断直接调用会导致绑定的布局颜色设置有问题！

**Comment by li-xiaojun** [comment]
你的意思是继承 InputConfirmPopupView 进行自定义？

**Comment by Vicent9920** [comment]
我在使用`bindlayout`方法的时候，有这个问题。当然，自定义也可以解决，只是你的这个api就浪费了！

**Comment by li-xiaojun** [comment]
试试1.9.3，应该修复了这个问题
