### ISSUE TITLE
锁屏之后不能正常出现弹窗但有黑色阴影

### ISSUE THREAD

**Issue by mengzhidaren** [li-xiaojun/XPopup#395]
华为  9.0系统上

**Comment by uuuBird** [comment]
如此可解:
public class RepairedCenterPopupView extends CenterPopupView {
    private ViewTreeObserver.OnGlobalLayoutListener listener;

    public RepairedCenterPopupView(@NonNull Context context) {
        super(context);
    }

    @Override
    protected void initPopupContent() {
        View contentView = LayoutInflater.from(getContext()).inflate(getImplLayoutId(), centerPopupContainer, false);
        LayoutParams params = (LayoutParams) contentView.getLayoutParams();
        params.gravity = Gravity.CENTER;
        centerPopupContainer.addView(contentView, params);
        getPopupContentView().setTranslationX(popupInfo.offsetX);
        getPopupContentView().setTranslationY(popupInfo.offsetY);
        listener = new ViewTreeObserver.OnGlobalLayoutListener() {
            @Override
            public void onGlobalLayout() {
                applyPopupSize((ViewGroup) getPopupContentView(), getMaxWidth(), getMaxHeight());
                getViewTreeObserver().removeOnGlobalLayoutListener(listener);
            }
        };
        getViewTreeObserver().addOnGlobalLayoutListener(listener);
    }
}

**Comment by mengzhidaren** [comment]
谢谢 我在生命周期内判断了 如果非前台显示就禁止了
