### ISSUE TITLE
空指针

### ISSUE THREAD

**Issue by dary123** [li-xiaojun/XPopup#396]
1 com.lxj.xpopup.util.KeyboardUtils.registerSoftInputChangedListener(KeyboardUtils.java:73)
--
2 com.lxj.xpopup.core.BasePopupView.show(BasePopupView.java:185)
3 com.yujianapp.achat.activity.UserActivity.SettingActivity$8.onClick(SettingActivity.java:320)
4 android.view.View.performClick(View.java:6304)
5 android.view.View$PerformClick.run(View.java:24803)
6 android.os.Handler.handleCallback(Handler.java:794)
7 android.os.Handler.dispatchMessage(Handler.java:99)
8 android.os.Looper.loop(Looper.java:176)
9 android.app.ActivityThread.main(ActivityThread.java:6651)
10 java.lang.reflect.Method.invoke(Native Method)
11 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
12 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)

**Comment by dary123** [comment]
java.lang.NullPointerException
Attempt to invoke virtual method 'android.view.ViewTreeObserver android.widget.FrameLayout.getViewTreeObserver()' on a null object reference

**Comment by li-xiaojun** [comment]
哪个版本

**Comment by dary123** [comment]
最新版

**Comment by li-xiaojun** [comment]
试试1.9.3，应该修复了这个问题
