### ISSUE TITLE
android support 混乱

### ISSUE THREAD

**Issue by Jas67810** [li-xiaojun/XPopup#398]
'com.lxj:xpopup:1.8.11' 非androidx的版本，在 SmartDragLayout.java 文件中引用了androidx的内容。
需要改回
import android.support.v4.view.NestedScrollingParent;
import android.support.v4.view.ViewCompat;

**Comment by mrchenmo** [comment]
还有一个插值器
androidx.interpolator.view.animation.FastOutSlowInInterpolator

**Comment by li-xiaojun** [comment]
新版本切了androidx
