### ISSUE TITLE
状态栏背景是怎么处理的呢？

### ISSUE THREAD

**Issue by parcool** [li-xiaojun/XPopup#4]
默认是这样：
![image](https://user-images.githubusercontent.com/12092478/50322952-6b582600-0512-11e9-9a85-2b7b4f0d5d70.png)
打开侧滑dialog是这样：
![image](https://user-images.githubusercontent.com/12092478/50322965-790dab80-0512-11e9-8a46-8952d3a0e7b6.png)
状态栏的背景是怎么出现的呢？可以干掉吗？要不点不到上面的

**Comment by li-xiaojun** [comment]
感谢您的建议，状态栏背景是我用占位的View模拟的效果，如果你的背景是白色的你就明白我的用意了。

不过我没明白您说的，状态栏的背景导致点不到上面的什么，可以再具体一点么。

**Comment by parcool** [comment]
![image](https://user-images.githubusercontent.com/12092478/50325985-c42fba80-0522-11e9-8919-ac169c8c2980.png)
就是这一块区域，如果上面有事件就会点不到，因为会把系统的抽屉给点到。。。

**Comment by li-xiaojun** [comment]
@parcool 兄弟，这个灰色区域是在状态栏下面的，如果我不加灰色，你点击这个区域的话也是点到状态栏。对于任何一个Activity，这个区域都是状态栏来响应的，你可以随便打开一个应用看看。

**Comment by parcool** [comment]
@li-xiaojun 有道理。但是感觉还是有点遮挡UI了，有木有办法取消掉？

**Comment by li-xiaojun** [comment]
@parcool 我已经在新版本`0.0.8`中增加了Drawer弹窗是否设置状态栏阴影的功能，默认是没有。具体看README的screenshot演示和说明。

**Comment by parcool** [comment]
@li-xiaojun 好的，已经看到了。感谢作者！另外：遇到过几次BasePopupView#doDismissAnimation报空指针错误，记不清是popupInfo空了还是shadowBgAnimator空了。。。当然，这个错误不是出现在侧滑这里哈，是底部弹出菜单的问题，模拟器测试的哈。

**Comment by li-xiaojun** [comment]
@parcool 老版本是有这个bug，不过现在新版解决了。你看看你出问题的版本号是多少，如果是新版本，请将log信息截图发下，thanks。

**Comment by li-xiaojun** [comment]
@parcool  Demo中的bug已经修复
