### ISSUE TITLE
application设置主色调崩溃

### ISSUE THREAD

**Issue by VincentYD** [li-xiaojun/XPopup#40]
版本 1.3.5

application设置主色调崩溃

![image](https://user-images.githubusercontent.com/31061813/52900701-e9475d80-3233-11e9-9cb3-9b19b7f01d9d.png)

**Comment by li-xiaojun** [comment]
@VincentYD 
在最新的`1.3.6`版本中做了修改，设置弹窗无需传上下文，这样既可：
```
XPopup.setPrimaryColor(xxx);
```
