### ISSUE TITLE
Android support 引用错误

### ISSUE THREAD

**Issue by yangchendev** [li-xiaojun/XPopup#400]
![image](https://user-images.githubusercontent.com/12218109/77300458-07ca3300-6d29-11ea-8a2b-b89fabf89205.png)
非Androidx 版本却引用了Androidx下的包，导致编译错误

**Comment by YanYanLun** [comment]
![图片](https://user-images.githubusercontent.com/17606580/77715535-cf6f7100-7016-11ea-8a99-6efafef1b6ec.png)，我也是同样问题

**Comment by li-xiaojun** [comment]
新版本已经换到了androidx，没有这个问题了
