### ISSUE TITLE
自定义BottomPopupView报错

### ISSUE THREAD

**Issue by RyanJeson** [li-xiaojun/XPopup#401]
XPopup版本：1.8.11
自定义BottomPopupView报错：
android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class com.lxj.xpopup.widget.SmartDragLayout

在之前等版本：1.8.10，1.8.9 ，都没有出现这个问题。 换成新版本后 报了这个错误。

**Comment by li-xiaojun** [comment]
尝试新版本
