### ISSUE TITLE
底部弹出，选中效果没有，没有出现打勾

### ISSUE THREAD

**Issue by Timan86** [li-xiaojun/XPopup#402]
case R.id.btnShowBottomListWithCheck: //从底部弹出，带手势拖拽的列表弹窗,带选中效果
                new XPopup.Builder(getContext())
                        .asBottomList("", new String[]{"条目1", "条目2", "条目3", "条目4", "条目5"},
                                null, 2,
                                new OnSelectListener() {
                                    @Override
                                    public void onSelect(int position, String text) {
                                        toast("click " + text);
                                    }
                                })
                        .show();

**Comment by li-xiaojun** [comment]
最新版已经修复
