### ISSUE TITLE
图片浏览器手势无效的问题

### ISSUE THREAD

**Issue by yangchendev** [li-xiaojun/XPopup#405]
在图片浏览器滑动图片过程中，当滑动到某个图片时，向下拉会拉不动图片，不会有向下缩放的效果，DEMO可以100%复现，希望可以解决下 @li-xiaojun

**Comment by li-xiaojun** [comment]
不知道你说的什么问题，加xpopup群发视频

**Comment by yangchendev** [comment]
额，这不是很明显的BUG吗，另外早就加群发了视频了 ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Jun&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年6月6日(星期六) 晚上7:37
收件人:&nbsp;&quot;li-xiaojun/XPopup&quot;<XPopup@noreply.github.com&gt;;
抄送:&nbsp;&quot;chenfeng&quot;<1048027353@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [li-xiaojun/XPopup] 图片浏览器手势无效的问题 (#405)

**Comment by li-xiaojun** [comment]
@yangchendev 在群里再发个视频，我无法复现
