### ISSUE TITLE
Android 10问题打开弹框闪屏不显示

### ISSUE THREAD

**Issue by jinhuizxc** [li-xiaojun/XPopup#409]
9.0系统可以用的，升级了android10，调用作者的这个方法：
 new XPopup.Builder(getContext())
                        .atView(view)  // 依附于所点击的View，内部会自动判断在上方或者下方显示
                        .asAttachList(new String[]{"分享", "编辑", "不带icon"},
                                new int[]{R.mipmap.ic_launcher, R.mipmap.ic_launcher},
                                new OnSelectListener() {
                                    @Override
                                    public void onSelect(int position, String text) {
                                        ToastUtils.showShort("click " + text);
                                    }
                                })
                        .show();
并不能显示出弹框，反而闪屏，不显示，不知道原因，希望作者解决这个问题;

**Comment by li-xiaojun** [comment]
你是真机还是模拟器

**Comment by li-xiaojun** [comment]
试试1.9.3，应该修复了这个问题

**Comment by tswdwwl** [comment]
华为荣耀10 ， 2.0.7 版本 还有此问题

**Comment by tswdwwl** [comment]
华为荣耀10，也是9升级Android10出现此问题，版本2.0.7
