### ISSUE TITLE
征集三星手机底部留白问题修复的PullRequest！！！

### ISSUE THREAD

**Issue by li-xiaojun** [li-xiaojun/XPopup#410]
由于我本人没有三星手机，很多朋友提出在三星手机底部留白的问题；我暂时也无能为力。
如果有人有这个手机可以尝试修复这个问题，给我提个PR，非常感谢。

如果某位朋友愿意给我邮寄一个三星手机过来，我也很是感谢。问题修复后给你邮寄回去。如果你愿意邮寄，可以加我微信：dance20150514 

我们一起让XPopup更强大更好用。

**Comment by hoanX** [comment]
我的是三星手机s10(右上角挖空，算刘海屏)，使用1.8.17版本底部没有留白问题，今天升级到1.9.0版本才出现这个问题

` if (RomUtils.isSamsung()){      //判断是否是三星
                    popupInfo.decorView.addView(BasePopupView.this, new LayoutParams(LayoutParams.MATCH_PARENT,
                            XPopupUtils.getAppScreenHeight(getContext())));
                }`
这里的高度判断取得到比实际小，需要加上刘海的高度，才是完整的高度

但是看你提出问题时间4月2号，不知道是不是一个问题

**Comment by hoanX** [comment]
我又看翻了下issue，如果开启Android10底部的导航小白条，老版本也会有底部留白问题，不开启就正常
XPopupUtils.getAppScreenHeight(getContext()) + 刘海高度  不论开不开起导航条都正常
有点意思~

**Comment by DaveBoy** [comment]
https://github.com/li-xiaojun/XPopup/issues/438 试试这个方法  我机型有限 可能测试不够完全

**Comment by hoanX** [comment]
@DaveBoy 你的这个也不行，BarUtils.getNavBarHeight() 不论我开不开导航条值都是一样的，只有开启虚拟按键才会正常

**Comment by DaveBoy** [comment]
> @DaveBoy 你的这个也不行，BarUtils.getNavBarHeight() 不论我开不开导航条值都是一样的，只有开启虚拟按键才会正常

你测试的三星吗   我测miui12和pixel2开手势指示条和开虚拟按键的情况都是正常的

**Comment by hoanX** [comment]
> > @DaveBoy 你的这个也不行，BarUtils.getNavBarHeight() 不论我开不开导航条值都是一样的，只有开启虚拟按键才会正常
> 
> 你测试的三星吗 我测miui12和pixel2开手势指示条和开虚拟按键的情况都是正常的

嗯，三星手机S10

**Comment by DaveBoy** [comment]
> > > @DaveBoy 你的这个也不行，BarUtils.getNavBarHeight() 不论我开不开导航条值都是一样的，只有开启虚拟按键才会正常
> > 
> > 
> > 你测试的三星吗 我测miui12和pixel2开手势指示条和开虚拟按键的情况都是正常的
> 
> 嗯，三星手机S10

那就只能三星维持群主的源码写法了

**Comment by DaveBoy** [comment]
> > > @DaveBoy 你的这个也不行，BarUtils.getNavBarHeight() 不论我开不开导航条值都是一样的，只有开启虚拟按键才会正常
> > 
> > 
> > 你测试的三星吗 我测miui12和pixel2开手势指示条和开虚拟按键的情况都是正常的
> 
> 嗯，三星手机S10

老哥  have a try 我刚发出来的写法试试

**Comment by li-xiaojun** [comment]
@DaveBoy  @hoanX 

1.9.3已修复这个问题
