### ISSUE TITLE
asAttachList这个内置pop的item点击范围太小

### ISSUE THREAD

**Issue by zqlq4ever** [li-xiaojun/XPopup#412]
![image](https://user-images.githubusercontent.com/37474811/78333600-b89fc000-75bc-11ea-9a3d-5ddcb4ef894e.png)
当每个item的长度不一样时，比如item 0 = “12345678”  item 1 = “12”，那么item1的空白部分点击无效，只有点到文字上，才会响应

**Comment by li-xiaojun** [comment]
是最新版吗

**Comment by zqlq4ever** [comment]
> 是最新版吗

1.8.14

**Comment by li-xiaojun** [comment]
升级到最新版试试

**Comment by zqlq4ever** [comment]
> 升级到最新版试试

1.8.17还没有修复。
我在你的demo里看了也是的。
按下之后的效果没填充item
![IMG_20200407_094738](https://user-images.githubusercontent.com/37474811/78621359-0108f780-78b5-11ea-86ec-b2a121fc9cb8.jpg)
![IMG_20200407_094746](https://user-images.githubusercontent.com/37474811/78621367-036b5180-78b5-11ea-8b95-e2fbc7dcdcf6.jpg)

**Comment by li-xiaojun** [comment]
1.9.4已修复
