### ISSUE TITLE
ConfirmPopupView.setTitleContent 不起作用

### ISSUE THREAD

**Issue by RyanJeson** [li-xiaojun/XPopup#414]
页面上有多处要提示默认的弹窗。
想着复用ConfirmPopupView，然后修改弹窗里面的内容。
看了源码调用了setTitleContent设置title和content。
但是实际复用ConfirmPopupView调用setTitleContent方法设置title和content不会发生修改，会显示第一次创建的标题和内容。

      代码：
        if (mConfirmPopupView == null) {
            mConfirmPopupView = new XPopup.Builder(this)
                     .dismissOnTouchOutside(false)
                    .setPopupCallback(new SimpleCallback() {
                        @Override
                        public void onCreated() {
                            Log.e("tag", "弹窗创建了");
                        }

                        @Override
                        public void onShow() {
                            Log.e("tag", "onShow");
                        }

                        @Override
                        public void onDismiss() {
                            Log.e("tag", "onDismiss");
                        }

                        //如果你自己想拦截返回按键事件，则重写这个方法，返回true即可
                        @Override
                        public boolean onBackPressed() {
                            ToastUtils.showShort("我拦截的返回按键，按返回键XPopup不会关闭了");
                            return true;
                        }
                    }).asConfirm(title, content,
                            "取消", "确定",
                            this,null, TextUtils.isEmpty(cancel));
        }else {
            // 如果已创建，则修改其标题和内容。
            mConfirmPopupView.setTitleContent(title, content, null);
        }
        mConfirmPopupView.show();

**Comment by li-xiaojun** [comment]
在else中这样写：
```
else {
        // 如果已创建，则修改其标题和内容。
        mConfirmPopupView = mConfirmPopupView.setTitleContent(title, content, null);
    }
```
