### ISSUE TITLE
超出屏幕宽度了，请问怎么处理？

### ISSUE THREAD

**Issue by maxhsh** [li-xiaojun/XPopup#415]
XPopup.Builder builder = new XPopup.Builder(getContext());
                    builder .watchView(view).atView(view).asCustom(new CustomAttachPopup(getAttachActivity()))
                            .show();
![image](https://user-images.githubusercontent.com/8461810/79059029-d00b3700-7ca7-11ea-9940-5669ef279bdf.png)

**Comment by li-xiaojun** [comment]
你的attach弹窗的布局贴下
