### ISSUE TITLE
让本库兼容DialogFragment的解决方案

### ISSUE THREAD

**Issue by zwt-ss** [li-xiaojun/XPopup#416]
hi我尝试在dialogFragment上使用该库的时候发现它没法在其上显示，issue里也提到了这点 #153 
我阅读了源码，这不是一个无法解决的问题
下面是解决方案
关键在于show方法里这段代码
```
final Activity activity = (Activity) getContext();
        popupInfo.decorView = (ViewGroup) activity.getWindow().getDecorView();
```
在BasePopup中这里获取了DecorView，而DialogFragment同样有DecorView，它并不是一个系统级对话框，而是一个Fragment，在DialogFragment中获取DecorView的方法是getDialog().getWindow().getDecorView();
所以请允许传入一个DialogFragment，并在强制类型转换前添加一个判断，或者直接允许传入DecorView。
期待你的回复：）

**Comment by aLittleGreens** [comment]
你好，我也碰到了，同样的问题，请问怎么解决的啊

**Comment by zwt-ss** [comment]
> 你好，我也碰到了，同样的问题，请问怎么解决的啊

我使用这个库，手动替换掉了xpopup里面的一些类，自行修复这个问题
https://github.com/iwhys/sdk-editor-plugin

**Comment by aLittleGreens** [comment]
> > 你好，我也碰到了，同样的问题，请问怎么解决的啊
> 
> 我使用这个库，手动替换掉了xpopup里面的一些类，自行修复这个问题
> https://github.com/iwhys/sdk-editor-plugin

我也改了源码，可以弹出来，但是弹出的位置不对，而且点击，弹窗就消失来，请问你怎么解决的，能不能分享一下代码啊？

**Comment by li-xiaojun** [comment]
@zwt-ss  @aLittleGreens 
支持dialog的版本已经发布，请升级到:
```
com.lxj:xpopup:dialog-1.9.9 
```
