### ISSUE TITLE
asAttachList 选项item之间存在分割线，如何去除

### ISSUE THREAD

**Issue by abcdisgreat** [li-xiaojun/XPopup#418]
默认情况下白色看不出来，但是使用自定义bindItemLayout或者把_xpopup_adapter_text.xml背景色改深色就会看到分割线

![image](https://user-images.githubusercontent.com/33865977/79322633-aec47800-7f3f-11ea-98b5-db1ddce73152.png)

**Comment by DaveBoy** [comment]
VerticalRecyclerView这里面的原因吧。。。。自定义xml，改成recycleview

**Comment by li-xiaojun** [comment]
这种特殊的需求很难满足，你可以选择自定义弹窗了。
