### ISSUE TITLE
InputConfirmPopupView中applyPrimary方法有误，导致bindLayout中设置的EditText样式被修改

### ISSUE THREAD

**Issue by fzhengx** [li-xiaojun/XPopup#421]
库版本：1.8.17 类：InputConfirmPopupView

`
protected void applyPrimary(){
        super.applyPrimaryColor();
        //这里应该判断判断bindLayoutId才对
        if(bindItemLayoutId==0){
            XPopupUtils.setCursorDrawableColor(et_input, XPopup.getPrimaryColor());
            et_input.post(new Runnable() {
                @Override
                public void run() {
                    BitmapDrawable defaultDrawable = XPopupUtils.createBitmapDrawable(getResources(), et_input.getMeasuredWidth(), Color.parseColor("#888888"));
                    BitmapDrawable focusDrawable = XPopupUtils.createBitmapDrawable(getResources(), et_input.getMeasuredWidth(), XPopup.getPrimaryColor());
                    et_input.setBackgroundDrawable(XPopupUtils.createSelector(defaultDrawable, focusDrawable));
                }
            });
        }
    }
`
同样，父类ConfirmPopupView中也拿了bindItemLayoutId作为判断条件（applyPrimaryColor方法。即使由于先判断了bindLayoutId而没有出现异常）

**Comment by li-xiaojun** [comment]
试试最新版本已经修复
