### ISSUE TITLE
输入法是否可以设置InputType属性

### ISSUE THREAD

**Issue by wushange** [li-xiaojun/XPopup#423]
输入法是否可以设置InputType属性

**Comment by li-xiaojun** [comment]
InputConfirmPopup只适用于简单的输入场景，如果有复杂需求，就需要自定义了

**Comment by KunNiu** [comment]
@wushange , 试试这种方法
`.setPopupCallback(new SimpleCallback() {
                    @Override
                    public void onCreated(BasePopupView popupView) {
                        super.onCreated(popupView);
                            ((InputConfirmPopupView) popupView).getEditText().setInputType(EditorInfo.TYPE_CLASS_NUMBER);
                    }
                })`
