### ISSUE TITLE
如何实现横屏时弹出带有EditText的自定义对话框，自动弹出底部键盘

### ISSUE THREAD

**Issue by dary123** [li-xiaojun/XPopup#425]
如何实现横屏时弹出带有EditText的自定义对话框，自动弹出底部键盘，我这边需要点击EditText一下，然后才能进入全屏的输入页面，我这边不想要全屏形式输入，只要在底部弹出输入键盘就好了

**Comment by dary123** [comment]
我在demo里将页面方向改为横向，结果键盘是在系统自带的一个单独的输入页面弹出来的，而不是当前页面底部弹出键盘

**Comment by TianGuisen** [comment]
dialogfragment也有这样的问题，同求解决方法

**Comment by li-xiaojun** [comment]
这个问题和弹窗没有关系，可能和EditText的行为有关
