### ISSUE TITLE
if we open nested 5 popup then first popup activity dismiss on backpressed

### ISSUE THREAD

**Issue by Maulik61** [li-xiaojun/XPopup#426]
From my one activity I created Parent popup and there are other 4 children popup in parent popup.
if i open child popup more then 2 time then i am trying to click OnBackpress Button then whole Activity remove rather then Parent Popup Remove.

I required solution is that successfully remove Parent pop (Not Activity) after open two or more child Popup.

**Comment by li-xiaojun** [comment]
which version you are using?

**Comment by Maulik61** [comment]
I am using version 1.8.10. 
 
  On Sun, 7 Jun 2020 at 12:59 PM, Jun<notifications@github.com> wrote:   


which version you are using?

**Comment by li-xiaojun** [comment]
can you show me your code?

**Comment by Maulik61** [comment]
Not I described you if you want 

Sent from Yahoo Mail on Android 
 
  On Sun, 7 Jun 2020 at 1:05 PM, Jun<notifications@github.com> wrote:   


can you show me your code?

**Comment by li-xiaojun** [comment]
If you cannot show me code , I cannot help you.
But you can  download XPopup source code , see DemoActivity.java . this file show multi popup
situation

**Comment by Maulik61** [comment]
I will trying to send same scenario code tomorrow. 
 
  On Tue, 9 Jun 2020 at 11:57 AM, Jun<notifications@github.com> wrote:   


If you cannot show me code , I cannot help you.
But you can download XPopup source code , see DemoActivity.java . this file show multi popup
situation
