### ISSUE TITLE
loadview.dismiss无效 1.8.17版本

### ISSUE THREAD

**Issue by nxnyk** [li-xiaojun/XPopup#427]
我再方法开始时show了loadview
![image](https://user-images.githubusercontent.com/42330422/80070966-709a0a80-8576-11ea-97ef-65b2ad4ec2dc.png)
然后在处理中调用了dismiss 发现 无效 不会消失
![image](https://user-images.githubusercontent.com/42330422/80071047-90313300-8576-11ea-9baa-066cb299da76.png)

**Comment by nxnyk** [comment]
代码见图

**Comment by kokod21** [comment]
你这个是必现吗？我们项目偶现loadView无法dismiss的情况，但是很偶然出现

**Comment by nxnyk** [comment]
> 你这个是必现吗？我们项目偶现loadView无法dismiss的情况，但是很偶然出现

必现  前提是  网络请求 返回异常  就会dismiss不了

**Comment by kokod21** [comment]
> > 你这个是必现吗？我们项目偶现loadView无法dismiss的情况，但是很偶然出现
> 
> 必现 前提是 网络请求 返回异常 就会dismiss不了

难道是线程的问题么

**Comment by nxnyk** [comment]
> > > 你这个是必现吗？我们项目偶现loadView无法dismiss的情况，但是很偶然出现
> > 
> > 
> > 必现 前提是 网络请求 返回异常 就会dismiss不了
> 
> 难道是线程的问题么

有可能，指定在ui线程dismiss试试看

**Comment by kokod21** [comment]
> > > > 你这个是必现吗？我们项目偶现loadView无法dismiss的情况，但是很偶然出现
> > > 
> > > 
> > > 必现 前提是 网络请求 返回异常 就会dismiss不了
> > 
> > 
> > 难道是线程的问题么
> 
> 有可能，指定在ui线程dismiss试试看

大哥，结果怎样吗？

**Comment by nxnyk** [comment]
> > > > > 你这个是必现吗？我们项目偶现loadView无法dismiss的情况，但是很偶然出现
> > > > 
> > > > 
> > > > 必现 前提是 网络请求 返回异常 就会dismiss不了
> > > 
> > > 
> > > 难道是线程的问题么
> > 
> > 
> > 有可能，指定在ui线程dismiss试试看
> 
> 大哥，结果怎样吗？

没试呢，，，先降级10版本用了，，，

**Comment by guochenchn** [comment]
是因为你的dismissOnTouchOutside(false) 设置了false 才无法dismiss 他的源码是根据这个值判断的 你可以看下源码 不知道作者这么判断为了什么

**Comment by nxnyk** [comment]
> 是因为你的dismissOnTouchOutside(false) 设置了false 才无法dismiss 他的源码是根据这个值判断的 你可以看下源码 不知道作者这么判断为了什么

还有这种操作。。。谢谢老哥解答~

**Comment by AttackPangHu** [comment]
我也出现了这种情况。。。但是我dismissOnTouchOutside设置了false一般掉dismiss是能关闭的，但是在fragment中，同样的代码，dismiss无效
