### ISSUE TITLE
一共有两个问题

### ISSUE THREAD

**Issue by dlgchg** [li-xiaojun/XPopup#43]
第一,设置最大高度失效.我首先是设置了布局的最大高度maxheight,不行,然后我在代码中设置maxWidthAndHeight,依然不行.
第二,我如果强制高度为某一高度,listview数据就乱,实测自适应高度,等于全屏,listview数据不会有任何问题!

**Comment by li-xiaojun** [comment]
@dlgchg 
贴下你的布局和你的代码

**Comment by li-xiaojun** [comment]
@dlgchg 
弹窗默认就是自适应高度的，如果你想限制最大高度有3种方式：
1. 调用maxWidthAndHeight来限制
2. 重写弹窗的getMaxWidth和getMaxHeight方法
3. 自定义弹窗的时候布局内写固定的高
