### ISSUE TITLE
使用全屏弹窗的时候,怎样可以让弹出的内容不包括状态栏呢?

### ISSUE THREAD

**Issue by roybill** [li-xiaojun/XPopup#430]
使用全屏弹窗的时候,怎样可以让弹出的内容不包括状态栏呢?现在弹出来全屏的内容和顶部状态栏重叠了,我是这样按照官方的弹出来的.
 private void show(){
        String[] str={"条目1", "条目2", "条目3", "条目4", "条目5","条目1", "条目2", "条目3", "条目4", "条目5","条目1", "条目2", "条目3", "条目4", "条目5",
                "条目1", "条目2", "条目3", "条目4", "条目5","条目1", "条目2", "条目3", "条目4", "条目5","条目1", "条目2", "条目3", "条目4", "条目5"};
        new XPopup.Builder(Lingsierqi.this)
                .autoDismiss(false)
                .asBottomList("请选择一项", str,
                        new OnSelectListener() {
                            @Override
                            public void onSelect(int position, String text) {
                                ToastUtils.showShort("点击"+position);
                                show();
                            }
                        })
                .show();
    }

**Comment by li-xiaojun** [comment]
可以给全屏弹窗的布局添加marginTop或者paddingTop，记住，弹窗就是Activity的View而已，把它当做一个普通View

**Comment by roybill** [comment]
已经搞定了,谢谢
