### ISSUE TITLE
LoadingPopupView的复用问题

### ISSUE THREAD

**Issue by kokod21** [li-xiaojun/XPopup#431]
版本：1.8.13
但是看到最新版本的源码也是这样：
发现LoadingPopupView有个小问题，

我调用代码如下：
    public void showLoadingDialog(String msg) {
        if (loadingPopup == null) {
            loadingPopup = new XPopup.Builder(this).asLoading(msg);
        }
        loadingPopup.setTitle(msg);
        loadingPopup.show();
    }
然后去到下面这个方法会有个问题
protected void setup(){
        if(title!=null && tv_title!=null){
            tv_title.setVisibility(VISIBLE);
            tv_title.setText(title);
        }
    }

比如我第一次setTitle("xxxxx") ，第二次我调用setTitle(null)的话，还会显示上一次的title文字，setTitle("")的话，title的leftPadding又会显示出来，右边好大一片空白
能不能这样优化下
protected void setup(){
       if(tv_title!=null){
            if(TextUtils.isEmpty(title)){
                tv_title.setVisibility(GONE);
            } else {
                tv_title.setVisibility(VISIBLE);
                tv_title.setText(title);
            }
        }
    }
主要是懒，不想改源码，不然下次升级好麻烦，希望大佬下个版本可以优化下这个问题

**Comment by li-xiaojun** [comment]
可以
