### ISSUE TITLE
MIUI12不兼容

### ISSUE THREAD

**Issue by niexg** [li-xiaojun/XPopup#432]
在12上，获取navigationbar高度不对

**Comment by YuYongzhi** [comment]
在MIUI 12上，有手势提示线，导致获取的NavigationBar的高度为完成的导航栏高度
![WechatIMG1337](https://user-images.githubusercontent.com/6104276/81070165-74824100-8f15-11ea-963a-efd0bf334086.jpeg)
![WechatIMG1338](https://user-images.githubusercontent.com/6104276/81070182-7946f500-8f15-11ea-8e24-a64234cc31aa.jpeg)

**Comment by Boliang-Lu** [comment]
顶一下

**Comment by DaveBoy** [comment]
https://github.com/li-xiaojun/XPopup/issues/438 试试这个方法

**Comment by li-xiaojun** [comment]
@YuYongzhi @DaveBoy @niexg @Boliang-Lu 

试试最新的1.9.3版本，应该修复了
