### ISSUE TITLE
使用bttomPopupView 可以给一个选项是否下拉时候需要退出吗？

### ISSUE THREAD

**Issue by UsingMisz** [li-xiaojun/XPopup#433]
![786D6535-B35D-47e0-AA37-8CBBD0778145](https://user-images.githubusercontent.com/18585336/80668857-7ee7a980-8ad5-11ea-9e4a-feb90b0c8345.png)

**Comment by li-xiaojun** [comment]
弹窗只承载UI方面的逻辑，其他的逻辑就没有必要实现。
