### ISSUE TITLE
1.9.0 pixel2xl手势底部留白

### ISSUE THREAD

**Issue by fishballzzz** [li-xiaojun/XPopup#435]
采取 #337 的做法可以修复此问题， 然后在`applySize`里使用`boolean isNavBarShown = XPopupUtils.isShowNavBar(getContext());`

![image](https://user-images.githubusercontent.com/43075130/80896968-f9751c80-8cc1-11ea-9886-85c9fdd38dd7.png)

**Comment by finalrose7** [comment]
在哪里加代码呢？

**Comment by fishballzzz** [comment]
> 在哪里加代码呢？

源码

**Comment by Boliang-Lu** [comment]
MIUI 12上边还是一样，但模拟器是正常的

**Comment by DaveBoy** [comment]
https://github.com/li-xiaojun/XPopup/issues/438  试试这个方法？

**Comment by fishballzzz** [comment]
1.9.4已修复
