### ISSUE TITLE
miui12和pixel2 全面屏底部留白问题解决方案

### ISSUE THREAD

**Issue by DaveBoy** [li-xiaojun/XPopup#438]
可以通过改pop的源码  或者自己继承重写 ，我采用的继承 ，懒得改源码
```
class ShareBottomPopView(context:Context):BottomPopupView(context) {
...
 override fun init() {
      
        if (parent != null) {
            (parent as ViewGroup).removeView(this);
        }
        popupInfo.decorView.addView(this,  LayoutParams(LayoutParams.MATCH_PARENT,
            ScreenUtils.getScreenHeight()-BarUtils.getNavBarHeight()));
        super.init()

    }
}
```
BarUtils、ScreenUtils均来自[AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode/blob/master/lib/utilcode/README-CN.md)1.26.0
暂时测试了miui12和pixel2 AttachPopupView/BottomPopupView 均无问题。其他机型大家可以试试。

**Comment by DaveBoy** [comment]
https://github.com/li-xiaojun/XPopup/issues/410 据@hoanx 测试 三星好像有问题

**Comment by DaveBoy** [comment]
如果三星有问题，那么在继承重写的时候需要判断一下是否是三星，三星就不变，维持群主的源码里的操作

**Comment by DaveBoy** [comment]
排除三星之后的代码：
```
    override fun init() {
        if (!RomUtils.isSamsung()) {
            (parent as? ViewGroup)?.removeView(this)
            popupInfo.decorView.addView(this, LayoutParams(LayoutParams.MATCH_PARENT, ScreenUtils.getScreenHeight() - BarUtils.getNavBarHeight()))
        }
        super.init()
    }
```

**Comment by DaveBoy** [comment]
如果不放心的朋友把判断改成 群主源码没适配的机型（比如pixel），即只对群主没判断的机型采用这种形式，而不是非三星都采用。

**Comment by DaveBoy** [comment]
解决横竖屏的问题，还有就是增加isNavVisible和isFullScreen的判断。
@hoanX 老哥要不要试试这种方式三星行不行
```
       (parent as? ViewGroup)?.removeView(this)
        val isNavVisible=XPopupUtils.isNavBarVisible(context)
        val isFullScreen=ScreenUtils.isFullScreen(context as Activity)
        if(ScreenUtils.isPortrait()){
            popupInfo.decorView.addView(this,
                FrameLayout.LayoutParams(
                    FrameLayout.LayoutParams.MATCH_PARENT,
                    ScreenUtils.getScreenHeight() - if(isNavVisible&&!isFullScreen) BarUtils.getNavBarHeight() else 0
                )
            )
        }else{
            popupInfo.decorView.addView(this,
                FrameLayout.LayoutParams(ScreenUtils.getScreenWidth() - if(isNavVisible&&!isFullScreen) BarUtils.getNavBarHeight() else 0
                    ,FrameLayout.LayoutParams.MATCH_PARENT
                )
            )
        }
```

**Comment by renhuan2015** [comment]
> 可以通过改pop的源码 或者自己继承重写 ，我采用的继承 ，懒得改源码
> 
> ```
> class ShareBottomPopView(context:Context):BottomPopupView(context) {
> ...
>  override fun init() {
>       
>         if (parent != null) {
>             (parent as ViewGroup).removeView(this);
>         }
>         popupInfo.decorView.addView(this,  LayoutParams(LayoutParams.MATCH_PARENT,
>             ScreenUtils.getScreenHeight()-BarUtils.getNavBarHeight()));
>         super.init()
> 
>     }
> }
> ```
> 
> BarUtils、ScreenUtils均来自[AndroidUtilCode](https://github.com/Blankj/AndroidUtilCode/blob/master/lib/utilcode/README-CN.md)1.26.0
> 暂时测试了miui12和pixel2 AttachPopupView/BottomPopupView 均无问题。其他机型大家可以试试。

你的Xpopu是什么版本，我这MIUI12还是无效

**Comment by DaveBoy** [comment]
1.9.0 呢，我自己的机子就是miui12呢，我自己测试是没问题的呢  你试下下面我最后发的[DaveBoy commented 15 days ago](https://github.com/li-xiaojun/XPopup/issues/438#issuecomment-627698299) ,有问题可以截图界面和代码我看一下

**Comment by li-xiaojun** [comment]
@renhuan2015 @DaveBoy 
试试最新的1.9.3版本，应该修复了这个问题

**Comment by renhuan2015** [comment]
> @renhuan2015 @DaveBoy
> 试试最新的1.9.3版本，应该修复了这个问题

测试通过
