### ISSUE TITLE
华为pad使用demo留白问题

### ISSUE THREAD

**Issue by cocolove2** [li-xiaojun/XPopup#442]
![1589444469175 (1)](https://user-images.githubusercontent.com/16257185/81911752-4c26d080-9600-11ea-982f-8fae49000732.jpg)

**Comment by DaveBoy** [comment]
老哥试试https://github.com/li-xiaojun/XPopup/issues/438 这个

**Comment by DaveBoy** [comment]
原因应该是因为   横屏的状态下减去了导航栏的高度

**Comment by li-xiaojun** [comment]
试试最新版本
