### ISSUE TITLE
关于底部导航栏留白问题，我这里统一给大家一个适配所有系统的解决方案

### ISSUE THREAD

**Issue by hyx0804xiaokeai** [li-xiaojun/XPopup#446]
先说原因，是因为弹窗设置了margin，当判断有底部导航栏的时候，设置margin的高度为底部导航栏的高度，但是由于MIUI12，三星，一加之类的新版本系统获取的高度不准确，就造成了设置margin错误导致留白的问题。

再说解决方案。
1.下载源码直接在BasePopupView里修改applySize方法
2.继承任意父类是BasePopupView的弹窗，重写applySize方法。

      protected void applySize(boolean isShowNavBar) {
        //获取屏幕高度
        int height = XPopupUtils.getPhoneScreenHeight(getContext());
       //获取应用内屏幕可用高度
        if (popupInfo.decorView.getChildCount() > 0) {
            height = popupInfo.decorView.getChildAt(0).getMeasuredHeight();
        }
        LayoutParams params = (LayoutParams) getLayoutParams();
        int rotation = ((WindowManager) getContext().getSystemService(Context.WINDOW_SERVICE)).getDefaultDisplay().getRotation();
        boolean isNavBarShown = XPopupUtils.isNavBarVisible(getContext());
       //设置margin为屏幕高度减去应用可用高度
        if (rotation == 0) {
            params.leftMargin = 0;
            params.rightMargin = 0;
            params.bottomMargin = isNavBarShown ? XPopupUtils.getPhoneScreenHeight(getContext()) - height : 0;
        } else if (rotation == 1) {
            params.bottomMargin = 0;
            params.rightMargin = isNavBarShown ? XPopupUtils.getPhoneScreenHeight(getContext()) - height : 0;
            params.leftMargin = 0;
        } else if (rotation == 3) {
            params.bottomMargin = 0;
            params.leftMargin = 0;
            params.rightMargin = isNavBarShown ? XPopupUtils.getPhoneScreenHeight(getContext()) - height : 0;
        }
        setLayoutParams(params);
    }
      
       //获取应用可用的屏幕高度
       public static int getPhoneScreenHeight(Context context){
        Activity ac = (Activity) context;
        DisplayMetrics outMetrics = new DisplayMetrics();
        ac.getWindowManager().getDefaultDisplay().getRealMetrics(outMetrics);
        return  outMetrics.heightPixels;
       }

另外，如果是1.9.0版本，需要把basePopupView的show方法修改一下，把适配各机型的代码删除。

       public BasePopupView show() {
        if (getParent() != null) return this;
        final Activity activity = (Activity) getContext();
        popupInfo.decorView = (ViewGroup) activity.getWindow().getDecorView();
        KeyboardUtils.registerSoftInputChangedListener(activity, this, new KeyboardUtils.OnSoftInputChangedListener() {
            @Override
            public void onSoftInputChanged(int height) {
                if (height == 0) { // 说明对话框隐藏
                    XPopupUtils.moveDown(BasePopupView.this);
                    hasMoveUp = false;
                } else {
                    //when show keyboard, move up
                    XPopupUtils.moveUpToKeyboard(height, BasePopupView.this);
                    hasMoveUp = true;
                }
            }
        });
        // 1. add PopupView to its decorView after measured.
        popupInfo.decorView.post(new Runnable() {
            @Override
            public void run() {
                if (getParent() != null) {
                    ((ViewGroup) getParent()).removeView(BasePopupView.this);
                }
                popupInfo.decorView.addView(BasePopupView.this, new LayoutParams(LayoutParams.MATCH_PARENT,
                            LayoutParams.MATCH_PARENT));
                //2. do init，game start.
                init();
            }
        });
        return this;
    }

**Comment by finalrose7** [comment]
希望作者能够采用这个修复方法到下一个版本里。

**Comment by li-xiaojun** [comment]
@hyx0804xiaokeai  这个方案在哪些系统测试通过了

**Comment by hyx0804xiaokeai** [comment]
> @ hyx0804xiaokeai 这个方案在一些系统测试通过了

目前测试小米三星一加华为都没问题。产生这个问题的原理已经讲清楚了，具体解决方案可以看代码的注释。

**Comment by li-xiaojun** [comment]
@hyx0804xiaokeai 
我集成一下发个版本，感谢提供

**Comment by hyx0804xiaokeai** [comment]
@li-xiaojun 
没改其它地方，就这两个地方。如果你是1.9.0的话  把show()的代码改成1.8.9的show()代码就好了。
然后把BasePopupView这个类的applySize()改成我上边写的，中间你可以自行打印VIew的高度看看不显示是不是因为高度为0或者margin为屏幕高度。

**Comment by finalrose7** [comment]
这代码可行，我测试过三星，一加，都正常了。

**Comment by li-xiaojun** [comment]
@hyx0804xiaokeai  @finalrose7 
最新版本已经修复
