### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by yansideyu76** [li-xiaojun/XPopup#448]
直接关闭activity 在onDestroy调用dismiss()  
postDelayed(doAfterDismissTask, getAnimationDuration());
不会执行 doAfterDismissTask
导致内存泄露了 用反射调用doAfterDismissTask 的run方法 不会泄漏

正常调用dismiss 会执行 doAfterDismissTask 也不会泄漏

**Comment by yansideyu76** [comment]
使用的是 PartShadowPopupView

**Comment by li-xiaojun** [comment]
这个问题我抽空解决下，直接destory确实不会调用doAfterDismissTask

**Comment by li-xiaojun** [comment]
@yansideyu76 
最新版本已经修复，直接destory也会释放了。
