### ISSUE TITLE
AttachPopupView背景为黑色时动画显示有问题

### ISSUE THREAD

**Issue by insomniastay** [li-xiaojun/XPopup#45]
用了AttachPopupView 把item背景设置为黑色,用默认的ScrollScaleAnimator动画加载会看到一个白色的背景先于黑色背景出现,用ScaleAlphaAnimator没有这个问题.,

**Comment by insomniastay** [comment]
..额.背景自定义的popview可以设置..

**Comment by insomniastay** [comment]
阴影度自定义的popupview可以修改,,

**Comment by li-xiaojun** [comment]
代码贴下我帮你看看

**Comment by insomniastay** [comment]
知道原因了,我看你底层用的是CardView做的父view,白色的是CardView.代码,你的demo中的用Attach的例子把里面的item背景色改成黑的就看到了,
...可以直接把类似BottomPopupView的父view改成protected吗,有些功能要改下父view的参数,还得再find一下

**Comment by li-xiaojun** [comment]
@insomniastay 
`1.4.2`已更新，将弹窗容器都设为protected，并移除默认的颜色。
