### ISSUE TITLE
引入后运行时报 Android dependency 'androidx.documentfile:documentfile' has different version for the compile (1.0.0-rc01) and runtime (1.0.0) classpath. 

### ISSUE THREAD

**Issue by 1159577995** [li-xiaojun/XPopup#451]
引入 implementation 'com.lxj:xpopup:1.9.0'  运行时报 Android dependency 'androidx.documentfile:documentfile' has different version for the compile (1.0.0-rc01) and runtime (1.0.0) classpath. You should manually set the same version via DependencyResolution

**Comment by li-xiaojun** [comment]
类库冲突而已，百度一下你就知道
