### ISSUE TITLE
pop框是模态类型的,会屏蔽其他事件

### ISSUE THREAD

**Issue by woshiluoyong** [li-xiaojun/XPopup#453]
目前发现一个问题,这个pop框是模态类型的,当显示成AttachPopupView依附于某个view时,结果把全部内容的事件都给拦截了,这就尴尬了,然后翻看源码,发现是在BasePopupView底部覆盖了onTouchEvent,然后直接返回了true,拦截了所有事件,
`@Override
    public boolean onTouchEvent(MotionEvent event) {
        // 如果自己接触到了点击，并且不在PopupContentView范围内点击，则进行判断是否是点击事件,如果是，则dismiss
        Rect rect = new Rect();
        getPopupContentView().getGlobalVisibleRect(rect);
        if (!XPopupUtils.isInRect(event.getX(), event.getY(), rect)) {
            switch (event.getAction()) {
                case MotionEvent.ACTION_DOWN:
                    x = event.getX();
                    y = event.getY();
                    break;
                case MotionEvent.ACTION_UP:
                    float dx = event.getX() - x;
                    float dy = event.getY() - y;
                    float distance = (float) Math.sqrt(Math.pow(dx, 2) + Math.pow(dy, 2));
                    if (distance < touchSlop && popupInfo.isDismissOnTouchOutside) {
                        dismiss();
                    }
                    x = 0;
                    y = 0;
                    break;
            }
        }
        return true;
    }`
因此目前我是在继承的AttachPopupView类里面覆盖了onTouchEvent,返回了false解决这个问题,
`override fun onTouchEvent(event: MotionEvent?): Boolean {
        return false
    }`
,理论上官方这个应该根据判断来返回true或false,望修复哈

**Comment by li-xiaojun** [comment]
弹窗的设计就算要拦截一层，系统的popupWindow，PopupMenu, Dialog都是如此，这是个特性，不是Bug。
基本上所有App的交互都是弹窗会拦截事件，以微信为例看看就知道了。
