### ISSUE TITLE
稍微大一点的图就直接Canvas: trying to draw too large(547553280bytes) bitmap.

### ISSUE THREAD

**Issue by Rayslone** [li-xiaojun/XPopup#454]

**Comment by Rayslone** [comment]
在使用ImageViewerPopupView的时候

**Comment by li-xiaojun** [comment]
那检测你加载图片的代码，弹窗本身不负责加载图片。这个和弹窗没有关系。
如果图片报错，你单独加载也会报错

**Comment by Rayslone** [comment]
> 那检测你加载图片的代码，弹窗本身不负责加载图片。这个和弹窗没有关系。
> 如果图片报错，你单独加载也会报错

是用ImageViewerPopupView就崩溃了

**Comment by Rayslone** [comment]
> 那检测你加载图片的代码，弹窗本身不负责加载图片。这个和弹窗没有关系。
> 如果图片报错，你单独加载也会报错

应该是override(Target.SIZE_ORIGINAL))导致，但是不用这个，直接交给Glide来，长图加载PhotoView又太模糊了

**Comment by li-xiaojun** [comment]
override(Target.SIZE_ORIGINAL)) 会导致增大内存占用，但一般不会爆内存。
正常应用里面加载的图片都是压缩过的图片，你的图片有没有压缩过？

**Comment by Rayslone** [comment]
> override(Target.SIZE_ORIGINAL)) 会导致增大内存占用，但一般不会爆内存。
> 正常应用里面加载的图片都是压缩过的图片，你的图片有没有压缩过？

你是说服务端压缩还是本地？本地加载网络图片没有压缩

**Comment by Rayslone** [comment]
> override(Target.SIZE_ORIGINAL)) 会导致增大内存占用，但一般不会爆内存。
> 正常应用里面加载的图片都是压缩过的图片，你的图片有没有压缩过？

服务端也没有压过

**Comment by Rayslone** [comment]
> override(Target.SIZE_ORIGINAL)) 会导致增大内存占用，但一般不会爆内存。
> 正常应用里面加载的图片都是压缩过的图片，你的图片有没有压缩过？

加载宽高比太大的长图相当尴尬，压缩了模糊，不压缩内存受不了

**Comment by yonglf** [comment]
> > override(Target.SIZE_ORIGINAL)) 会导致增大内存占用，但一般不会爆内存。
> > 正常应用里面加载的图片都是压缩过的图片，你的图片有没有压缩过？
> 
> 加载宽高比太大的长图相当尴尬，压缩了模糊，不压缩内存受不了

你好  请问你解决了吗

**Comment by li-xiaojun** [comment]
@Rayslone @yonglf wiki上更新了加载超长图片(超过100M)的代码，copy即可
