### ISSUE TITLE
有没有办法实现类似BottomSheetDialog的效果

### ISSUE THREAD

**Issue by JueShouGitHub** [li-xiaojun/XPopup#455]
BottomPopupView 高度出来基本上都是固定的了，只能下拉消失，能不能上滑的是时候沾满屏幕，下滑然后停在固定高度上，再下滑消失，就是BottomSheetDialog的效果

**Comment by li-xiaojun** [comment]
下个版本实现

**Comment by li-xiaojun** [comment]
2.0.3版本，开启`isThreeDrag(true)`可实现类型效果

**Comment by DuShuYuan** [comment]
isThreeDrag 能不能两级滑动  一种满屏 一种自己设置高度

**Comment by AlbertZyc** [comment]
isThreeDrag 能不能两级滑动 一种满屏 一种自己设置高度
