### ISSUE TITLE
华为 VCE AL00弹出后会立刻关闭

### ISSUE THREAD

**Issue by TianGuisen** [li-xiaojun/XPopup#456]
Android 10,level 29
华为 VCE AL00

'com.lxj:xpopup:1.9.0'
bug视频地址
https://nim.nosdn.127.net/MTY3NzcwMzU=/bmltYV8xOTE1Nzk2OTg5OF8xNTkyMDQ3MTMxMzAyXzk1MmM2YzU1LTZjNzEtNDQ5ZC05ZjZiLTE3OGRmNGQ5NDJhNQ==

代码:
class PlayLiveMoreDia(context: Context) : AttachPopupView(context) {
    override fun getImplLayoutId(): Int {
        return R.layout.dia_play_live_dia
    }

    override fun getPopupAnimator(): PopupAnimator? {
        return ScrollScaleAnimator(popupContentView, PopupAnimation.ScrollAlphaFromBottom)
    }

    override fun getPopupBackground(): Drawable {
        return getDrawable(R.drawable.ic_live_more_dilog)!!
    }
    var definitionLis: (() -> Unit)? = null
    var reportLis: (() -> Unit)? = null
    override fun onCreate() {
        super.onCreate()
        tv_definition_start_info.setSingClick {
            definitionLis?.invoke()
            dismiss()
        }
        tv_report.setSingClick {
            reportLis?.invoke()
            dismiss()
        }
    }
}

 XPopup.Builder(act)
                    .hasShadowBg(false)
                    .offsetX(-AutoSizeUtil.dp2px(2f))
                    .offsetY(-AutoSizeUtil.dp2px(8f))
                    .popupPosition(PopupPosition.Top)
                    .atView(iv_live_seting_more)
                    .asCustom(playLiveMoreDia)
                    .show()

**Comment by TianGuisen** [comment]
原来2.0改为dialog了，应该没这个bug了。

**Comment by li-xiaojun** [comment]
> 原来2.0改为dialog了，应该没这个bug了。

2.0解决你的问题没

**Comment by TianGuisen** [comment]
还有问题，但是现在是变成白色无内容，不会闪一下关闭

class LiveMoreDia(context: Context, var pking: Boolean, var pkPermission: Boolean) : AttachPopupView(context) {

    override fun getImplLayoutId(): Int {
        return R.layout.dia_live_more
    }

    override fun getPopupAnimator(): PopupAnimator? {
        return ScrollScaleAnimator(popupContentView, PopupAnimation.ScrollAlphaFromBottom)
    }}
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="55dp"
    android:layout_height="wrap_content"
    android:gravity="center_horizontal"
    android:orientation="vertical"
    android:background="@drawable/ic_live_more_dilog"
    android:paddingLeft="3dp"
    tools:context=".ui.live.anchor.dialog.LiveMoreDia">


    <TextView
        android:id="@+id/tv_other_info_start_live"
        android:layout_width="match_parent"
        android:layout_height="30dp"
        android:gravity="center"
        android:text="美颜"
        android:textColor="@color/black"
        android:textSize="11dp" />

    <View
        android:layout_width="match_parent"
        android:layout_height="1dp"
        android:background="@color/color_979797" />


    <TextView
        android:id="@+id/tv_decals"
        android:layout_width="match_parent"
        android:layout_height="30dp"
        android:gravity="center"
        android:text="贴纸"
        android:textColor="@color/black"
        android:textSize="11dp" />

    <View
        android:layout_width="match_parent"
        android:layout_height="1dp"
        android:background="@color/color_979797" />

    <TextView
        android:id="@+id/tv_pk"
        android:layout_width="match_parent"
        android:layout_height="30dp"
        android:gravity="center"
        android:text="连麦"
        android:visibility="gone"
        android:textColor="@color/black"
        android:textSize="11dp" />

    <View
        android:id="@+id/view_pk"
        android:visibility="gone"
        android:layout_width="match_parent"
        android:layout_height="1dp"
        android:background="@color/color_979797" />

    <TextView
        android:id="@+id/tv_definition_start_info"
        android:layout_width="match_parent"
        android:layout_height="30dp"
        android:layout_marginBottom="5dp"
        android:gravity="center"
        android:text="清晰度"
        android:textColor="@color/black"
        android:textSize="11dp" />
</LinearLayout>

**Comment by TianGuisen** [comment]
> 还有问题，但是现在是变成白色无内容，不会闪一下关闭
> 
> class LiveMoreDia(context: Context, var pking: Boolean, var pkPermission: Boolean) : AttachPopupView(context) {
> 
> ```
> override fun getImplLayoutId(): Int {
>     return R.layout.dia_live_more
> }
> 
> override fun getPopupAnimator(): PopupAnimator? {
>     return ScrollScaleAnimator(popupContentView, PopupAnimation.ScrollAlphaFromBottom)
> }}
> ```
> 
> ```
> <TextView
>     android:id="@+id/tv_other_info_start_live"
>     android:layout_width="match_parent"
>     android:layout_height="30dp"
>     android:gravity="center"
>     android:text="美颜"
>     android:textColor="@color/black"
>     android:textSize="11dp" />
> 
> <View
>     android:layout_width="match_parent"
>     android:layout_height="1dp"
>     android:background="@color/color_979797" />
> 
> 
> <TextView
>     android:id="@+id/tv_decals"
>     android:layout_width="match_parent"
>     android:layout_height="30dp"
>     android:gravity="center"
>     android:text="贴纸"
>     android:textColor="@color/black"
>     android:textSize="11dp" />
> 
> <View
>     android:layout_width="match_parent"
>     android:layout_height="1dp"
>     android:background="@color/color_979797" />
> 
> <TextView
>     android:id="@+id/tv_pk"
>     android:layout_width="match_parent"
>     android:layout_height="30dp"
>     android:gravity="center"
>     android:text="连麦"
>     android:visibility="gone"
>     android:textColor="@color/black"
>     android:textSize="11dp" />
> 
> <View
>     android:id="@+id/view_pk"
>     android:visibility="gone"
>     android:layout_width="match_parent"
>     android:layout_height="1dp"
>     android:background="@color/color_979797" />
> 
> <TextView
>     android:id="@+id/tv_definition_start_info"
>     android:layout_width="match_parent"
>     android:layout_height="30dp"
>     android:layout_marginBottom="5dp"
>     android:gravity="center"
>     android:text="清晰度"
>     android:textColor="@color/black"
>     android:textSize="11dp" />
> ```

**Comment by li-xiaojun** [comment]
加群发个视频看看
