### ISSUE TITLE
没有适配阿拉伯语

### ISSUE THREAD

**Issue by yyg20101** [li-xiaojun/XPopup#458]
切换阿拉伯语的环境下，使用atView，左右位置会不对，视图会跑到边框外
目前环境为AndroidX  sdk29 版本为最新的2.0.0
demo在阿拉伯语环境下也会出现这个问题
求更新支持rtl

**Comment by Moster1h** [comment]
的确，没有适配RTL是最大的缺点

**Comment by li-xiaojun** [comment]
@yyg20101  @Moster1h  
应群友要求，最新版本 2.0.7-rc2 已完美支持RTL布局。

**Comment by Moster1h** [comment]
我就是那个群友，RTL有一些小bug！

**Comment by zhuzhutai** [comment]
驻马店老乡...
