### ISSUE TITLE
Android10适配 保存预览图片失败

### ISSUE THREAD

**Issue by iGYry** [li-xiaojun/XPopup#460]
当把项目targetSdkVersion设为29+时：
查看大图，点击保存时，提示：没有保存权限，保存功能无法使用！
new XPopup.Builder(context).asImageViewer(imageView, imagePath, new XPopupImageLoader(){...}).show();

问题出在[XPopupUtils.java]第387行，[target.createNewFile();]创建文件失败，抛出异常。
[Android 10]中引入了[Scoped Storage]的概念，通过添加外部存储访问限制来实现更好的文件管理。

**Comment by li-xiaojun** [comment]
@iGYry 
我用android10试了，targetSdkVersion设置为30了，没有遇到问题。
加 783659607 qq群录个视频我给你看看
