### ISSUE TITLE
启动PermissionActivity引起程序闪退

### ISSUE THREAD

**Issue by wucan871952374** [li-xiaojun/XPopup#461]
android.content.ActivityNotFoundException

Unable to find explicit activity class {
/com.lxj.xpopup.util.XPermission$PermissionActivity}; have you declared this activity in your AndroidManifest.xml?

1 android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2118)
--
2 android.app.Instrumentation.execStartActivity(Instrumentation.java:1746)
3 android.app.Activity.startActivityForResult(Activity.java:5362)
4 androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
5 android.app.Activity.startActivityForResult(Activity.java:5303)
6 androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:662)
7 android.app.Activity.startActivity(Activity.java:5733)
8 android.app.Activity.startActivity(Activity.java:5701)
9 com.lxj.xpopup.util.XPermission$PermissionActivity.start(XPermission.java:388)
10 com.lxj.xpopup.util.XPermission.startPermissionActivity(XPermission.java:301)
11 com.lxj.xpopup.util.XPermission.request(XPermission.java:292)
12 com.lxj.xpopup.core.ImageViewerPopupView.save(ImageViewerPopupView.java:451)
13 com.lxj.xpopup.core.ImageViewerPopupView.onClick(ImageViewerPopupView.java:431)
14 android.view.View.performClick(View.java:7199)
15 android.view.View.performClickInternal(View.java:7173)
16 android.view.View.access$3500(View.java:824)
17 android.view.View$PerformClick.run(View.java:27623)
18 android.os.Handler.handleCallback(Handler.java:894)

**Comment by wucan871952374** [comment]
![RWF(AN$0R85JLP7G5X0VOES](https://user-images.githubusercontent.com/19754367/84849925-03dc5180-b089-11ea-8567-67ee72ee4844.png)

**Comment by li-xiaojun** [comment]
@wucan871952374  
加xpopup群交流把，这个太慢了
