### ISSUE TITLE
LeakCanary 内存泄漏

### ISSUE THREAD

**Issue by 13120241790** [li-xiaojun/XPopup#462]
LeakCanary 注释了 我把 LeakCanary 放开在 demo 上随便点了几下，发现有五个内存泄漏
大部分都是 stateLayout 造成的，希望作者在扩展功能的同时关注下内存泄漏的问题，祝国产开源越来越棒  👍

**Comment by li-xiaojun** [comment]
@13120241790 这个是demo的内存泄漏，XPopup本身应该是没有内存泄漏的，这个不用关系，你用到项目的时候是不会有的
