### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable.mutate()' on a null object reference

### ISSUE THREAD

**Issue by vi1zen** [li-xiaojun/XPopup#464]
if (!popupInfo.hasShadowBg) {
            //实现shadow
            Drawable newDrawable = getPopupImplView().getBackground().mutate().getConstantState().newDrawable();
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
                //优先使用implView的背景
                if (getPopupImplView().getBackground() != null) {
                    //复制一份
                    attachPopupContainer.setBackground(newDrawable);
                    getPopupImplView().setBackground(null);
                } else {
                    attachPopupContainer.setBackgroundColor(Color.WHITE);
                }
                attachPopupContainer.setElevation(XPopupUtils.dp2px(getContext(), 20));
            } else {
                //优先使用implView的背景
                if (getPopupImplView().getBackground() == null) {
                    defaultOffsetX -= bgDrawableMargin;
                    defaultOffsetY -= bgDrawableMargin;
                    attachPopupContainer.setBackgroundResource(R.drawable._xpopup_shadow);
                } else {
                    getPopupImplView().setBackground(null);
                    attachPopupContainer.setBackground(newDrawable);
                }
            }
        }
设置hasShadowBg= false时，getPopupImplView().getBackground()会报空指针异常，版本2.0.2
            Drawable newDrawable = getPopupImplView().getBackground().mutate().getConstantState().newDrawable();

**Comment by li-xiaojun** [comment]
2.0.3版本已修复
