### ISSUE TITLE
自定义AttachPopupView设置popupAnimation(PopupAnimation.TranslateFromLeft)后显示位置不正确

### ISSUE THREAD

**Issue by vi1zen** [li-xiaojun/XPopup#465]
**设置popupAnimation(PopupAnimation.TranslateFromLeft)后**
显示位置不正确，正常情况应该显示在目前view的下方，目前显示在屏幕的左上角

**Comment by li-xiaojun** [comment]
加群录个视频我看看

**Comment by vi1zen** [comment]
我看了下这个问题好像在模拟器上才会出现，用真机就不会
