### ISSUE TITLE
BottomPopupView 软键盘为题问题

### ISSUE THREAD

**Issue by JiayuanChan** [li-xiaojun/XPopup#466]
继承BottomPopupView 实现评论输入框，当去@页面选人后返回，软键盘未能弹出

**Comment by li-xiaojun** [comment]
加群发视频，描述太抽象

**Comment by li-xiaojun** [comment]
@JiayuanChan 加群了吗？

**Comment by luorou** [comment]
> 继承BottomPopupView 实现评论输入框，当去@页面选人后返回，软键盘未能弹出

在返回后调一下  
        editComment.setFocusable(true);
        editComment.setFocusableInTouchMode(true);
        editComment.requestFocus();

        editComment.getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
            @Override
            public void onGlobalLayout() {
                InputMethodManager imm = (InputMethodManager) view.getContext()
                        .getSystemService(Context.INPUT_METHOD_SERVICE);
                if (imm.showSoftInput(editComment, 0)) {
                    editComment.getViewTreeObserver().removeOnGlobalLayoutListener(this);
                }
            }
        });
这种  看看有没有用
