### ISSUE TITLE
可以做一版高斯模糊背景的弹窗吗

### ISSUE THREAD

**Issue by GeneralZMX** [li-xiaojun/XPopup#467]
如图  用了很多方式实现高思模糊背景  但是放入弹窗后都很突兀  效果不佳

**Comment by li-xiaojun** [comment]
你想要什么样的模糊，模糊有很多种，可以给个效果图吗，我考量一下

**Comment by GeneralZMX** [comment]
![毛玻璃](https://user-images.githubusercontent.com/39935739/85100454-c7e4f000-b232-11ea-9ef0-a0b219d4bd86.jpg)
这种

**Comment by li-xiaojun** [comment]
更新到最新版本，设置hasBlurBg(true)即可享有模糊背景
