### ISSUE TITLE
gradle加上这个库后，com.google.android.material.chip.Chip使用的地方报异常

### ISSUE THREAD

**Issue by shoushuai** [li-xiaojun/XPopup#469]
本来chip用的好好，刚发现加上这个库就闪退了，报

android.view.InflateException:Binary XML file line #9 in com.ruanmei.ithome:layout/list_item_keyword_view: Binary XML file line #9 in com.ruanmei.ithome:layout/list_item_keyword_view: Error inflating class com.google.android.material.chip.Chip
--
2 ......
3 Caused by:
4 java.lang.IllegalArgumentException:The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).
5 com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:243)
6 com.google.android.material.internal.ThemeEnforcement.checkMaterialTheme(ThemeEnforcement.java:217)

上网查后给chip加上android:theme="@style/Theme.MaterialComponents"就好了，就是点击效果变了。

看了源码gradle，发现material:1.3.0-alpha01，而我的是1.0.0，所以才这样。

**Comment by li-xiaojun** [comment]
你可以配置gradle只使用你的版本

**Comment by shoushuai** [comment]
@li-xiaojun 谢谢
