### ISSUE TITLE
大佬，可以让弹窗依附在软键盘上面吗？

### ISSUE THREAD

**Issue by yangpotato** [li-xiaojun/XPopup#47]

**Comment by li-xiaojun** [comment]
@yangpotato 
当弹窗内含有输入法时会默认依附在软键盘上面，就是弹窗的底边贴这软键盘。我内部实现了智能的移动，不论是Center类型的弹窗还是Bottom类型的弹窗都有这样的行为。

**Comment by yangpotato** [comment]
@li-xiaojun 
发现几个问题 
1.弹窗显示在软键盘上方时切换首页   再次返回时软键盘会遮挡住弹窗
2.弹窗和软键盘之间有一个明显的空隙

**Comment by li-xiaojun** [comment]
@yangpotato 
可以加我QQ：16167479，录制个简单的小视频发给我，帮你看看。

**Comment by yixi195** [comment]
https://github.com/li-xiaojun/XPopup/issues/47#issuecomment-467274128
可以设置底边不贴软键盘吗？ 就是软键盘跟着 EditText 下面就可以了，不用整个弹窗
