### ISSUE TITLE
关于局部阴影点击事件的响应

### ISSUE THREAD

**Issue by zaceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee** [li-xiaojun/XPopup#476]
之前局部阴影，弹出之后，非阴影部分的按钮可以正常响应点击事件，也就是说点击非阴影部分，弹出框小时，同时那个地方的按钮响应点击事件，现在是必须弹出框消失之后，再点击按钮，才能响应点击事件，这个有设置的地方吗？

**Comment by li-xiaojun** [comment]
更新到2.0.5版本，就支持点击透传了
