### ISSUE TITLE
在小米手机上，全面屏的情况下，底部会留出一段空隙。

### ISSUE THREAD

**Issue by daitao996565239** [li-xiaojun/XPopup#482]
我的手机是Android9.0，红米note8pro.还是跑的xpop2.0的demo的情况下

**Comment by li-xiaojun** [comment]
这个估计是MIUI的兼容问题，用系统全屏对话框应该也会有这个问题，我抽时间看看怎么兼容下

**Comment by FerrandTian** [comment]
我用的是AndroidX，所以只能用com.lxj:xpopup:1.8.9-x版。在小米9上底部同样出现白边，用其他版本会报错。

com.lxj:xpopup:2.0.8版报错如下：
`Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.view.View.getLayoutParams()' on a null object reference
        at com.lxj.xpopup.impl.PartShadowPopupView.doAttach(PartShadowPopupView.java:80)`

**Comment by li-xiaojun** [comment]
> 我用的是AndroidX，用com.lxj:xpopup:1.8.9-x版。在小米9上底部同样出现白边，用其他版本会报错。
> 
> com.lxj:xpopup:2.0.8版报错如下：（在show()之前调用doAttach()）（同时在我自定义的布局的上边会多一条白边）
> `Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.view.View.getLayoutParams()' on a null object reference at com.lxj.xpopup.impl.PartShadowPopupView.doAttach(PartShadowPopupView.java:80)`

2.0之后都是androidx，报这个错误，能否贴下你弹窗的代码

**Comment by FerrandTian** [comment]
public class SingleChoicePopupView extends PartShadowPopupView {

    private RecyclerView recyclerView;
    private SingleChoiceAdapter adapter = new SingleChoiceAdapter(this);

    public SingleChoicePopupView(@NonNull Context context, OnSelectChangeListener<SingleChoiceAdapter.ViewHolder> listener, List<String> items) {
        super(context);
        adapter.setItems(items, 0);
        adapter.setOnSelectChangeListener(listener);
    }

    public void show(int selectedPosition) {
        adapter.setSelectedPosition(selectedPosition);
        doAttach();
        super.show();
    }

    @Override
    protected int getImplLayoutId() {
        return R.layout.list_wrap;
    }

    @Override
    protected void onCreate() {
        super.onCreate();
        recyclerView = findViewById(R.id.list);
        recyclerView.setBackgroundResource(R.color.background);
        recyclerView.setAdapter(adapter);
    }
}

我重写了show()，就是调这里会出错；
另外，我去掉onAttach()就不会出错，但是布局上边多了一条白边。
![微信图片_20200720185355](https://user-images.githubusercontent.com/11403598/87930340-77271800-caba-11ea-95e8-349f0b58db6d.jpg)

**Comment by li-xiaojun** [comment]
加QQ群交流把

**Comment by FerrandTian** [comment]
> 加QQ群交流把

OK

**Comment by woshiluoyong** [comment]
作者最新版本2.0.8-rc5已经修改这个问题了,感谢
