### ISSUE TITLE
全屏的 Activity 使用 XPopup 的全屏弹窗会显示导航栏

### ISSUE THREAD

**Issue by timmy-gzw** [li-xiaojun/XPopup#484]
有一个全屏视频 Activity, show 某个全屏自定义弹窗会导致导航栏自动显示出来, 状态栏是继续隐藏的, 有没有什么方法能够显示弹窗同时导航栏不显示呢?

**Comment by li-xiaojun** [comment]
把你Activity隐藏导航栏的代码发下

**Comment by li-xiaojun** [comment]
更新到2.0.6-rc4，设置hasNavigationbar(false)即可
