### ISSUE TITLE
使用vivo手机打开对话框，上方通知栏没有阴影覆盖

### ISSUE THREAD

**Issue by chenyaocheng** [li-xiaojun/XPopup#488]
[使用vivo手机打开对话框，上方通知栏没有阴影覆盖。打开局部阴影模块的对话框，对话框打开位置不对

![S2SK8Q%X%EEJWQQIIP9S3GI](https://user-images.githubusercontent.com/16594972/86891968-329e9280-c132-11ea-9cb9-1b83ae789bfe.png)
![SCXQ70JPP(L7LRRR Z(R{7](https://user-images.githubusercontent.com/16594972/86891983-392d0a00-c132-11ea-8702-31e710506553.png)
![7E190F2551C85AD15EDB750CA79DF088](https://user-images.githubusercontent.com/16594972/86891993-3b8f6400-c132-11ea-8e7a-9a23a0173f4b.jpg)
![631D4F1F8E23BBEE52834F51D8549DF8](https://user-images.githubusercontent.com/16594972/86892001-3df1be00-c132-11ea-98fd-573a872ea62d.jpg)

**Comment by li-xiaojun** [comment]
我用了该机型，无法复现

**Comment by chenyaocheng** [comment]
我这是能一直复现的，demo和集成到项目里的都会这样。我这边排查的话要怎样排查？

**Comment by ZHOUJJIN** [comment]
我这里的vivo手机 也是同样的问题 上方通知栏没有阴影覆盖

**Comment by Duanyinyin504** [comment]
vivo手机状态栏没有阴影覆盖，全屏弹窗有输入框时，会出现键盘遮盖输入框的问题。

**Comment by ZHOUJJIN** [comment]
> 我这是能一直复现的，demo和集成到项目里的都会这样。我这边排查的话要怎样排查？



> 我用了该机型，无法复现

FullScreenDialog 加上 Window window = getWindow();
        View decorView = window.getDecorView();
        //设置window背景，默认的背景会有Padding值，不能全屏。当然不一定要是透明，你可以设置其他背景，替换默认的背景即可。
        window.setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));

        //两个 flag 要结合使用，表示让应用的主体内容占用系统状态栏的空间
        int option = View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN | View.SYSTEM_UI_FLAG_LAYOUT_STABLE;
        decorView.setSystemUiVisibility(option);
        window.addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS);
        window.setStatusBarColor(Color.TRANSPARENT);
        //设置导航栏颜
        window.setNavigationBarColor(Color.TRANSPARENT);
        //内容扩展到导航栏
        window.setType(WindowManager.LayoutParams.TYPE_APPLICATION_PANEL);
就可以了

**Comment by ZHOUJJIN** [comment]
FullScreenDialog 加上 
 Window window = getWindow();
        View decorView = window.getDecorView();
        //设置window背景，默认的背景会有Padding值，不能全屏。当然不一定要是透明，你可以设置其他背景，替换默认的背景即可。
        window.setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));

        //两个 flag 要结合使用，表示让应用的主体内容占用系统状态栏的空间
        int option = View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN | View.SYSTEM_UI_FLAG_LAYOUT_STABLE;
        decorView.setSystemUiVisibility(option);
        window.addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS);
        window.setStatusBarColor(Color.TRANSPARENT);
        //设置导航栏颜
        window.setNavigationBarColor(Color.TRANSPARENT);
        //内容扩展到导航栏
        window.setType(WindowManager.LayoutParams.TYPE_APPLICATION_PANEL);

**Comment by li-xiaojun** [comment]
@Duanyinyin504  @chenyaocheng  @ZHOUJJIN 
更新到2.0.7-rc8试试，我不确定有没有修复，因为我没有这块手机，而且用云真机测试是没问题的

**Comment by li-xiaojun** [comment]
@Duanyinyin504 @chenyaocheng @ZHOUJJIN 
更新到2.1.0版本，此问题已修复。
