### ISSUE TITLE
使用自定义局部阴影时的一个小问题, CustomPartShadowPopupView

### ISSUE THREAD

**Issue by Joehaivo** [li-xiaojun/XPopup#489]
今天看到这个库, 感觉很强大, 遂引入试验一下, 目前发现一点问题, 请作者大大帮忙看看
 
![微信图片_20200709105758](https://user-images.githubusercontent.com/12687795/86992161-785f6780-c1d3-11ea-8f70-e1b116d8aad9.jpg)

![微信图片_20200709105805](https://user-images.githubusercontent.com/12687795/86992169-7d241b80-c1d3-11ea-8821-e12bc0558cd1.jpg)

图一是未点击"筛选"前, 图二是点击筛选后, 代码采用了继承PartShadowPopupView的方式, 显示时采用.offsetY(20), 会发现底下的阴影部分没有跟着下移

非常感谢, 期待作者的回复

**Comment by Joehaivo** [comment]
我找到方法了 在oncreate()里加入popupContentView.translationY = 20f即可,

**Comment by li-xiaojun** [comment]
算是一个小Bug，稍后修复下

**Comment by li-xiaojun** [comment]
> 我找到方法了 在oncreate()里加入popupContentView.translationY = 20f即可,

你是不是想在灰色背景那个View下方显示，如果是的话，可以直接传灰色背景的View，就无需设置偏移了

**Comment by Joehaivo** [comment]
我的意思是设置偏移时，应该让implView和contentView同时移动，不然头部的阴影就漏出来了

**Comment by li-xiaojun** [comment]
> 我的意思是设置偏移时，应该让implView和contentView同时移动，不然头部的阴影就漏出来了

明白，这个我修复下

**Comment by xiaojigugu** [comment]
![image](https://user-images.githubusercontent.com/39613470/125021003-66492b00-e0ac-11eb-849b-3d290a042469.png)
![image](https://user-images.githubusercontent.com/39613470/125021036-76610a80-e0ac-11eb-935b-415343d63728.png)
您好，请问这个问题解决了吗，用的2.4.3的版本
