### ISSUE TITLE
最新的版本号是多少

### ISSUE THREAD

**Issue by yunfanasd** [li-xiaojun/XPopup#49]
每次更新能不能把read me中引用改一下就行了，为啥每次让我们自己找版本号
implementation 'com.lxj:xpopup:latest release'   加载不了
用github的库第一次因为这个提issues

**Comment by yunfanasd** [comment]
implementation 'com.lxj:xpopup:1.41'这个加载也不行呀

**Comment by li-xiaojun** [comment]
![image](https://user-images.githubusercontent.com/4426715/53456593-f05b4080-3a69-11e9-8d63-e14de4bfb2a3.png)

**Comment by li-xiaojun** [comment]
@yunfanasd 
建议已采纳

**Comment by yunfanasd** [comment]
![image](https://user-images.githubusercontent.com/46099753/53462070-77fe7a80-3a7d-11e9-9d56-152d53fb34c0.png)   总是加载不了你的库

**Comment by li-xiaojun** [comment]
版本号是1.4.2啊，不是1.41

**Comment by li-xiaojun** [comment]
@yunfanasd 
你看下最新版本是多少啊，是1.4.2

**Comment by yunfanasd** [comment]
1.4.2的版本compileSdkVersion必须是28吗？

**Comment by li-xiaojun** [comment]
@yunfanasd 
是的，尽量更新最新SDK。

**Comment by yunfanasd** [comment]
之前是27 升级到28 之后提示 Cannot access android.support.v4.app.BaseFragmentActivityApi16  
![image](https://user-images.githubusercontent.com/46099753/53476421-52896500-3aad-11e9-8f28-4a4aea331580.png)  很多地方都出现了，但是不影响编译，有遇到过吗？
这个库可以降低一些sdk 的要求吗，比如你用到了28中自带的样式啥的你可以自己写，这样我们就不用升级sdk了，很多老项目升级一下要修改的东西太多了

**Comment by li-xiaojun** [comment]
@yunfanasd 
我会在下个版本降低一下。

**Comment by yunfanasd** [comment]
我升级到28 ,没啥问题，但是导入你的库就会出现Cannot access android.support.v4.app.BaseFragmentActivityApi16，尴尬

**Comment by li-xiaojun** [comment]
@yunfanasd 
很显然这个类在28更改了访问权限，你们build.gradle是不是指定support-v4的版本了？

**Comment by yunfanasd** [comment]
没有指定v4,我看到zhi之前的issues中有一个v4不兼容的，我是用他最后提供的exclude 也不管用

**Comment by yunfanasd** [comment]
更改了访问权限这个没有懂什么意思？有什么解决方案吗

**Comment by li-xiaojun** [comment]
@yunfanasd 

最新的1.4.3版本已将complieSdkVersion降低到26，请更新试试。
