### ISSUE TITLE
点击事件异常

### ISSUE THREAD

**Issue by hply** [li-xiaojun/XPopup#496]
demo中，【图片浏览】在4.4机型上点击图片无响应；com.lxj.xpopup.util.XPopupUtils#context2Activity方法逻辑有问题，建议使用官方appCompat包里一个通过View获取Activity事例方法(androidx.appcompat.widget.TooltipPopup#getAppRootView);
Context context = anchorView.getContext();
        while (context instanceof ContextWrapper) {
            if (context instanceof Activity) {
                return ((Activity) context);
            } else {
                context = ((ContextWrapper) context).getBaseContext();
            }
        }

**Comment by li-xiaojun** [comment]
更新到2.0.7-rc8即可

**Comment by li-xiaojun** [comment]
> demo中，【图片浏览】在4.4机型上点击图片无响应；com.lxj.xpopup.util.XPopupUtils#context2Activity方法逻辑有问题，建议使用官方appCompat包里一个通过View获取Activity事例方法(androidx.appcompat.widget.TooltipPopup#getAppRootView);
> Context context = anchorView.getContext();
> while (context instanceof ContextWrapper) {
> if (context instanceof Activity) {
> return ((Activity) context);
> } else {
> context = ((ContextWrapper) context).getBaseContext();
> }
> }

另外多谢你提供的代码！
