### ISSUE TITLE
CenterListPopupView内存泄漏

### ISSUE THREAD

**Issue by JackZ-2019** [li-xiaojun/XPopup#497]

**Comment by JackZ-2019** [comment]
if (classifyPopup == null) {
            classifyPopup = new XPopup.Builder(getContext())
                    .asCenterList(getContext().getString(R.string.please_select_linen_type),
                            classifyArray,
                            (i, text) -> {
                        //do nothing
                            });
        }
        if (classifyPopup != null)
            classifyPopup.show();

经过测试发现，只要设置了OnSelectListener，即使不选中也会内存泄漏。
设置为null时不会

**Comment by JackZ-2019** [comment]
ConfirmPopupView设置listener后也有内存泄漏的问题。

**Comment by li-xiaojun** [comment]
看文档，有关于内存泄漏的说明和解决方案
