### ISSUE TITLE
弹出窗口的半透明背景会遮盖底部虚拟导航栏，可以解决这个吗？

### ISSUE THREAD

**Issue by zaaach** [li-xiaojun/XPopup#50]

**Comment by li-xiaojun** [comment]
可以截图图，并附上机型和系统版本吗

**Comment by zaaach** [comment]
![_20190227113707](https://user-images.githubusercontent.com/9695127/53464181-4b9a2c80-3a84-11e9-90ea-95f5214cea54.jpg)
三星Galaxy A9
系统版本：8.0

**Comment by zaaach** [comment]
底部虚拟导航栏本来是白色的，被遮挡了，但是可以按

**Comment by li-xiaojun** [comment]
嗯，属于系统适配问题，我抽空解决下。

**Comment by li-xiaojun** [comment]
@zaaach 

最新的`1.4.3`版本已修复该问题，请更新试试。

**Comment by zaaach** [comment]
感谢，的确修复了
