### ISSUE TITLE
 kotlin.TypeCastException: null cannot be cast to non-null type T

### ISSUE THREAD

**Issue by qq171161636** [li-xiaojun/XPopup#500]
用的内置弹窗
      new XPopup.Builder(MerchantPicActivity.this)
                        .asBottomList("选择", new String[]{"1111", "2222", "3333"}, null, -1, false, new OnSelectListener() {
                            @Override
                            public void onSelect(int position, String text) {

                            }
                        },R.layout.testry,R.layout.test)
                        .show();

tsetry布局
--------------------------------------------------------------
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <com.lxj.xpopup.widget.VerticalRecyclerView
        android:id="@+id/recyclerView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"></com.lxj.xpopup.widget.VerticalRecyclerView>
</LinearLayout>
-----------------------------------------------
tset布局
---------------------------------------------------------
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <ImageView
        android:id="@+id/iv_image"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content" />

    <TextView
        android:id="@+id/tv_text"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center_horizontal"
        android:text="1111"
        android:textColor="#ff12" />
</LinearLayout>
------------------------------------------------------------------------
    kotlin.TypeCastException: null cannot be cast to non-null type T
        at com.lxj.easyadapter.ViewHolder.getView(ViewHolder.kt:21)
        at com.lxj.xpopup.impl.BottomListPopupView$1.bind(BottomListPopupView.java:88)
        at com.lxj.xpopup.impl.BottomListPopupView$1.bind(BottomListPopupView.java:68)

**Comment by SheepYang1993** [comment]
我刚好也遇到这个问题，需要在布局里面加一个id=xpopup_divider的view

**Comment by li-xiaojun** [comment]
@qq171161636  @SheepYang1993 
这个是bug，更新到2.0.8-rc4即可
