### ISSUE TITLE
2.0.8升级后底部弹出弹框被底部导航栏遮盖

### ISSUE THREAD

**Issue by startfromandroid** [li-xiaojun/XPopup#504]

**Comment by li-xiaojun** [comment]
加群发视频我帮你看看

**Comment by object1984** [comment]
我也遇到了

**Comment by loveppp** [comment]
遇到 +1

**Comment by kaedeno1** [comment]
同样问题

**Comment by onion2333** [comment]
我也遇到了

**Comment by DuJieJerry** [comment]
同样问题+1

**Comment by 50kg** [comment]
同样问题+1，虚拟状态栏会挡住asBottomList

**Comment by amber-yi** [comment]
目前暂时使用了 
val h=DensityUtil.getNavigationBarHeight(this)
XPopup.Builder(this@UserInfoActivity).offsetY(-h).XXX
解决了这个问题

**Comment by ousq** [comment]
> 目前暂时使用了
> val h = DensityUtil.getNavigationBarHeight（this）
> XPopup.Builder（this @ UserInfoActivity）.offsetY（-h）.XXX
> 解决了这个问题

如果这样设置的话 没有导航栏的    也是 提上去了

**Comment by fc-dream** [comment]
+1

**Comment by yansideyu76** [comment]
+1

**Comment by tomloveyou** [comment]
同样问题+1

**Comment by songchuanyang** [comment]
+1 带键盘弹出

**Comment by songchuanyang** [comment]
2.0.8-rc5解决了这个问题

**Comment by li-xiaojun** [comment]
2.0.9以上的版本都解决这个问题
