### ISSUE TITLE
在vivo手机上弹窗位置有偏移

### ISSUE THREAD

**Issue by love999** [li-xiaojun/XPopup#508]
![Screenshot_20200728_090637](https://user-images.githubusercontent.com/3806410/88607661-5a8a7180-d0b2-11ea-96a5-8e673a8725b6.jpg)
![Screenshot_20200728_090657](https://user-images.githubusercontent.com/3806410/88607664-5ceccb80-d0b2-11ea-80b0-42bca7035808.jpg)
![Screenshot_20200728_090707](https://user-images.githubusercontent.com/3806410/88607669-5eb68f00-d0b2-11ea-8070-8e3178f34aa1.jpg)

demo也有一样的问题
使用PartShadowPopupView， AttachPopupView，在Y轴上会下移，感觉是一个状态栏的高度。在测试的vivo手机上有这个问题，在我手机上是正常的。

**Comment by ZaneSummer** [comment]
vivo手机遇到了同样的问题，这个怎么解

**Comment by love999** [comment]
换了个库。。另一个库没问题

**Comment by xuexirong** [comment]
@love999 请问你换的哪个库

**Comment by love999** [comment]
> @love999 请问你换的哪个库


    implementation 'com.github.razerdp:BasePopup:2.2.4.1'

**Comment by li-xiaojun** [comment]
@love999 @ZaneSummer @xuexirong 
更新到2.1.0版本，此问题已修复。
