### ISSUE TITLE
无法修改confirmTextview的字体颜色

### ISSUE THREAD

**Issue by xiaxinqing** [li-xiaojun/XPopup#509]

**Comment by 805058027** [comment]
这个问题解决了没有？  只能使用自定义的布局解决么？

**Comment by li-xiaojun** [comment]
在onCreated或者onShow回调中设置即可。

**Comment by 805058027** [comment]
> 在onCreated或者onShow回调中设置即可。

回调的方法叫什么，能不能给一下代码段，我在onShow之前设置popupView.getConfirmTextView().setTextColor(Color.RED);无效

**Comment by li-xiaojun** [comment]
> > 在onCreated或者onShow回调中设置即可。
> 
> 回调的方法叫什么，能不能给一下代码段，我在onShow之前设置popupView.getConfirmTextView().setTextColor(Color.RED);无效

![image](https://user-images.githubusercontent.com/4426715/92920793-75982180-f465-11ea-93ee-17cad8a321c7.png)

**Comment by li-xiaojun** [comment]
另外更新到2.0.11版本
