### ISSUE TITLE
返回按键bug

### ISSUE THREAD

**Issue by dawnhope** [li-xiaojun/XPopup#510]
展示一个popup后，点击dismiss后立马打开另外一个popup，这时点击返回按键会直接返回上一页

**Comment by onlylin** [comment]
遇到相同的问题

**Comment by dawnhope** [comment]
> 遇到相同的问题

具体也没看啥问题，暂时处理可以在展示第二个popup的时候延时200毫秒就可以，等作者回复吧

**Comment by li-xiaojun** [comment]
哪个版本的xpopup
