### ISSUE TITLE
decorView方式添加弹窗

### ISSUE THREAD

**Issue by liukai2530533** [li-xiaojun/XPopup#515]
以前的版本我添加方法setDecorView ,可以把弹窗添加到自定义的ViewGroup中，而不是默认的Window的DecorView.。但是现在升级2.0之后默认是自定义的FullScreenDialog方式实现的，添加到这个Dialog中我设置的自己的ViewGroup就无效了，我改如何添加到自定义位置的ViewGrou中呢？

**Comment by li-xiaojun** [comment]
这个目前做不到
