### ISSUE TITLE
重写getAnimationDuration后导致的问题

### ISSUE THREAD

**Issue by JackZ-2019** [li-xiaojun/XPopup#517]
例如：
 @Override
    public int getAnimationDuration() {
        return 80;
    }
使用场景是全屏弹窗，动画是：PopupAnimation.TranslateFromBottom。 关闭弹窗时弹窗会在屏幕中间停留一刻再关闭。时间设置的越短越明显

**Comment by li-xiaojun** [comment]
不要去修改这个动画时间，你可以全局设置动画时间
