### ISSUE TITLE
自定义popup view 找不到 子控件的问题

### ISSUE THREAD

**Issue by hustlemickey** [li-xiaojun/XPopup#52]
代码如下

`class SearchPopup @JvmOverloads constructor(
        context: Context, attrs: AttributeSet? = null, defStyleAttr: Int = 0
) : AttachPopupView(context, attrs, defStyleAttr) {

    override fun getImplLayoutId(): Int {
        return R.layout.search_result
    }

    override fun initPopupContent() {
        super.initPopupContent()
        val rvSearchResult = findViewById<RecyclerView>(R.id.rvSearchResult)
        rvSearchResult.layoutManager = LinearLayoutManager(context)
        val list = arrayListOf<SearchItemDC>()
        
        val adapter = SearchResultAdapter(list)
        adapter.bindToRecyclerView(rvSearchResult)
    }
}`

运行后异常，提示 rvSearchResult  为 null

**Comment by hustlemickey** [comment]
已找到问题，基类AttachPopupView构造参数只有一个构造参数有实现

**Comment by li-xiaojun** [comment]
@hustlemickey 
自定义弹窗，只需实现一个参数的构造。
