### ISSUE TITLE
kotlin.TypeCastException: null cannot be cast to non-null type T

### ISSUE THREAD

**Issue by jiqianwen** [li-xiaojun/XPopup#520]
new XPopup.Builder(getContext())
                        .hasShadowBg(false)
                        .isCenterHorizontal(true)
                        .popupPosition(PopupPosition.Bottom)
                        .atView(v)
                        .asAttachList(new String[]{"全部", "获取", "使用"}, null, new OnSelectListener() {
                                    @Override
                                    public void onSelect(int position, String text) {

                                    }
                                }, R.layout.dialog_select_coin_details_type,
                                R.layout.item_coin_details_type)
                        .show();

<?xml version="1.0" encoding="utf-8"?>
<com.charity.supports.view.XRecyclerView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/recyclerView"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    app:bl_corners_radius="@dimen/dp_5"
    app:bl_solid_color="@color/white" />

<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="@dimen/dp_20">

    <ImageView
        android:id="@+id/iv_image"
        android:layout_width="@dimen/dp_10"
        android:layout_height="@dimen/dp_10"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <TextView
        android:id="@+id/tv_text"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:paddingStart="@dimen/dp_10"
        android:paddingEnd="@dimen/dp_10"
        android:text="全部"
        android:textColor="@color/c_8f9496"
        android:textSize="@dimen/sp_10"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

</androidx.constraintlayout.widget.ConstraintLayout>

**Comment by li-xiaojun** [comment]
不用怀疑，看看是不是传的atView(v)中的v是null？
