### ISSUE TITLE
navigation架构的只有一个activity 其他都是fragment ，怎么防止内存泄漏

### ISSUE THREAD

**Issue by sy5251** [li-xiaojun/XPopup#521]
我使用navigationg的方案，全局就一个mainactivity其他都是fragment ，怎么绑定fragment的生命周期，现在内存泄漏很严重

**Comment by li-xiaojun** [comment]
尽量不要复用弹窗，弹窗只使用一次，并且设置isDestroyOnDismiss(true)

**Comment by sy5251** [comment]
好的谢谢
