### ISSUE TITLE
自定义BottomPopupView 布局内有ViewPager时 findViewById报错

### ISSUE THREAD

**Issue by tinsan** [li-xiaojun/XPopup#525]
No view found for id 0x7f09000c (com.xx.xx:id/pager) for fragment CommonWordFragment{e78623}

在自定义的BottomPopupView 中 当布局内有ViewPager时，findViewById找不到控件

**2.0.0版本之上有这个问题，老版本没有此问题 我当前用的版本是2.0.8报此异常**

![image](https://user-images.githubusercontent.com/9840930/90641965-64903200-e264-11ea-80c3-bd7b6b95d812.png)

**Comment by xueweipeng** [comment]
可以使用静态布局，复写fragment的onInflate即可

**Comment by li-xiaojun** [comment]
这个错误是Android的限制，Dialog中是无法使用Fragment的。

**Comment by YangShaoXiong** [comment]
可以设置isViewMode(true)，让Xpopup的默认实现为View，就可以愉快的在Xpopup中使用ViewPager+Fragment了
