### ISSUE TITLE
dialog消失时  onShow 也会执行？？？

### ISSUE THREAD

**Issue by DuShuYuan** [li-xiaojun/XPopup#526]
如题，弹窗展示时执行一次，消失时还会执行一次
方法名叫onShow  不是应该只在展示时执行吗？

**Comment by xichunjie** [comment]
我也发现了，按返回键和调用dismis，消失时不会调用，点击屏幕消失时onShow会再次调用

**Comment by xichunjie** [comment]
是继承BottomPopupView的底部弹窗，

**Comment by li-xiaojun** [comment]
哪个版本？

**Comment by xichunjie** [comment]
'com.lxj:xpopup:2.0.8-rc5'版本，大佬

**Comment by li-xiaojun** [comment]
更新到最新版本 2.0.11即可
