### ISSUE TITLE
小米最新系统12.0.1稳定版，新增navigationBar，弹窗阴影不适配

### ISSUE THREAD

**Issue by Tell-me502** [li-xiaojun/XPopup#528]
![image](https://user-images.githubusercontent.com/25097200/91032914-35e3d400-e635-11ea-93c9-660e287b923f.png)

当弹窗弹出时，阴影部分不会覆盖下面的navigationBar，会留出一个白色区域。求救大佬有适配的方式吗？

**Comment by yangqb** [comment]
我也遇到了，怎么解决

**Comment by Tell-me502** [comment]
还没解决

**Comment by li-xiaojun** [comment]
这个区域是无法覆盖的，你的Activity都无法伸展到这个区域，这个是正常的。
