### ISSUE TITLE
在弹窗显示的时候怎么设置不影响没有弹窗View 的 手势

### ISSUE THREAD

**Issue by liyunfu** [li-xiaojun/XPopup#529]
比如屏幕下方弹出占了一半屏幕的弹窗, 在不关闭弹窗的情况下, 现在怎么让上半部分仍然响应原来的手势,如点击等

**Comment by li-xiaojun** [comment]
目前可以设置isClickThrough(true)，但是只对局部阴影弹窗有效。
其他弹窗不支持这个特性，如果支持的话会出现很大的问题。

**Comment by foxcode7** [comment]
请问现在这个问题解决了吗？
我看2.0.8版本就说全面支持了isClickThrough属性。
但是目前最新的2.5.8版本里，我在demo里设置了该属性后，依然不能透传手势
![image](https://user-images.githubusercontent.com/7324556/128627981-667d809a-4c31-48d2-87e2-4caa2b6d205f.png)

**Comment by foxcode7** [comment]
@li-xiaojun 辛苦大佬确认下

**Comment by foxcode7** [comment]
忽略我，没注意到注释内容
![image](https://user-images.githubusercontent.com/7324556/128628146-705d48bb-2e1d-4c5d-939f-41623e192113.png)
