### ISSUE TITLE
2.0.3后面的版本 都会出现弹框下移问题 

### ISSUE THREAD

**Issue by xuexirong** [li-xiaojun/XPopup#533]
比如底部弹框高度50dp  可能只显示了30dp。我估计是少了一个标题栏的高度。我的是华为手机

**Comment by ZQ173** [comment]
+1，还真是啊，上来看了楼上兄弟的反馈，改为 2.0.3 版本后，华为 nova 2s AL00 安卓 9.0 弹窗底部就正常不会被裁剪了

**Comment by songchuanyang** [comment]
2.0.8 也被吃掉了一块 底部弹出带键盘弹出

**Comment by tenda2014** [comment]
就是啊2.0.8也是这样，怎么解决啊？

**Comment by xuexirong** [comment]
@tenda2014 改成2.0.3版本  或者换个库吧，我现在是退回了2.0.3

**Comment by li-xiaojun** [comment]
2.0.9以上的版本解决这个问题
