### ISSUE TITLE
在某些手机上浏览超长图片提示Bitmap too large to be uploaded into a texture

### ISSUE THREAD

**Issue by zhuhuan0122** [li-xiaojun/XPopup#535]
运行XPopup V2.0.8 Demo
在小米5C（android7.1.2，MIUI11.0.3）和OPPO  R9sk（android6.0.1，ColorOS V3.0）手机上，浏览超长图片时不显示图片，并提示以下warn：
com.lxj.xpopupdemo W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (440x8507, max=8192x8192)。

在Redmi K20 Pro（android10，MIUI 12.0.3）手机上没有问题。

烦请大佬看看啊。

**Comment by li-xiaojun** [comment]
考虑压缩图片，这个是Glide的问题，非XPopup所能解决
