### ISSUE TITLE
继承CenterPopupView自定义的Dialog，设置布局的圆角无效

### ISSUE THREAD

**Issue by LG12300** [li-xiaojun/XPopup#536]
版本2.0.7
![image](https://user-images.githubusercontent.com/49315781/91789044-54069100-ec40-11ea-89bd-2ce37fbd3155.png)
![image](https://user-images.githubusercontent.com/49315781/91789083-700a3280-ec40-11ea-81e5-94dc398d975a.png)
布局预览的时候还是有圆角的
![image](https://user-images.githubusercontent.com/49315781/91789164-a0ea6780-ec40-11ea-9de8-831c7b2a47ed.png)

**Comment by li-xiaojun** [comment]
这个不能把，demo中不是有一个自定义布局的例子吗。

**Comment by LG12300** [comment]
尝试改了几种方法，这个弹窗的圆角还是不生效；唯一不同的是这个dialog是从另一个dialog中弹出来的；后来我用DialogFragment试了一下，同样的布局DialogFragment圆角是正常的

**Comment by the6nnoo** [comment]
xpopup 1.93中依旧有这个问题，从一个dialog中弹出另外一个CenterPopupView的自定义dialog xml中设置的圆角drawable 无效
当我强行设置到100的时候 有点效果，但不是个标准圆角。目前我是直接用自定义的dialog 用透明背景来处理的。

**Comment by the6nnoo** [comment]
找到原因了，因为dialog的布局设置的宽度 而这个宽度长于默认的80%，故有问题
