### ISSUE TITLE
自定义AttachPopupView 未显示，左上角闪烁一下消失

### ISSUE THREAD

**Issue by tswdwwl** [li-xiaojun/XPopup#537]
华为荣耀10，从Android 9.0升级到Android 10后
自定义的AttachPopupView 不显示，左上角闪烁一下消失，内置的asAttchList只显示白色背景，我看以前也有哥们提了这问题，但还是没有解决
版本：2.0.7、2.0.8 都还有这问题

**Comment by li-xiaojun** [comment]
更新到最新版本

**Comment by XD-Z** [comment]
请问问题解决了吗，我也出现了这个问题， 用的最新版本（2.10.0）依然能复现，一加手机9Pro，Android版本14

**Comment by csh159** [comment]
解决了不？我也出现了，华为p40 pro
