### ISSUE TITLE
自定义布局宽度问题

### ISSUE THREAD

**Issue by ygeng** [li-xiaojun/XPopup#54]
继承BottomPopupView的自定义布局对话框，如果布局里第一个view的宽度设置为wrap_content，根布局宽度为match_parent，那对话框弹出以后就是wrap_content的，宽度与第一个view宽度一致。
![image](https://user-images.githubusercontent.com/13791355/53477497-cdec1600-3aaf-11e9-97cd-e7bf40975e13.png)

**Comment by li-xiaojun** [comment]
@ygeng 
还有这种操作？我试试。

**Comment by li-xiaojun** [comment]
@ygeng 
最新的`1.4.3`版本已修复该问题，请更新试试。

**Comment by ygeng** [comment]
完美！
