### ISSUE TITLE
在浏览图片的时候 如果图片很长  保存按钮看不清楚

### ISSUE THREAD

**Issue by zylRookie** [li-xiaojun/XPopup#545]
长图的时候保存2个字的颜色是白色的  图片的底色也是白色的
就看不清楚保存的字样，能添加修改字体的颜色 或者其他的解决方案嘛？？？

**Comment by li-xiaojun** [comment]
这个你最好继承自图片预览弹窗，重写下面的布局。 修改颜色也不靠谱，因为你无法预览图片的颜色，总有可能同色。
