### ISSUE TITLE
PopupView在RecyclerView中的问题

### ISSUE THREAD

**Issue by Biswangluo** [li-xiaojun/XPopup#547]
我在RecyclerView中 item 点击弹出PartShadowPopupView 当RecyclerView滑动时候 再次弹出还是原来的位置 只要重新创建弹窗才是正确的位置 。

**Comment by Biswangluo** [comment]
看了源码 创建弹窗的时候 只会初始化一次位置，最好把源码copy出来，重写show 方法，每次show 之前重写测算下位置 

``  @Override
    public BasePopupView show() {
        //尝试手动更改距离
        ViewGroup.MarginLayoutParams params = (MarginLayoutParams) getPopupContentView().getLayoutParams();
        int[] locations = new int[2];
        popupInfo.getAtView().getLocationOnScreen(locations);
        Rect rect = new Rect(locations[0], locations[1], locations[0] + popupInfo.getAtView().getMeasuredWidth(),
                locations[1] + popupInfo.getAtView().getMeasuredHeight());
        int centerY = rect.top + rect.height()/2;
        params.width = getMeasuredWidth();
        params.height = getMeasuredHeight() - rect.bottom;
        isShowUp = false;
        params.topMargin = rect.bottom;
        // 同时自定义的impl View应该Gravity居于顶部
        View implView = ((ViewGroup)getPopupContentView()).getChildAt(0);
        FrameLayout.LayoutParams implParams = (LayoutParams) implView.getLayoutParams();
        implParams.gravity = Gravity.TOP;
        if(getMaxHeight()!=0)
            implParams.height = Math.min(implView.getMeasuredHeight(), getMaxHeight());
        implView.setLayoutParams(implParams);
        return super.show();
    }``

**Comment by li-xiaojun** [comment]
更新到最新版本 2.0.11即可
