### ISSUE TITLE
有计划出androidX的版本吗？

### ISSUE THREAD

**Issue by shlockfan** [li-xiaojun/XPopup#55]
为了用这个库我把gradle和target都升到了最新，后续会出androidX的版本吗？(最好能两个版本都有)

**Comment by li-xiaojun** [comment]
@shlockfan 
下个版本我会降低compileSdkVersion，这样不需要升级target和gradle了。
androidx的版本等功能稳定后会出的。

**Comment by shlockfan** [comment]
好的，谢谢
