### ISSUE TITLE
弹出窗 默认半透明背景遮罩，遮盖导航栏

### ISSUE THREAD

**Issue by 805058027** [li-xiaojun/XPopup#552]
当前使用版本2.0.11
机型红米 5plus 
导航栏默认 白色  图标灰色。弹出窗之后就遮盖如下图所示
![BB57BAEB04AB8A66B1FC69ACF26C8CA7](https://user-images.githubusercontent.com/16000497/93078575-4ed42800-f6bd-11ea-8027-a5474e821752.jpg)
不弹窗效果如下图所示
![9D373EAFCA2010F68AEA8D536EACCD33](https://user-images.githubusercontent.com/16000497/93078611-5e537100-f6bd-11ea-8474-6c3f340b05ce.jpg)

**Comment by li-xiaojun** [comment]
@805058027 
已修复，更新到2.1.3

**Comment by HQLIE2018** [comment]
> @805058027
> 已修复，更新到2.1.3

2.1.4又会有这个问题了
