### ISSUE TITLE
华为手机会报错，我用小米手机正常运行

### ISSUE THREAD

**Issue by githulining** [li-xiaojun/XPopup#554]
onResume中调用 popupView = new XPopup.Builder(this)
                .dismissOnBackPressed(false) // 按返回键是否关闭弹窗，默认为true
                .dismissOnTouchOutside(false) // 点击外部是否关闭弹窗，默认为true
                .isRequestFocus(true)
                .asLoading(txt)
                .show();
报错：--------------------------------------------
09-15 17:55:07.128 15959-16095/com.xxx.aismart E/OpenGLRenderer: resultIndex is -1, the polygon must be invalid!
    
    --------- beginning of crash
09-15 17:55:07.129 15959-16095/com.xxx.aismart A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xe2 in tid 16095 (hwuiTask1)
09-15 17:55:07.182 2958-2958/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-15 17:55:07.182 2958-2958/? A/DEBUG: Build fingerprint: 'HONOR/PLK-AL10/HWPLK:6.0/HONORPLK-AL10/C00B389:user/release-keys'
09-15 17:55:07.182 2958-2958/? A/DEBUG: Revision: '0'
09-15 17:55:07.182 2958-2958/? A/DEBUG: ABI: 'arm'
09-15 17:55:07.182 2958-2958/? A/DEBUG: pid: 15959, tid: 16095, name: hwuiTask1  >>> com.example.aismart <<<
09-15 17:55:07.182 2958-2958/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xe2
09-15 17:55:07.199 2958-2958/? A/DEBUG:     r0 00000027  r1 000000e5  r2 00000002  r3 000000e6
09-15 17:55:07.199 2958-2958/? A/DEBUG:     r4 00000026  r5 00000102  r6 00000001  r7 d93dcce8
09-15 17:55:07.199 2958-2958/? A/DEBUG:     r8 00000025  r9 d93dc068  sl d93dd070  fp 000000de
09-15 17:55:07.199 2958-2958/? A/DEBUG:     ip d93dce6c  sp 000000e3  lr 0000001f  pc f633e008  cpsr 000f0030
09-15 17:55:07.200 2958-2958/? A/DEBUG: backtrace:
09-15 17:55:07.200 2958-2958/? A/DEBUG:     #00 pc 0005c008  /system/lib/libhwui.so
09-15 17:55:07.200 2958-2958/? A/DEBUG:     #01 pc 0000000d  <unknown>
09-15 17:55:07.458 2958-2958/? A/DEBUG: Tombstone written to: /data/tombstones/tombstone_02
09-15 17:55:07.458 2958-2958/? E/DEBUG: AM write failed: Broken pipe
09-15 17:55:07.489 3267-3514/? E/logserver: process_one_event, can not find this event(data_app_native_crash@1600163707485.txt)
09-15 17:55:07.684 3528-4730/? E/HsmCoreServiceImpl: onTransact in code is: 102
09-15 17:55:07.801 17157-17171/com.xxx.aismart E/HAL: load: id=gralloc != hmi->id=gralloc
09-15 17:55:08.344 17157-17176/com.xxx.aismart E/HAL: load: id=gralloc != hmi->id=gralloc
09-15 17:55:09.375 17199-17199/? E/HAL: load: id=memtrack != hmi->id=memtrack
09-15 17:55:09.390 17199-17199/? E/HAL: load: id=fm != hmi->id=fm
09-15 17:55:09.390 17199-17199/? E/fm_if.c: find the id:fm and begins to open the devices
09-15 17:55:09.435 3528-3552/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 60)
09-15 17:55:09.470 3528-4255/? E/HsmCoreServiceImpl: onTransact in code is: 102

**Comment by li-xiaojun** [comment]
这个错应该不是XPopup引起的，试着注释弹窗代码，看看是否还有错误
