### ISSUE TITLE
功能建议，现在可以设置背景为高斯模糊背景，希望也能设置 模糊 dialog

### ISSUE THREAD

**Issue by xyggs** [li-xiaojun/XPopup#555]
功能建议，现在可以设置背景为高斯模糊背景，希望也能设置 模糊 dialog

**Comment by li-xiaojun** [comment]
模糊dialog？这是什么效果，有截图吗

**Comment by xyggs** [comment]
其实就是  activity 弹出 对话框  ， 对话框 覆盖下的 activity 部分布局模糊
![微信截图_20201013104446](https://user-images.githubusercontent.com/26700996/95809407-48c77a80-0d41-11eb-85e1-b4cf052d4f55.png)

**Comment by xyggs** [comment]
类似于这种效果：  https://blog.csdn.net/lvshaorong/article/details/50392057
