### ISSUE TITLE
targetSdkVersion 29 attach类弹窗在华为P30（安卓10）上弹窗内容显示空白

### ISSUE THREAD

**Issue by hsq2025** [li-xiaojun/XPopup#556]
弹窗内容显示一下就被隐藏了

**Comment by hsq2025** [comment]
targetSdkVersion 小于29的话就没问题

**Comment by li-xiaojun** [comment]
试了无法复现，可以上代码吗

**Comment by hoanX** [comment]
我这边也有人反馈mate20(Android10) 弹框空白，但是没设备没法验证，但是我的targetSdkVersion也是29

**Comment by zhuwujing** [comment]
我这边也遇到类似的问题，不是所有的机器都有这个问题，目前发现华为7x,荣耀x15,华为plus,三星 A50：
代码如下
 public class CustomAttachPopup extends AttachPopupView {
    private Context mContext;
    private IPopuClickLisenter mIPopuLisenter;
    private boolean mHasFirUpdate;

    public void setIPopuLisenter(IPopuClickLisenter IPopuLisenter) {
        mIPopuLisenter = IPopuLisenter;
    }

    public CustomAttachPopup(Context context) {
        super(context);
        mContext = context;
    }

    public CustomAttachPopup(Context context, boolean hasFirUpdate) {
        super(context);
        mContext = context;
        mHasFirUpdate = hasFirUpdate;
    }

    public void setLayoutParamsByUser(int with, int height) {
        LayoutParams layoutParams = (LayoutParams) attachPopupContainer.getLayoutParams();
        if (with != 0){
            layoutParams.width = with;
        }
        if (height != 0){
            layoutParams.height = height;
        }
        attachPopupContainer.setLayoutParams(layoutParams);
    }

    @Override
    protected int getImplLayoutId() {
        return R.layout.custom_attach_popup;
    }


    @Override
    protected void onCreate() {
        super.onCreate();
        ImageView morePointIv = findViewById(R.id.more_point);
        if (mHasFirUpdate) {
            morePointIv.setVisibility(VISIBLE);
        } else {
            morePointIv.setVisibility(GONE);
        }
        findViewById(R.id.light_tv).setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                if (mIPopuLisenter != null) {
                    mIPopuLisenter.onClick(v);
                }
            }
        });
        findViewById(R.id.find_robot_tv).setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                if (mIPopuLisenter != null) {
                    mIPopuLisenter.onClick(v);
                }
            }
        });
        findViewById(R.id.apponit_tv).setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                if (mIPopuLisenter != null) {
                    mIPopuLisenter.onClick(v);
                }
            }
        });
        findViewById(R.id.more_tv).setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                if (mIPopuLisenter != null) {
                    mIPopuLisenter.onClick(v);
                }
            }
        });
    }
}

使用：
  mPopupView = new CustomAttachPopup(mContext, hasFirUpdate);
//有省略部分业务代码
  new XPopup.Builder(mContext)
                .atView(view)
                .hasShadowBg(false) // 去掉半透明背景
                .offsetY(XPopupUtils.dp2px(mContext, 10))
                .offsetX(-XPopupUtils.dp2px(mContext, 10))
                .popupPosition(PopupPosition.Bottom)
                .asCustom(mPopupView)
                .show();

**Comment by zhuwujing** [comment]
@hoanX

**Comment by li-xiaojun** [comment]
用的哪个版本的xpopup  @zhuwujing

**Comment by hsq2025** [comment]
@li-xiaojun  xpopup版本2.0.11

targetSdkVersion 26
![微信图片_20200923112832](https://user-images.githubusercontent.com/35363900/93963538-076e2b80-fd90-11ea-8dc7-8dfe1f2ae1f1.jpg)
![微信图片_20200923112838](https://user-images.githubusercontent.com/35363900/93963593-2a004480-fd90-11ea-9260-2634be4bb6c5.jpg)

targetSdkVersion 29
![微信图片_20200923112827](https://user-images.githubusercontent.com/35363900/93963607-32f11600-fd90-11ea-8a37-328005b6df88.jpg)
![微信图片_20200923112821](https://user-images.githubusercontent.com/35363900/93963613-35ec0680-fd90-11ea-8dcd-7c8fed27c6f2.jpg)

手机（P30）型号和系统版本
![微信图片_20200923114352](https://user-images.githubusercontent.com/35363900/93964530-659c0e00-fd92-11ea-983d-38a316becfa7.jpg)
![微信图片_20200923114347](https://user-images.githubusercontent.com/35363900/93964543-6d5bb280-fd92-11ea-859b-308cfdb172a0.jpg)

**Comment by chengxiaorun** [comment]
![IMG_20200925_103157](https://user-images.githubusercontent.com/26917324/94219890-65c71580-ff1a-11ea-8f38-6052c6ba8fdd.png)
版本是2.0.8
出现问题的手机是荣耀8x

final XPopup.Builder builder = new XPopup.Builder(getContext())
                    .hasShadowBg(false)
                    .watchView(msgView)
                    .attachList(array,null,selectListener)
                    .show();

**Comment by li-xiaojun** [comment]
application的theme发下

**Comment by zhuwujing** [comment]
和上面发的是一至的，最新版本，有问题手机上，用demo app 也有问题

**Comment by li-xiaojun** [comment]
@zhuwujing 升级到2.1.4试下

**Comment by zhuwujing** [comment]
好的，我找手机测试一下，谢谢

**Comment by hsq2025** [comment]
@li-xiaojun 2.1.4版本targetSdkVersion 29 attach类弹窗在华为P30还是不行哦

**Comment by li-xiaojun** [comment]
奇怪，我用Mate20，P30, P40都无法复现

**Comment by hsq2025** [comment]
@li-xiaojun EMUI的版本也是一样的吗

**Comment by li-xiaojun** [comment]
更新到最新版试试

**Comment by li-xiaojun** [comment]
你是不是在开发者模式下关闭了动画了，我关闭动画的时候复现了

**Comment by li-xiaojun** [comment]
@hoanX  @chengxiaorun  @zhuwujing  @hsq2025 试试2.1.12版本是否解决
