### ISSUE TITLE
手势滑动问题

### ISSUE THREAD

**Issue by graysonwu2018** [li-xiaojun/XPopup#558]
Bottom 弹窗（自带拖拽交互）手势滑动有问题，在惯性滑动的情况下，按下不能停止。
复杂交互 Bottom 弹窗（各种手势滑动嵌套）左右滑动出现卡顿问题，惯性滑动也不能停止。

**Comment by xueweipeng** [comment]
我也遇到了同样的问题，而且频繁戳屏幕还会崩溃

**Comment by graysonwu2018** [comment]
点击拖拽滑动后，第二次点击事件没有响应。

**Comment by li-xiaojun** [comment]
更新到最新版本即可
