### ISSUE TITLE
我想设置向下滑动的距离来进行收起操作，比如向下滑动100 个像素就关闭，现在看好像没有这样的接口

### ISSUE THREAD

**Issue by xueweipeng** [li-xiaojun/XPopup#560]
SmartDragLayout中
int threshold = isScrollUp ? (maxY - minY) / 3 : (maxY - minY) * 2 / 3;
int dy = (getScrollY() > threshold ? maxY : minY) - getScrollY();
我在代码中看到这样的计算，看样子应该是滑动距离的计算

**Comment by li-xiaojun** [comment]
目前没有这样的功能。。。
