### ISSUE TITLE
同时弹两个窗会崩溃

### ISSUE THREAD

**Issue by AttackPangHu** [li-xiaojun/XPopup#561]
1：版本号：com.lxj:xpopup:2.0.13
2：场景：当弹出第一个窗口，点击窗口确认事件，关闭第一个窗口 然后立马弹出第二个窗口，前天用的低版本没问题，用上面那个版本会崩溃  异常   java.lang.IllegalStateException: Already in the pool!

**Comment by li-xiaojun** [comment]
更新到2.0.14即可发自我的华为手机-------- 原始邮件 --------发件人： AttackPangHu <notifications@github.com>日期： 2020年9月18日周五 半夜11:52收件人： li-xiaojun/XPopup <XPopup@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [li-xiaojun/XPopup] 同时弹两个窗会崩溃 (#561)

1：版本号：com.lxj:xpopup:2.0.13

2：场景：当弹出第一个窗口，点击窗口确认事件，关闭第一个窗口 然后立马弹出第二个窗口，前天用的低版本没问题，用上面那个版本会崩溃  异常   java.lang.IllegalStateException: Already in the pool!

**Comment by li-xiaojun** [comment]
更新到2.0.14即可

**Comment by AttackPangHu** [comment]
不好意思，最近才看这个库，升级了试下，确实解决了这个问题。作者大大辛苦了
