### ISSUE TITLE
有bug！三星s10e，底部虚拟导航键问题。

### ISSUE THREAD

**Issue by yaoxin2017** [li-xiaojun/XPopup#562]
![微信图片_20200920141630](https://user-images.githubusercontent.com/26868608/93704976-ecab7500-fb4b-11ea-8594-cafb168f245a.jpg)
![微信图片_20200920141641](https://user-images.githubusercontent.com/26868608/93704977-ef0dcf00-fb4b-11ea-9856-99fd06788176.jpg)

底部有部分被导航键遮住了，上面是github上最新demo截图；以下是我自己app里的截图，使用使用androidx，还是版本1.8.10,
![微信图片_20200920141929](https://user-images.githubusercontent.com/26868608/93705020-50ce3900-fb4c-11ea-8dc9-077bb6d603c9.jpg)

**Comment by yaoxin2017** [comment]
[Desktop.zip](https://github.com/li-xiaojun/XPopup/files/5251223/Desktop.zip)
 这个是图片压缩包

**Comment by li-xiaojun** [comment]
用最新版本
