### ISSUE TITLE
hasBlurBg  弹出底部弹框时   底部会有一段距离上移

### ISSUE THREAD

**Issue by xuexirong** [li-xiaojun/XPopup#563]
![微信图片_20200921171725](https://user-images.githubusercontent.com/13816024/93750627-5a2fd200-fc2e-11ea-9fe9-118690ee1619.jpg)

**Comment by li-xiaojun** [comment]
xpopup的版本，和 手机型号系统版本 说下

**Comment by xuexirong** [comment]
@li-xiaojun xpop 2.1.1  华为P20 EMUI：10.0.0  android：10

**Comment by xuexirong** [comment]
@li-xiaojun 被上移的  是底部的页面  不是弹框内部

**Comment by li-xiaojun** [comment]
我用p20 pro试的，没有出现这种情况。你试试demo会不会有这种情况。如果demo也有就是机型兼容bug了，如果demo没有就检测下你的代码看看哪里出问题了。

**Comment by xuexirong** [comment]
@li-xiaojun 好的
