### ISSUE TITLE
引入Xpopup之后项目直接X掉了

### ISSUE THREAD

**Issue by Dboy233** [li-xiaojun/XPopup#565]
**XPopup版本**
2.1.4

**手机系统和型号**
华为Mate20 Android 10

**描述你的问题**

引入Xpopup之后项目直接X掉了

![image](https://user-images.githubusercontent.com/37604230/94254564-85c9f980-ff59-11ea-9ceb-6af5c5d90c4e.png)

![image](https://user-images.githubusercontent.com/37604230/94254630-a2fec800-ff59-11ea-805c-643fa0704cb2.png)

**Comment by li-xiaojun** [comment]
gradle会有build日志的，把报错信息贴下

**Comment by Dboy233** [comment]
也没有报错信息，同步是同步成功了的。
