### ISSUE TITLE
关于适配的问题

### ISSUE THREAD

**Issue by roybill** [li-xiaojun/XPopup#566]
请问一下,用的最新的库2.1.4,红米8上面的弹框会底部会有一片空白,小米10正常.但是当我改回1.8.17的版本,就变成红米8正常,小米10有一片空白了,这个该怎么解决呢?   public class AnswerDetailWindow extends AttachPopupView{}

**Comment by li-xiaojun** [comment]
更新到最新版本试试

**Comment by li-xiaojun** [comment]
@roybill 更新到最新版试试，不行的话上个图
