### ISSUE TITLE
希望支持一下Databinding

### ISSUE THREAD

**Issue by guozhiqiang123** [li-xiaojun/XPopup#567]
![QQ截图20200928152417](https://user-images.githubusercontent.com/20378988/94402511-bbabef80-019e-11eb-93db-6c8abbe28eb7.png)
希望这里不要限定死，而是由使用者给你返回一个View,至于使用者用什么方式加载View则由他们自己决定吧。

**Comment by li-xiaojun** [comment]
是支持的，弹窗本质是自定义View，如果你想要获取弹窗的跟View，可以使用getPopupContentView()
