### ISSUE TITLE
attacklistpopupview存在布局id硬编码问题,自定义item布局不灵活

### ISSUE THREAD

**Issue by dongbaoming123** [li-xiaojun/XPopup#568]
![image](https://user-images.githubusercontent.com/23044410/94521457-ab5c4900-0260-11eb-9872-6a869fc2b655.png)

源码中写死了从布局中  View check = holder.getView(R.id.check_view);所以算定义item布局中也必须有check_view这个id.不然ViewHolder中  return view as T强转出错.null强转

**Comment by dongbaoming123** [comment]
![image](https://user-images.githubusercontent.com/23044410/94521846-47865000-0261-11eb-9794-6d87fb5988e2.png)

**Comment by dongbaoming123** [comment]
![image](https://user-images.githubusercontent.com/23044410/94521894-579e2f80-0261-11eb-8d22-4391032c7e13.png)

**Comment by dongbaoming123** [comment]
低版本有问题升到高版本,高版本还是有坑,注释可以更新一下,感谢楼主分享,继续加油啊

**Comment by li-xiaojun** [comment]
这个不用id硬编码有什么好的方案推荐吗？

**Comment by dongbaoming123** [comment]
硬编id的时候,viewholder里的view变量为null时不能强转.return view as T当view为null就出错了.现在自定义布局里必须得有check_view的id.

**Comment by dongbaoming123** [comment]
增加一个布局中得有这个id的注释吧.示例实现硬编没问题,我没有更好的办法.

**Comment by li-xiaojun** [comment]
更新到2.1.5即可
