### ISSUE TITLE
包含的attachlistpopupview不能使用库中的TranslateAnimator

### ISSUE THREAD

**Issue by dongbaoming123** [li-xiaojun/XPopup#569]
**XPopup版本**
如2.1.4

**描述你的问题**
库中现有的AttachListPopupView默认使用的是ScrollScaleAnimator.当在AttachListPopupView子类中重写getpopupAnimator()方法改成TranslateAnimator时不能实现弹框在锚点view的下方.

**Comment by dongbaoming123** [comment]
看了一下源码
AttachPopupView中的doAttach方法中最后是    
                    translationY = rect.bottom + defaultOffsetY;
                    }
                    getPopupContentView().setTranslationX(translationX);
                    getPopupContentView().setTranslationY(translationY);
没在当前translationx/y基础上设置新值,而是直接替换成与历史值无关的新值.同时,TranslateAnimator中的实现也是只替换了与历史translationx/y无关的新值,感觉都应该在原有translationx/y基础上累加.

**Comment by dongbaoming123** [comment]
是不是 AttachListPopupView及其子类不改写doattach()的话没办法使用translateanimator?

**Comment by li-xiaojun** [comment]
@li-xiaojun 你可以直接指定popupAnimation(xxx)；默认情况下弹窗已经使用了合适的动画，如果修改为其他动画，效果可能不是很合适
