### ISSUE TITLE
提一个需求：能否在内部支持设置时间自动关闭

### ISSUE THREAD

**Issue by yuanxiaofan** [li-xiaojun/XPopup#57]
需求是下单后弹窗显示订单详情，并在3秒后自动关闭

**Comment by li-xiaojun** [comment]
@yuanxiaofan 
抱歉兄弟，这个功能不属于弹窗或者不够通用；XPopup力求实现实实在在的通用功能需求；所以暂时不会添加。仍然感谢您的建议！

**Comment by yuanxiaofan** [comment]
嗯嗯，没关系，谢谢你的回答

**Comment by devzwy** [comment]
同求
