### ISSUE TITLE
targetSdkVersion30   Xpop 2.1.4 版本 小米9 自定义中心弹框出现内容展示空白，展示部分的情况

### ISSUE THREAD

**Issue by zhangi789** [li-xiaojun/XPopup#571]
public class QuitLiveDialog extends CenterPopupView _{_
    public CallBack mCallBack;
    private TextView tv_title;
    private TextView tv_left;
    private TextView tv_right;
    private String title;
    private String leftTxt;
    private String rightTxt;
    public QuitLiveDialog(@NonNull Context context, String title,
                          String leftTxt,
                          String rightTxt,
                          CallBack mCallBack) {
        super(context);
        this.mCallBack = mCallBack;
        this.title = title;
        this.leftTxt = leftTxt;
        this.rightTxt = rightTxt;

    }

    public interface CallBack {
        public void onSure();
    }

    @Override
    protected int getImplLayoutId() {
        return R.layout.pop_open;
    }

    @Override
    protected void initPopupContent() {
        super.initPopupContent();
        tv_title = (TextView) findViewById(R.id.tv_content);
        tv_left = (TextView) findViewById(R.id.tv_cancle);
        tv_right = (TextView) findViewById(R.id.tv_sure);
        tv_title.setText(title);
        tv_left.setText(leftTxt);
        tv_right.setText(rightTxt);
        findViewById(R.id.tv_sure).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                mCallBack.onSure();
                dismiss();
            }
        });
        findViewById(R.id.tv_cancle).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                dismiss();
            }
        });
    }
}

使用过程
 new XPopup.Builder(PushStreamActivity.this)
                        .asCustom(new QuitLiveDialog(PushStreamActivity.this, "您确定要退出直播？", "不了", "是的", new QuitLiveDialog.CallBack() {
                            @Override
                            public void onSure() {

                                startActivity(new Intent(mContext, MainActivity.class));
                            }
                        })).show();

**Comment by zhangi789** [comment]
![QQ图片20201003194536](https://user-images.githubusercontent.com/18211585/94990750-11263900-05b1-11eb-9d02-c6352180d852.jpg)

**Comment by li-xiaojun** [comment]
把 pop_open 的布局截图我看看
