### ISSUE TITLE
版本底部弹窗设置 enableDrag(false)//禁用拖拽后；反复几次打开关闭popup后，进出场动画混乱，直接从顶部飞出了

### ISSUE THREAD

**Issue by yk007** [li-xiaojun/XPopup#572]
new XPopup.Builder(this)
                     .enableDrag(false) 
                     .asCustom(myBottomPopWindow)
                     .show();

**Comment by yk007** [comment]
经测试，底部布局中如果没有recyclerview，多次打开后进场动画偶尔会闪进，有recyclerview后几次打开后就从顶部飞出了；
Popup高度是屏幕80%；不设置enableDrag(false)没有问题

**Comment by yk007** [comment]
enableDrag(true) 通过拖拽关闭popup再打开时 软键盘会自动弹出；点击返回按钮或者空白区域退出在打开不会出现这种情况
popup中有EditText,默认父容器获取焦点的

**Comment by yk007** [comment]
经测试当根布局高度是match_parent 布局高度设置的是屏幕80% 并且布局中有RecyclerView时会出现
改为wrap_content 后没有问题了，但是多次打开关闭后入场动画偶尔是闪进没有从底部滑入

enableDrag(true) 通过拖拽关闭popup再打开时 软键盘会自动弹出；点击返回按钮或者空白区域退出在打开不会出现这种情况
popup中有EditText,默认父容器获取焦点的

**Comment by li-xiaojun** [comment]
@yk007 
更新到2.2.12，修复了这个问题
