### ISSUE TITLE
RTL 布局，查看大图时，图片过度动画位置对不上

### ISSUE THREAD

**Issue by DuShuYuan** [li-xiaojun/XPopup#573]
**XPopup版本**
2.1.4

**手机系统和型号**
Android 7

**描述你的问题**
![yRBOepB9AS](https://user-images.githubusercontent.com/11830896/95560804-5aacd300-0a4c-11eb-9160-b40d920facac.gif)

RTL 布局，查看大图时，图片过度动画位置对不上
`
XPopup.Builder(mContext)
                    .asImageViewer(it as ImageView?, item.imgUrl, MyXPopupImageLoader())
                    .isShowSaveButton(false)
                    .show()
`

**Comment by li-xiaojun** [comment]
@DuShuYuan 更新到2.1.5即可
