### ISSUE TITLE
局部阴影小问题

### ISSUE THREAD

**Issue by yu893145181** [li-xiaojun/XPopup#575]
版本2.1.4，设置isClickThrough(true)，综合，价格，筛选，每次点一下消失了，再点一下才会弹出。虽然点击事件击穿了，但是在击穿前还是做了dismiss，所以才会这样

**Comment by yu893145181** [comment]
可不可以不让它dismiss，直接响应点击事件，从而直接更新弹框里面的UI

**Comment by li-xiaojun** [comment]
你可以设置dismissOnTouchOutside(false)
