### ISSUE TITLE
activity全屏显示时，Bottom弹窗阴影没有覆盖刘海区域

### ISSUE THREAD

**Issue by DuShuYuan** [li-xiaojun/XPopup#577]
**XPopup版本**
2.1.4

**手机系统和型号**
小米9 Android 10

**描述你的问题**

activity全屏显示时，Bottom弹窗阴影没有覆盖刘海区域

XPopup.Builder(this)
                .hasNavigationBar(false)
                .moveUpToKeyboard(false)
                .asCustom(BottomPopupView)
                .show()
![1e052f6f77687ac0b76aa0a509da782](https://user-images.githubusercontent.com/11830896/95808192-824ab680-0d3e-11eb-8f93-5a71bb685837.jpg)

**Comment by li-xiaojun** [comment]
你Activity的全屏是如何设置的

**Comment by DuShuYuan** [comment]
```kotlin
class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        // 刘海屏适配
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
            val lp = window.attributes
            lp.layoutInDisplayCutoutMode = WindowManager.LayoutParams.LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES
            window.attributes = lp
        }
        setContentView(R.layout.activity_main)
        SystemBarUtils.hideStableStatusBar(this)
        SystemBarUtils.hideStableNavBar(this)
        button.onClick {
            showD()
        }

    }

    private fun showD(){
        XPopup.Builder(this)
            .hasNavigationBar(false)//设置true没问题，false-顶部就没有阴影覆盖
            .moveUpToKeyboard(false)
            .asBottomList(
                "请选择", arrayOf("条目1", "条目2", "条目3", "条目4")
            ) { position, text -> toast("click $text") }
            .show()
    }


}

```
[SystemBarUtils.txt](https://github.com/li-xiaojun/XPopup/files/5442456/SystemBarUtils.txt)

**Comment by li-xiaojun** [comment]
把SystemBarUtils相关设置注释试试还有没有

**Comment by DuShuYuan** [comment]
> 把SystemBarUtils相关设置注释试试还有没有

还是一样，状态栏那部分没有阴影。
设置 hasNavigationBar = true    就没有问题

**Comment by li-xiaojun** [comment]
把demo跑到你手机上看看是否有这样的问题，如果有说明确实是兼容性问题。
如果demo没有问题，说明你用的不对，检测下代码，哪里可能影响了这个状态栏

**Comment by DuShuYuan** [comment]
> 把demo跑到你手机上看看是否有这样的问题，如果有说明确实是兼容性问题。
> 如果demo没有问题，说明你用的不对，检测下代码，哪里可能影响了这个状态栏

用是新建的小demo，没有多余的代码，手机是小米9 有刘海，其他没有刘海的手机没有问题；问题就在hasNavigationBar(false) 这句代码上

**Comment by li-xiaojun** [comment]
我试了小米9无法复现，

**Comment by DuShuYuan** [comment]
> 我试了小米9无法复现，

新建demo  只需要加上hasNavigationBar(false)  不管是不是全屏，状态栏都没有阴影，所有弹窗都一样 
```

class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
    }
    fun show(view: View){
        XPopup.Builder(this)
                .hasNavigationBar(false)//设置true没问题，false-顶部就没有阴影覆盖
//                .asConfirm(",","===",{}).show()
//                .asLoading().show()
                .asBottomList(
                        "请选择", arrayOf("条目1", "条目2", "条目3", "条目4")
                ) { position, text -> }
                .show()
    }
}
```


![3ae0ffd4e6580364db63f16cb3a0a7f](https://user-images.githubusercontent.com/11830896/97531403-1b402980-19ef-11eb-98bb-52a658616cd5.jpg)
![200d8595005e7718d7303ae6ffb808c](https://user-images.githubusercontent.com/11830896/97531410-1da28380-19ef-11eb-9de4-b1567140b346.jpg)
![21053443bf6afd2b9db8da63b203bba](https://user-images.githubusercontent.com/11830896/97531411-1ed3b080-19ef-11eb-823e-7c0de0d9432b.jpg)

**Comment by dyj11** [comment]
XPopup版本
2.1.4

手机系统和型号
OPPO R17 Android 10

遇到相同问题+1，刘海屏手机全屏时布局覆盖不到刘海屏
![Screenshot_2020-11-05-14-53-09-04_b7505542251123fa702ebdf104d64780](https://user-images.githubusercontent.com/37290585/98207549-d11ef100-1f76-11eb-89f5-b889bf8df9ac.jpg)

**Comment by li-xiaojun** [comment]
@DuShuYuan  @dyj11  更新到2.2.12试试
