### ISSUE TITLE
三星系统底部导航适配错乱

### ISSUE THREAD

**Issue by chenxiaojin** [li-xiaojun/XPopup#579]
**XPopup版本**
2.1.3

**手机系统和型号**
三星A6s Android 8.1.0

**描述你的问题**
三星系统底部虚拟导航栏可以设置为自动隐藏， 打开APP后， 默认情况导航栏默认是隐藏的。
在打开带输入框的dialog后， 键盘弹出， 底部的导航栏也显示了， 然后dialog的位置错乱了。

![Screenshot_20201014-105450287](https://user-images.githubusercontent.com/9512516/95938471-8b09be00-0e0c-11eb-8e80-5823c6d62124.png)
![image](https://user-images.githubusercontent.com/9512516/95938398-66154b00-0e0c-11eb-9122-10208b7e0a7d.png)

**Comment by li-xiaojun** [comment]
试试2.2.0，看看是否解决了你的问题

**Comment by chenxiaojin** [comment]
> 试试2.2.0，看看是否解决了你的问题

试了一下， 还是不行

**Comment by li-xiaojun** [comment]
更新到2.2.5试试

**Comment by crazysniper** [comment]
2.2.5还是不行呢

**Comment by li-xiaojun** [comment]
@crazysniper @chenxiaojin 更新到2.2.17试试，尝试修复了这个问题
