### ISSUE TITLE
WARNING: API 'variantOutput.getPackageLibrary()' is obsolete and has been replaced with 'variant.getPackageLibraryProvider()'.

### ISSUE THREAD

**Issue by one1go** [li-xiaojun/XPopup#58]
在导入您的库时，遇到了这个问题，不知道如何解决
![image](https://user-images.githubusercontent.com/23009655/53707658-d73c0080-3e6a-11e9-901e-f6b637aa9aae.png)

**Comment by li-xiaojun** [comment]
这只是一个警告，只是说gradle的某些语法过时了，可能跟你的gradle版本有关。

**Comment by one1go** [comment]
> 这只是一个警告，只是说 gradle 的某些语法过时了，可能跟你的 gradle 版本有关。

谢谢提醒，我检查了一下我的gradle配置
 app/build.gradle
compileSdkVersion 28
 buildToolsVersion "28.0.3"

项目目录下/ build.gradle
classpath 'com.android.tools.build:gradle:3.3.1'
classpath 'com.novoda:bintray-release:0.9'

可能跟这个有关系:(
