### ISSUE TITLE
Android resource compilation failed资源文件报错

### ISSUE THREAD

**Issue by qq837890739** [li-xiaojun/XPopup#580]
**XPopup版本**
如2.1.4

**描述你的问题**
原来项目用的版本是1.8.11，更新到2.1.4的时候运行项目很多资源文件报错，Android resource compilation failed，看了一下就是那些资源文件有些代码书写不规范，但是有些是第三方的，gradle集成的，根本修改不了。原来1.8.11版本是没问题的！然后尝试了一下2.1.3的版本也是一样报错！

**Comment by li-xiaojun** [comment]
编译问题一般是项目问题，非类库问题
