### ISSUE TITLE
Xpopup在全屏模式下的状态栏问题

### ISSUE THREAD

**Issue by wuyang2000** [li-xiaojun/XPopup#584]
**XPopup版本**
2.0.6

**手机系统和型号**
Redmi Note 8 （Android 9 API 28）

**描述你的问题**
横屏显示的app需要全屏。
全屏之后状态栏就不再显示了，但是每次使用Xpopup的时候，状态栏就会出来。
有没有全屏模式下弹框不影响状态栏的方法。
望作者大大解惑！

**Comment by li-xiaojun** [comment]
使用最新版本即可
