### ISSUE TITLE
设置atView(view)之后，代码中想知道显示的pop是显示在view的上方或下方

### ISSUE THREAD

**Issue by ZYRzyr** [li-xiaojun/XPopup#586]
**XPopup版本**
2.1.8

**手机系统和型号**
华为Mate20 Android 10

**描述你的问题**
wiki中写的：`.atView(v)  // 依附于所点击的View，内部会自动判断在上方或者下方显示`

那么在设置了这个之后，想通过某种方式知道弹出的pop此时是显示在v的上方或者下方的，现在的版本有这样的功能吗？

**Comment by li-xiaojun** [comment]
Attach弹窗有个属性isShowUp可以用，但注意要在显示之后再用
