### ISSUE TITLE
使用ImageViewerPopupView查看图片导致immersionbar沉浸式状态栏失效

### ISSUE THREAD

**Issue by dyj11** [li-xiaojun/XPopup#590]
XPopup版本
2.1.4

手机系统和型号
OPPO R17 Android 10

描述你的问题
程序中使用immersionbar对实现沉浸式状态栏，使用自定义的BottomPopupView对状态栏无影响，但是在使用ImageViewerPopupView时，会导致我原本透明的状态栏变为白色，请问有什么解决办法吗？
![IMG_20201104_110716](https://user-images.githubusercontent.com/37290585/98064983-7c07b000-1e8e-11eb-90dd-3d48b8aea243.jpg)
![Screenshot_2020-11-04-11-05-00-32_b7505542251123fa702ebdf104d64780](https://user-images.githubusercontent.com/37290585/98064990-8033cd80-1e8e-11eb-8aea-204970dadf16.jpg)
![IMG_20201104_110752](https://user-images.githubusercontent.com/37290585/98064997-83c75480-1e8e-11eb-9d4a-b2a712b7e7a7.jpg)

**Comment by li-xiaojun** [comment]
更新到最新版本试试

**Comment by dyj11** [comment]
> 更新到最新版本试试

更新到了2.2.0，结果还是一样，大牛，为什么使用ImageViewerPopupView修改了状态栏字体颜色呢？

**Comment by li-xiaojun** [comment]
xpopup不会去修改字体，可能是你那个框架引起的，试试原生activity就知道了 ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;dyj11&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月9日(星期一) 中午11:04
收件人:&nbsp;&quot;li-xiaojun/XPopup&quot;<XPopup@noreply.github.com&gt;;
抄送:&nbsp;&quot;Jun&quot;<16167479@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [li-xiaojun/XPopup] 使用ImageViewerPopupView查看图片导致immersionbar沉浸式状态栏失效 (#590)

**Comment by dyj11** [comment]
> xpopup不会去修改字体，可能是你那个框架引起的，试试原生activity就知道了 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;dyj11&quot;<notifications@github.com&gt; 发送时间:&nbsp;2020年11月9日(星期一) 中午11:04 收件人:&nbsp;&quot;li-xiaojun/XPopup&quot;<XPopup@noreply.github.com&gt;; 抄送:&nbsp;&quot;Jun&quot;<16167479@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [li-xiaojun/XPopup] 使用ImageViewerPopupView查看图片导致immersionbar沉浸式状态栏失效 (#590)

好的。谢谢

**Comment by li-xiaojun** [comment]
问题解决了吗

**Comment by dyj11** [comment]
> 问题解决了吗

嗯嗯，我监听了一下ImageViewerPopupView的关闭，关闭后重置我的状态栏颜色
