### ISSUE TITLE
我发现，在布局中不可以使用android:layout_width=wrap_content来描述控件，这样会让弹窗的宽度不正确

### ISSUE THREAD

**Issue by ChinaTang** [li-xiaojun/XPopup#592]
__<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/frameContent"
    android:background="#50000000"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <LinearLayout
        android:orientation="vertical"
        
        android:layout_width="match_parent"
        android:layout_height="wrap_content">
        <TextView
            android:layout_marginTop="20dp"
            android:layout_marginLeft="15dp"
            android:layout_marginBottom="12dp"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="来源"
            android:textColor="#ff999999"
            android:textSize="13sp" />

        

        <View
            android:background="#DEDEDE"
            android:layout_width="match_parent"
            android:layout_height="0.5dp"/>

        <TextView
            android:layout_marginTop="20dp"
            android:layout_marginLeft="15dp"
            android:layout_marginBottom="12dp"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="行业"
            android:textColor="#ff999999"
            android:textSize="13sp"
            />

    </LinearLayout>

</FrameLayout>

### 这个布局应该显示的是一个占满屏幕的弹窗，但最终显示的结果却只有textView的实际大小的弹窗，我继承的是AttachPopupView

**Comment by li-xiaojun** [comment]
这个是Attach的特性，故意为之

**Comment by li-xiaojun** [comment]
@ChinaTang 如果你确实想让Attach的宽度充满，那可以重写getPopupWidth()或者设置.popupWidth(xxx)
