### ISSUE TITLE
Drawer弹窗输入框遮挡问题

### ISSUE THREAD

**Issue by xiaobaiAndroid** [li-xiaojun/XPopup#598]
**XPopup版本**
如2.2.0

**手机系统和型号**
华为P9 Android 8

**描述你的问题**
有虚拟导航栏的时候软键盘弹出，底部输入框会被遮挡
![WechatIMG11](https://user-images.githubusercontent.com/20510161/98914455-a814d800-2503-11eb-951d-fadab39e4c06.jpeg)
![WechatIMG12](https://user-images.githubusercontent.com/20510161/98914468-ac40f580-2503-11eb-8c88-306b5cd5b480.jpeg)

**Comment by li-xiaojun** [comment]
很奇怪试了你这个机型无法复现，你把2.2.0的demo跑到你这个手机上，点击那个显示右边Drawer弹窗，里面有个输入框，看看输入框会不会被遮挡

**Comment by li-xiaojun** [comment]
@xiaobaiAndroid 更新到2.2.10试试

**Comment by li-xiaojun** [comment]
@xiaobaiAndroid  更新到2.2.17试试，尝试修复了这个问题
