### ISSUE TITLE
使用自定义黏贴在输入法之上的弹窗的问题

### ISSUE THREAD

**Issue by chengmenghuiAndroid** [li-xiaojun/XPopup#600]
**XPopup版本**
2.1.18

**手机系统和型号**
oppo手机Android 10.0

**描述你的问题**
使用自定义黏贴在输入法之上的弹窗 键盘宇输入框之前会有一个导航栏高度的空白距离

**Comment by li-xiaojun** [comment]
更新到2.2.1试试

**Comment by chengmenghuiAndroid** [comment]
> 更新到2.2.1试试

ok

**Comment by chengmenghuiAndroid** [comment]
![image](https://user-images.githubusercontent.com/20322861/99373978-07f0f180-28fd-11eb-854f-7013c559b396.png)

**Comment by chengmenghuiAndroid** [comment]
![Uploading image.png…]()

**Comment by chengmenghuiAndroid** [comment]
![Uploading image.png…]()

**Comment by chengmenghuiAndroid** [comment]
你好，今天运行了一下demo，oppo手机在隐藏状态栏的情况下还是，弹窗和输入法之间会有一块空白

**Comment by li-xiaojun** [comment]
@chengmenghuiAndroid 具体是哪个机型

**Comment by zhyazaq** [comment]
三星s8会和上面情况一样，最新版本

**Comment by li-xiaojun** [comment]
试试最新版本有没有解决你的问题

**Comment by zhyazaq** [comment]
我也碰到这种问题，软键盘上面有一个输入框。可以横竖屏切换，发现多次弹出以后输入框距离软件有一定的高度，应该是底部导航栏的高度，更新到最新的2.2.13直接软键盘遮住了输入框了

**Comment by renyanxu2000** [comment]
![WechatIMG115](https://user-images.githubusercontent.com/8318097/105606875-b66e5280-5dd6-11eb-8971-4e8bc58b856d.jpeg)
![WechatIMG114](https://user-images.githubusercontent.com/8318097/105606885-c128e780-5dd6-11eb-874a-aec5128470b0.jpeg)

**Comment by li-xiaojun** [comment]
更新到最新版本试试，尝试解决了这个问题
