### ISSUE TITLE
xpopup 确定取消按钮的字体颜色修改未生效

### ISSUE THREAD

**Issue by wangtaolin** [li-xiaojun/XPopup#601]
**XPopup版本**
如2.1.8

**手机系统和型号**
华为Mate20 Android 10

**描述你的问题**
最好能上代码截图和问题截图
![image](https://user-images.githubusercontent.com/51851868/99208934-d8f35680-27fc-11eb-94ec-90ef4df7e359.png)

**Comment by li-xiaojun** [comment]
时机不对，因为XPopup在创建的时候会有默认颜色，你设置的被覆盖的，把你设置的代码放到onShow监听中即可
