### ISSUE TITLE
asAttachList设置动画无效果

### ISSUE THREAD

**Issue by WenChaoLuo** [li-xiaojun/XPopup#603]
**XPopup版本**
2.1.4

**手机系统和型号**
小米6

**描述你的问题**
设置动画后是默认右上弹出的效果：
`new XPopup.Builder(getContext())
                .atView(notDealDutyLayout)
                .hasShadowBg(false)
                .isCenterHorizontal(true)
                .setPopupCallback(new XPopupCallback() {
                    @Override
                    public void onCreated(BasePopupView popupView) {

                    }

                    @Override
                    public void beforeShow(BasePopupView popupView) {

                    }

                    @Override
                    public void onShow(BasePopupView popupView) {

                    }

                    @Override
                    public void onDismiss(BasePopupView popupView) {

                    }

                    @Override
                    public void beforeDismiss(BasePopupView popupView) {
                        rotateDutyIcon();
                    }

                    @Override
                    public boolean onBackPressed(BasePopupView popupView) {
                        return false;
                    }
                })
                .popupAnimation(PopupAnimation.ScrollAlphaFromTop)
                .asAttachList(
                        new String[]{"我方责任", "第三方厂商责任", "未知责任", "条目4", "条目5"},
                        null,
                        (position, text) -> {
                            RxToast.showTips("click " + text);
                       
                        }
                )
                .show();`

**Comment by li-xiaojun** [comment]
用最新版本即可
