### ISSUE TITLE
状态栏不隐藏的情况下用自定义全屏弹窗，弹窗会被状态栏遮挡

### ISSUE THREAD

**Issue by huaxuanHan** [li-xiaojun/XPopup#606]
**XPopup版本**
![微信图片_20201119171021](https://user-images.githubusercontent.com/60837230/99645818-a9f21480-2a8a-11eb-9ae6-786d770286dc.jpg)

如2.2.1

**手机系统和型号**
警翼P3 Android 7

**描述你的问题**
状态栏不隐藏的情况下用自定义全屏弹窗，弹窗会被状态栏遮挡，全屏就是整个屏幕？不能根据状态栏的显示状态变化吗？

**Comment by li-xiaojun** [comment]
任何弹窗都无法覆盖状态栏的，XPopup也无能为力，状态栏的层级是最高的。
