### ISSUE TITLE
2.2.5版本，显示依附于某个View或者某个点的弹窗，都是显示在上面

### ISSUE THREAD

**Issue by huaxuanHan** [li-xiaojun/XPopup#608]
我用最新的2.2.5，显示依附于某个View或者某个点的弹窗，都是显示在上面，不会自动判断是显示上面还是下面了，2.2.4和2.2.3都可以

**Comment by huaxuanHan** [comment]
刚看到更新了2.2.8，我又试了一下，2.8还是不行，自动显示在上面了，换回2.4就会显示在下面

**Comment by li-xiaojun** [comment]
应该不会吧，我试了很多次都没问题，你是什么机型

**Comment by li-xiaojun** [comment]
@huaxuanHan 更新到2.2.10，修复了这个问题
