### ISSUE TITLE
跟Hilt使用冲突，希望兼容

### ISSUE THREAD

**Issue by jiqianwen** [li-xiaojun/XPopup#609]
**XPopup版本**
2.2.4

**手机系统和型号**
跟手机系统无关

**描述你的问题**
跟hilt一起使用冲突
![QQ图片20201127092001](https://user-images.githubusercontent.com/26268908/100400610-1922c680-3092-11eb-9c49-7c3aa15b5d02.png)

**Comment by li-xiaojun** [comment]
图片挂了，冲突是指哪方面冲突？

**Comment by jiqianwen** [comment]
> 图片挂了，冲突是指哪方面冲突？

![100400610-1922c680-3092-11eb-9c49-7c3aa15b5d02](https://user-images.githubusercontent.com/26268908/102029904-6372aa00-3deb-11eb-8c04-5248ef275f79.png)
dagger.hilt.internal.managers.ViewComponentManager$FragmentContextWrapper cannot be cast to android.app.Activity
我是在fragment使用的Xpopup  貌似hilt在fragment自动生成的上下文有点问题，我也是刚研究hilt，头大

**Comment by li-xiaojun** [comment]
XPopup的上下文必须是Activity，保证你传入的是Activity即可
