### ISSUE TITLE
继承centerPop，宽度没有自适应，导致点击区域不对

### ISSUE THREAD

**Issue by zqlq4ever** [li-xiaojun/XPopup#611]
**XPopup版本**
如2.2.4

**手机系统和型号**
机型无关

**描述你的问题**

自定义布局
![8e822dce7f4f35a8ff5abae332acb34](https://user-images.githubusercontent.com/37474811/100429337-22cb1f00-30d0-11eb-8fa4-d5d7da720731.png)
pop以及调用出，均未手动设置最大宽度
![bc2be3c4b2e938fbca32ffa557b8d01](https://user-images.githubusercontent.com/37474811/100429338-22cb1f00-30d0-11eb-80b7-c50f8ffc100f.png)
实际效果，pop宽度不是布局中的613dp，而是默认的centerPopupContainer宽度
![6755a499e2cf2c44c188d3035bcdfa2](https://user-images.githubusercontent.com/37474811/100429350-252d7900-30d0-11eb-8a9d-b63af4f86569.png)
这是2.2.4源码中的centerPopupContainer，写的match
![微信截图_20201127164313](https://user-images.githubusercontent.com/37474811/100429361-29599680-30d0-11eb-83b5-e0c803c953db.png)

**Comment by zqlq4ever** [comment]
手动修改参数centerPopupContainer，正常了。
希望在新版本修复这个问题，发现所有的自定义centerpop都有了这问题
![微信截图_20201127171751](https://user-images.githubusercontent.com/37474811/100432459-9c650c00-30d4-11eb-86de-44fe31921dde.png)

**Comment by zqlq4ever** [comment]
根据作者提示，重写了最大宽度，也可以解决这个问题
   override fun getMaxWidth(): Int {
        return -1
    }

**Comment by TwilightKHQ** [comment]
继承centerpop 宽度出现问题 +1 也是通过上面的方法恢复正常的
