### ISSUE TITLE
弹窗设置最大宽度和高度无效

### ISSUE THREAD

**Issue by ximenchuipaopao** [li-xiaojun/XPopup#612]
**XPopup版本**
2.0.7

**手机系统和型号**
华为荣耀 Android 8.0

**描述你的问题**
最好能上代码截图和问题截图
XPopup.Builder(context)
            .hasShadowBg(false)
            .isDestroyOnDismiss(true)
            .atView(getBinding().tvSite)
            .maxWidth(100)
            .maxHeight(100)
            .asAttachList(
                siteList, null
            ) { position, text ->
      
            }
            .show()

下拉的数据多，图片效果就是高度在指定控件下面撑满屏幕了，一直到屏幕最底下

**Comment by li-xiaojun** [comment]
图片挂了

**Comment by li-xiaojun** [comment]
更新到2.2.10即可
