### ISSUE TITLE
XPopup弹窗的时候，底部导航栏会变白色。原生Dialog不会变色

### ISSUE THREAD

**Issue by crazysniper** [li-xiaojun/XPopup#613]
**XPopup版本**
2.2.5

**手机系统和型号**
红米6Pro Android 9

**描述你的问题**
最好能上代码截图和问题截图
`
                new XPopup.Builder(this)
                        .asConfirm("提示", "提示内容", "", "确定",
                                new OnConfirmListener() {
                                    @Override
                                    public void onConfirm() {
                                    }
                                }, null, true).show();`
#
XPopup弹窗的时候，底部导航栏会变白色。
而原生的dialog不会变。能帮忙看下是怎么回事吗
![1111](https://user-images.githubusercontent.com/6258476/100719892-317b4400-33f8-11eb-9823-92808acd292e.png)
![2222](https://user-images.githubusercontent.com/6258476/100720252-b1091300-33f8-11eb-9ad1-bca174c31518.png)

**Comment by li-xiaojun** [comment]
实际上XPopup并未修改导航栏颜色，在你的应用theme下，导航栏就是白色的，只不过和弹窗的背景阴影对比就好像修改了颜色一样。
原生Dialog看起来没有修改，是因为原生Dialog直接覆盖了导航栏的区域，这在很多情况下是不科学不合理的，比如底部弹窗直接会覆盖导航栏。XPopup内部已经智能的处理了这一点。
所以这个其实不是问题，是一个合理的设计。
