### ISSUE TITLE
自定义CenterPopup中的EditTtext无法调起输入法

### ISSUE THREAD

**Issue by PlexPt** [li-xiaojun/XPopup#614]
**XPopup版本**
 2.2.5

**手机系统和型号**
  Android 6 模拟器

**描述你的问题**
 当设置成hasStatusBarShadow(false)时，无法弹出软键盘

new XPopup.Builder(getActivity())
                .autoDismiss(true)
                .hasStatusBarShadow(false)
                .hasNavigationBar(false)
                .autoFocusEditText(false)
                .asCustom(customPopup);

**Comment by PlexPt** [comment]
自动dismiss之后，statusBar 无法自动收起（进入全屏）

**Comment by li-xiaojun** [comment]
模拟器就是算了，模拟器本身自带各种bug

**Comment by PlexPt** [comment]
> 模拟器就是算了，模拟器本身自带各种bug

？？？
真机上一样
