### ISSUE TITLE
BottomPopupView 类型，调用dismiss后多点触控屏幕弹窗不消失情况：场景需要有时候置空BottomPopupView 对象，但是当dismiss后快速在点击弹窗任意位置，弹窗并不会消失，但此时对象已被代码置空，如何做到dismiss后弹出一定消失？

### ISSUE THREAD

**Issue by luomaa** [li-xiaojun/XPopup#617]
BottomPopupView 类型，调用dismiss后多点触控屏幕弹窗不消失情况，场景需要有时候置空BottomPopupView 对象，但是当dismiss后快速再点击弹窗屏幕任意位置，弹窗并不会消失，但此时对象已被代码置空，如何做到dismiss后弹出一定消失？ 
尝试在根布局xml添加：  android:splitMotionEvents="false" 并没有效果，如何避免当屏幕同时多点触控时，弹窗也一定会消失呢？

**Comment by li-xiaojun** [comment]
xpopup的版本是？

**Comment by luomaa** [comment]
> xpopup的版本是？

1.x版本会有以上问题，更换最新版2.x版本，正常了。应该是新版修复了此问题。谢谢！
