### ISSUE TITLE
键盘落下后,AttachPopupView还是显示在键盘升起时依附view的位置

### ISSUE THREAD

**Issue by zydjiushige** [li-xiaojun/XPopup#619]
**XPopup版本**
2.2.5
**手机系统和型号**
华为MatePad(BAH3-W09) Android 10

**描述你的问题**
最好能上代码截图和问题截图
![35714DAD-0951-4F5F-B7DD-116CF2F236EB](https://user-images.githubusercontent.com/15188362/100995320-94a0de00-3592-11eb-815e-ce1278eec9f0.png)
![E89876E1-626C-4DAE-843E-14C8E678EC9B](https://user-images.githubusercontent.com/15188362/100995335-9a96bf00-3592-11eb-8a35-73163612e8ed.png)
![DB40C2802CBEE2A01D68DFCD6EDD979E](https://user-images.githubusercontent.com/15188362/100995350-9ff40980-3592-11eb-829d-9a247444c3eb.jpg)

**Comment by li-xiaojun** [comment]
登录弹窗和选择弹窗都是用的XPopup吗，

**Comment by zydjiushige** [comment]
是的,都是用Xpopup

**Comment by li-xiaojun** [comment]
@zydjiushige 
更新到2.2.10试试
