### ISSUE TITLE
如何判断当前弹窗的显示状态

### ISSUE THREAD

**Issue by KarlLargerFeld** [li-xiaojun/XPopup#62]
如何获取当前XPopup的PopupStatus？ 
我想在show之前判断一下当前窗口是否showing，如果true，则关闭，false则show

或者能否在Xpopup类中新增一个 toggle()方法

**Comment by li-xiaojun** [comment]
@KarlLargerFeld 
每个弹窗都有个`popupStatus`变量。

**Comment by KarlLargerFeld** [comment]
`view_filter.setOnClickListener {
            context?.let { ctx ->
                val popup = XPopup.get(ctx)
                        .asCustom(object : PartShadowPopupView(ctx) {
                            override fun getImplLayoutId(): Int {
                                return R.layout.layout_collect_filter
                            }

                            override fun onCreate() {
                                super.onCreate()
                                //TODO  get checkbox instance in layout and set click listener on checkbox
                            }

                            override fun onShow() {
                                super.onShow()
                                mPopupShowing = this.popupStatus
                            }

                            override fun onDismiss() {
                                super.onDismiss()
                                mPopupShowing = this.popupStatus
                            }

                        }).atView(slidingTabLayout)
                if (mPopupShowing == PopupStatus.Show) {
                    popup.dismiss()
                } else {
                    popup.show()
                }
            }
        }`
目前通过这种方式实现了效果，但还是建议作者能够提供一个toggle()方法，方便有这种需求的朋友使用

**Comment by KarlLargerFeld** [comment]
`view_filter.setOnClickListener {
            context?.let { ctx ->
                val popup = XPopup.get(ctx)
                        .asCustom(object : PartShadowPopupView(ctx) {
                            override fun getImplLayoutId(): Int {
                                return R.layout.layout_collect_filter
                            }

                            override fun onCreate() {
                                super.onCreate()
                                //TODO  get checkbox instance in layout and set click listener on checkbox
                            }

                            override fun onShow() {
                                super.onShow()
                                mPopupShowing = this.popupStatus
                            }

                            override fun onDismiss() {
                                super.onDismiss()
                                mPopupShowing = this.popupStatus
                            }

                        }).atView(slidingTabLayout)
                if (mPopupShowing == PopupStatus.Show) {
                    popup.dismiss()
                } else {
                    popup.show()
                }
            }
        }`
目前通过这种方式实现了效果，但还是建议作者能够提供一个toggle()方法，方便有这种需求的朋友使用

**Comment by li-xiaojun** [comment]
@KarlLargerFeld 
目前弹窗增加`isShow`和`isDismiss`方法来判断状态。
