### ISSUE TITLE
红米note8pro，底部虚拟键隐藏时，底部弹框异常，无法覆盖全屏

### ISSUE THREAD

**Issue by Zyanchao** [li-xiaojun/XPopup#620]
**XPopup版本**
下载demo 运行也不行

**手机系统和型号**
红米note8pro miui [v11]

**描述你的问题**
最好能上代码截图和问题截图
红米手机 底部虚拟机隐藏时，弹框无法覆盖全屏，底部虚拟键位置无法被弹框遮盖住
效果如下
![1 1](https://user-images.githubusercontent.com/4935202/101148820-0e9b9a80-3659-11eb-8f67-8f6501608d02.jpg)

![1 4](https://user-images.githubusercontent.com/4935202/101148842-15c2a880-3659-11eb-8f43-874f0a82957a.jpg)

**Comment by Zyanchao** [comment]
华为手机如下

![1 2](https://user-images.githubusercontent.com/4935202/101147409-4d305580-3657-11eb-9100-82f39c001333.jpg)

**Comment by li-xiaojun** [comment]
更新到2.2.6试试

**Comment by lucheng0522** [comment]
已更新到2.2.10最新版本，依旧存在弹框底部无法覆盖的问题 红米note8pro miui [v11]

**Comment by zYinux** [comment]
我也遇到了，知道怎么解决吗这个

**Comment by lucheng0522** [comment]
目前作者并没有修复，自己简易实现了一个bottomdialog替换项目中的弹框。然后坐等作者修复



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zYinux"<notifications@github.com&gt;; 
发送时间: 2021年1月13日(星期三) 下午3:17
收件人: "li-xiaojun/XPopup"<XPopup@noreply.github.com&gt;; 
抄送: "路城"<1149097472@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [li-xiaojun/XPopup] 红米note8pro，底部虚拟键隐藏时，底部弹框异常，无法覆盖全屏 (#620)





 
我也遇到了，知道怎么解决吗这个

**Comment by li-xiaojun** [comment]
这款机型不太好找，云真机一直没租到这款机型，有点棘手

**Comment by li-xiaojun** [comment]
更新到最新版本试试，尝试解决了这个问题
