### ISSUE TITLE
 how can i resize the XPopup

### ISSUE THREAD

**Issue by jjarroyo** [li-xiaojun/XPopup#621]
**XPopup版本**
如2.1.0

**手机系统和型号**
华为Mate20 Android 10

**描述你的问题**
最好能上代码截图和问题截图

my XPopup
![WhatsApp Image 2020-12-05 at 9 53 15 PM](https://user-images.githubusercontent.com/5465462/101270150-5ba86b00-3744-11eb-8ccb-aaaf8da359f2.jpeg)

when opening the keyboard the title is raised

![WhatsApp Image 2020-12-05 at 9 54 57 PM](https://user-images.githubusercontent.com/5465462/101270173-898daf80-3744-11eb-8476-9907d3264e44.jpeg)

I would like to get this result, help
![ddd](https://user-images.githubusercontent.com/5465462/101270198-d5d8ef80-3744-11eb-8732-4b052f3b8af8.jpg)

**Comment by li-xiaojun** [comment]
you can use two popup to get this.
first popup，is the real Comment popup, but the EditText at bottom  is fake，maybe a TextView instead of EditText 。 when click the TextView, than show second popup.
second popup is a EditText popup,  set hasShadowBg(false) to remove the shadown background,.

**Comment by jjarroyo** [comment]
> puede usar dos ventanas emergentes para obtener esto.
> la primera ventana emergente, es la ventana emergente de comentarios real, pero el EditText en la parte inferior es falso, tal vez un TextView en lugar de EditText。 cuando haga clic en TextView, luego se muestra la segunda ventana emergente.
> La segunda ventana emergente es una ventana emergente EditText, configure hasShadowBg (false) para eliminar el fondo sombreado.


thanks using .hasShadowBg (true) works perfect

![WhatsApp Image 2020-12-06 at 11 20 17 AM](https://user-images.githubusercontent.com/5465462/101285815-461f5980-37b5-11eb-8cc0-5cb37a9b6c0a.jpeg)
