### ISSUE TITLE
XPopupUtils.moveUpToKeyboard发生空指针

### ISSUE THREAD

**Issue by TFanatic** [li-xiaojun/XPopup#623]
**XPopup版本**
2.2.2
**描述你的问题**
问题不是必现,请问下大佬这里可能是什么原因引起的？
![微信截图_20201208171057](https://user-images.githubusercontent.com/35485252/101463810-dc4fad00-3978-11eb-95cb-302c3f2de895.png)

**Comment by li-xiaojun** [comment]
这个可能是极端情况引起的NPE，我加个判断，你更新到最新版本

**Comment by li-xiaojun** [comment]
更新到2.2.10即可，已经加上了这个判断

**Comment by TFanatic** [comment]
好的,谢谢大佬！
