### ISSUE TITLE
使用BottomPopupView，有 getMaxHeight 设置弹窗最大高度，请问如何设置弹窗的最小高度？

### ISSUE THREAD

**Issue by YuYongzhi** [li-xiaojun/XPopup#624]
**XPopup版本**
如2.2.8

**手机系统和型号**
Google Pixel

**描述你的问题**

使用BottomPopupView，有 getMaxHeight 设置弹窗最大高度，请问如何设置弹窗的最小高度？

**Comment by li-xiaojun** [comment]
你直接在布局中给根View设置minHeight就行
