### ISSUE TITLE
当设置hasNavigationBar为false后,点返回键无法关闭弹窗,dismissOnBackPressed和dismissOnTouchOutside都为true

### ISSUE THREAD

**Issue by GeneralZMX** [li-xiaojun/XPopup#627]
**XPopup版本**
如2.2.11

**手机系统和型号**
所有

**描述你的问题**
如题,因为最近在做全屏应用,突然发现这个问题,我从2.2.0到2.2.11都试过都有这个问题,代码如下:
                    XPopup.Builder(requireActivity())
                        .hasStatusBar(false)
                        .hasNavigationBar(false)
                        .setPopupCallback(object : SimpleCallback() {
                            override fun onDismiss(popupView: BasePopupView?) {
                                super.onDismiss(popupView)
                                val show = GoogleInterstitialAdHelper.defaultInstance().show()
                                show.addCompletedListener {
                                    it.isSuccessful.`true` {
                                        model.close.value = model.close.value!! + 1
                                    }
                                }
                            }
                        })
                        .asCustom(Loading1Dialog(requireActivity()))
                        .show()

**Comment by li-xiaojun** [comment]
更新到2.2.12，应该修复了这个问题

**Comment by GeneralZMX** [comment]
这样好是好了  但是底部导航栏那一块会有黑色的,不是透明的

**Comment by GeneralZMX** [comment]
我发现只有bottompopview是这样的,然后我发现个新bug  bottompopview在show的一瞬间点击空白区域会消失,我设置了点击空白区域消失为false

**Comment by li-xiaojun** [comment]
@GeneralZMX 更新到2.2.13，应该修复了
