### ISSUE TITLE
requestLegacyExternalStorage 在低库别加进去啊

### ISSUE THREAD

**Issue by Wietas** [li-xiaojun/XPopup#628]
**XPopup版本**
如2.2.10

**手机系统和型号**
mumu模拟器

**描述你的问题**
AAPT: error: attribute android:requestLegacyExternalStorage not found

**Comment by Wietas** [comment]
误会你   低库compileSdkVersion 是29引起   开发也要compileSdkVersion 29 。。。。

**Comment by li-xiaojun** [comment]
compileSdkVersion >= 29

targetSdkVersion 不作要求
