### ISSUE TITLE
弹窗会导致底部导航栏的颜色改变

### ISSUE THREAD

**Issue by TwilightKHQ** [li-xiaojun/XPopup#630]
**XPopup版本**
2.2.1-2.2.11

**手机系统和型号**
Google Pixel 3 Android 9

**描述你的问题**
![device-2020-12-19-145522](https://user-images.githubusercontent.com/25874642/102683280-9d3c1a00-420a-11eb-82b0-659a23bcf9e8.png)
底部导航栏颜色
![device-2020-12-19-145536](https://user-images.githubusercontent.com/25874642/102683281-a0cfa100-420a-11eb-9572-7fa8c873b5fa.png)
弹出时底部导航栏变成原来的颜色。
在2.2.0版本是没问题的，试过2.2.1、2.2.5和2.2.11都有问题

**Comment by li-xiaojun** [comment]
看起来你在应用中修改了导航栏的颜色为蓝色，那你显示弹窗的时候应该要.navigationBarColor(蓝色)，这样弹窗的状态栏也是蓝色的了。弹窗是个Dialog，默认不设置的话显示的是Theme默认的导航栏颜色的

**Comment by TwilightKHQ** [comment]
在2.2.0中是没有问题的，之后是因为什么问题将其移除了呢？

**Comment by li-xiaojun** [comment]
2.2.0可能强制把导航栏颜色设置为透明了，看起来没问题。但这种做法存在机型兼容性问题，有些升级不行；而且有些需求要动态设置弹窗的导航栏颜色，所以增加了navigationBarColor(颜色)的方法。

**Comment by TwilightKHQ** [comment]
好的 
![image](https://user-images.githubusercontent.com/25874642/102685212-024b3c00-421a-11eb-97ec-a35a445814e3.png)

**Comment by Moster1h** [comment]
> 2.2.0可能强制把导航栏颜色设置为透明了，看起来没问题。但这种做法存在机型兼容性问题，有些机型设置透明的效果不好；而且有些需求要动态设置弹窗的导航栏颜色，所以增加了navigationBarColor(颜色)的方法。

这是假的需求,因为在清单文件中已经设置了导航栏颜色,并且我们可以自己修改导航栏颜色,而不是你内部自动切换导航栏颜色

**Comment by LnLooFa** [comment]
这个可以全局设置吗
