### ISSUE TITLE
设置hasNavigationBar为false后关闭时效果问题

### ISSUE THREAD

**Issue by qq570026938** [li-xiaojun/XPopup#631]
**XPopup版本**
如2.2.12
**手机系统和型号**
华为LDN Android 8.0

**描述你的问题**
设置hasNavigationBar为false后,点击外面关闭时，底部导航栏会会闪烁一下，弹窗消失的瞬间会快速的显示和隐藏，我在横屏的时候试的，竖屏没测试会不会这样

**Comment by li-xiaojun** [comment]
@qq570026938 更新到2.2.13试试

**Comment by qq570026938** [comment]
> @qq570026938 更新到2.2.13试试

**Comment by li-xiaojun** [comment]
更新到最新版本试试
