### ISSUE TITLE
BottomPopupView 复用，第二次 show 不会再显示

### ISSUE THREAD

**Issue by skywolfwen** [li-xiaojun/XPopup#632]
**XPopup版本**
2.2.9 之后的所有版本

**手机系统和型号**
荣耀8X Android 10；小米6 Android 9

**描述你的问题**
BottomPopupView 复用后，再次调用 show() 方法不会显示弹窗，只是背景会变暗

**Comment by li-xiaojun** [comment]
最新版本为2.2.12，经测试没有发现你这个问题

**Comment by skywolfwen** [comment]
> 最新版本为2.2.12，经测试没有发现你这个问题


https://user-images.githubusercontent.com/24934850/103068462-1f0bb900-45f8-11eb-842c-aaa235e08a72.mp4
这是我升级到 2.2.12 后的样子，如果您测试没有问题的话……那可能是我使用的姿势不对？不过 2.2.9 上却是好的，哪怕复用时的动画不太好
