### ISSUE TITLE
BottomCommentPopup 会在某些情况抢夺焦点：当模拟小孩子用五个手指同时在recyclerview （多行多列）屏幕上点击乱划触摸，BottomCommentPopup不会弹出，页面直接失去了焦点，无法效应任何点击了

### ISSUE THREAD

**Issue by luomaa** [li-xiaojun/XPopup#633]
**XPopup版本**
2.0.11

**手机系统和型号**
Android平板 5.1

**问题**--当模拟小孩子用五个手指同时在recyclerview （多行多列）屏幕上点击乱划触摸，BottomCommentPopup不会弹出，页面直接失去了焦点，无法效应任何点击了，这时候看日志，所有的日志都在，应用并没有崩溃，recyclerview 在xml 里面已经添加了android:splitMotionEvents="false" 防止多点触控，当我把弹出弹窗的代码注释后，再次模拟小孩多个手指同时点击item ，页面不会出现失去焦点的情况。

项目是一个自动售卖柜，商品展示页是recyclerview（多行多列），然后每次点击item 需要弹出购物车弹出BottomCommentPopup，现在的情况是，当正常的点击时，弹窗一直都可以正常弹出和关闭弹窗；当模拟小孩子用五个手指同时在屏幕上点击乱划触摸，BottomCommentPopup不会弹出，页面直接失去了焦点，无法效应任何点击了，这时候看日志，所有的日志都在，应用并没有崩溃，recyclerview 在xml 里面已经添加了android:splitMotionEvents="false" 防止多点触控，当我把弹出弹窗的代码注释后，再次模拟小孩多个手指同时点击item ，页面不会出现失去焦点的情况，请问如何避免这种情况发生，点击recyclerview 的item 弹出弹窗的代码：
 private void showPopup() {
        if (mBottomCommentPopup == null) {
            mBottomCommentPopup = new BottomCommentPopup(IntegralGoodsActivity.this, mCartGoodsItemList);
        }

        new XPopup.Builder(IntegralGoodsActivity.this)
                .dismissOnTouchOutside(false)
                .enableDrag(false)
                .hasShadowBg(false)
                .isRequestFocus(false)
                .asCustom(mBottomCommentPopup)
                .show();

    }

**Comment by li-xiaojun** [comment]
用最新版本，这个问题早已解决。
