### ISSUE TITLE
bottompopview的问题

### ISSUE THREAD

**Issue by GeneralZMX** [li-xiaojun/XPopup#635]
**XPopup版本**
如2.2.12

**手机系统和型号**
所有手机

**描述你的问题**
1:当设置hasNavigationBar为false后,之前是返回键没用,现在好了,但是多了个新问题,底部状态栏会留黑色的一块
2:bottompopview在show的一瞬间点击空白区域会消失,我设置了点击空白区域消失为false

**Comment by GeneralZMX** [comment]
错了  所有的弹窗都是第一个问题

**Comment by li-xiaojun** [comment]
@GeneralZMX 上个截图，不太清除你的问题，我用华为和小米手机都看不出来

**Comment by li-xiaojun** [comment]
@GeneralZMX 更新到2.2.13试试

**Comment by GeneralZMX** [comment]
> @GeneralZMX更新到2.2.13试试

![2001609402807_ pic_hd](https://user-images.githubusercontent.com/39935739/103401511-0d8c5900-4b84-11eb-86a3-e0e4c92508af.jpg)
还是一样的,底部导航栏那一块还是黑的,然后多了个新的问题,高斯模糊设置为tru无效果, centerpopview是正常的

**Comment by li-xiaojun** [comment]
更新到最新版本试试 @GeneralZMX
