### ISSUE TITLE
asInputConfirm 自定义输入框后的展示问题

### ISSUE THREAD

**Issue by aijason** [li-xiaojun/XPopup#638]
**XPopup版本**
如2.2.11

**手机系统和型号**
小米6 Android 9

**描述你的问题**
![image](https://user-images.githubusercontent.com/13975853/103518563-f6fd3f00-4eae-11eb-965e-6f67a036a59c.png)

![image](https://user-images.githubusercontent.com/13975853/103518682-2b70fb00-4eaf-11eb-9021-1753acd8ae3c.png)

自定义的布局，编译后有横线

**Comment by aijason** [comment]
InputConfirmPopupView 这个类绘制了黑色下划线，自定义布局时无法覆盖父类里的样式设置

**Comment by li-xiaojun** [comment]
把自定义布局的代码贴下

**Comment by aijason** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:paddingTop="20dp"
    android:background="@drawable/white_default_round_15"
    android:orientation="vertical">

    <TextView
        android:id="@+id/tv_title"
        android:textSize="16sp"
        android:textColor="#000000"
        android:lines="1"
        android:ellipsize="end"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:gravity="center_horizontal" />

    <TextView
        android:id="@+id/tv_content"
        android:paddingStart="20dp"
        android:paddingEnd="20dp"
        android:textColor="#6D6D6D"
        android:textSize="14sp"
        android:gravity="center"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text=""
        android:visibility="gone"/>

    <LinearLayout
        android:layout_marginStart="25dp"
        android:layout_marginEnd="25dp"
        android:layout_marginBottom="23dp"
        android:layout_marginTop="25dp"
        android:layout_width="match_parent"
        android:layout_height="30dp"
        android:background="@drawable/shape_input"
        android:gravity="center">

        <EditText
            android:id="@+id/et_input"
            android:textSize="14sp"
            android:singleLine="true"
            android:background="@null"
            android:textColorHint="#999999"
            android:textColor="#6D6D6D"
            android:textAlignment="center"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"/>

    </LinearLayout>

    <View
        android:layout_marginTop="20dp"
        android:layout_width="match_parent"
        android:id="@+id/xpopup_divider1"
        android:background="@color/_xpopup_list_divider"
        android:layout_height=".5dp"/>
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="50dp"
        android:gravity="right"
        android:orientation="horizontal">
        <TextView
            android:id="@+id/tv_cancel"
            android:textSize="16sp"
            android:text="@string/cancel"
            android:textColor="#777777"
            android:background="@drawable/cancel_selector"
            android:gravity="center"
            android:paddingTop="10dp"
            android:paddingBottom="10dp"
            android:layout_width="0dp"
            android:layout_weight="1"
            android:layout_height="match_parent" />

        <View
            android:layout_width=".5dp"
            android:id="@+id/xpopup_divider2"
            android:background="@color/_xpopup_list_divider"
            android:layout_height="match_parent"/>

        <TextView
            android:textSize="16sp"
            android:id="@+id/tv_confirm"
            android:text="@string/confirm"
            android:textColor="@color/white"
            android:gravity="center"
            android:paddingTop="10dp"
            android:paddingBottom="10dp"
            android:background="@drawable/confirm_selector"
            android:layout_width="0dp"
            android:layout_weight="1"
            android:layout_height="match_parent" />
    </LinearLayout>
</LinearLayout>`

**Comment by aijason** [comment]
把源码里画黑线部分代码注释掉就没问题的，不过我已经另外写了自定义的输入框弹窗类处理了

**Comment by li-xiaojun** [comment]
更新到最新版本即可
