### ISSUE TITLE
弹窗被推上去后不能恢复到原位！！！

### ISSUE THREAD

**Issue by ibelieve-mm** [li-xiaojun/XPopup#64]
继承 `PartShadowPopupView` 自定义了一个弹窗后，在弹窗里面有输入框，当点击了输入框键盘弹出来后，弹窗被推上去，但是当键盘收下去之后，这个弹窗却无法恢复到原位了

**Comment by li-xiaojun** [comment]
PartShadowPopupView设计的时候不适合在有输入框的场景中使用，目前没有对输入框做一些兼容处理；您可以尝试使用Bottom弹窗替代，它对输入框做了智能处理。

或者你可以截图下您的界面，我看看是什么样，给你推荐一个解决方案。

**Comment by ibelieve-mm** [comment]
您好！这是我要的效果，这个不适合用Bottom的那个

![11552025273_ pic](https://user-images.githubusercontent.com/16853817/54010934-b4338880-41ab-11e9-8b6c-36c76a3f2384.jpg)

**Comment by li-xiaojun** [comment]
@ibelieve-mm 
这种输入应该提供一个区间，让用户选择，比如：10-50万。输入的话体验差，用户自己输起来也不方便，可以和产品沟通下，这种类型的场景大都是用选择而不是输入。

**Comment by li-xiaojun** [comment]
@ibelieve-mm 
我抽空也让这种弹窗兼容下输入法弹出的情况，敬请期待。。。

**Comment by ibelieve-mm** [comment]
ok

**Comment by li-xiaojun** [comment]
@ibelieve-mm 
最新版本已经处理了输入法的问题，可以更新试试。

**Comment by ibelieve-mm** [comment]
好的👌辛苦了


ChenME

-------- 原始邮件 --------
发件人：lxj <notifications@github.com>
时间：2019年3月12日 09:58
收件人：li-xiaojun/XPopup <XPopup@noreply.github.com>
抄送：ChenME <ibelieve1210@163.com>,Mention <mention@noreply.github.com>
主题：Re: [li-xiaojun/XPopup] 弹窗被推上去后不能恢复到原位！！！ (#64)

**Comment by threedeer** [comment]
我这边使用Bottom弹窗第一次不能恢复，然后每次都可以。这是为什么
