### ISSUE TITLE
 ConfirmPopupView 报内存泄露

### ISSUE THREAD

**Issue by kulong51** [li-xiaojun/XPopup#641]
**XPopup版本**
如2.2.13

**手机系统和型号**
华为vivo x9i  Android 7.1.2

**描述你的问题**
┬───
    │ GC Root: System class
    │
    ├─ com.lxj.xpopup.core.BasePopupView class
    │    Leaking: NO (a class is never leaking)
    │    ↓ static BasePopupView.stack
    │                           ~~~~~
    ├─ java.util.Stack instance
    │    Leaking: UNKNOWN
    │    Retaining 1208112 bytes in 9806 objects
    │    ↓ Stack.elementData
    │            ~~~~~~~~~~~
    ├─ java.lang.Object[] array
    │    Leaking: UNKNOWN
    │    Retaining 1208088 bytes in 9805 objects
    │    ↓ Object[].[0]
    │               ~~~
    ├─ com.lxj.xpopup.impl.ConfirmPopupView instance
    │    Leaking: YES (View.mContext references a destroyed activity)
    │    Retaining 549754 bytes in 4866 objects
    │    View not part of a window view hierarchy
    │    View.mAttachInfo is null (view detached)
    │    View.mWindowAttachCount = 1
    │    mContext instance of com.xxx.xx.ui.activity.xxActivity with mDestroyed = true
    │    ↓ ConfirmPopupView.mContext

使用方式如下：
        new XPopup.Builder(mContext)
                .isDestroyOnDismiss(true)
                .dismissOnTouchOutside(false)
                .autoDismiss(true)
                .dismissOnBackPressed(true)
                .setPopupCallback(new SimpleCallback() {
                    @Override
                    public void onCreated(BasePopupView popupView) {
                        ((ConfirmPopupView) popupView).getConfirmTextView().setTextColor(Color.parseColor("#FF7D00"));
                    }
                })
                .asConfirm(getString(R.string.prompt_message), getString(R.string.gather_service_running),
                        getString(R.string.navigation_cancel), getString(R.string.confirm),
                        () -> {
                          //do something 
                        }, null, false).show();

**Comment by li-xiaojun** [comment]
@kulong51 是直接关闭Activity的场景吗？

**Comment by kulong51** [comment]
是的

**Comment by kulong51** [comment]
> @kulong51 是直接关闭Activity的场景吗？

是的

**Comment by li-xiaojun** [comment]
@kulong51 更新到2.2.14试试

**Comment by kulong51** [comment]
> @ kulong51更新到2.2.14试试
2.2.14 版本验证无此问题
