### ISSUE TITLE
自定义大图弹窗设置长按后导致滑动无效

### ISSUE THREAD

**Issue by Dreamxhx** [li-xiaojun/XPopup#645]
我写了个view全屏盖住 ：
    <TextView
        android:id="@+id/tv_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>
设置的TextView长按事件后，不能操作图片的滑动了

CustomImageViewerPopup imageViewerPopup = new CustomImageViewerPopup(this);
            imageViewerPopup.setImageUrls(list);
            imageViewerPopup.setSrcView((ImageView) view, position);
            imageViewerPopup.setXPopupImageLoader(new XpopImageLoader());
            imageViewerPopup.isShowSaveButton(false);
            imageViewerPopup.isShowPlaceholder(false);
            imageViewerPopup.setSrcViewUpdateListener(new OnSrcViewUpdateListener() {
                @Override
                public void onSrcViewUpdate(@NonNull ImageViewerPopupView popupView, int position) {
                    popupView.updateSrcView((ImageView) view);
                }
            });
            new XPopup.Builder(getContext())
                    .asCustom(imageViewerPopup)
                    .show();

**Comment by li-xiaojun** [comment]
全屏盖住了肯定会影响事件的传递。

**Comment by Dreamxhx** [comment]
那怎么实现长按保存图片功能呢？

**Comment by li-xiaojun** [comment]
自定义大图弹窗，布局随便写，看文档或demo
