### ISSUE TITLE
CenterPopupView中show方法先于getImplLayoutId和onCreate方法执行

### ISSUE THREAD

**Issue by AdamTaurus** [li-xiaojun/XPopup#646]
**XPopup版本**
2.2.13

**手机系统和型号**
自研设备 Android8.0

**问题描述**
当我想在show方法调用后立刻对view进行操作时，这时候onCreate未执行，会导致异常。

例如继承自CenterPopupView：
 fun showLoading(type: Int = 0, text: String = "") {
        Log.i(tag,"showLoading")
        //init()
        show()
        iv_connecting.visibility = GONE
    }
在调用show方法时，不手动调用父类的init方法会抛出iv_connecting值为空的异常，因为CenterPopupView中init是在show方法中通过handler运行的。

继承BaseFullScreenPopupView类则不会有这个问题

**Comment by li-xiaojun** [comment]
自定义弹窗的逻辑最好在弹窗内部的onCreate中编写。
如果非要在外面写，可以给弹窗设置监听器，在弹窗的onCreated回调方法中编写

**Comment by AdamTaurus** [comment]
> 自定义弹窗的逻辑最好在弹窗内部的onCreate中编写。
> 如果非要在外面写，可以给弹窗设置监听器，在弹窗的onCreated回调方法中编写

好的，明白了。因为要在show的时候传参，比如不同loading文字这种，如果放在创建方法中，那就每次都需要新建对象了。
