### ISSUE TITLE
XPopup内使用RecyclerView嵌套RecyclerView显示不全

### ISSUE THREAD

**Issue by Arms-merchants** [li-xiaojun/XPopup#647]
**XPopup版本**
2.2.13

**手机系统和型号**
华为Mate10 Android 10

**描述你的问题**
![Screenshot](https://user-images.githubusercontent.com/20468592/104556905-514e8a80-567b-11eb-9a07-ab2dc7aa9686.jpg)
你好在使用xpop中的弹窗进行了RecyclerView嵌套RecyclerView的操作，但是最终的效果是最后一个显示不全
popup的代码
class ProcessRecordPopup(context: Context) : BottomPopupView(context) {

    override fun getImplLayoutId(): Int {
        return R.layout.popup_process_record
    }

    override fun onCreate() {
        super.onCreate()
        val rv = findViewById<RecyclerView>(R.id.rv)
        val data = arrayListOf<String>()
        for (i in 0..2) {
            data.add("current:$i")
        }
        val adapter = ProcessRecordAdapter(data)
        rv.adapter = adapter
    }

    class ProcessRecordAdapter(data: ArrayList<String>?) :
        BaseQuickAdapter<String, BaseDataBindingHolder<ItemProcessRecordBinding>>(
            R.layout.item_process_record,
            data
        ) {

        override fun convert(
            holder: BaseDataBindingHolder<ItemProcessRecordBinding>,
            item: String
        ) {
            val binding = holder.dataBinding
            binding?.apply {
                tvPointName.text = item
                val testCount = holder.adapterPosition + 1
                rvContent.isNestedScrollingEnabled = false
                val testData = arrayListOf<String>()
                for (i in 0 until testCount) {
                    testData.add("测试$i")
                }
                val pointAdapter = ProcessRecordPointAdapter(testData)
                rvContent.adapter = pointAdapter
            }
        }
    }

    class ProcessRecordPointAdapter(data: ArrayList<String>?) :
        BaseQuickAdapter<String, BaseDataBindingHolder<ItemProcessRecordPointBinding>>(
            R.layout.item_process_record_point,
            data
        ) {

        override fun convert(
            holder: BaseDataBindingHolder<ItemProcessRecordPointBinding>,
            item: String
        ) {
            val binding = holder.dataBinding
            binding?.apply {
                tvName.text = item
                tvContent.text = "测试$holder.adapterPosition"
                tvTime.text = "2021.1.1"
            }
        }
    }
}
两个item布局：
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools">

    <data>

    </data>

    <androidx.constraintlayout.widget.ConstraintLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="10dp">

        <ImageView
            android:id="@+id/iv_status"
            android:layout_width="16dp"
            android:layout_height="16dp"
            android:src="@drawable/ic_edit_delete"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent" />

        <TextView
            android:id="@+id/tv_point_name"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginStart="10dp"
            android:textColor="@color/common_text_deep"
            android:textSize="15sp"
            app:layout_constraintBottom_toBottomOf="@id/iv_status"
            app:layout_constraintStart_toEndOf="@id/iv_status"
            app:layout_constraintTop_toTopOf="@id/iv_status"
            tools:text="@string/use" />

        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/rv_content"
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            android:layout_marginTop="20dp"
            android:orientation="vertical"
            app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager"
            app:layout_constraintStart_toStartOf="@id/tv_point_name"
            app:layout_constraintTop_toBottomOf="@id/tv_point_name" />

        <Space
            android:id="@+id/space"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginTop="20dp"
            app:layout_constraintTop_toBottomOf="@id/rv_content" />

        <View
            style="@style/vLineView"
            android:layout_width="2dp"
            android:layout_height="0dp"
            app:layout_constraintBottom_toTopOf="@id/space"
            app:layout_constraintEnd_toEndOf="@id/iv_status"
            app:layout_constraintStart_toStartOf="@id/iv_status"
            app:layout_constraintTop_toBottomOf="@id/iv_status" />

    </androidx.constraintlayout.widget.ConstraintLayout>
</layout>

<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">

    <data>

    </data>

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical">

        <TextView
            android:id="@+id/tv_name"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginTop="15dp"
            android:includeFontPadding="false"
            android:textColor="@color/color_666666"
            android:textSize="16sp"
            tools:text="1111" />

        <TextView
            android:id="@+id/tv_content"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginTop="10dp"
            android:includeFontPadding="false"
            android:textColor="@color/common_text_light"
            android:textSize="12sp"
            tools:text="111" />

        <TextView
            android:id="@+id/tv_time"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginTop="10dp"
            android:includeFontPadding="false"
            android:textColor="@color/common_text_light"
            android:textSize="12sp"
            tools:text="1111" />

    </LinearLayout>
</layout>

**Comment by li-xiaojun** [comment]
把布局放Activity试试，看看是不是布局的问题
