### ISSUE TITLE
横屏下字体变大问题

### ISSUE THREAD

**Issue by qq570026938** [li-xiaojun/XPopup#649]
**XPopup版本**
如2.1.3

**手机系统和型号**
华为LDN-AL00 安卓8.0

**描述你的问题**
在横屏状态下，切换到桌面，在返回到应用，自定义的popupview字体会变大

**Comment by li-xiaojun** [comment]
这个不是弹窗的问题吧，弹窗就是个dialog，看看你是不是用了什么适配框架导致的

**Comment by qq570026938** [comment]
> 这个不是弹窗的问题吧，弹窗就是个dialog，看看你是不是用了什么适配框架导致的

嗯，用了个今日头条的那个适配框架，不知道是不是它有影响
