### ISSUE TITLE
能不能定义AppCompat主题？

### ISSUE THREAD

**Issue by tmxd09887** [li-xiaojun/XPopup#65]
目前的样式是白色底的。

谢谢

**Comment by li-xiaojun** [comment]
@tmxd09887 
目前支持primaryColor的设置，但是这个颜色不改变背景色。如果背景色允许你改的话，那你可能设置各种颜色，那么弹窗里面的文字颜色我无法判断该如何设置，所以目前不支持设置背景色。不过后面会增加白色主题和黑色主题。

**Comment by tmxd09887** [comment]
谢谢
