### ISSUE TITLE
自定义BottomPopupView反复弹起关闭几次后,整个页面无法再响应事件

### ISSUE THREAD

**Issue by BreezeAndMoon** [li-xiaojun/XPopup#650]
**XPopup版本**
2.2.10

**手机系统和型号**
华为Mate20 Android 10,小米5,其他手机应该也一样

**描述你的问题**
//弹起事件(为了保存状态,复用了自定义弹窗view,即mCropWhitePopupView，测试发现如果不复用倒是正常)
 val cropPopupView = XPopup.Builder(context).hasShadowBg(false).dismissOnBackPressed(false).dismissOnTouchOutside(false).enableDrag(false).asCustom(mCropWhitePopupView)
            cropPopupView.show()
//关闭事件(禁用了点击外部关闭,只能在自定义弹窗View中点击关闭按钮关闭)
class CropWhitePopupView(context: Context) : BottomPopupView(context) {
override fun onCreate() {
            findViewById<ImageView>(R.id.img_close).click{
                dismiss()
            }
}
}

**Comment by li-xiaojun** [comment]
测试多次无法复现，可以录个视频发到群里
