### ISSUE TITLE
Demo的显示自由定位Position弹窗, offsetXY失效

### ISSUE THREAD

**Issue by yatw** [li-xiaojun/XPopup#651]
**XPopup版本**
2.2.14

**手机系统和型号**
所有

**描述你的问题**
![Screenshot_2021-01-20-21-16-18-344_com lxj xpopupdemo 1](https://user-images.githubusercontent.com/19565177/105283287-ffb76b80-5b64-11eb-94b5-651e70414cac.jpg)

2.2.6版本Demo还是好的,但是如果  
`implementation 'com.lxj:xpopup:2.2.6'`  到另一個小項目  
仍然有同样的问题  

.popupAnimation(PopupAnimation.TranslateFromLeft)  

![image](https://user-images.githubusercontent.com/19565177/105283520-7d7b7700-5b65-11eb-8a28-419febe77ffe.png)  
注释掉popupAnimationoffsetXY又有效了

**Comment by yatw** [comment]
有其他人有这个问题吗？這是最新版本demo

**Comment by yatw** [comment]
总结一下, 旧版本2.2.5demo正常,  旧版本2.2.5 import 到另一個小項目有问题, 新版本2.2.14有同样的问题  
小项目只是最简单的PositionPopupView  
![image](https://user-images.githubusercontent.com/19565177/105647489-eb23ed80-5e5a-11eb-81f4-2ec39ed621a6.png)  
![image](https://user-images.githubusercontent.com/19565177/105647506-14dd1480-5e5b-11eb-9930-d39cd5aab77e.png)


我看一下代碼，用debugger比較了旧版本2.2.5demo和小項目


2.2.5demo 正常步骤
1. PositionPopupView.initPopupContent() called
2. XpopupUtils.applyPopupSize called
3. XpopupUtils.applyPopupSize 里面的 afterApplySize.run()  执行 
4. PositionPopupView.initPopupContent 里面的 run() setTranslationXY
5. BasePopupView.initTask()  -> BasePopupView.this.doShowAnimation();
6. TranslateAnimator.animateShow() use the XY set from step 4

2.2.5小項目 错误步骤 <- 2.2.14 错误也是相同
1. PositionPopupView.initPopupContent() called
2. XpopupUtils.applyPopupSize called
3. BasePopupView.initTask()  -> BasePopupView.this.doShowAnimation();
4. TranslateAnimator.animateShow() using XY 0,0
5. XpopupUtils.applyPopupSize 里面的 afterApplySize.run()  执行 
6. PositionPopupView.initPopupContent 里面的 run() setTranslationXY


看起来像一些asyncTask次序问题, 
当次序错误时，PositionPopupView.initPopupContent在动画显示后才设置XY

**Comment by li-xiaojun** [comment]
@yatw 更新到2.2.16即可
