### ISSUE TITLE
   implementation 'com.lxj:xpopup:2.2.14' 关闭 enableDrag(false)后，点击弹窗外部无法关闭弹窗

### ISSUE THREAD

**Issue by BugRui** [li-xiaojun/XPopup#652]
implementation 'com.lxj:xpopup:2.2.14' 

关闭 enableDrag(false)后，点击弹窗外部无法关闭弹窗

**Comment by li-xiaojun** [comment]
经测试发发现没有这个问题，可以贴下你的代码

**Comment by BugRui** [comment]
XPopup.Builder(this)
                .hasShadowBg(true)
                .autoFocusEditText(false)
                .enableDrag(false)
                .popupPosition(PopupPosition.Right)
                .asCustom(popup)
                .show()

**Comment by BugRui** [comment]
这里的popup是一个DrawerPopupView，

**Comment by BugRui** [comment]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/container"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/colorWhite"
    android:orientation="vertical">

    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1">

        <com.bugrui.library.MultiTypeLayout
            android:id="@+id/multi_type_layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

        <ScrollView
            android:id="@+id/scrollView"
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:orientation="vertical">

                <View
                    android:id="@+id/viewTop"
                    android:layout_width="0dp"
                    android:layout_height="0dp" />


                <com.syc.slms.widget.customWidget.CustomWidgetFormLayout
                    android:id="@+id/widgetFormLayout"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:paddingStart="15dp"
                    android:paddingEnd="15dp"
                    android:paddingBottom="15dp" />

            </LinearLayout>

        </ScrollView>

    </FrameLayout>


    <View style="@style/viewLien" />

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="44dp"
        android:orientation="horizontal">

        <TextView
            android:id="@+id/tvClear"
            android:layout_width="0dp"
            android:layout_height="match_parent"
            android:layout_weight="2"
            android:gravity="center"
            android:text="清空"
            android:textColor="@color/color666666"
            android:textSize="17sp" />

        <TextView
            android:id="@+id/tvConfirm"
            android:layout_width="0dp"
            android:layout_height="match_parent"
            android:layout_weight="3"
            android:background="@color/colorFF3D7BED"
            android:gravity="center"
            android:text="确认"
            android:textColor="@color/colorWhite"
            android:textSize="17sp" />
    </LinearLayout>
</LinearLayout>

**Comment by BugRui** [comment]
class ServiceOrderFilterPopupView(context: Context) : BaseDrawerPopupView(context) {

    override fun getImplLayoutId(): Int = R.layout.popup_service_order_filter

    private val viewModel by context.findActivity()?.viewModels<ServiceOrderFilterViewModel>()

    private lateinit var container: LinearLayout
    private lateinit var viewTop: View
    private lateinit var mMultiTypeLayout: MultiTypeLayout
    private lateinit var scrollView: ScrollView
    private lateinit var widgetFormLayout: CustomWidgetFormLayout

    private var mCallback: OnCallback? = null


    override fun onCreate() {
        super.onCreate()
        container = findViewById(R.id.container)
        viewTop = findViewById(R.id.viewTop)
        mMultiTypeLayout = findViewById(R.id.multi_type_layout)
        scrollView = findViewById(R.id.scrollView)
        widgetFormLayout = findViewById(R.id.widgetFormLayout)

        container.setParams(width = context.screenWidth / 10 * 8, height = layoutMatchParent)
        viewTop.setParams(width = 0, height = context.statusBarHeight)

        mMultiTypeLayout.loadDefaultLayout(context)

        findViewById<TextView>(R.id.tvClear).setOnClickListener {
            widgetFormLayout.removeAllViews()
            getCustomForm()
        }
        findViewById<TextView>(R.id.tvConfirm).setOnClickListener {
            mCallback?.onCallback(widgetFormLayout.getAllConditions())
            dismiss()
        }
    }

 


}
