### ISSUE TITLE
BottomPopupView 里面的 RecyclerView 无法全部显示，需要手动拖上去

### ISSUE THREAD

**Issue by wangrui460** [li-xiaojun/XPopup#653]
**XPopup版本**
如2.1.0

**手机系统和型号**
华为Mate20 Android 10

**描述你的问题**
BottomPopupView 里面的 RecyclerView 无法全部显示，需要手动拖上去，如何直接全部展示，毕竟只有几个item

这是有问题的：
![image](https://user-images.githubusercontent.com/11909313/105472413-de768c80-5cd6-11eb-87e3-64766fa57b6a.png)

这是手动拖上去的：
![image](https://user-images.githubusercontent.com/11909313/105472501-fa7a2e00-5cd6-11eb-9f93-425b507fe38d.png)

**Comment by li-xiaojun** [comment]
布局高度设置为wrap，然后看需要给弹窗设置个最大高度

**Comment by wangrui460** [comment]
是wrap啊
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
	android:layout_width="match_parent"
	android:layout_height="wrap_content"
	xmlns:app="http://schemas.android.com/apk/res-auto"
	android:background="@color/bg_white"
	android:orientation="vertical">

	<com.google.android.material.appbar.AppBarLayout
		android:layout_width="match_parent"
		android:layout_height="wrap_content"
		app:elevation="0dp"
		android:background="@color/bg_white">

		<TextView
			android:id="@+id/tv_title"
			android:layout_marginTop="@dimen/dp_25"
			android:layout_marginStart="@dimen/dp_20"
			android:layout_width="match_parent"
			android:layout_height="wrap_content"
			android:text="文中提到的"
			android:maxLines="1"
			android:ellipsize="end"
			android:textColor="#4E4D4D"
			android:textStyle="bold"
			android:textSize="@dimen/sp_15" />
	</com.google.android.material.appbar.AppBarLayout>

	<com.scwang.smartrefresh.layout.SmartRefreshLayout
		android:background="@color/bg_white"
		app:srlEnablePureScrollMode="true"
		android:layout_width="match_parent"
		android:layout_height="wrap_content">

		<RelativeLayout
			android:orientation="vertical"
			android:layout_width="match_parent"
			android:layout_height="wrap_content">

			<androidx.recyclerview.widget.RecyclerView
				android:id="@+id/rv"
				android:nestedScrollingEnabled="false"
				android:overScrollMode="never"
				android:layout_width="match_parent"
				android:layout_height="wrap_content" />
		</RelativeLayout>
	</com.scwang.smartrefresh.layout.SmartRefreshLayout>

</LinearLayout>`

**Comment by ZakAnun** [comment]
> **XPopup版本**
> 如2.1.0
> 
> **手机系统和型号**
> 华为Mate20 Android 10
> 
> **描述你的问题**
> BottomPopupView 里面的 RecyclerView 无法全部显示，需要手动拖上去，如何直接全部展示，毕竟只有几个item
> 
> 这是有问题的：
> ![image](https://user-images.githubusercontent.com/11909313/105472413-de768c80-5cd6-11eb-87e3-64766fa57b6a.png)
> 
> 这是手动拖上去的：
> ![image](https://user-images.githubusercontent.com/11909313/105472501-fa7a2e00-5cd6-11eb-9f93-425b507fe38d.png)

你好，请问这个问题有解决了吗？我用 ConstraintLayout 包裹 RecyclerView，ConstraintLayout 高度设置为 wrap_content，RecyclerView 也设置为 wrap_content，并且给了宽高比，就不能全部弹出来，但是 RecyclerView 高度设置为 0 就可以（因为有宽高比设置的固定高度）

**Comment by li-xiaojun** [comment]
@wangrui460  @ZakAnun 更新到最新版本试试
