### ISSUE TITLE
能再指定的容器中展示吗

### ISSUE THREAD

**Issue by liukai2530533** [li-xiaojun/XPopup#655]
**XPopup版本**
如2.2.10

**手机系统和型号**
华为Mate20 Android 10

**描述你的问题**
之前的版本我可以修改Xpopup的容器 展示到到我自定义的FrameLayout中，现在到2.0+版本没办法这么指定了。我想问问如果我不想让Xpopup在Activity的Window上展示，我想让Xpopup再我定义的一个FrameLayout中展示，该怎么实现？

**Comment by li-xiaojun** [comment]
2.0不行了。底层是dialog了
