### ISSUE TITLE
從v2.0.0起,BasePopUpView扩展的PositionPopupView类offsetY沒效

### ISSUE THREAD

**Issue by yatw** [li-xiaojun/XPopup#657]
**XPopup版本**
v2.0.0起

**手机系统和型号**
samsung SM-T290, Xiaomi Redmi 7, 所有

**描述你的问题**
## 这是一个从v2.0.0开始一直存在的问题

1. 從release版下载v2.0.0demo  
![image](https://user-images.githubusercontent.com/19565177/105909059-e8043b00-5fdb-11eb-81f8-4f41fbc32361.png)

2. 在fragment/QuickStartDemo, Position自由定位弹窗 set XY  
![image](https://user-images.githubusercontent.com/19565177/105908844-8f34a280-5fdb-11eb-9d71-f49047deab43.png)

3. 在xpopup创建PositionPopupView2, **代码与PositionPopupView完全一样**    
![image](https://user-images.githubusercontent.com/19565177/105909443-6cef5480-5fdc-11eb-82d3-250d14543930.png)

4 QQMsgPopup 不继承 PositionPopupView, 继承我自己的PositionPopupView2  
![image](https://user-images.githubusercontent.com/19565177/105910061-42ea6200-5fdd-11eb-90f5-4063f62b4f82.png)

# offsetX有效, offsetY沒效
![Screenshot_20210126-133424_XPopup 1](https://user-images.githubusercontent.com/19565177/105908650-54cb0580-5fdb-11eb-835b-df10b7cbda86.jpg)

继承 xpopup的PositionPopupView,没问题  
如果继承我自己的PositionPopupView2, offsetY就沒效了
PositionPopupView2和PositionPopupView的代码是完全相同的

## 相同的步骤，在v1.9.12中，没问题
能调查为什么吗，非常感谢

我不能直接使用使用PositionPopupView的原因是因为我的项目没有xml布局，只有以编程方式生成的View  
所以我需要创建自己的类处理布局,不能使用getImplLayoutId()

**Comment by li-xiaojun** [comment]
@yatw 更新到2.2.15版本即可

**Comment by yatw** [comment]
2.2.15仍然不好，demo的PositionPopupView offsetXY都沒效了

**Comment by li-xiaojun** [comment]
@yatw 更新到2.2.16即可

**Comment by yatw** [comment]
release 还没有2.2.16, 更新后我马上测试
![image](https://user-images.githubusercontent.com/19565177/106086548-38ac8e80-60d7-11eb-84c5-026e06806f9a.png)

**Comment by yatw** [comment]
@li-xiaojun 
release 的 2.2.16 仍然不好，demo的PositionPopupView offsetXY都没效了  
release 的 2.2.17 demo的显示自由定位Position弹窗 offsetXY没问题了 , 但是如果继承自己的PositionPopupView2, offsetY仍然沒效 (offsetX有效)  

如果不是很麻烦，可以告诉我问题的原因么?谢谢
