### ISSUE TITLE
PositionPopupView 不显示

### ISSUE THREAD

**Issue by zqlq4ever** [li-xiaojun/XPopup#659]
**XPopup版本**
2.2.16

**手机系统和型号**
任何手机

**描述你的问题**
继承自 PositionPopupView 的 pop,只有第一次会显示,消失后,再次点击按钮,没任何反应.
2.2.14 没任何问题

主要代码如下:
![微信图片_20210129141910](https://user-images.githubusercontent.com/37474811/106239353-6f9cb480-623d-11eb-8a50-568ae00481dc.png)

**Comment by li-xiaojun** [comment]
更新到2.2.18即可
