### ISSUE TITLE
androidManifest里能不能不要添加悬浮窗权限？

### ISSUE THREAD

**Issue by jingzz1** [li-xiaojun/XPopup#660]
等需要的时候，在主module里添加，否则app明明不需要悬浮框功能，上传到应用市场，依旧被解析出悬浮框敏感权限

**Comment by zqlq4ever** [comment]
> 等需要的时候，在主module里添加，否则app明明不需要悬浮框功能，上传到应用市场，依旧被解析出悬浮框敏感权限

可以在自己项目里加移除配置

**Comment by li-xiaojun** [comment]
更新到2.2.18即可，已移除权限
