### ISSUE TITLE
AttachPopupView 宽贴边时，显示不全

### ISSUE THREAD

**Issue by zqlq4ever** [li-xiaojun/XPopup#662]
**XPopup版本**
2.2.18

**手机系统和型号**
所有机型

**描述你的问题**
![贴边](https://user-images.githubusercontent.com/37474811/106419755-1d090580-6494-11eb-9d5c-ca27384002a2.png)

点击整个 item 时
![111](https://user-images.githubusercontent.com/37474811/106420801-5c385600-6496-11eb-83b9-c41d1ac3cbc5.png)

**Comment by li-xiaojun** [comment]
把显示弹窗的代码贴下

**Comment by zqlq4ever** [comment]
> 把显示弹窗的代码贴下

转移主持人弹窗的代码
![微信截图_20210222104128](https://user-images.githubusercontent.com/37474811/108650456-94154500-74fa-11eb-9ce0-197b5a7ae9aa.png)

**Comment by li-xiaojun** [comment]
是不是offsetX引起的？

**Comment by zqlq4ever** [comment]
> 是不是offsetX引起的？

不是的，加 offsetX 的原因，就是因为右边被遮住了部分，我把它强制移出来

**Comment by li-xiaojun** [comment]
问题还在吗

**Comment by zqlq4ever** [comment]
> 问题还在吗

离职了，哈哈哈。公司代码没了，没法验证。
