### ISSUE TITLE
recycleview上弹出中间输入框弹框，点击完成后输入法再次弹出

### ISSUE THREAD

**Issue by LuoGuoXin** [li-xiaojun/XPopup#663]
**XPopup版本**
如2.1.0

**手机系统和型号**
小米10 Android 11

**描述你的问题**
就是在recycleview上面的一个item，里面一个评论按钮，点击了，然后弹出中间输入框的弹框。输入完成，点击完成或者取消，都会先消失弹窗，但是输入法会先隐藏，然后马上又弹出来。

**Comment by li-xiaojun** [comment]
更新到最新版本试试
