### ISSUE TITLE
全屏后dialog导航条不应该出现关闭的动画

### ISSUE THREAD

**Issue by mengzhidaren** [li-xiaojun/XPopup#664]
**XPopup版本**
2.2.18

**手机系统和型号**
rk3288平板

**描述你的问题**
在全屏的主题下导航条是不显示的，但是弹窗配置不显示导航条后会执行一个导航条向下关闭的动画，视觉上闪烁了一下

**Comment by li-xiaojun** [comment]
@mengzhidaren 更新到最新版本试试，应该修复了

**Comment by mengzhidaren** [comment]
好的 谢谢
