### ISSUE TITLE
2.2.19, 1.BottomPopupView设置高斯模糊无效  2.FullScreenPopupView 复用dialog第二次弹出不显示内容

### ISSUE THREAD

**Issue by GeneralZMX** [li-xiaojun/XPopup#666]
**XPopup版本**
如2.2.19

**手机系统和型号**
所有
**描述你的问题**
1.BottomPopupView设置高斯模糊无效  
2.FullScreenPopupView 复用dialog第二次弹出不显示内容

**Comment by li-xiaojun** [comment]
更新到2.2.23即可
