### ISSUE TITLE
Recyclerview里面使用updateSrcView(ImageView srcView)，如果开启isInfinite(true)，会出现数组越界

### ISSUE THREAD

**Issue by DNJusername** [li-xiaojun/XPopup#667]
**XPopup版本**
版本：2.2.5

**描述你的问题**
查看发现，应该是
public void updateSrcView(ImageView srcView) {
        setSrcView(srcView, position);
        addOrUpdateSnapshot();
 }中setSrcView(srcView, position)的position，没有使用(position % list.size())导致的,不知道是否这样，我测试了一下，
开启轮播，先手动调用setSrcView(srcView, position%list.size()),再调用updateSrcView(ImageView srcView)，没有出现数据越界异常

**Comment by li-xiaojun** [comment]
把报错信息贴下

**Comment by DNJusername** [comment]
![图1](https://user-images.githubusercontent.com/37464240/108823008-d32abf80-75fa-11eb-93b5-f8b45f83a6a6.jpg)
![图2](https://user-images.githubusercontent.com/37464240/108823019-d8880a00-75fa-11eb-8e62-402039ce8ccf.jpg)

**Comment by DNJusername** [comment]
> 把报错信息贴下

![图1](https://user-images.githubusercontent.com/37464240/108823072-eb024380-75fa-11eb-8f20-b5dbec5a0693.jpg)
![图2](https://user-images.githubusercontent.com/37464240/108823079-ef2e6100-75fa-11eb-951b-bc57de8a8e1e.jpg)

**Comment by li-xiaojun** [comment]
直接recycler.getChildAt(position) 试试。

**Comment by DNJusername** [comment]
> 直接recycler.getChildAt(position) 试试。

之前用的recycler.getChildAt(position)，也是报这个错误，用recycler.getChildAt(position % list.size)同样是报这个错误。后面我手动调用setSrcView(srcView, position)，对position重新赋值position % list.size，就没有这个数组越界了

**Comment by li-xiaojun** [comment]
我试了试没有这个问题，更新到最新版试试
