### ISSUE TITLE
请问，怎么动态设置dismissOnBackPressed

### ISSUE THREAD

**Issue by jingzz1** [li-xiaojun/XPopup#668]
弹窗弹出后，需要根据用户操作动态设置 是否按返回键关闭弹窗
代码设置 popupInfo.isDismissOnBackPressed = false 无效
请问，有办法设置吗?

**Comment by li-xiaojun** [comment]
逻辑复杂的话，你可以设置XPopup的listener，重写onBackPressed方法，返回true，这样按返回键弹窗就不消失了。
然后你根据你的逻辑在适当时候让弹窗dismiss()

**Comment by jingzz1** [comment]
其实逻辑也不复杂，就像普通的dialog 动态调用setCanceledOnTouchOutside和setCancelable方法一样
每个dialog持有一个popupInfo，结果popupInfo在弹窗之后就无法修改，这样使用很不灵活啊
