### ISSUE TITLE
basePopupDialog能不能提供动态显示或隐藏背景阴影的api?

### ISSUE THREAD

**Issue by 9292922** [li-xiaojun/XPopup#671]
有的时候，需要在弹窗上再显示一个弹窗，但是两个弹窗都有阴影的话，会导致阴影重叠，用户肉眼可见颜色加深变化，影响视感。

当然，把前置窗口阴影去掉也行，但是这样子做就会导致某些地方没有阴影出现更加难看的情况。

所以如果可以在内部提供显示或隐藏阴影的api就可以轻松解决了，在弹出前置dialog前先隐藏自身的，前置窗口dismiss后再显示阴影。这些由程序员调控即可

**Comment by li-xiaojun** [comment]
2.3.6版本支持给每个弹窗设置不同的阴影值
