### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by KiWiLss** [li-xiaojun/XPopup#677]
**XPopup版本**
如2.2.20

**手机系统和型号**
 荣耀 9x  Android 10

**描述你的问题**
引入随意使用都会出现内存泄漏，下载 Xpopup 使用一样会出现。
![Screenshot_20210224_154401_com lxj xpopupdemo](https://user-images.githubusercontent.com/28781114/108965336-b1434280-76b7-11eb-910f-36624b687d4e.jpg)
![Screenshot_20210224_152626_com kiwilss wanandroid](https://user-images.githubusercontent.com/28781114/108965452-d637b580-76b7-11eb-9214-254d3fc893b6.jpg)

**Comment by li-xiaojun** [comment]
试试2.2.22版本

**Comment by zhangjianzhu** [comment]
我用的2.2.23版本 自定义继承的BottomPopupView 内存泄漏问题 必现耶

**Comment by li-xiaojun** [comment]
查看wiki-常见问题
