### ISSUE TITLE
需求：希望在bottompopup 新增一个取消的按钮

### ISSUE THREAD

**Issue by wlingf** [li-xiaojun/XPopup#678]
假设需求场景：
    上传用户头像,用bottompopup,又没有取消的按钮，传自定义布局，取消按钮的点击事件又没办法设置，只能通过自定义popup,但是就这么简单的样式，感觉没必要自定义，希望作者可以内置一个这样的UI

**Comment by li-xiaojun** [comment]
@wlingf 更新到最新版本即可
