### ISSUE TITLE
Confirm弹窗是否可以有一种只有一个按钮的弹窗

### ISSUE THREAD

**Issue by franticn** [li-xiaojun/XPopup#68]
用于给用户展示消息

**Comment by li-xiaojun** [comment]
@franticn 
下个版本添加此功能。

**Comment by zhaoxiuyu** [comment]
Demo 代码 还没看，目前只体验了 APK 程序， 只有一个 按钮的弹窗  是在自定义里面的，如果只有一个按钮的展示性信息弹窗，还需要自定义，确实不太方便。

**Comment by franticn** [comment]
> @franticn
> 下个版本添加此功能。

多谢，祝生活愉快

**Comment by li-xiaojun** [comment]
@franticn @zhaoxiuyu 
最新版本asConfirm方法增加isHideCancel选项，为true就只显示一个button.

**Comment by franticn** [comment]
> @franticn @zhaoxiuyu
> 最新版本asConfirm方法增加isHideCancel选项，为true就只显示一个button.

收到
