### ISSUE TITLE
关闭当前弹窗后，再立马弹另外一个弹窗问题

### ISSUE THREAD

**Issue by yxyaxng** [li-xiaojun/XPopup#681]
![弹窗bug](https://user-images.githubusercontent.com/24906252/109285087-96a9ce80-785b-11eb-89d1-177e5b6cf2c7.png)
在当前弹窗的消失回调中(SimpleCallback)onDismiss() 弹起另外一个弹窗，检测当前弹窗是否展示isShow返回false
查看源码监听回调，是先回调消失方法，再更改弹窗状态，能先改状态再回调消失方法吗

**Comment by li-xiaojun** [comment]
ok，下个版本更新

**Comment by li-xiaojun** [comment]
@yxyaxng 更新到最新版本即可
