### ISSUE TITLE
浏览大图，放大缩小有一定的几率导致图片显示在底部

### ISSUE THREAD

**Issue by xiaoxnn** [li-xiaojun/XPopup#683]
**XPopup版本**
如2.2.19

**手机系统和型号**
 OPPO Reno Android 10

**描述你的问题**
![image](https://user-images.githubusercontent.com/18131828/109917840-f89d8480-7cf0-11eb-9d62-cf282a60af21.png)

**Comment by li-xiaojun** [comment]
怎么操作才能复现？

**Comment by xiaoxnn** [comment]
> 怎么操作才能复现？

手指滑动图片放大缩小几次就会出现

https://user-images.githubusercontent.com/18131828/110266694-4ff56a80-7ff9-11eb-92a1-cf6b7510573e.mp4

**Comment by li-xiaojun** [comment]
更新到最新版本试试
