### ISSUE TITLE
2.2.22 crash

### ISSUE THREAD

**Issue by 330676687** [li-xiaojun/XPopup#685]
> Back traces starts.
java.lang.NullPointerException: Attempt to read from field 'boolean h.o.b.e.b.B' on a null object reference
	at com.lxj.xpopup.core.PositionPopupView$1.run(PositionPopupView.java:42)
	at com.lxj.xpopup.util.XPopupUtils$1$1.run(XPopupUtils.java:167)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
Back traces ends.

**Comment by 330676687** [comment]
> Back traces starts.
> java.lang.NullPointerException: Attempt to read from field 'h.o.b.g.i h.o.b.e.b.r' on a null object reference
> 	at com.lxj.xpopup.core.BottomPopupView$1.onDrag(BottomPopupView.java:63)
> 	at com.lxj.xpopup.widget.SmartDragLayout.scrollTo(SmartDragLayout.java:175)
> 	at com.lxj.xpopup.widget.SmartDragLayout.onLayout(SmartDragLayout.java:70)
> 	at android.view.View.layout(View.java:22215)
> 	at android.view.ViewGroup.layout(ViewGroup.java:6340)
> 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:364)
> 	at android.widget.FrameLayout.onLayout(FrameLayout.java:302)
> 	at android.view.View.layout(View.java:22215)
> 	at android.view.ViewGroup.layout(ViewGroup.java:6340)
> 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:364)
> 	at android.widget.FrameLayout.onLayout(FrameLayout.java:302)
> 	at android.view.View.layout(View.java:22215)
> 	at android.view.ViewGroup.layout(ViewGroup.java:6340)
> 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
> 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
> 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
> 	at android.view.View.layout(View.java:22215)
> 	at android.view.ViewGroup.layout(ViewGroup.java:6340)
> 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:364)
> 	at android.widget.FrameLayout.onLayout(FrameLayout.java:302)
> 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:912)
> 	at android.view.View.layout(View.java:22215)
> 	at android.view.ViewGroup.layout(ViewGroup.java:6340)
> 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3311)
> 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2772)
> 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1884)
> 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7949)
> 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1101)
> 	at android.view.Choreographer.doCallbacks(Choreographer.java:917)
> 	at android.view.Choreographer.doFrame(Choreographer.java:847)
> 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1086)
> 	at android.os.Handler.handleCallback(Handler.java:883)
> 	at android.os.Handler.dispatchMessage(Handler.java:100)
> 	at android.os.Looper.loop(Looper.java:230)
> 	at android.app.ActivityThread.main(ActivityThread.java:7851)
> 	at java.lang.reflect.Method.invoke(Method.java)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
> Back traces ends.

**Comment by 330676687** [comment]
> Back traces starts.
> java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Window android.app.Dialog.getWindow()' on a null object reference
> 	at com.lxj.xpopup.core.BasePopupView.getHostWindow(BasePopupView.java:211)
> 	at com.lxj.xpopup.core.BasePopupView.getWindowDecorView(BasePopupView.java:163)
> 	at com.lxj.xpopup.core.BasePopupView$6.run(BasePopupView.java:533)
> 	at android.os.Handler.handleCallback(Handler.java:836)
> 	at android.os.Handler.dispatchMessage(Handler.java:103)
> 	at android.os.Looper.loop(Looper.java:232)
> 	at android.app.ActivityThread.main(ActivityThread.java:6914)
> 	at java.lang.reflect.Method.invoke(Method.java)
> 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1103)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
> Back traces ends.

**Comment by 330676687** [comment]
> Back traces starts.
> java.lang.NullPointerException: Attempt to read from field 'java.lang.Boolean h.o.b.e.b.u' on a null object reference
> 	at com.lxj.xpopup.impl.FullScreenPopupView.dispatchDraw(FullScreenPopupView.java:57)
> 	at android.view.View.draw(View.java:20533)
> 	at android.view.View.updateDisplayListIfDirty(View.java:19397)
> 	at android.view.View.draw(View.java:20258)
> 	at android.view.ViewGroup.drawChild(ViewGroup.java:4443)
> 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4199)
> 	at android.view.View.updateDisplayListIfDirty(View.java:19388)
> 	at android.view.View.draw(View.java:20258)
> 	at android.view.ViewGroup.drawChild(ViewGroup.java:4443)
> 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4199)
> 	at android.view.View.updateDisplayListIfDirty(View.java:19388)
> 	at android.view.View.draw(View.java:20258)
> 	at android.view.ViewGroup.drawChild(ViewGroup.java:4443)
> 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4199)
> 	at android.view.View.draw(View.java:20533)
> 	at com.android.internal.policy.DecorView.draw(DecorView.java:910)
> 	at android.view.View.updateDisplayListIfDirty(View.java:19397)
> 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
> 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
> 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
> 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3988)
> 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3739)
> 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3051)
> 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1885)
> 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8134)
> 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1147)
> 	at android.view.Choreographer.doCallbacks(Choreographer.java:958)
> 	at android.view.Choreographer.doFrame(Choreographer.java:884)
> 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1133)
> 	at android.os.Handler.handleCallback(Handler.java:873)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at android.os.Looper.loop(Looper.java:226)
> 	at android.app.ActivityThread.main(ActivityThread.java:7224)
> 	at java.lang.reflect.Method.invoke(Method.java)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:500)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:913)
> Back traces ends.

**Comment by 330676687** [comment]
> Back traces starts.
> java.lang.NullPointerException: Attempt to read from field 'java.lang.Boolean h.o.b.e.b.u' on a null object reference
> 	at com.lxj.xpopup.core.DrawerPopupView$1.onDrag(DrawerPopupView.java:67)
> 	at com.lxj.xpopup.widget.PopupDrawerLayout$1.calcFraction(PopupDrawerLayout.java:222)
> 	at com.lxj.xpopup.widget.PopupDrawerLayout$1.onViewPositionChanged(PopupDrawerLayout.java:201)
> 	at androidx.customview.widget.ViewDragHelper.abort(ViewDragHelper.java:561)
> 	at com.lxj.xpopup.widget.PopupDrawerLayout$3.run(PopupDrawerLayout.java:315)
> 	at android.os.Handler.handleCallback(Handler.java:790)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at android.os.Looper.loop(Looper.java:197)
> 	at android.app.ActivityThread.main(ActivityThread.java:7022)
> 	at java.lang.reflect.Method.invoke(Method.java)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:515)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:837)
> Back traces ends.

**Comment by li-xiaojun** [comment]
更新到最新版本即可
