### ISSUE TITLE
关于 PartShadowPopupView isClickThrough = true 的一个问题

### ISSUE THREAD

**Issue by tangwanchao** [li-xiaojun/XPopup#686]
我的一个自定义 View 继承了 PartShadowPopupView
当我使用以下配置时,点击 Xpopup  顶部会关闭 Xpopup 后才传递事件到 Activity.这样可能导致一个事件被处理了两次(例:关闭了 Xpopup  后开启了新的页面)

fun createLevelFilterView(
    context: Context,
    filterView: FilterView
): LevelFilterView = XPopup.Builder(context)
    .atView(filterView)
    .popupPosition(PopupPosition.Bottom)
    .isClickThrough(true)
    .asCustom(LevelFilterView(context)) as LevelFilterView

查看源代码发现 PartShadowPopupView 内部使用了 PartShadowContainer,并且 PartShadowContainer 消费了所有事件.
所以如果 PartShadowPopupView 重写 onTouchEvent 直接传递事件到 Activity  即可
代码如下

@SuppressLint("ClickableViewAccessibility")
override fun onTouchEvent(event: MotionEvent): Boolean {
    passClickThrough(event)
    return true
}

private fun passClickThrough(event: MotionEvent) {
    if (dialog != null && popupInfo != null && popupInfo.isClickThrough) dialog.passClick(event)
}

我使用了这样的办法解决了一个事件被多次传递的问题,目前仅仅阅读了极小部分代码,这样会导致其他问题吗?

**Comment by li-xiaojun** [comment]
isClickThrough的作用就是点击交个弹窗的同时，还能让下层的UI处理，这个场景一般是要处理2次。
