### ISSUE TITLE
弹出的Xpopup会把BottomNavigationView往上顶，贴在输入法上面

### ISSUE THREAD

**Issue by kanshenmekan** [li-xiaojun/XPopup#688]
**XPopup版本**
2.2.23

**手机系统和型号**
试了好几款手机都会出现，应该是都会出现
![4442CB72-9F43-4B1E-AA8C-6A667F741230](https://user-images.githubusercontent.com/26561615/111116173-9837fe00-85a0-11eb-8aea-769920169238.png)

**Comment by li-xiaojun** [comment]
设置 Activity的windowSoftMode=adjustNothing，和弹窗无关
