### ISSUE TITLE
BottomPopupView 被输入法顶上去了，怎么设置不顶上去

### ISSUE THREAD

**Issue by csh159** [li-xiaojun/XPopup#69]

**Comment by li-xiaojun** [comment]
@csh159 
弹窗和输入法的交互行为就是顶上去的，但保证不会盖住输入框；这个设计是经过很多考虑的。你可以截图下我看看是否是正常的。

**Comment by csh159** [comment]
比如BottomPopupView弹出评论列表，底部有个点击评论的，然后会弹出输入法，然后BottomPopupView也没顶上去了!

**Comment by csh159** [comment]
就好比抖音评论列表类似的功能

**Comment by li-xiaojun** [comment]
@csh159 
刚刚更新到1.4.9版本，轻松实现抖音评论列表+输入框交互效果，具体看demo和效果图。

**Comment by csh159** [comment]
好的，谢谢
