### ISSUE TITLE
PartShadowPopupView如何添加拖拽效果

### ISSUE THREAD

**Issue by Janky-Young** [li-xiaojun/XPopup#691]
PartShadowPopupView怎么添加类似BottomPopupView的手势拖拽效果呢？

**Comment by li-xiaojun** [comment]
目前不支持这个效果

**Comment by Janky-Young** [comment]
> 目前不支持这个效果

有实现思路吗？ @li-xiaojun

**Comment by li-xiaojun** [comment]
@Janky-Young copy PartShadow的源码，把里面的布局修改为自定义布局。拖拽用ViewDragHelper做，也比较容易实现。
