### ISSUE TITLE
大图保存图片  之后内存泄漏

### ISSUE THREAD

**Issue by tangjiaqq** [li-xiaojun/XPopup#693]
官方demo  提iss是最新版本

**手机系统和型号**
华为P30 Android 10

    │ GC Root: Local variable in native code
    │
    ├─ android.os.HandlerThread instance
    │    Leaking: NO (PathClassLoader↓ is not leaking)
    │    Thread name: 'LeakCanary-Heap-Dump'
    │    ↓ Thread.contextClassLoader
    ├─ dalvik.system.PathClassLoader instance
    │    Leaking: NO (XPermission↓ is not leaking and A ClassLoader is never leaking)
    │    ↓ ClassLoader.runtimeInternalObjects
    ├─ java.lang.Object[] array
    │    Leaking: NO (XPermission↓ is not leaking)
    │    ↓ Object[].[1452]
    ├─ com.lxj.xpopup.util.XPermission class
    │    Leaking: NO (a class is never leaking)
    │    ↓ static XPermission.sInstance
    │                         ~~~~~~~~~
    ├─ com.lxj.xpopup.util.XPermission instance
    │    Leaking: UNKNOWN
    │    Retaining 355.5 kB in 6456 objects
    │    context instance of com.lxj.xpopupdemo.MainActivity with mDestroyed = true
    │    ↓ XPermission.context
    │                  ~~~~~~~
    ╰→ com.lxj.xpopupdemo.MainActivity instance
    ​     Leaking: YES (ObjectWatcher was watching this because com.lxj.xpopupdemo.MainActivity received
    ​     Activity#onDestroy() callback and Activity#mDestroyed is true)
    ​     Retaining 355.1 kB in 6443 objects
    ​     key = b3e56c0d-4d14-49fa-85b0-596f68b16423
    ​     watchDurationMillis = 5142
    ​     retainedDurationMillis = 133
    ​     mApplication instance of com.lxj.xpopupdemo.XPopupApp
    ​     mBase instance of androidx.appcompat.view.ContextThemeWrapper
    ====================================

**Comment by YancyYe** [comment]
一样出现泄漏  看了下 发现是 XPermission 里面拿了 context 做单例，  除非 Xpopup Build 的时候传 Application 的上下文。

**Comment by YancyYe** [comment]
或者隐藏 保存图片

**Comment by YancyYe** [comment]
或者 提前初始化 XPermission

**Comment by tangjiaqq** [comment]
![image](https://user-images.githubusercontent.com/12968616/115802326-41300f00-a411-11eb-9b77-438455c88ae3.png)
这里限制了只能用Activity的

**Comment by li-xiaojun** [comment]
已修复，下版本更新

**Comment by li-xiaojun** [comment]
@YancyYe @tangjiaqq 更新到最新版本，已修复
