### ISSUE TITLE
使用2.2.23 版本 无法实现复用显示，无法重叠显示多个Popup

### ISSUE THREAD

**Issue by sichuanyl** [li-xiaojun/XPopup#698]
从2.2.5 升级到2.2.23

测试手机 小米6x android9 、oppoR15 android10、雷电模拟器 Android7 等

1. 对话框复用无法显示，只能正常显示一次。（每次创建新pop正常显示）
2. 在对话框显示情况下再次创建pop无法显示

**Comment by li-xiaojun** [comment]
无法复现
