### ISSUE TITLE
你好，现在android:requestLegacyExternalStorage在android11上不准用了，请问去掉这个会有其他影响吗

### ISSUE THREAD

**Issue by qinRight** [li-xiaojun/XPopup#699]
你好，现在android:requestLegacyExternalStorage在android11上不准用了，请问后期会修改这个吗

**Comment by LnLooFa** [comment]
我也遇到同样的问题

商店提示广泛滥用权限,从5月5日期  说明为啥使用android:requestLegacyExternalStorage ,在Android11 上让我用分区储存,我发现我的项目里面就Xpopup使用了这个权限

**Comment by dyz930509** [comment]
target改为10即可

**Comment by DuShuYuan** [comment]
targetSdkVersion 30

**Comment by DuShuYuan** [comment]
弹窗怎么会用到文件存储权限？？？

**Comment by li-xiaojun** [comment]
升级到2.2.25即可
