### ISSUE TITLE
一关联就报错了，根本无法编译

### ISSUE THREAD

**Issue by zhongzhihuashanghai** [li-xiaojun/XPopup#7]
![image](https://user-images.githubusercontent.com/16789055/50371947-7dfc5900-05ff-11e9-88ee-c405a9f8620c.png)

**Comment by li-xiaojun** [comment]
@zhongzhihuashanghai 我是用28的`complieSdkVersion`编译的，log说，你本地只有26的SDK，找不到28版本的部分资源，请尝试下载28版本的SDK后重新编译。
