### ISSUE TITLE
Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference

### ISSUE THREAD

**Issue by zhaoxiuyu** [li-xiaojun/XPopup#70]
我在onCreate方法初始化:
        xPopup = XPopup.get(this);   // 全局变量
1 我点击按钮的时候 显示Dialog
  xPopup.asLoading("正在处理,请稍候").show();
2 点击其他的区域后 Dialog消失
3 当我第二次点击按钮 想 显示 Dialog的时候出现如下错误 ：
 java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference

4 我debug 看了下，第二次点击的时候contextRef为空
![_B{J(YD`574C6_CC2Z~E(7A](https://user-images.githubusercontent.com/16554580/54406840-9cfa1b00-4716-11e9-8f15-92f2c6bd13f3.png)

**Comment by li-xiaojun** [comment]
@zhaoxiuyu 
尽量不要保存XPopup实例，每个弹窗消失后contextRef就被释放了，每次显示弹窗都用XPopup.get(ctx)即可。

**Comment by zhaoxiuyu** [comment]
好的
