### ISSUE TITLE
BottomPopupView recyclerview 滑动问题

### ISSUE THREAD

**Issue by oudengding** [li-xiaojun/XPopup#700]
**XPopup版本**
2.2.23

**手机系统和型号**
华为6x Android 8

**描述你的问题**
BottomPopupView 布局中使用RecyclerView无法滑动

RecyclerView为垂直滑动

 /**
     * 显示搜索弹窗
     */
    public void showSearchLocationDialog() {
        if (SearchLocationDialog.isShow(mSearchDialog)){
            return;
        }

        SearchLocationDialog dialog = new SearchLocationDialog(mReference.get());
        dialog.setDialogListener(this::initDialogView);

        mSearchDialog = new XPopup.Builder(mReference.get())
                .dismissOnTouchOutside(false)
                //显示弹窗同时是否自动打开输入法（弹窗中要包含et）
                .autoOpenSoftInput(true)
                // 软键盘弹出时，弹窗是否移动到软键盘上面
                .moveUpToKeyboard(false)
                //禁止拖动
                .enableDrag(false)
                .popupAnimation(PopupAnimation.TranslateFromBottom)
                .asCustom(dialog)
                .show();
    }

弹窗布局文件

<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_marginTop="30dp"
    android:background="@color/white">

    <androidx.constraintlayout.widget.ConstraintLayout
        android:id="@+id/temp_cl_search"
        android:layout_width="0dp"
        android:layout_height="50dp"
        android:background="#f3f3f3"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintEnd_toEndOf="parent">

        <com.yuanli.lonlatcmera.mvp.ui.widget.ClearEditText
            android:id="@+id/et_search_location"
            android:layout_width="0dp"
            android:layout_height="35dp"
            android:layout_marginStart="16dp"
            android:paddingStart="10dp"
            android:paddingEnd="10dp"
            android:gravity="center_vertical"
            android:background="@color/white"
            android:drawablePadding="5dp"
            android:drawableStart="@mipmap/search_grid_32"
            android:lines="1"
            android:textSize="12sp"
            android:hint="搜索地点"
            app:clear_ic="@mipmap/clear_32"
            app:layout_constraintTop_toTopOf="parent"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintEnd_toStartOf="@+id/tv_cancel_search_btn"
            />

        <TextView
            android:id="@+id/tv_cancel_search_btn"
            android:layout_width="60dp"
            android:layout_height="0dp"
            android:gravity="center"
            android:textColor="@color/cl_1296db"
            android:textSize="14sp"
            android:text="@string/common_cancel"
            app:layout_constraintTop_toTopOf="parent"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintStart_toEndOf="@+id/et_search_location"
            app:layout_constraintEnd_toEndOf="parent"
            />

    </androidx.constraintlayout.widget.ConstraintLayout>

    <androidx.recyclerview.widget.RecyclerView
        android:id="@+id/rv_search_poi"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        tools:listitem="@layout/item_poi"
        tools:itemCount="2"
        app:layout_constraintTop_toBottomOf="@+id/temp_cl_search"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintEnd_toEndOf="parent" />

    <androidx.constraintlayout.widget.ConstraintLayout
        android:id="@+id/cl_custom_location_root"
        android:layout_width="0dp"
        android:layout_height="56dp"
        android:paddingStart="16dp"
        android:paddingEnd="16dp"
        android:visibility="gone"
        app:layout_constraintTop_toBottomOf="@+id/rv_search_poi"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintEnd_toEndOf="parent">

        <TextView
            android:id="@+id/tv_custom_location"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginBottom="5dp"
            android:textColor="@color/cl_333"
            android:textSize="14sp"
            tools:text="涡流岛"
            app:layout_constraintVertical_chainStyle="packed"
            app:layout_constraintTop_toTopOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintBottom_toTopOf="@+id/tv_custom_location_2"
            />

        <TextView
            android:id="@+id/tv_custom_location_2"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="创建为自定义地点"
            android:textColor="@color/cl_1296db"
            android:textSize="12sp"
            app:layout_constraintTop_toBottomOf="@+id/tv_custom_location"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintStart_toStartOf="parent"/>

        <Button
            android:id="@+id/btn_create_custom_location"
            android:layout_width="65dp"
            android:layout_height="35dp"
            android:background="@drawable/shape_3478f5_4"
            android:textColor="@color/white"
            android:text="创建"
            app:layout_constraintTop_toTopOf="parent"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"/>
    </androidx.constraintlayout.widget.ConstraintLayout>

</androidx.constraintlayout.widget.ConstraintLayout>

**Comment by qihaogao** [comment]
同问，有一样的问题不知道怎么处理

**Comment by qihaogao** [comment]
> **XPopup版本**
> 2.2.23
> 
> **手机系统和型号**
> 华为6x Android 8
> 
> **描述你的问题**
> BottomPopupView 布局中使用RecyclerView无法滑动
> 
> RecyclerView为垂直滑动
> 
> /**
> * 显示搜索弹窗
> */
> public void showSearchLocationDialog() {
> if (SearchLocationDialog.isShow(mSearchDialog)){
> return;
> }
> 
> ```
>     SearchLocationDialog dialog = new SearchLocationDialog(mReference.get());
>     dialog.setDialogListener(this::initDialogView);
> 
>     mSearchDialog = new XPopup.Builder(mReference.get())
>             .dismissOnTouchOutside(false)
>             //显示弹窗同时是否自动打开输入法（弹窗中要包含et）
>             .autoOpenSoftInput(true)
>             // 软键盘弹出时，弹窗是否移动到软键盘上面
>             .moveUpToKeyboard(false)
>             //禁止拖动
>             .enableDrag(false)
>             .popupAnimation(PopupAnimation.TranslateFromBottom)
>             .asCustom(dialog)
>             .show();
> }
> ```
> 
> 弹窗布局文件
> 
> <androidx.constraintlayout.widget.ConstraintLayout
> xmlns:android="http://schemas.android.com/apk/res/android"
> xmlns:app="http://schemas.android.com/apk/res-auto"
> xmlns:tools="http://schemas.android.com/tools"
> android:layout_width="match_parent"
> android:layout_height="match_parent"
> android:layout_marginTop="30dp"
> android:background="@color/white">
> 
> ```
> <androidx.constraintlayout.widget.ConstraintLayout
>     android:id="@+id/temp_cl_search"
>     android:layout_width="0dp"
>     android:layout_height="50dp"
>     android:background="#f3f3f3"
>     app:layout_constraintTop_toTopOf="parent"
>     app:layout_constraintStart_toStartOf="parent"
>     app:layout_constraintEnd_toEndOf="parent">
> 
>     <com.yuanli.lonlatcmera.mvp.ui.widget.ClearEditText
>         android:id="@+id/et_search_location"
>         android:layout_width="0dp"
>         android:layout_height="35dp"
>         android:layout_marginStart="16dp"
>         android:paddingStart="10dp"
>         android:paddingEnd="10dp"
>         android:gravity="center_vertical"
>         android:background="@color/white"
>         android:drawablePadding="5dp"
>         android:drawableStart="@mipmap/search_grid_32"
>         android:lines="1"
>         android:textSize="12sp"
>         android:hint="搜索地点"
>         app:clear_ic="@mipmap/clear_32"
>         app:layout_constraintTop_toTopOf="parent"
>         app:layout_constraintBottom_toBottomOf="parent"
>         app:layout_constraintStart_toStartOf="parent"
>         app:layout_constraintEnd_toStartOf="@+id/tv_cancel_search_btn"
>         />
> 
>     <TextView
>         android:id="@+id/tv_cancel_search_btn"
>         android:layout_width="60dp"
>         android:layout_height="0dp"
>         android:gravity="center"
>         android:textColor="@color/cl_1296db"
>         android:textSize="14sp"
>         android:text="@string/common_cancel"
>         app:layout_constraintTop_toTopOf="parent"
>         app:layout_constraintBottom_toBottomOf="parent"
>         app:layout_constraintStart_toEndOf="@+id/et_search_location"
>         app:layout_constraintEnd_toEndOf="parent"
>         />
> 
> </androidx.constraintlayout.widget.ConstraintLayout>
> 
> 
> <androidx.recyclerview.widget.RecyclerView
>     android:id="@+id/rv_search_poi"
>     android:layout_width="0dp"
>     android:layout_height="wrap_content"
>     tools:listitem="@layout/item_poi"
>     tools:itemCount="2"
>     app:layout_constraintTop_toBottomOf="@+id/temp_cl_search"
>     app:layout_constraintStart_toStartOf="parent"
>     app:layout_constraintEnd_toEndOf="parent" />
> 
> 
> <androidx.constraintlayout.widget.ConstraintLayout
>     android:id="@+id/cl_custom_location_root"
>     android:layout_width="0dp"
>     android:layout_height="56dp"
>     android:paddingStart="16dp"
>     android:paddingEnd="16dp"
>     android:visibility="gone"
>     app:layout_constraintTop_toBottomOf="@+id/rv_search_poi"
>     app:layout_constraintStart_toStartOf="parent"
>     app:layout_constraintEnd_toEndOf="parent">
> 
>     <TextView
>         android:id="@+id/tv_custom_location"
>         android:layout_width="wrap_content"
>         android:layout_height="wrap_content"
>         android:layout_marginBottom="5dp"
>         android:textColor="@color/cl_333"
>         android:textSize="14sp"
>         tools:text="涡流岛"
>         app:layout_constraintVertical_chainStyle="packed"
>         app:layout_constraintTop_toTopOf="parent"
>         app:layout_constraintStart_toStartOf="parent"
>         app:layout_constraintBottom_toTopOf="@+id/tv_custom_location_2"
>         />
> 
>     <TextView
>         android:id="@+id/tv_custom_location_2"
>         android:layout_width="wrap_content"
>         android:layout_height="wrap_content"
>         android:text="创建为自定义地点"
>         android:textColor="@color/cl_1296db"
>         android:textSize="12sp"
>         app:layout_constraintTop_toBottomOf="@+id/tv_custom_location"
>         app:layout_constraintBottom_toBottomOf="parent"
>         app:layout_constraintStart_toStartOf="parent"/>
> 
>     <Button
>         android:id="@+id/btn_create_custom_location"
>         android:layout_width="65dp"
>         android:layout_height="35dp"
>         android:background="@drawable/shape_3478f5_4"
>         android:textColor="@color/white"
>         android:text="创建"
>         app:layout_constraintTop_toTopOf="parent"
>         app:layout_constraintBottom_toBottomOf="parent"
>         app:layout_constraintEnd_toEndOf="parent"/>
> </androidx.constraintlayout.widget.ConstraintLayout>
> ```
> 
> </androidx.constraintlayout.widget.ConstraintLayout>

请问问题解决了吗？ @oudengding

**Comment by RUANHAOANDROID** [comment]
+1

**Comment by li-xiaojun** [comment]
@RUANHAOANDROID @qihaogao @oudengding 问题解决了吧，
