### ISSUE TITLE
弹框位于状态栏底部，没有实现全屏显示

### ISSUE THREAD

**Issue by xuexirong** [li-xiaojun/XPopup#702]
**XPopup版本**
2.2.23

**手机系统和型号**
小米11

**描述你的问题**
hasStatusBar设置了false
但是弹框位于状态栏，没有实现全屏显示
![4AE6A00867CD0BA908DCB6A9B9EE83CF](https://user-images.githubusercontent.com/13816024/115674429-37120000-a380-11eb-8e13-c7b4371252d6.jpg)

**Comment by sj1114191961** [comment]
我也遇到这个问题了，楼主解决了吗？

**Comment by xuexirong** [comment]
@sj1114191961 hasStatusBar设置为true试试
