### ISSUE TITLE
后台弹窗在横屏后没有适配

### ISSUE THREAD

**Issue by zofnk** [li-xiaojun/XPopup#704]
**XPopup版本**
2.2.22

**手机系统和型号**
Samsung SM-A9080 Android 11

**描述你的问题**
全局后台弹窗在横屏后位置和宽高没有适配

![image](https://user-images.githubusercontent.com/17997544/116025983-4cd73c00-a684-11eb-9871-ee6720c59dd4.png)
![image](https://user-images.githubusercontent.com/17997544/116025992-5365b380-a684-11eb-882e-c1df93b64029.png)

**Comment by li-xiaojun** [comment]
试试最新版本
