### ISSUE TITLE
带输入框的弹窗，弹窗崩溃

### ISSUE THREAD

**Issue by Yonion** [li-xiaojun/XPopup#707]
**XPopup版本**
如2.2.5

**手机系统和型号**
Android 7

**描述你的问题**
崩溃日志如下：
Attempt to read from field 'java.lang.Boolean com.lxj.xpopup.core.PopupInfo.isMoveUpToKeyboard' on a null object reference

com.lxj.xpopup.util.XPopupUtils.moveUpToKeyboardInternal(XPopupUtils.java:234)

代码如下：
   new XPopup.Builder(mContext)
                .moveUpToKeyboard(true)
                .isDestroyOnDismiss(true)
                .asCustom(bookPopWindow)
                .show();

而且我这边所有带多个输入框的页面，这样写都会有这个崩溃。

**Comment by li-xiaojun** [comment]
更新到最新版本试试
