### ISSUE TITLE
当自定义弹窗中含有密码输入的EditText，弹窗显示后会不断抖动

### ISSUE THREAD

**Issue by pozhupt** [li-xiaojun/XPopup#708]
**XPopup版本**
如2.1.0

**手机系统和型号**
红米 k20 pro

**描述你的问题**
布局中设置编辑框输入类型
 edtFirst.setInputType(InputType.TYPE_CLASS_TEXT | InputType.TYPE_TEXT_VARIATION_PASSWORD);

**Comment by li-xiaojun** [comment]
我用最新版本测试无法复现，更新到最新版本试试
