### ISSUE TITLE
无法正常保存图片，添加requestLegacyExternalStorage标签才能正常保存

### ISSUE THREAD

**Issue by Peek-A-Booo** [li-xiaojun/XPopup#710]
**XPopup版本**
2.2.25

**手机系统和型号**
华为HONOR 30S Android 10

**描述你的问题**
第一次安装app之后进入图片，点击大图然后点击保存按钮，正常提示获取权限。但是获取权限之后提示“没有保存权限，保存功能无法使用”。还是requestLegacyExternalStorage问题

**Comment by li-xiaojun** [comment]
在自己的工程中添加requestLegacyExternalStorage即可
