### ISSUE TITLE
 .isViewMode(true)    之后.positionByWindowCenter(true)失效（pop在软键盘底部）

### ISSUE THREAD

**Issue by 287138531** [li-xiaojun/XPopup#711]
**XPopup版本**
2.3.0

**手机系统和型号**
vivo Y55a Android 6.0.1

**描述你的问题**
     .isViewMode(true)    之后.positionByWindowCenter(true)失效（pop在软键盘底部）

实际需求是，pop往下弹出到软键盘顶部的距离如果大于，往状态栏上弹出，就往下弹，到软键盘高度。。小于则，往上弹出。而不是pop去遮挡软件怕，或者软键盘遮挡pop。

而且如果是自定义pop .isViewMode(true) 之后，点击事件有问题，点pop，会自动隐藏配pop。。比如我自己写的rv，往下滑动，就关掉了

**Comment by liudaohong** [comment]
isViewMode 就设置成View  了 就直接是当成View  加载窗口 自然回在软件盘底部  需要自己去处理软件盘和 你的View 底部高度问题

**Comment by liudaohong** [comment]
自己监听软件盘高度 来设置底部边距
