### ISSUE TITLE
popupInfo 为空 

### ISSUE THREAD

**Issue by Xue-Zhou** [li-xiaojun/XPopup#713]
**XPopup版本**
如2.3.2

**手机系统和型号**
模拟器 OPPO

**描述你的问题**
侧滑菜单中 显示confirm弹窗，点击确定时会崩溃，popupInfo 为空
![image](https://user-images.githubusercontent.com/32625233/118429699-dcf92600-b704-11eb-896b-8263e3ef7327.png)
![image](https://user-images.githubusercontent.com/32625233/118429713-e2567080-b704-11eb-9f12-3777c169f4a2.png)
![image](https://user-images.githubusercontent.com/32625233/118429722-e6828e00-b704-11eb-8807-53b6a63f2f54.png)
解决方法 dismiss 换成 dismissWith
![image](https://user-images.githubusercontent.com/32625233/118429781-087c1080-b705-11eb-9f09-b217d82a03d4.png)
建议可使用 getContext

**Comment by li-xiaojun** [comment]
更新到2.3.3即可，已修复
