### ISSUE TITLE
CenterInputPopupView autoOpenSoftInput（true）无效

### ISSUE THREAD

**Issue by szhdev** [li-xiaojun/XPopup#715]
**XPopup版本**
如2.3.2

**手机系统和型号**
小米 Android 11

**描述你的问题**
修改昵称的时候弹窗弹出 但是 输入法未弹出，2.2.23版本正常

**Comment by li-xiaojun** [comment]
autoFocusEditText(true)

**Comment by szhdev** [comment]
> autoFocusEditText（true）

2.3.3版本
这是vivo x60 Android 11上的  在小米上一次都弹不出

https://user-images.githubusercontent.com/35017612/118911351-a1ef3080-b958-11eb-8610-f6f9e7d5ec25.mp4

![image](https://user-images.githubusercontent.com/35017612/118911392-b16e7980-b958-11eb-9d21-6f73df05ede7.png)
