### ISSUE TITLE
LifecycleObserver里的回调事件无法dismiss

### ISSUE THREAD

**Issue by Zerbaoo** [li-xiaojun/XPopup#716]
**XPopup版本**
2.3.3

**描述你的问题**

在activity里
activity｛

  loadingDialog = LoadingDialog(this)
            XPopup.Builder(this)
                .asCustom(loadingDialog).show()

 lifecycle.addObserver(XXXUtil)
xxxUtil.setOnListener (){
onListen（）｛
 loadingDialog .dismiss//无法消失
｝
｝

｝

class XXXUtil: LifecycleObserver｛

fun backListen(){
if(onListener !=null){
onListener.onListen()
}
}

private var onListener : OnListener ? = null

    fun setOnListener (onListener : OnListener ?) {
        this.onListener = onListener 
    }

    interface OnListener {
        fun onListen()
    }

｝

添加runOnUiThread｛
｝
可以消失。可能是lifecycle的问题把

**Comment by li-xiaojun** [comment]
backListen()执行的时机是什么

**Comment by Zerbaoo** [comment]
> backListen()执行的时机是什么

LifecycleObserver里封装一个倒计时 CountDownTimer的onFinish事件

**Comment by li-xiaojun** [comment]
问题解决了吗

**Comment by Zerbaoo** [comment]
> 问题解决了吗

嗯 用runOnUiThread
