### ISSUE TITLE
怎么设置才能在触摸或者滑动弹框外部时关闭弹框

### ISSUE THREAD

**Issue by jackma11** [li-xiaojun/XPopup#717]
**XPopup版本**
2.2.10

**手机系统和型号**
vivo 1818CA

**描述你的问题**
PartShadowDemo中,指定在上方显示/指定在下方显示,弹框展示后,滑动弹框外部的rv,弹框不能关闭,只有点击事件才能关闭,能否在触摸或者滑动弹框外部时关闭弹框

https://user-images.githubusercontent.com/51396482/119016361-e60b2100-b9aa-11eb-881e-30ee62927da5.mp4

**Comment by li-xiaojun** [comment]
@jackma11 更新到最新版本即可

**Comment by jackma11** [comment]
使用2.3.3最新版本,在demo中局部阴影页面,弹框如果使用复用方式的话,弹框第一次正常弹出后,再次复用弹出时,会瞬间出现再关闭一次,然后才动画弹出,为了方便查看,在设置动画时长为2秒时,能比较清楚的看到这一过程

isClickThrough设置true和false一样都会有这个问题

机型 vivo 1818CA   华为荣耀10




![image](https://user-images.githubusercontent.com/51396482/119092497-9286ea80-ba1f-11eb-86fc-a1ce66e5a9d1.png)


https://user-images.githubusercontent.com/51396482/119093048-41c3c180-ba20-11eb-91e4-6f219100fdc9.mp4

**Comment by jackma11** [comment]
> @jackma11 更新到最新版本即可

使用2.3.3最新版本,在demo中局部阴影页面,弹框如果使用复用方式的话,弹框第一次正常弹出后,再次复用弹出时,会瞬间出现再关闭一次,然后才动画弹出,为了方便查看,在设置动画时长为2秒时,能比较清楚的看到这一过程

isClickThrough设置true和false一样都会有这个问题

机型 vivo 1818CA 华为荣耀10



![image](https://user-images.githubusercontent.com/51396482/119095295-27d7ae00-ba23-11eb-92b5-221fee5bd531.png)



https://user-images.githubusercontent.com/51396482/119095862-df6cc000-ba23-11eb-96a1-f9d3cc44ae76.mp4

**Comment by jackma11** [comment]
> > @jackma11 更新到最新版本即可
> 
> @li-xiaojun
> 
> 使用2.3.3最新版本,在demo中局部阴影页面,弹框如果使用复用方式的话,弹框第一次正常弹出后,再次复用弹出时,会瞬间出现再关闭一次,然后才动画弹出,为了方便查看,在设置动画时长为2秒时,能比较清楚的看到这一过程
> 
> isClickThrough设置true和false一样都会有这个问题
> 
> 机型 vivo 1818CA 华为荣耀10
> 
> ![image](https://user-images.githubusercontent.com/51396482/119095295-27d7ae00-ba23-11eb-92b5-221fee5bd531.png)
> 
>  Screenrecording_20210521_105624.mp4

@li-xiaojun 在弹框关闭时,初始PopupContent的透明度为0就好了

![image](https://user-images.githubusercontent.com/51396482/119125429-d0e1d100-ba42-11eb-962e-c04daf4dc212.png)
