### ISSUE TITLE
> 无法弹出输入法

### ISSUE THREAD

**Issue by szhdev** [li-xiaojun/XPopup#718]
> autoFocusEditText（true）autoOpenSoftInput（true）

2.3.3版本
这是vivo x60 Android 11上的  在小米上一次都弹不出

https://user-images.githubusercontent.com/35017612/118911351-a1ef3080-b958-11eb-8610-f6f9e7d5ec25.mp4

![image](https://user-images.githubusercontent.com/35017612/118911392-b16e7980-b958-11eb-9d21-6f73df05ede7.png)

_Originally posted by @szhdev in https://github.com/li-xiaojun/XPopup/issues/715#issuecomment-844642470_

**Comment by li-xiaojun** [comment]
小米的系统和机型说下，不说机型没法定位

**Comment by szhdev** [comment]
> 小米的系统和机型说下，不说机型没法定位



> 小米的系统和特定说说下，不说确定没法定位

小米Mi 11     系统版本是：11

**Comment by li-xiaojun** [comment]
试试2.3.5版本  @szhdev

**Comment by szhdev** [comment]
> 试试2.3.5版本 @szhdev
 
试了最新的2.3.6版本 还是不行

https://user-images.githubusercontent.com/35017612/120991166-f0535a80-c7b3-11eb-81fc-d82502b032df.mp4
![Screenshot_2021-06-07-17-16-44-724_com android settings](https://user-images.githubusercontent.com/35017612/120991544-5344f180-c7b4-11eb-9376-8e63ea26adb1.jpg)

**Comment by li-xiaojun** [comment]
@szhdev 更新到2.3.7试试，尝试修复了这个问题

**Comment by szhdev** [comment]
> @szhdev 更新到2.3.7试试，尝试修复了这个问题

测试 在小米Mi 11 系统版本是：Android11 正常
