### ISSUE TITLE
版本号>2.0.0或引入Ext的包，在BroadcastReceiver中无法弹出弹窗

### ISSUE THREAD

**Issue by SaltedFish0318** [li-xiaojun/XPopup#720]
**XPopup版本**
>2.0.0

**手机系统和型号**
红米K30Pro Android 11

**描述你的问题**
版本号>2.0.0或引入XPopupExt依赖后，在BroadcastReceiver中无法弹出弹窗
![image](https://user-images.githubusercontent.com/41811466/119247185-242a5f80-bbba-11eb-885f-5ff2c9d84850.png)
在这段代码中，Toast能正常弹出，但是弹窗没有弹出。在2.0.0版本中正常显示

**Comment by li-xiaojun** [comment]
请保证你的context为Activity类型
