### ISSUE TITLE
AttachPopupView 横屏的时候，x轴位置不对，和竖屏的位置相差明显，

### ISSUE THREAD

**Issue by BugRui** [li-xiaojun/XPopup#722]
implementation 'com.lxj:xpopup:2.2.14'

**手机系统和型号**
oppo r15，其他的机型也发现了这个问题

**描述你的问题**
最好能上代码截图和问题截图

**Comment by li-xiaojun** [comment]
放个截图吧，我用华为手机小米手机都正常

**Comment by BugRui** [comment]
我是没有固定屏幕的方向的，

https://static.sycdev.com/24zzo4ntcyev7nw1agwfyl53a.jpeg

https://static.sycdev.com/3vochmgnyrdxuiog8csf1wfux.jpeg

**Comment by li-xiaojun** [comment]
用最新版本试试
