### ISSUE TITLE
asBottomList建议能设置字体大小

### ISSUE THREAD

**Issue by zhangyin2019** [li-xiaojun/XPopup#723]
asBottomList建议能设置字体大小

**Comment by li-xiaojun** [comment]
内置弹窗的实用性有限，不准备添加这些特性了，因为还涉及到字体颜色，粗细，padding等，过造成库的臃肿；如果不满足需求，建议自定义弹窗。

**Comment by zhangyin2019** [comment]
好的，感谢回复





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "li-xiaojun/XPopup"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月27日(星期四) 下午3:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [li-xiaojun/XPopup] asBottomList建议能设置字体大小 (#723)





 
内置弹窗的实用性有限，不准备添加这些特性了，因为还涉及到字体颜色，粗细，padding等，过造成库的臃肿；如果不满足需求，建议自定义弹窗。
