### ISSUE TITLE
后台弹窗传递context必须是activity?

### ISSUE THREAD

**Issue by Jasperben** [li-xiaojun/XPopup#726]
![image](https://user-images.githubusercontent.com/15630036/120139078-4f402f00-c20a-11eb-9a36-16390f5d588c.png)

**Comment by li-xiaojun** [comment]
是的，你可以传递你的topActivity；你的app至少有一个Activity位于栈顶的。

**Comment by Jasperben** [comment]
没有  我用是系统应用  在后台service弹窗
