### ISSUE TITLE
2.2.19 崩溃 The specified child already has a parent. You must call removeView() on the child's parent first.  com.lxj.xpopup.core.FullScreenDialog.onCreate(FullScreenDialog.java:86)

### ISSUE THREAD

**Issue by goooggle** [li-xiaojun/XPopup#727]
**XPopup版本**
2.2.19

**描述你的问题**
The specified child already has a parent. You must call removeView() on the child's parent first.

com.lxj.xpopup.core.FullScreenDialog.onCreate(FullScreenDialog.java:86)

![image](https://user-images.githubusercontent.com/75106451/120171380-92af9300-c234-11eb-8a63-33dea523f059.png)

**Comment by goooggle** [comment]
popupInfo.isDestroyOnDismiss  需要设置为 true 是吗?

**Comment by li-xiaojun** [comment]
> popupInfo.isDestroyOnDismiss 需要设置为 true 是吗?

如果弹窗是复用的，就不要设置为true了；不是复用的最好设置为true
