### ISSUE TITLE
自定义AttachPopupView没有getPopupBackground方法了，会出现白色背景。

### ISSUE THREAD

**Issue by fuxuanyang11** [li-xiaojun/XPopup#728]
**XPopup版本**
如2.3.4

**Comment by li-xiaojun** [comment]
直接在布局中设置任意背景即可

**Comment by fuxuanyang11** [comment]
> 直接在布局中设置任意背景即可

> 设置完布局后会有白色背景在底部

**Comment by fuxuanyang11** [comment]
![Screenshot_2021-06-04-18-47-07-014_com mostone fr](https://user-images.githubusercontent.com/21265701/120790443-8f364780-c565-11eb-8c75-4990eaa84b50.jpg)

`<?xml version="1.0" encoding="utf-8"?>

<com.cpiz.android.bubbleview.BubbleLinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    app:bb_arrowHeight="4dp"
    app:bb_fillColor="@color/black_1c1c1e"
    app:bb_arrowDirection="Down">
        <TextView
            android:id="@+id/tv_copy"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:paddingHorizontal="16dp"
            android:paddingVertical="10dp"
            android:text="复制"
            android:textColor="@color/white"
            android:textSize="14sp" />
        <View
            android:layout_width="1px"
            android:layout_height="match_parent"
            android:background="#eee" />
        <TextView
            android:id="@+id/tv_del"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:paddingHorizontal="16dp"
            android:paddingVertical="10dp"
            android:text="删除"
            android:textColor="@color/white"
            android:textSize="14sp" />
        <View
            android:layout_width="1px"
            android:layout_height="match_parent"
            android:background="#eee" />

        <TextView
            android:id="@+id/tv_report"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:paddingHorizontal="16dp"
            android:paddingVertical="10dp"
            android:text="举报"
            android:textColor="@color/white"
            android:textSize="14sp" />
    </com.cpiz.android.bubbleview.BubbleLinearLayout>
`

**Comment by fuxuanyang11** [comment]
> > 直接在布局中设置任意背景即可
> 
> > 设置完布局后会有白色背景在底部
> > 截图我看看效果，然把布局也发下

![Screenshot_2021-06-04-18-47-07-014_com mostone fr](https://user-images.githubusercontent.com/21265701/120790683-d9b7c400-c565-11eb-9194-76d1f9f25560.jpg)

**Comment by fuxuanyang11** [comment]
`<?xml version="1.0" encoding="utf-8"?>

<com.cpiz.android.bubbleview.BubbleLinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    app:bb_arrowHeight="4dp"
    app:bb_fillColor="@color/black_1c1c1e"
    app:bb_arrowDirection="Down">
        <TextView
            android:id="@+id/tv_copy"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:paddingHorizontal="16dp"
            android:paddingVertical="10dp"
            android:text="复制"
            android:textColor="@color/white"
            android:textSize="14sp" />
        <View
            android:layout_width="1px"
            android:layout_height="match_parent"
            android:background="#eee" />
        <TextView
            android:id="@+id/tv_del"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:paddingHorizontal="16dp"
            android:paddingVertical="10dp"
            android:text="删除"
            android:textColor="@color/white"
            android:textSize="14sp" />
        <View
            android:layout_width="1px"
            android:layout_height="match_parent"
            android:background="#eee" />

        <TextView
            android:id="@+id/tv_report"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:paddingHorizontal="16dp"
            android:paddingVertical="10dp"
            android:text="举报"
            android:textColor="@color/white"
            android:textSize="14sp" />
    </com.cpiz.android.bubbleview.BubbleLinearLayout>
`

**Comment by fuxuanyang11** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<com.cpiz.android.bubbleview.BubbleLinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    app:bb_arrowHeight="4dp"
    app:bb_fillColor="@color/black_1c1c1e"
    app:bb_arrowDirection="Down">
        <TextView
            android:id="@+id/tv_copy"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:paddingHorizontal="16dp"
            android:paddingVertical="10dp"
            android:text="复制"
            android:textColor="@color/white"
            android:textSize="14sp" />
        <View
            android:layout_width="1px"
            android:layout_height="match_parent"
            android:background="#eee" />
        <TextView
            android:id="@+id/tv_del"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:paddingHorizontal="16dp"
            android:paddingVertical="10dp"
            android:text="删除"
            android:textColor="@color/white"
            android:textSize="14sp" />
        <View
            android:layout_width="1px"
            android:layout_height="match_parent"
            android:background="#eee" />

        <TextView
            android:id="@+id/tv_report"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:paddingHorizontal="16dp"
            android:paddingVertical="10dp"
            android:text="举报"
            android:textColor="@color/white"
            android:textSize="14sp" />
    </com.cpiz.android.bubbleview.BubbleLinearLayout>
`
这是布局文件

**Comment by fuxuanyang11** [comment]
@li-xiaojun 能帮忙看下吗

**Comment by fuxuanyang11** [comment]
![image](https://user-images.githubusercontent.com/21265701/121179384-472f6180-c892-11eb-99ff-05bca4d4cf01.png)
![Uploading image.png…]()

**Comment by fuxuanyang11** [comment]
![image](https://user-images.githubusercontent.com/21265701/121179441-58786e00-c892-11eb-8f29-85b1e80d2b58.png)
