### ISSUE TITLE
自定义自由定位Position弹窗的点击监听等逻辑该如何写

### ISSUE THREAD

**Issue by Jack-bin183** [li-xiaojun/XPopup#729]
**XPopup版本**
2.1.0

**手机系统和型号**
华为nave2s Android 8

**描述你的问题**
自定义自由定位Position弹窗的点击监听等逻辑该如何写

**Comment by li-xiaojun** [comment]
在onCreate方法中setOnClickListener

**Comment by Jack-bin183** [comment]
嗯嗯，还有个问题就是自由定位Position弹窗的灰色背景如何取消呀

**Comment by Jack-bin183** [comment]
自由定位Position弹窗会拦截全屏的点击事件，如何取消呀，让弹窗的触摸点击只对弹窗view生效，不拦截它下方的view触摸事件

**Comment by li-xiaojun** [comment]
看下文档，有个设置

**Comment by Jack-bin183** [comment]
您是说 .isRequestFocus(false)这个设置吗，我设置里但似乎还是一样会拦截全屏的点击事件呢

**Comment by li-xiaojun** [comment]
isClickThrough(false)
