### ISSUE TITLE
2.3.7 安卓旧版本一直弹输入法

### ISSUE THREAD

**Issue by fiytodie** [li-xiaojun/XPopup#731]
**XPopup版本**
2.3.7

**手机系统和型号**
Android 7.0的触摸屏和华为P40，安卓10

**描述你的问题**
`
new XPopup.Builder(this)
                    .isDestroyOnDismiss(true)
                    .autoOpenSoftInput(false)
                    .asCenterList("请选择当前要进行的操作",
`
会自动弹出系统输入法...切换到2.3.6就OK了，手机倒是并没有出现，尝试把demo安装到机器上，把
`implementation project(':library')`
改成
`implementation 'com.github.li-xiaojun:XPopup:2.3.7'`
安装到触摸屏，点击demo中的asCenterList演示也是会自动弹出输入法

**Comment by li-xiaojun** [comment]
@fiytodie 更新到2.3.8即可
