### ISSUE TITLE
自定义继承AttachPopupView弹窗位置偏移

### ISSUE THREAD

**Issue by Dawnton** [li-xiaojun/XPopup#736]
**XPopup版本**
2.4.0

**手机系统和型号**
华为Nova2s Android 9
三星 Galaxy Note20 Android11

**描述你的问题**
自定义弹窗继承AttachPopupView位置偏移

![image](https://user-images.githubusercontent.com/15863163/122206626-225f6d80-ced4-11eb-84f9-e14db332c6db.png)
![image](https://user-images.githubusercontent.com/15863163/122206979-34411080-ced4-11eb-8fc5-7346391a28f6.png)

**Comment by li-xiaojun** [comment]
难道不是你设置了offsetX ?

**Comment by Dawnton** [comment]
> 难道不是你设置了offsetX ?

这里设置的offsetX是0，还有个问题就是弹窗右边有一部分布局不显示了。。。

**Comment by li-xiaojun** [comment]
isCenterHorizontal(false)试试

**Comment by backin** [comment]
父容器要设置成match_parant吧
