### ISSUE TITLE
继承 PartShadowPopupView

### ISSUE THREAD

**Issue by chuxiaokeAndroid** [li-xiaojun/XPopup#737]
extends PartShadowPopupView之后，依附在某一个view下面，宽度要跟随view'的宽度自适应》》》有方法实现吗

**Comment by li-xiaojun** [comment]
可以重新getPopupWidth()方法，返回自定义的宽度；但自适应就不好办了

**Comment by zhaoxiuyu** [comment]
能提供下载aar吗， @li-xiaojun
