### ISSUE TITLE
自定义bottompopup，resourceid为0x0

### ISSUE THREAD

**Issue by JacksonYANG** [li-xiaojun/XPopup#74]
自定义继承BottomPopupView之后，报错。
android.content.res.Resources$NotFoundException: Resource ID #0x0

sdk版本androidx，请问作者是不支持androidx吗？

**Comment by JacksonYANG** [comment]
compileSdkVersion 28
    defaultConfig {
        applicationId "top.jacksonyang.lottery"
        minSdkVersion 26
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

修改为26后报错，error: resource android:attr/dialogCornerRadius not found.
error: resource android:attr/dialogCornerRadius not found.
error: resource android:attr/fontVariationSettings not found.
error: resource android:attr/ttcIndex not found.
error: resource android:attr/textFontWeight not found.

**Comment by li-xiaojun** [comment]
@JacksonYANG 
目前还不支持AndroidX，后续有这个计划。
修改26报错，请检查本地是否有26的SDK和BuildTool
