### ISSUE TITLE
拉取的最新代码直接崩溃了

### ISSUE THREAD

**Issue by Dboy233** [li-xiaojun/XPopup#740]
## 我直接上截图吧
![image](https://user-images.githubusercontent.com/37604230/122676188-78ebe500-d20f-11eb-9694-4b0dbd99b7dd.png)
## 拉取的最新代码。本来想看看你更新了什么内容。考虑项目中升下版本的。
![image](https://user-images.githubusercontent.com/37604230/122676206-9b7dfe00-d20f-11eb-9a9a-05a6d26aa009.png)

**Comment by Dboy233** [comment]
## 当前提交没有问题
![image](https://user-images.githubusercontent.com/37604230/122676369-66be7680-d210-11eb-8675-7ae602fd4bb9.png)
## 在你提交的优化弹窗***处理出现的问题
## 单号7e121b6d0fdad1c5fe6bce7c1af32ddc2ad5d9d4
## 我怀疑是你这个listener导致的
![image](https://user-images.githubusercontent.com/37604230/122676466-d59bcf80-d210-11eb-801b-67986b2fd4cf.png)

**Comment by Dboy233** [comment]
## 还有一个崩溃位置
### 这段文本翻译过来就是：
 观察者类有一些使用较新 API 的方法，这些 API 在当前操作系统版本中不可用。 Lifecycles 甚至无法访问其他方法，因此您应该确保您的观察者类仅访问在您的最小 API 级别中可用的框架类或使用生命周期：编译器注释处理器。

![image](https://user-images.githubusercontent.com/37604230/122676817-38419b00-d212-11eb-90d0-823d93d5527e.png)

**Comment by li-xiaojun** [comment]
我的锅，更新到2.4.3即可
