### ISSUE TITLE
Android11保存图片无效

### ISSUE THREAD

**Issue by szhdev** [li-xiaojun/XPopup#741]
**XPopup版本**
 2.4.3

**手机系统和型号**
Android 11 版本

**描述你的问题**
如题浏览大图界面 点击保存图片无反应

**Comment by li-xiaojun** [comment]
经测试能正常保存的，你是什么牌子的手机

**Comment by szhdev** [comment]
> 经测试能正常保存的，你是什么牌子的手机
手机系统和型号
vivo x60 或者oppo FindX3   Android 11   
https://user-images.githubusercontent.com/35017612/122906300-95f5f480-d384-11eb-92a1-f56d217af63c.mp4

**Comment by eastluzihe** [comment]
XPopup版本 2.4.3
 荣耀10 android版本10 
预览大图 保存，在图库相册找不到图片

**Comment by li-xiaojun** [comment]
@szhdev  @eastluzihe  更新到2.5.0试试

**Comment by li-xiaojun** [comment]
更新到2.5.1试试

**Comment by szhdev** [comment]
@li-xiaojun 已修复 可以正常保存！只是权限拒绝后  再次点击下载的时候没有提示
