### ISSUE TITLE
vivo 8.0 弹窗高度问题

### ISSUE THREAD

**Issue by 18810069046** [li-xiaojun/XPopup#743]
**XPopup版本**
2.2.23

**手机系统和型号**
VIVO Y73 Android 8.1.0

**描述你的问题**
看到源码对vivo8.0手机进行高度的特殊处理，导致此手机弹窗时，多出了导航栏的高度。
![Dingtalk_20210624170342](https://user-images.githubusercontent.com/39757351/123235418-6b37a780-d50e-11eb-89b9-e69a054d18ce.jpg)

**Comment by li-xiaojun** [comment]
看看Demo在你手机上有没有问题

**Comment by 18810069046** [comment]
demo也是同样的问题
![Screenshot_20210628_142802](https://user-images.githubusercontent.com/39757351/123591850-156d4300-d81f-11eb-81a3-e70994a8ef4a.jpg)
![image](https://user-images.githubusercontent.com/39757351/123591903-24ec8c00-d81f-11eb-8549-5d8d44166aad.png)

**Comment by li-xiaojun** [comment]
@18810069046 更新到最新版本试试

**Comment by 18810069046** [comment]
![Screenshot_20210702_182039](https://user-images.githubusercontent.com/39757351/124260851-bf700680-db62-11eb-8b7f-a0a081ef2b4a.jpg)
![Screenshot_20210702_182056](https://user-images.githubusercontent.com/39757351/124260860-c139ca00-db62-11eb-8779-ae00453c388a.jpg)

**Comment by Zhuangyongbing** [comment]
作者在basepopup初始化的时候 把导航栏的高度给margin了 所以会造成这个高度的问题，要想解决掉 就之下他的的库  做成module然后自己写多个方法 提供是否需要覆盖导航栏高度把

**Comment by li-xiaojun** [comment]
@Zhuangyongbing  @18810069046 设置`isViewMode(true)`试试

**Comment by 18810069046** [comment]
已解决，谢谢
