### ISSUE TITLE
小米全面屏手机使用上滑手势回到home界面后，再返回到应用界面，界面背景出现异常

### ISSUE THREAD

**Issue by vyve** [li-xiaojun/XPopup#745]
**XPopup版本**
如2.4.3

**手机系统和型号**
小米8SE，红米7A
![2805DF5142E3D5310015626394919B06](https://user-images.githubusercontent.com/22363688/123382269-50c00580-d5c4-11eb-8b09-cd9b60ec52ff.jpg)
![C4998CBFF449FE4E41EACDACD6CCB5CD](https://user-images.githubusercontent.com/22363688/123382273-5289c900-d5c4-11eb-8693-42a27576a84f.jpg)

**描述你的问题**
最好能上代码截图和问题截图

**Comment by li-xiaojun** [comment]
你这个异常跟弹窗应该无关，能录个视频发到群里吗

**Comment by vyve** [comment]
视频我发到群里了，运行了 demo ，重新进行开始的步骤，也会出现上图有灰色边框的情况。

**Comment by li-xiaojun** [comment]
奇怪，我用这2款手机都无法复现，

**Comment by li-xiaojun** [comment]
@vyve  问题没解决的话，尝试设置下isViewMode(true)试试看还有没有

**Comment by li-xiaojun** [comment]
@vyve 你的程序是不是禁用了硬件加速
