### ISSUE TITLE
加载图片的弹框问题

### ISSUE THREAD

**Issue by xqzc000** [li-xiaojun/XPopup#746]
**XPopup版本**
如1.8

**手机系统和型号**
几乎所有手机

**描述你的问题**
弹框如果加载图片，有设置背景的时候，图片还为加载的情况下，当前activity由不可见变为可见的时候，弹框只剩下背景，没有显示图片。

**Comment by li-xiaojun** [comment]
更新到2.4.7，增加了进度条，优化了体验。
