### ISSUE TITLE
Attempt to invoke virtual method 'void com.lxj.xpopup.animator.ShadowBgAnimator.animateDismiss()' on a null object

### ISSUE THREAD

**Issue by MrDomin** [li-xiaojun/XPopup#748]
**XPopup版本**
如2.4.3

**手机系统和型号**
VIVO iQOO Neo3/V1981A(Android 10)

**描述你的问题**
asConfirm

Attempt to invoke virtual method 'void com.lxj.xpopup.animator.ShadowBgAnimator.animateDismiss()' on a null object reference,BasePopupView.java,473

**Comment by li-xiaojun** [comment]
更新到2.4.4即可
