### ISSUE TITLE
可以提供api,去设置dialog.getWindow().setType吗?

### ISSUE THREAD

**Issue by ccc007xp** [li-xiaojun/XPopup#749]
**描述你的问题**
可以提供api,去设置dialog.getWindow().setType吗？现在想要设置Dialog之间的层级设置(不需要使用TYPE_SYSTEM_ALERT)，但目前XPopup的api没找到能设置地方。

getWindow().setType默认是TYPE_APPLICATION=2级别，当设置为TYPE_APPLICATION_STARTING=3时,Dialog在应用里处于上层级。

数值不是越大越高层级，粗略实验猜测，SYSTEM_WINDOW层级(2000~2999)>APPLICATION_WINDOW层级(1～99)>SUB_WINDOW层级(1000～1999)

参考博客:
Android Dialog之间的层级设置（WindowManager.LayoutParams）:
https://blog.csdn.net/yu540135101/article/details/108881206

Android 浮窗开发之窗口层级:
https://www.cnblogs.com/lianghe01/p/6259772.html

**Comment by li-xiaojun** [comment]
弹窗有个dialog属性，你可以设置的。

**Comment by ccc007xp** [comment]
dialog.getWindow().setType需要在dialog.show之前调用,不然会报错java.lang.IllegalArgumentException: Window type can not be changed after the window is added.

这是报错的代码,如果用法有问题,请指教

`BasePopupView basePopupView=new XPopup.Builder(mActivity).moveUpToKeyboard(true).dismissOnBackPressed(false).dismissOnTouchOutside(false).setPopupCallback(new SimpleCallback(){@Override
public void onCreated(BasePopupView popupView){super.onCreated(popupView);LogUtils.v("BasePopupView onCreated");popupView.dialog.getWindow().setType(3);}@Override
public void beforeShow(BasePopupView popupView){super.beforeShow(popupView);LogUtils.v("BasePopupView beforeShow");}}).asCustom(popup);basePopupView.show();`

![QQ截图20210706170011](https://user-images.githubusercontent.com/23648421/124572953-a9708780-de7b-11eb-8031-f32f36d03957.png)
