### ISSUE TITLE
最新版loadingDialog调用dismiss会闪退

### ISSUE THREAD

**Issue by fuxuanyang11** [li-xiaojun/XPopup#757]
**XPopup版本**
2.4.7

**手机系统和型号**
大部分机型

**描述你的问题**
 `、
private var mLoadingDialog: BasePopupView? = null
mLoadingDialog = XPopup.Builder(mActivity)
                    .asLoading()
                    .show()
mLoadingDialog?.dismiss()
`
调用dismiss会出现这个错误
![986 Y` MYQT4_4UMCC{8CXP](https://user-images.githubusercontent.com/21265701/125432298-cbb0207c-5560-40dc-95a4-024b3999b78c.png)

**Comment by fuxuanyang11** [comment]
@li-xiaojun 帮忙看下哈

**Comment by li-xiaojun** [comment]
@fuxuanyang11 已修复，更新到2.4.9即可
