### ISSUE TITLE
PartShadowPopupView 复用  除了第一次show以外，后面每次show弹窗都会闪一下

### ISSUE THREAD

**Issue by ZHOUJJIN** [li-xiaojun/XPopup#759]
**XPopup版本**![image](https://user-images.githubusercontent.com/24580327/125583103-0b712c32-d339-4759-b269-62945616d90f.png)如2.4.9![image](https://user-images.githubusercontent.com/24580327/125583141-3b7b8eed-e880-4d97-b246-3e2f4b621b2e.png)
**手机系统和型号**
很多机型都出现

**描述你的问题**

**Comment by ZHOUJJIN** [comment]
![image](https://user-images.githubusercontent.com/24580327/125589063-0f3022ac-1590-4662-a10c-2064d8c37dcf.png)
这是demo里面的对比

**Comment by li-xiaojun** [comment]
@ZHOUJJIN 经测试不会闪，可以发个视频到QQ交流群。

**Comment by ZHOUJJIN** [comment]
会闪的 视频我发你了

**Comment by li-xiaojun** [comment]
@ZHOUJJIN 更新到2.5.0，修复了这个问题

**Comment by luoxiong94** [comment]
最新版本还是会出现这个问题

**Comment by li-xiaojun** [comment]
@luoxiong94 可否给个能复现的demo，按上面的代码无法复现
