### ISSUE TITLE
编译环境只能是26吗？我的是28编译出错啊，然后改成26就通过了。

### ISSUE THREAD

**Issue by alx1992** [li-xiaojun/XPopup#76]
compileSdkVersion 26

dependencies {
    implementation 'com.android.support:appcompat-v7:26.0.0'
    implementation 'com.android.support:cardview-v7:26.0.0'
    implementation 'com.android.support:recyclerview-v7:26.0.0'
}

**Comment by li-xiaojun** [comment]
@alx1992 
我demo就是28的，不会出错啊；你截个图我看看。

**Comment by zhaoxiuyu** [comment]
我在A  Activity跳转到B Activity ，A的onDestroy 里面dismiss，B的onCreate里面进行弹出Dialog，就弹不出来。
有办法解决吗
@li-xiaojun

**Comment by li-xiaojun** [comment]
@zhaoxiuyu 
贴下代码片段。

**Comment by zhaoxiuyu** [comment]
protected void onDestroy() {
        super.onDestroy();
        XPopup.get(this).dismiss();
    }

![Uploading image.png…]()

**Comment by zhaoxiuyu** [comment]
![Y4NEZY3WB{336B~{LH7P(G2](https://user-images.githubusercontent.com/16554580/54662254-6d814f00-4b18-11e9-8cb1-ac23ff2db58b.png)
![VRPG}S)UG11XOHI(YL4{IHX](https://user-images.githubusercontent.com/16554580/54662258-6eb27c00-4b18-11e9-9149-8f5610949408.png)

**Comment by zhaoxiuyu** [comment]
会不会因为popupViews 是 static 的原因
@li-xiaojun

**Comment by alx1992** [comment]
我的原因，多导入了一个用不到的包。
