### ISSUE TITLE
loadingview样式问题

### ISSUE THREAD

**Issue by hegelsu** [li-xiaojun/XPopup#761]
**XPopup版本**
如2.4.9

**手机系统和型号**
夜神模拟器7.0.1.2，我手机荣耀30一样的效果
![1](https://user-images.githubusercontent.com/6879123/125731477-a102fd0b-f994-41b4-97a1-3bd939afac98.png)

**描述你的问题**
loadingview样式问题，如何设置成下面的效果：
![2](https://user-images.githubusercontent.com/6879123/125731563-bbb5bbe0-685a-457b-9f9e-737448b584fc.png)

**Comment by li-xiaojun** [comment]
@hegelsu  下面的样式去掉了，可自定义一个Loading弹窗，样式完全由你控制

**Comment by li-xiaojun** [comment]
必现吗？

**Comment by hegelsu** [comment]
不是去掉了么，那肯定是必现了啊。

**Comment by li-xiaojun** [comment]
看你截图 加载中 三个字没有显示全，我还以为是异常情况

**Comment by hegelsu** [comment]
不是，只是纯问样式的问题。
