### ISSUE TITLE
在Vivo设备上XPopup 弹窗显示时会自动弹出输入法

### ISSUE THREAD

**Issue by UserName-Haha** [li-xiaojun/XPopup#762]
**XPopup版本**
2.4.9

**手机系统和型号**
Vivo Z1青春版 Android 8.1

**描述你的问题**
在Vivo设备上XPopup 弹窗显示时会自动弹出输入法。
查看源码后发现是因为在 Xpopup.show() 时会默认抢占焦点导致的，目前是设置 isRequestFocus(false) 暂时解决，盼后续能进行适配优化。
源码中这行代码导致的：
```
if (popupInfo.isRequestFocus) KeyboardUtils.hideSoftInput(activity.getWindow());
```
以下是会出问题的代码：
![image](https://user-images.githubusercontent.com/35187059/125886117-428191db-c536-4d14-9283-66bb265a9c57.png)

修改后解决自动弹出的代码：
![image](https://user-images.githubusercontent.com/35187059/125886445-a437d191-fcae-4c45-8216-0ad052967c9b.png)

**Comment by li-xiaojun** [comment]
更新到最新版本即可

**Comment by zqlq4ever** [comment]
> 更新到最新版本即可

2.5.15 又出现了这个问题，加上 .isRequestFocus(false) 就不弹出输入法了

**Comment by licheedev** [comment]
> > 更新到最新版本即可
> 
> 2.5.15 又出现了这个问题，加上 .isRequestFocus(false) 就不弹出输入法了

确实，设置了就不弹输入法了，我最后是通过动态禁用启用输入法实现的。

扩展方法：
```
/** 禁用软键盘 */
fun Window?.disableSoftInputMethod() {
    this?:return
    addFlags(WindowManager.LayoutParams.FLAG_ALT_FOCUSABLE_IM);
}

/** 启用软键盘 */
fun Window?.enableSoftInputMethod() {
    this?:return
    clearFlags(WindowManager.LayoutParams.FLAG_ALT_FOCUSABLE_IM);
}
```

在显示前禁用输入法，显示后启用输入法
```
override fun beforeShow() {
    hostWindow.disableSoftInputMethod()
    super.beforeShow()
}
override fun doAfterShow() {
    super.doAfterShow()
    hostWindow.enableSoftInputMethod()
}
```
