### ISSUE TITLE
图片放大后，垂直滑动只有屏幕内部分的图片会缩放

### ISSUE THREAD

**Issue by Iduace** [li-xiaojun/XPopup#764]
**XPopup版本**
2.5.1

**手机系统和型号**

**描述你的问题**
图片放大后，垂直滑动只有屏幕内部分的图片会缩放，能改成整体缩放的话效果应该会更好，或者放大时不执行滑动退出

**Comment by li-xiaojun** [comment]
你说的交互不太行，多看看类似的交互就知道我为什么这么设计了。
