### ISSUE TITLE
点击查看大图弹窗部分图片会旋转

### ISSUE THREAD

**Issue by xhh1993** [li-xiaojun/XPopup#769]
**XPopup版本**
最新版2.3.5

**手机系统和型号**
华为Mate20 Android 10

**描述你的问题**
点击放大图片使用SmartGlideImageLoader加载，部分图片会旋转为横图

**Comment by xhh1993** [comment]
使用最新的Dome图片浏览也会出现这种情况，比如使用下面的连接：
https://img.live.qiqushiting.com/Pimg/img/squ/img/107821622429832886.jpg

**Comment by li-xiaojun** [comment]
@xhh1993 更新到2.5.4即可

**Comment by xhh1993** [comment]
> @xhh1993 更新到2.5.4即可

多谢大佬

**Comment by linxingxi** [comment]
最新版本2.6.8发现部分图还是有点击查看预览图会旋转的情况

**Comment by androidjiajia** [comment]
> 最新版本2.6.8发现部分图还是有点击查看预览图会旋转的情况

如这张图：http://test-yjk.oss-cn-chengdu.aliyuncs.com/APP/dynamic/picture/1637229940713.jpeg
在最新demo里查看该张图也是旋转的
