### ISSUE TITLE
大图浏览弹窗设置onSrcViewUpdate方法后滑动会卡顿

### ISSUE THREAD

**Issue by 9292922** [li-xiaojun/XPopup#770]
设置了这个更新监听onSrcViewUpdate，切换图片浏览时会卡顿，不设置就不会。但是如果不设置，返回的时候不是开始的照片时，共享元素有点奇怪

官方demo不会卡顿，估计是图片太小像素低这些，我看了demo的源码实现不会出现这样的情况。

gif图片可能不明显，但是手机上很明显。

**Comment by li-xiaojun** [comment]
@9292922 你是图片都是不压缩的？是什么使用场景

**Comment by 9292922** [comment]
不压缩的（读取的是本地图片的uri)，就是用于大图浏览呀，因为很方便。如果没有设置onSrcViewUpdate，imagepopup速度是没问题的，就是设置了就会卡顿



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月28日(周六) 晚上6:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [li-xiaojun/XPopup] 大图浏览弹窗设置onSrcViewUpdate方法后滑动会卡顿 (#770)




 
@9292922 你是图片都是不压缩的？是什么使用场景

**Comment by li-xiaojun** [comment]
不压缩卡顿就对了，耗时主要在decode上面。
