### ISSUE TITLE
红米note8pro底部弹窗显示不全

### ISSUE THREAD

**Issue by tdxtxt** [li-xiaojun/XPopup#771]
XPopup版本：2.5.4
手机系统和型号：Redmi Note 8 Pro
描述你的问题：底部弹窗显示不完整问题，截图（demo）如下
![1627523396(1)](https://user-images.githubusercontent.com/5369160/127419531-7d4fbb32-8c0f-40a6-916f-e595a2c94595.jpg)
![1627523457(1)](https://user-images.githubusercontent.com/5369160/127419647-1e8c2fbb-99cf-48a1-9e23-9cc2cd26bcbc.jpg)

**Comment by li-xiaojun** [comment]
@tdxtxt 更新到2.5.4试试

**Comment by tdxtxt** [comment]
版本2.5.4运行如下：
只有【复杂交互的Bottom弹窗】是显示正常的，【显示自定义Bottom弹窗】和【显示Bottom类型的List弹窗】不正常，截图如下
![1627638579](https://user-images.githubusercontent.com/5369160/127636088-07bce1c0-9965-4dbb-9203-2770389a889c.jpg)
![1627638692(1)](https://user-images.githubusercontent.com/5369160/127636107-18945cdb-ef52-47c4-9dcf-d48665de881d.jpg)
![1627638912(1)](https://user-images.githubusercontent.com/5369160/127636349-86e89578-3cf2-4874-bd56-398737df3873.jpg)

**Comment by li-xiaojun** [comment]
设置isViewMode(true)试试

**Comment by tdxtxt** [comment]
这个方法确实可以，能解决问题。
