### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by Traveler1991** [li-xiaojun/XPopup#773]
**XPopup版本**
com.lxj:xpopup:2.2.23

**手机系统和型号**
OPPO Reno5 5G Android 11

**描述你的问题**
![image](https://user-images.githubusercontent.com/13065967/127731066-7981e250-c0f2-4b8a-9262-d5cf604f47dd.png)
![image](https://user-images.githubusercontent.com/13065967/127731079-2bb1cbf0-13d2-43b8-b82f-2e9d2a46769e.png)

**Comment by li-xiaojun** [comment]
你申请弹窗权限了吗？如果要再后台开启，需要申请弹窗权限的。

**Comment by Traveler1991** [comment]
权限都开了，这个也不是在后台开启的
