### ISSUE TITLE
moveUpToKeyboard切换中英模式时，高度不会跟随改变

### ISSUE THREAD

**Issue by Iduace** [li-xiaojun/XPopup#774]
**XPopup版本**
最新版本

**手机系统和型号**

**描述你的问题**
moveUpToKeyboard的bottom弹窗，切换中英键盘高度改变会留白或遮挡

**Comment by Iduace** [comment]
@Override
    protected void onKeyboardHeightChange(int height) {
        XPopupUtils.moveUpToKeyboard(height,this);
    }
目前是用这个解决的

**Comment by Iduace** [comment]
@Override
    protected void onKeyboardHeightChange(int height) {
        XPopupUtils.moveUpToKeyboard(height,this);
    }

**Comment by li-xiaojun** [comment]
我优化下

**Comment by li-xiaojun** [comment]
@Iduace 更新到2.5.7即可，我已实现弹窗根据输入法高度变化进行智能移动

**Comment by Iduace** [comment]
@li-xiaojun 多谢
