### ISSUE TITLE
使用isViewMode(true)，导航栏不兼容问题

### ISSUE THREAD

**Issue by xhh1993** [li-xiaojun/XPopup#779]
**XPopup版本**
最新版

项目需求弹窗内部使用viewPager+fragment，使用isViewMode(true)，手机导航栏会挡住部分弹窗。导致弹窗底部的按钮无法响应。最新demo也是必现。

**Comment by xhh1993** [comment]
好像之前1.x的版本没有isViewMode(true)方法，但是使用这种方式没有问题

**Comment by xhh1993** [comment]
![QQ图片20210804153611](https://user-images.githubusercontent.com/17424639/128140934-2bbb651f-2887-4c7f-b663-345cab1b4d20.jpg)

**Comment by li-xiaojun** [comment]
@xhh1993 你用的是哪个版本，我记得是解决了
