### ISSUE TITLE
其他popupwindow dimiss后，DrawerLayout 无法显示显示

### ISSUE THREAD

**Issue by ljxx** [li-xiaojun/XPopup#78]
问题一：我的列表头上有价格排序，用到下拉的popupwindow, 手动dimiss以后。DrawerLayout类型的po pupwindow就无法再显示出来；

问题二：XPopupCallback中的onShow() 和 onDismiss()方法，监听不稳定，时而好，时而没有响应

**Comment by li-xiaojun** [comment]
贴个效果图

**Comment by li-xiaojun** [comment]
@ljxx 
最新版本1.6.0已修复，但是不兼容之前的API，酌情升级。
