### ISSUE TITLE
能加上去掉事件间隔时间的选项吗

### ISSUE THREAD

**Issue by Iduace** [li-xiaojun/XPopup#783]
**XPopup版本**
2.5.8

**手机系统和型号**

**描述你的问题**
BottomPopupView展示RecyclerView列表信息时，事件间隔时间太久滑动后点击之类衔接会不流畅

**Comment by li-xiaojun** [comment]
不明白你说的啥意思，能详细说下吗

**Comment by Iduace** [comment]
比如两次点击之间有个默认的应该是防止重复点击的时间间隔，如果用来做评论区之类的话上下滑动后再进行点击等操作太快会被拦截导致不流畅

**Comment by li-xiaojun** [comment]
这个点击防抖是业务层去做，不应该框架层做。
