### ISSUE TITLE
应用在后台时，弹出弹窗会出现：背景暗掉，但是弹窗没显示

### ISSUE THREAD

**Issue by fuxuanyang11** [li-xiaojun/XPopup#786]
**XPopup版本**
如2.5.8

**手机系统和型号**
所有

**描述你的问题**
应用在后台时，弹出弹窗会出现：背景暗掉，但是弹窗没显示

**Comment by fuxuanyang11** [comment]
isViewMode 为true才会

**Comment by li-xiaojun** [comment]
应用在后台时不支持isViewMode，因为Activity的界面都没了，弹窗也找不到宿主界面了。去掉这个试试
