### ISSUE TITLE
全屏下,弹窗切换到后台再回来（或系统弹窗弹出后），点击不能展示

### ISSUE THREAD

**Issue by ChengYong1214** [li-xiaojun/XPopup#787]
**XPopup版本**
如2.5.8

**手机系统和型号**
小米8 Android 10

**描述你的问题**
继承HorizontalAttachPopupView自定义，isViewModel=true；activity设置全屏（隐藏状态栏和导航栏），切换到后台再回来（或系统弹窗弹出后），点击页面不展示，观察过生命周期都会走，就是不展示页面。android:screenOrientation="landscape"去除后，可以正常。
![image](https://user-images.githubusercontent.com/60781231/128852733-cd7dbb88-3e9f-439e-99e0-483693f91c07.png)

**Comment by li-xiaojun** [comment]
@ChengYong1214 
我按你的步骤操作，没有复现。你能把操作步骤说详细点吗

**Comment by ChengYong1214** [comment]
在全屏和横屏下，isViewModel=true，继承HorizontalAttachPopupView，正常点击弹出弹窗，在应用切换到后台，再点击应用回来，发现之前的弹窗点击不能显示

**Comment by li-xiaojun** [comment]
更新到最新版本试试
