### ISSUE TITLE
设置popupAnimation后无法显示

### ISSUE THREAD

**Issue by HQLIE2018** [li-xiaojun/XPopup#789]
**XPopup版本**
如2.5.8

**手机系统和型号**
Android 10

**描述你的问题**
设置popupAnimation(PopupAnimation.TranslateAlphaFromRight)，调用show()无法显示
 new XPopup.Builder(this).moveUpToKeyboard(false)
                            .popupAnimation(PopupAnimation.TranslateAlphaFromRight).enableDrag(false).asCustom(new CustomerBottomDialog(this))

**Comment by wjwang0914** [comment]
新版本上我也到了这个问题，BottomPopupView，修改了popupAnimation就无法弹窗了
