### ISSUE TITLE
自定义jichengyu

### ISSUE THREAD

**Issue by fjyuqiang** [li-xiaojun/XPopup#79]

**Comment by fjyuqiang** [comment]
在MIUI 10，Android 9.0上View中间总是会有不透明的白色矩形

**Comment by li-xiaojun** [comment]
@fjyuqiang 
截个图，然后最好贴下代码。

**Comment by li-xiaojun** [comment]
@fjyuqiang 
我用MIUI10试了下发现没问题，能详细说下您的机型吗。

**Comment by fjyuqiang** [comment]
不好意思，没及时看到。之前是我用View叠加背景阴影造成的，和库没关系，已解决。现在还有个问题，没有找到关于设置PopWindow显示时的X、Y轴偏移量，能否添加相应的方法，比如像原生popWindow的#showAsLocation()。需求要点击titlebar显示菜单，显示的菜单需要一定的偏移，#watchView() 达不到效果

**Comment by fjyuqiang** [comment]
@li-xiaojun

**Comment by li-xiaojun** [comment]
@fjyuqiang 
更新到1.6.5版本，现在所有弹窗都已支持offsetX和offsetY了。

**Comment by fjyuqiang** [comment]
测试了下，1.6.5的offsetX和offsetY方法并没有真正生效，自定义弹窗继承的是attachPopwindow
![image](https://user-images.githubusercontent.com/18246136/55312412-11171b80-5498-11e9-8d5e-479c81933d8c.png)

**Comment by li-xiaojun** [comment]
@fjyuqiang 
我重新测试了下，确认没有问题。我怀疑你手机像素高，10太小，不太明显。你把offset的值改大点试试

**Comment by fjyuqiang** [comment]
是方法报红，没法用

**Comment by fjyuqiang** [comment]
demo中弹窗是继承的HorizontalAttachPopupView，必须要继承这个类才可以使用offset相关方法吗

**Comment by li-xiaojun** [comment]
@fjyuqiang 
方法爆红是编译器的问题，请尝试rebuild或者重启studio。offset方法是所有弹窗都能使用的。

**Comment by fjyuqiang** [comment]
clean之后可以了，偏移的单位是px还是dp

**Comment by li-xiaojun** [comment]
@fjyuqiang 
单位是px
