### ISSUE TITLE
PositionPopupView  外部点击不可取消

### ISSUE THREAD

**Issue by JsonCooler** [li-xiaojun/XPopup#791]
继承自PositionPopupView    设置在顶部弹出   设置了外部点击取消但是点击下面透明部分不会触发dimiss()方法

**Comment by JsonCooler** [comment]
![it](https://user-images.githubusercontent.com/16770276/130176484-a9f1375d-3e76-41ed-a9dc-a1fdf6a758e3.jpg)
点击下方无法取消Xpop

**Comment by li-xiaojun** [comment]
哪个xpopup版本

**Comment by JsonCooler** [comment]
implementation 'com.github.li-xiaojun:XPopup:2.4.1'
布局是这样得
` <androidx.constraintlayout.widget.ConstraintLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <com.dingjianlun.circleimageview.CircleImageView
            android:id="@+id/bgView"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:scaleType="centerCrop"
            android:src="@drawable/icon_home_head"
            app:civ_left_bottom_radius="12dp"
            app:civ_right_bottom_radius="12dp"
            app:civ_type="round"
            app:layout_constraintBottom_toBottomOf="@+id/addNewMember"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent" />


        <androidx.appcompat.widget.AppCompatTextView
            android:id="@+id/switchUserTips"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginStart="30dp"
            android:layout_marginTop="50dp"
            android:text="@string/switch_user"
            android:textColor="@color/white"
            android:textSize="18sp"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent" />


        <androidx.appcompat.widget.AppCompatImageView
            android:id="@+id/close"
            android:layout_width="30dp"
            android:layout_height="30dp"
            android:layout_marginEnd="15dp"
            android:padding="5dp"
            app:layout_constraintBottom_toBottomOf="@id/switchUserTips"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintTop_toTopOf="@id/switchUserTips"
            app:srcCompat="@drawable/ic_delete" />


        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/memberRv"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_marginTop="20dp"
            app:layout_constraintBottom_toTopOf="@id/addNewMember"
            app:layout_constraintDimensionRatio="w,1:1.4"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@id/switchUserTips" />

        <androidx.appcompat.widget.AppCompatTextView
            android:id="@+id/addNewMember"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:gravity="center"
            android:paddingTop="12dp"
            android:paddingBottom="20dp"
            android:text="@string/add_new_member"
            android:textColor="@color/white"
            app:layout_constraintTop_toBottomOf="@id/memberRv" />

    </androidx.constraintlayout.widget.ConstraintLayout>`

**Comment by JsonCooler** [comment]
> 哪个xpopup版本

不好意思，我才发现 在继承类里面重写了高度，使用了 XPopupUtils.getScreenHeight(context)导致Pop全屏了
