### ISSUE TITLE
继承FullScreenPopupView 的全屏dialog 设置dismissOnTouchOutside（true）无效

### ISSUE THREAD

**Issue by yuekong** [li-xiaojun/XPopup#792]
**XPopup版本**
如2.5.9

**手机系统和型号**
小米11 Android 11

**描述你的问题**
   if (mEcDropActionPopup == null) {
            mEcDropActionPopup = (EcDropActionPopup) new XPopup.Builder(AddDeviceTipActivity.this)
                    .dismissOnBackPressed(true)
                    .dismissOnTouchOutside(true)
                    .isRequestFocus(false)
                    .popupAnimation(PopupAnimation.TranslateFromTop)
                    .setPopupCallback(new SimpleCallback() {
                        @Override
                        public void onShow(BasePopupView popupView) {
                        }

                        @Override
                        public void onDismiss(BasePopupView popupView) {
                            mCurrentCode = mEcDropActionPopup.getMode();
                        }
                    })
                    .asCustom(new EcDropActionPopup(AddDeviceTipActivity.this));

        }
        mEcDropActionPopup.show();

**Comment by li-xiaojun** [comment]
全屏弹窗你是怎么触摸到外面的？这个属性对全面弹窗已经没有用了，因为无法触摸到弹窗外部了
