### ISSUE TITLE
推荐加XPopup的QQ群：783659607，交流更方便！

### ISSUE THREAD

**Issue by li-xiaojun** [li-xiaojun/XPopup#8]
## 优先看文档
文档已经非常详细的解释了如何使用，一些注意事项和常见问题的解决方式。所以具体的使用要先看文档。

## 编译出错问题
我的编译配置如下：
```
compileSdkVersion 26

dependencies {
    implementation 'com.android.support:appcompat-v7:26.0.0'
    implementation 'com.android.support:recyclerview-v7:26.0.0'
    implementation 'com.android.support:design:26.0.0'
}
```
如果你本地没有26版本的SDK，可能报错resource引用找不到或者其他编译类错误；
此时下载26的SDK重新编译即可，建议保持更新最新SDK。这个和你自己项目的编译版本完全可以不一样，关键是你本地要下26的SDK。

## 如何提Issue
如果您遇到问题，可以详细列出机型和系统版本，最好有代码和效果截图；如果只是XX手机上有什么问题，我还需要去找到这款手机去重现这个问题。我不可能找得到所有的手机，所以贴个代码和截图，很大程度我就能定位问题所在，谢谢了。

如果遇到问题，先运行我的Demo看看有没有问题。如果我的Demo没有问题，那么往往是你使用不当造成的；如果我的Demo也有问题，那么肯定就是Bug了。

**Comment by XD-Z** [comment]
Thank you for sharing

**Comment by etyhk** [comment]
![image](https://user-images.githubusercontent.com/8375979/54800353-64b98600-4c9c-11e9-9770-7dce5a5bc74d.png)
添加这个库就出这错，看了下一你的源码，也没有关于theme的设置啊

**Comment by etyhk** [comment]
com.android.support:appcompat-v7:26.1.0，提示一下，这个版本用不了

**Comment by li-xiaojun** [comment]
@etyhk
你本地有26的sdk么

**Comment by zbore** [comment]
@li-xiaojun 有些环境的问题尽显。。。，感觉有些人张口就来，就知道copy,paste,
都不主动思考！！！

**Comment by li-xiaojun** [comment]
@zbore 是的，有很多人习惯于CP(CopyPaste)编程，也可能是刚入行的没见过这种问题不知道怎么解决。

**Comment by etyhk** [comment]
> @etyhk
> 你本地有26的sdk么

有呢，测试过26.1有编译问题

**Comment by 15031021126** [comment]
怎么下载jar包导入到项目里

**Comment by alone19920109** [comment]
使用在平板里 显示有问题  我目前用着平板的横屏模式 在屏幕的边缘有明显的空余 没有全覆盖 大概流了有50dp左右（其余部分 全部有阴影）

**Comment by dary123** [comment]
java.lang.IllegalArgumentException

Parameter specified as non-null is null: method i.l2.t.i0.f, parameter text

解析原始
1 e.k.a.g.setText(Unknown Source:2)
2 com.lxj.xpopup.impl.CenterListPopupView$1.void bind(com.lxj.easyadapter.ViewHolder,java.lang.String,int)(CenterListPopupView.java:2)
3 com.lxj.xpopup.impl.CenterListPopupView$1.void bind(com.lxj.easyadapter.ViewHolder,java.lang.Object,int)(CenterListPopupView.java:1)
4 e.k.a.b$a.a(EasyAdapter.kt:2)
5 e.k.a.d.a(ItemDelegateManager.kt:21)
6 e.k.a.e.a(MultiItemTypeAdapter.kt:5)
7 e.k.a.e.a(MultiItemTypeAdapter.kt:11)
8 e.k.a.e.onBindViewHolder(MultiItemTypeAdapter.kt:1)
9 androidx.recyclerview.widget.RecyclerView$Adapter.void onBindViewHolder(androidx.recyclerview.widget.RecyclerView$ViewHolder,int,java.util.List)(RecyclerView.java:1)
10 androidx.recyclerview.widget.RecyclerView$Adapter.void bindViewHolder(androidx.recyclerview.widget.RecyclerView$ViewHolder,int)(RecyclerView.java:6)
11 androidx.recyclerview.widget.RecyclerView$Recycler.boolean tryBindViewHolderByDeadline(androidx.recyclerview.widget.RecyclerView$ViewHolder,int,int,long)(RecyclerView.java:8)
12 androidx.recyclerview.widget.RecyclerView$Recycler.androidx.recyclerview.widget.RecyclerView$ViewHolder tryGetViewHolderForPositionByDeadline(int,boolean,long)(RecyclerView.java:91)
13 androidx.recyclerview.widget.RecyclerView$Recycler.android.view.View getViewForPosition(int,boolean)(RecyclerView.java:1)
14 androidx.recyclerview.widget.RecyclerView$Recycler.android.view.View getViewForPosition(int)(RecyclerView.java:11)
15 androidx.recyclerview.widget.LinearLayoutManager$LayoutState.android.view.View next(androidx.recyclerview.widget.RecyclerView$Recycler)(LinearLayoutManager.java:4)
16 androidx.recyclerview.widget.LinearLayoutManager.void onAnchorReady(androidx.recyclerview.widget.RecyclerView$Recycler,androidx.recyclerview.widget.RecyclerView$State,androidx.recyclerview.widget.LinearLayoutManager$AnchorInfo,int)(LinearLayoutManager.java:148)
17 ##_parent_##1##_parent_##
18 ##_child_## void layoutChunk(androidx.recyclerview.widget.RecyclerView$Recycler,androidx.recyclerview.widget.RecyclerView$State,androidx.recyclerview.widget.LinearLayoutManager$LayoutState,androidx.recyclerview.widget.LinearLayoutManager$LayoutChunkResult)##_child_##
19 androidx.recyclerview.widget.LinearLayoutManager.void onAnchorReady(androidx.recyclerview.widget.RecyclerView$Recycler,androidx.recyclerview.widget.RecyclerView$State,androidx.recyclerview.widget.LinearLayoutManager$AnchorInfo,int)(LinearLayoutManager.java:135)
20 ##_parent_##1##_parent_##
21 ##_child_## int fill(androidx.recyclerview.widget.RecyclerView$Recycler,androidx.recyclerview.widget.LinearLayoutManager$LayoutState,androidx.recyclerview.widget.RecyclerView$State,boolean)##_child_##
22 androidx.recyclerview.widget.LinearLayoutManager.void onLayoutChildren(androidx.recyclerview.widget.RecyclerView$Recycler,androidx.recyclerview.widget.RecyclerView$State)(LinearLayoutManager.java:73)
23 androidx.recyclerview.widget.RecyclerView.void dispatchLayoutStep2()(RecyclerView.java:8)
24 androidx.recyclerview.widget.RecyclerView.void onMeasure(int,int)(RecyclerView.java:12)
25 android.view.View.measure(View.java:24742)
26 android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6903)
27 android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1562)
28 android.widget.LinearLayout.measureVertical(LinearLayout.java:849)
29 android.widget.LinearLayout.onMeasure(LinearLayout.java:728)
30 android.view.View.measure(View.java:24742)
31 android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6903)
32 android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
33 android.view.View.measure(View.java:24742)
34 android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6903)
35 android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
36 android.view.View.measure(View.java:24742)
37 android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6903)
38 android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
39 com.android.internal.policy.DecorView.onMeasure(DecorView.java:896)
40 android.view.View.measure(View.java:24742)
41 android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3211)
42 android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1974)
43 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2295)
44 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1857)
45 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8089)
46 android.view.Choreographer$CallbackRecord.run(Choreographer.java:1057)
47 android.view.Choreographer.doCallbacks(Choreographer.java:875)
48 android.view.Choreographer.doFrame(Choreographer.java:776)
49 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
50 android.os.Handler.handleCallback(Handler.java:888)
51 android.os.Handler.dispatchMessage(Handler.java:100)
52 android.os.Looper.loop(Looper.java:213)
53 android.app.ActivityThread.main(ActivityThread.java:8169)
54 java.lang.reflect.Method.invoke(Native Method)
55 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
56 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by JackZ-2019** [comment]
机型：OPPO A5 
ColorOS：v5.2.1
Android系统：8.1.0
问题描述：代码环境：viewPage2+Fragment；viewPage2中包含了FragmentA、FragmentB，FragmentB调用AsConfirm弹出了一个对话框，此时点击取消后，ViewPage2会触发OnScrolled

**Comment by li-xiaojun** [comment]
> 机型：OPPO A5
> ColorOS：v5.2.1
> Android系统：8.1.0
> 问题描述：代码环境：viewPage2+Fragment；viewPage2中包含了FragmentA、FragmentB，FragmentB调用AsConfirm弹出了一个对话框，此时点击取消后，ViewPage2会触发OnScrolled

加qq群: 783659607,   录个视频发出来我给你看看

**Comment by wzgl5533** [comment]
使用了图片预览的功能，很不错。想问一下，有没有扩展像微信那种短视频也能预览的打算？
