### ISSUE TITLE
资源报错selectableItemBackground 

### ISSUE THREAD

**Issue by tang5011235** [li-xiaojun/XPopup#80]
* What went wrong:
Execution failed for task ':commonlib:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  F:\company_project\mvpmarmsImprovment\commonlib\build\intermediates\res\merged\release\layout\_xpopup_adapter_text.xml:2: error: resource attr/selectableItemBackground (aka com.example.commonlib:attr/selectableItemBackgroun
d) not found.
  F:\company_project\mvpmarmsImprovment\commonlib\build\intermediates\res\merged\release\layout\_xpopup_center_impl_confirm.xml:41: error: resource attr/selectableItemBackground (aka com.example.commonlib:attr/selectableItemB
ackground) not found.
  F:\company_project\mvpmarmsImprovment\commonlib\build\intermediates\res\merged\release\layout\_xpopup_center_impl_confirm.xml:54: error: resource attr/selectableItemBackground (aka com.example.commonlib:attr/selectableItemB
ackground) not found.
  error: failed linking file resources.

**Comment by li-xiaojun** [comment]
@tang5011235 
先看看常见问题说明
