### ISSUE TITLE
华为Mate30 Pro 5G横屏问题

### ISSUE THREAD

**Issue by jiqianwen** [li-xiaojun/XPopup#800]
**XPopup版本**
如2.5.10

**手机系统和型号**
华为Mate30 Pro 5G

**描述你的问题**
自定义BottomPopupView横屏时对刘海屏的判断貌似反了，在Demo中也是如此，进入页面Demo QuickStartFragment设置横屏属性为requireActivity().requestedOrientation = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE 即可复现
![IMG_20210826_100032](https://user-images.githubusercontent.com/26268908/131206361-6501880a-0aa6-4f90-b7b9-c8ee7a7d131c.jpg)
![QQ图片20210828124039](https://user-images.githubusercontent.com/26268908/131206363-c1a117c6-1741-46dc-a3f4-18040bf21d44.png)

**Comment by li-xiaojun** [comment]
@jiqianwen 更新到2.5.12即可
