### ISSUE TITLE
如何更改大图浏览点击行为

### ISSUE THREAD

**Issue by fishballzzz** [li-xiaojun/XPopup#802]
**XPopup版本**
2.5.11

**手机系统和型号**
pixel4 Android 11

**描述你的问题**
如题。我希望大图浏览窗口tap的时候显示或隐藏保存按钮而不是dismiss。。我找了一圈没找到地方，感谢大佬

**Comment by li-xiaojun** [comment]
@fishballzzz 这种特殊的业务你需要继承ImageViewerPopupView，自己实现了，demo中也有自定义ImageViewPopupView的示例。
