### ISSUE TITLE
@li-xiaojun  hasStatusBar(false)只是隐藏了状态栏，但是状态栏的文字和图标还是操作的

### ISSUE THREAD

**Issue by BugRui** [li-xiaojun/XPopup#803]
@li-xiaojun  hasStatusBar(false)只是隐藏了状态栏，但是状态栏的文字和图标还是存在的

_Originally posted by @BugRui in https://github.com/li-xiaojun/XPopup/issues/797#issuecomment-907959130_

**Comment by li-xiaojun** [comment]
@BugRui xpopup版本 + 截图
