### ISSUE TITLE
友盟线上经常报错的一个问题：空指针

### ISSUE THREAD

**Issue by xhh1993** [li-xiaojun/XPopup#804]
**XPopup版本**
最新版：2.5.4

这是友盟上面经常报错的一个问题，大概占了0.03%。机型的话主要集中在模拟器android7以下的系统。由于我们有大量模拟器的使用用户，因此这个问题还是不能忽略的。
![QQ截图20210831155741](https://user-images.githubusercontent.com/17424639/131465465-ec6f1dd3-de3a-4f87-87e0-a179bdf8279c.png)

**Comment by li-xiaojun** [comment]
@xhh1993 更新到最新版本即可
