### ISSUE TITLE
XPopup显示弹窗的时候会更改底部状态的颜色

### ISSUE THREAD

**Issue by Stonejxn** [li-xiaojun/XPopup#806]
**XPopup版本**
如2.2.6

**手机系统和型号**
小米10 Android 11

**描述你的问题**
最好能上代码截图和问题截图
![image](https://user-images.githubusercontent.com/5425635/131647876-4487448e-0369-4366-ab24-5f96a7001f7e.png)
代码就是标准的方法使用，
显示调用  mXPopup_FindSettings.show();底部状态栏被修改成了白色。
然后关闭调用    mXPopup_FindSettings.dismiss();底部状态栏还原成我原来设置的颜色

**Comment by li-xiaojun** [comment]
@Stonejxn  版本太低，更新到最新版本
