### ISSUE TITLE
项目无法编译

### ISSUE THREAD

**Issue by shenqiwen** [li-xiaojun/XPopup#81]
![QJS)XMSMQ(L$N@GD~$TBOOV](https://user-images.githubusercontent.com/31466883/54739179-2b2c4080-4bf2-11e9-8d3f-865432f5065e.png)

**Comment by li-xiaojun** [comment]
@shenqiwen 
你网络有问题。

**Comment by shenqiwen** [comment]
需要翻墙吗? @li-xiaojun

**Comment by shenqiwen** [comment]
不晓得其他人是怎么编译Demo的,楼主的Demo对gradle小白来说确实一脸懵逼,无法编译, @li-xiaojun

**Comment by li-xiaojun** [comment]
@shenqiwen 
网络问题啊，无法下载类库。
