### ISSUE TITLE
弹窗动态高度问题

### ISSUE THREAD

**Issue by yixi195** [li-xiaojun/XPopup#810]
如何动态改变BottomPopupView弹窗的高度
场景：比如弹窗的View中某些组件由 gone 变为 visible

**Comment by li-xiaojun** [comment]
@yixi195 你弹窗布局的高度用wrap不就自动缩小了吗

**Comment by yixi195** [comment]
现在父布局是用的android:layout_height="wrap_content" ，然后子布局默认是 gone掉的，点击一个按钮以后 visible 的时候父布局没有变高。  你有空可以测试下看？

**Comment by yixi195** [comment]
@li-xiaojun

**Comment by yixi195** [comment]
可以了。感谢，是因为重写了 getMaxHeight导致wrap没有生效。
