### ISSUE TITLE
自定义BottomPopup  被底部导航栏挡住了

### ISSUE THREAD

**Issue by fuchengxin** [li-xiaojun/XPopup#811]
**XPopup版本**
2.0.8

**手机系统和型号**
华为KSA-AL10 Android 9
![image](https://user-images.githubusercontent.com/15795966/132175248-ed9b2529-3dff-460c-af8e-3cb13376b53b.png)
如图代码就是一个简单的自定义BottomPopupView，hasStatusBar true或者false 都不起作用

![75AD6F1C26E8623253ED33AA789D5B8C](https://user-images.githubusercontent.com/15795966/132175176-96faf2f5-c82c-40a2-b52d-51f0c253bc12.jpg)

**Comment by Rethen** [comment]
怎么解决的兄弟，我也遇到了
