### ISSUE TITLE
com.lxj.xpopup.core.BasePopupView#show  在子线程调用会导致crash

### ISSUE THREAD

**Issue by yygutn** [li-xiaojun/XPopup#813]
**XPopup版本**
如2.5.15

**手机系统和型号**
MI11 Android 11

**描述你的问题**
com.lxj.xpopup.core.BasePopupView#show 这个方法在子线程调用会导致crash
原因在于
```
if (this.popupInfo.isRequestFocus) {
                    KeyboardUtils.hideSoftInput(activity.getWindow());
                }
```
这里隐藏键盘会触发android.view.ViewRootImpl.checkThread
建议在show方法加上线程判断

**Comment by li-xiaojun** [comment]
@yygutn 线程的问题，需要调用方runOnUIThread一下；
