### ISSUE TITLE
筛选弹窗，导致手机状态栏字体被设置白色了

### ISSUE THREAD

**Issue by gwl026596** [li-xiaojun/XPopup#815]
**XPopup版本**
如2.5.15

**手机系统和型号**
华为荣耀Android 10

**描述你的问题**
最好能上代码截图和问题截图

**Comment by zhufeixiang** [comment]
同样问题
XPopup版本
如2.5.15

手机系统和型号
一加6T  Android 10

**Comment by li-xiaojun** [comment]
更新到2.5.16就行了

**Comment by xiaolong125** [comment]
最新的2.6.0又坏了

**Comment by 18363853135** [comment]
isLightStatusBar 可以用。

> @xiaolong125 XPopup不会自动设置状态栏，如果是白色，说明你的theme下，dialog的默认状态栏就是白色的。 你可以手动设置isLightStatusBar()。 如果不想手动设置，可以使用isViewMode(true)，这样就是View模式了，状态栏就不会变了。

isLightStatusBar可以解决 感谢
