### ISSUE TITLE
自定义BubbleAttachPopupView中，希望增加修改箭头圆角的属性

### ISSUE THREAD

**Issue by GuangNian10000** [li-xiaojun/XPopup#817]
**XPopup版本**
2.5.15

**手机系统和型号**
华为荣耀 20 Android 10

**描述你的问题**
希望增加修改箭头圆角的属性，或者箭头不要圆角
![image](https://user-images.githubusercontent.com/44353535/133401289-0e336533-e261-4a78-8218-2467156a9a60.png)

**Comment by li-xiaojun** [comment]
@GuangNian10000 更新到2.5.16，可以修改箭头圆角了

**Comment by GuangNian10000** [comment]
> @GuangNian10000 更新到2.5.16，可以修改箭头圆角了

感谢回复。
谢谢大佬
