### ISSUE TITLE
覆盖导航栏

### ISSUE THREAD

**Issue by jpc1028** [li-xiaojun/XPopup#82]
![image](https://user-images.githubusercontent.com/18493358/54741853-a560c300-4bfa-11e9-8f53-62393f5b5945.png)
能不能将这段代码注释了再上传一下，导航栏隐藏的时候，阴影部分会出现空白。

**Comment by li-xiaojun** [comment]
这是机型适配的问题，附上你的机型。

**Comment by jpc1028** [comment]
华为荣耀8

**Comment by li-xiaojun** [comment]
Bug效果贴下。

**Comment by jpc1028** [comment]
![369D04F3@4C8F6557 F6C3915C jpg_recompress](https://user-images.githubusercontent.com/18493358/54987795-2e5b6e00-4ff0-11e9-9a36-f722a930c5a6.jpg)
![D86A2B35@97740C65 F6C3915C jpg_recompress](https://user-images.githubusercontent.com/18493358/54987803-30bdc800-4ff0-11e9-9798-cffc669c8550.jpg)

**Comment by li-xiaojun** [comment]
@jpc1028 
我找到了华为荣耀8，试了试没有发现这个问题。
