### ISSUE TITLE
横屏后，左侧有空白

### ISSUE THREAD

**Issue by Lv-zhaoyang** [li-xiaojun/XPopup#820]
**XPopup版本**
2.5.15

**手机系统和型号**
小米K20Pro  MIUI 12.5.5

**描述你的问题**
![d8935cd771a0258201b97b3a7a872b3](https://user-images.githubusercontent.com/30335624/133892636-9cb644a7-58a2-4628-80ec-956a3b2f69f6.jpg)

兼容横屏模式下刘海屏  方案 有问题
![image](https://user-images.githubusercontent.com/30335624/133893208-4f7f9461-d793-46d9-81c8-5a941006ccb8.png)

**Comment by li-xiaojun** [comment]
@Lv-zhaoyang 更新到2.5.17试试
