### ISSUE TITLE
Attach弹窗与键盘无法同时显示

### ISSUE THREAD

**Issue by Iduace** [li-xiaojun/XPopup#822]
作为im场景长按聊天的弹窗一般都能和键盘同时显示，

试了下在dialog创建时设置dialog.getWindow().addFlags(FLAG_ALT_FOCUSABLE_IM);
同时删掉隐藏键盘相关方法后的BubbleAttach效果差不多(除了BubbleAttach其他和键盘同时显示会错位)，能否加上相关优化自定义选择BubbleAttach是否默认隐藏键盘之类的

**Comment by Iduace** [comment]
，主要应该就是键盘的自动显示隐藏，如果在显示隐藏方法里加个参数控制一下，然后自己选时机做和键盘的交互，除了这个外像输入面板和表情面板的切换应该也容易很多

**Comment by li-xiaojun** [comment]
看文档没，如果不想关闭输入法，设置 isRequestFocus(false)
