### ISSUE TITLE
横屏模式下底部弹出框，左边会出现一些间隔。

### ISSUE THREAD

**Issue by Rethen** [li-xiaojun/XPopup#823]
**XPopup版本**
2.5.15和2.5.16均有这个问题，2.5.1版本没有这个问题（中间版本没去尝试）

**手机系统和型号**
一加7Pro Android 10

**问题**
![$Y@W9VDO 2L%B1%J_@XNOIN](https://user-images.githubusercontent.com/7802673/134479900-cf86af25-e343-4b88-96d1-dfe427e8ef1d.jpg)

横屏模式下底部弹出框，左边会出现一些间隔。

**Comment by li-xiaojun** [comment]
@Rethen 更新到2.5.17试试

**Comment by Rethen** [comment]
> @Rethen 更新到2.5.17试试

好的，2.5.17没问题了，感谢
