### ISSUE TITLE
AttachPopupView在安卓11上位置不对

### ISSUE THREAD

**Issue by lc707776289** [li-xiaojun/XPopup#824]
AttachPopupView设置背景以后会自动出现阴影 和PartShadowPopupView设置背景后没有阴影（全机型）

![PTK0)_OE}5GTQN9H TC}TF](https://user-images.githubusercontent.com/57208233/134491977-916f8a6f-8684-4131-a8b5-19d8dc7f72b1.png)
![WYYLM0$RRERAQ(XN`~JW_90](https://user-images.githubusercontent.com/57208233/134492074-f6779c3d-aed5-44a2-8ba4-8dcf47aafdda.png)

AttachPopupView设置弹窗的位置在安卓11，小米10pro上会向右偏移一段距离，在安卓7、8、鸿蒙os上均正常
![1214GGMXX{ETJ1AHPHNKF`P](https://user-images.githubusercontent.com/57208233/134491898-4c515eab-9bd7-44fc-9ce7-2b8a6c22b47a.jpg)

**Comment by li-xiaojun** [comment]
@lc707776289 我用小米10 Pro无法复现，你试试demo在你手机上会偏移不

**Comment by li-xiaojun** [comment]
@lc707776289 更新到2.5.17试试
