### ISSUE TITLE
vivo5.0.2系统上屏蔽返回键隐藏弹框

### ISSUE THREAD

**Issue by shenhuniurou** [li-xiaojun/XPopup#828]
**XPopup版本**
2.5.18

**手机系统和型号**
Vivo X5M Android 5.0.2

**描述你的问题**
有个弹框需要点击返回键时也不隐藏，然后我设置了dismissOnBackPressed为false，无效，然后设置了callback，也无效，重写了onKeyDown和onBackPress方法都监听不到弹窗显示时点击返回键那个事件，当弹窗dismiss后又能监听到
```
new XPopup.Builder(mContext)
                    .dismissOnTouchOutside(false)
                    .dismissOnBackPressed(false)
                    .autoDismiss(false)
                    .setPopupCallback(new SimpleCallback())
                    .asCustom(alertPopup)
                    .show();
```

**Comment by li-xiaojun** [comment]
@shenhuniurou 其他手机上可以吗，还是只有这个手机不行？

**Comment by shenhuniurou** [comment]
> XPopup版本 2.6.0
> 
> 手机系统和型号 Android7.1.1 同样碰到这个问题,使用.isViewMode(true)暂时解决

设置isViewMode(true)确实可以了，然后我又发现这台机上autoFocusEditText无效

**Comment by li-xiaojun** [comment]
@liweihua802 你的手机型号是啥
