### ISSUE TITLE
非androidX版本xpopu底部空白问题

### ISSUE THREAD

**Issue by MinchinWang** [li-xiaojun/XPopup#830]
**XPopup版本**
如2.1.0

**手机系统和型号**
小米 10

**描述你的问题**
最好能上代码截图和问题截图
![微信图片_20211009170732](https://user-images.githubusercontent.com/3407244/136726312-71a6963d-4a64-4f4a-88a0-1aef1021ba25.jpg)

**Comment by ilkeew** [comment]
我也遇到了同样的问题，同设备我更新的jar的版本，看上去就OK
