### ISSUE TITLE
Duplicate class com.davemorrissey.labs.subscaleview.BuildConfig found in modules jetified-subsampling-scale-image-view-3.10.0-runtime.jar (com.davemorrissey.labs:subsampling-scale-image-view:3.10.0) and subsampling-scale-image-view-androidx-3.10.0-runtime.jar (com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0)

### ISSUE THREAD

**Issue by liutengsay1221** [li-xiaojun/XPopup#834]
**XPopup版本**
如6.1.0

**手机系统和型号**
华为Mate20 Android 10

**描述你的问题**
Duplicate class com.davemorrissey.labs.subscaleview.BuildConfig found in modules jetified-subsampling-scale-image-view-3.10.0-runtime.jar (com.davemorrissey.labs:subsampling-scale-image-view:3.10.0) and subsampling-scale-image-view-androidx-3.10.0-runtime.jar (com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0)

**Comment by li-xiaojun** [comment]
XPopup内部依赖了subsampling-scale-image-view，你自己就不应依赖了。如果是其他三方库也引用了，做个exclude即可

**Comment by zcyyouminghuo** [comment]
能具体一下吗，好像我两个3方库都冲突了报错了
subsampling-scale-image-view

**Comment by Ye83** [comment]
怎么exclude 呢

**Comment by Arvin-Li** [comment]
like this:
 implementation ('com.github.SherlockGougou:BigImageViewPager:androidx-6.0.2'){
        exclude group: 'com.davemorrissey.labs'
    }

**Comment by XD-Z** [comment]
> like this: implementation ('com.github.SherlockGougou:BigImageViewPager:androidx-6.0.2'){ exclude group: 'com.davemorrissey.labs' }

你的方法成功的解决了我的问题，感谢
