### ISSUE TITLE
关于DrawerPopupView 可以手势开启吗?

### ISSUE THREAD

**Issue by shenqiwen** [li-xiaojun/XPopup#84]

**Comment by cervy** [comment]
同问

**Comment by li-xiaojun** [comment]
drawer弹窗默认就带左右拖拽手势啊，而且不能关闭

**Comment by shenqiwen** [comment]
你的Demo里的自定义抽屉 左滑出不来啊 @li-xiaojun

**Comment by li-xiaojun** [comment]
@shenqiwen 
Drawer弹窗不能通过手势左滑，只能打开之后才能使用手势。

**Comment by shenqiwen** [comment]
可以考虑加上手势开启这个功能吗 @li-xiaojun

**Comment by li-xiaojun** [comment]
@shenqiwen 
弹窗是临时性的界面，在某种需求下显示，操作完毕就关闭。要实现那个功能，需要让弹窗始终作为当前界面的布局，在未显示的时候就能处理手势了。虽然能实现，但是对当前界面侵入大，也不适合用弹窗来做。

如果你有这种需求，请使用DrawerLayout。

**Comment by shenqiwen** [comment]
因为使用了官方DrawerLayout 组件后系统状态栏 和drawerlayout布局很难做到沉浸式,如下图这样,抽屉布局覆盖到状态栏,
![1553595238787](https://user-images.githubusercontent.com/31466883/54989306-32d55600-4ff3-11e9-8e27-61d55ddc2975.jpg)

**Comment by shenqiwen** [comment]
如果是使用自定义View 可以避免android高低版本和国内各厂商的rom系统的适配问题

**Comment by li-xiaojun** [comment]
@shenqiwen 
图中的DrawerLayout并没有覆盖状态栏啊，仍然在状态栏之下；如果覆盖了状态栏，那个WIFI图标你肯定看不到。

**Comment by shenqiwen** [comment]
额,可能我表述的不清楚,现在用您的库是实现了这样的效果,用DrawerLayout很难实现的,就剩一个手势开启了 @li-xiaojun

**Comment by li-xiaojun** [comment]
@shenqiwen 
加我QQ：16167479

**Comment by li-xiaojun** [comment]
@shenqiwen 
@cervy 
这个问题推荐用DrawerLayout实现，不适合用弹窗，Issue即将关闭。
