### ISSUE TITLE
什么时候会加入对viewBinding的支持呢？

### ISSUE THREAD

**Issue by monotcoder** [li-xiaojun/XPopup#845]
**XPopup版本**
如2.1.0

**手机系统和型号**
华为Mate20 Android 10

**描述你的问题**
最好能上代码截图和问题截图

**Comment by zcyyouminghuo** [comment]
wiki上只有Databinding貌似没有viewBinding

**Comment by li-xiaojun** [comment]
> wiki上只有Databinding貌似没有viewBinding

增加了描述
