### ISSUE TITLE
dismissOnBackPressed(false)无效问题

### ISSUE THREAD

**Issue by kanshenmekan** [li-xiaojun/XPopup#847]
**XPopup版本**
2.5.14及之后的版本，2..5.13版本都是正常的

**手机系统和型号**
android8.1会出现这个问题，android11就正常 

**描述你的问题**
如题，设置dismissOnBackPressed(false)，点击返回键弹窗还是会消失

**Comment by lmJojo** [comment]
同出现，android 7.1 出现此问题，android 10 正常

**Comment by li-xiaojun** [comment]
@kanshenmekan @lmJojo 更新到2.6.7即可

**Comment by JiangShuLiang** [comment]
> android

更新到最新版的2.8.14了，在android7上还是问题依旧：dismissOnBackPressed(false)无效
