### ISSUE TITLE
BottomPopupView有时候调用代码无法打开或者关闭

### ISSUE THREAD

**Issue by MissBin** [li-xiaojun/XPopup#849]
**XPopup版本**
如2.6.6

**手机系统和型号**
版本Android10 系统是定制的系统
![image](https://user-images.githubusercontent.com/19357839/140293781-ecbb05be-1173-49b9-af6d-8867ce78ab59.png)
![image](https://user-images.githubusercontent.com/19357839/140293810-aee3ea71-52c9-4306-bcee-795ceec4694b.png)
![image](https://user-images.githubusercontent.com/19357839/140293882-731c7d2d-725c-4c9b-b280-3e2bff6f2cac.png)
![image](https://user-images.githubusercontent.com/19357839/140293912-74da5e4e-3296-4754-9e29-1f0bb7d81f92.png)
这是所有关联代码      还有一个疑问为啥popupStatus状态等于Dismissing  调用show方法也是返回自身呢

**Comment by li-xiaojun** [comment]
可以打印一些日志看看是否代码执行了，但是弹窗没有显示
