### ISSUE TITLE
XPopup弹窗和系统dialog弹窗

### ISSUE THREAD

**Issue by pangyu646182805** [li-xiaojun/XPopup#851]
**XPopup版本**
2.6.6

**手机系统和型号**
华为Mate20 Android 11

**描述你的问题**
首先弹出XPopup弹窗 然后弹出项目里存在的dialog弹窗 这时候点返回两个弹窗一起dismiss了

**Comment by li-xiaojun** [comment]
@pangyu646182805 XPopup管不了系统的dialog，建议都用XPopup实现
