### ISSUE TITLE
加载大图内存溢出： java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by kokod21** [li-xiaojun/XPopup#853]
**XPopup版本**
2.6.2

**手机系统和型号**
Android 7.1.2,level 25
ROM
google/android_x86（应该是模拟器）

**描述你的问题**
加载大图内存溢出，不过这个bug只出现过一次
java.lang.OutOfMemoryError
Failed to allocate a 2742348 byte allocation with 1158680 free bytes and 1131KB until OOM

使用代码如下：
XPopup.Builder(context)
            .asImageViewer(
                view,
                position,
                data.toList(),
                { p, _ -> p.updateSrcView(view) },
                SmartGlideImageLoader()
            )
            .isShowSaveButton(false)
            .show()

bugly报错日志如下：
com.bumptech.glide.load.engine.CallbackException:Unexpected exception thrown by non-Glide code
2
com.bumptech.glide.load.engine.EngineJob.callCallbackOnResourceReady(EngineJob.java:161)
3
......
4
Caused by:
5
java.lang.OutOfMemoryError:Failed to allocate a 2742348 byte allocation with 1158680 free bytes and 1131KB until OOM
6
dalvik.system.VMRuntime.newNonMovableArray(Native Method)
7
android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
8
android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:646)
9
android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:622)
10
android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:402)
11
com.lxj.xpopup.util.XPopupUtils.getBitmap(XPopupUtils.java:622)
12
com.lxj.xpopup.util.SmartGlideImageLoader$1.onResourceReady(SmartGlideImageLoader.java:93)
13
com.lxj.xpopup.util.SmartGlideImageLoader$1.onResourceReady(SmartGlideImageLoader.java:66)
14
com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:639)
15
com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:578)
16
com.bumptech.glide.load.engine.EngineJob.callCallbackOnResourceReady(EngineJob.java:159)
17
com.bumptech.glide.load.engine.EngineJob$CallResourceReady.run(EngineJob.java:428)
18
android.os.Handler.handleCallback(Handler.java:751)
19
android.os.Handler.dispatchMessage(Handler.java:95)
20
android.os.Looper.loop(Looper.java:154)
21
android.app.ActivityThread.main(ActivityThread.java:6161)
22
java.lang.reflect.Method.invoke(Native Method)
23
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
24
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)

**Comment by li-xiaojun** [comment]
@kokod21 如果你的图片存在大图，可使用SmartGlideImageLoader(true)；看文档说明
