### ISSUE TITLE
虚拟按键出现/消失(乱蹦)

### ISSUE THREAD

**Issue by shy1118** [li-xiaojun/XPopup#856]
**XPopup版本**
如2.5.3

**手机系统和型号**
HUAWEU Mate10 Pro Android 10、原生Android10、原生Android9

**描述你的问题**
使用该弹窗时，如果有虚拟按键有一直弹出隐藏弹出隐藏(如：loading)、设置隐藏虚拟按键或者显示虚拟按键的话，没有虚拟按键的页面会出来，有虚拟按键的会隐藏。

**Comment by li-xiaojun** [comment]
更新到最新版本
