### ISSUE TITLE
底部弹窗设置enableDrag(false)的问题

### ISSUE THREAD

**Issue by jiqianwen** [li-xiaojun/XPopup#858]
**XPopup版本**
2.6.2  2.6.7

**手机系统和型号**
vivo Y70t Android 10

**描述你的问题**
2.6.2设置enableDrag(false)时，黑色遮罩先消失，底部弹窗会延迟一秒左右无动画直接消失
2.6.7版本是弹窗总是先闪一下消失，然后正常弹出

XPopup.Builder(this)
                .enableDrag(false)
                .navigationBarColor(ColorUtils.getColor(R.color.black))
                .asCustom(mExportSetUpXPopup)
                .show()

布局高度设置的是固定值

**Comment by LG12300** [comment]
我也遇到和你一样的问题

**Comment by li-xiaojun** [comment]
@jiqianwen 试试demo在你手机上有问题吗

**Comment by jiqianwen** [comment]
> @jiqianwen 试试demo在你手机上有问题吗

试了下   自定义的xpopup如果是全局的就会出现这种问题

**Comment by li-xiaojun** [comment]
@jiqianwen 更新到2.7.0即可
