### ISSUE TITLE
自定义BottomEditTextPopWindow，弹出键盘时，会把activity的布局顶上去一点

### ISSUE THREAD

**Issue by prookiee** [li-xiaojun/XPopup#86]

**Comment by prookiee** [comment]
val commentPop = BottomCommentPopup(this, popHeight)
        XPopup.get(this).asCustom(commentPop).hasShadowBg(false)
                .moveUpToKeyboard(false)
                .setPopupCallback(object : XPopupCallback {
            override fun onDismiss() {
                slideDownAnimal(videoView)
            }

            override fun onShow() {
                //To change body of created functions use File | Settings | File Templates.
            }
        }).show()

**Comment by prookiee** [comment]
就是copy仿知乎那个popWindow的代码，而且下拉里面的recyclerView没有drag效果

**Comment by li-xiaojun** [comment]
你运行下我的demo看是否有问题，如果demo都不行那就是我的代码有问题，如果demo没有问题，那就是你用法有问题。和demo比对下看看哪里不一样
