### ISSUE TITLE
设置 Attach弹窗 设置气泡背景色不一致

### ISSUE THREAD

**Issue by ehuiz** [li-xiaojun/XPopup#860]
**XPopup版本**
2.5.10

**手机系统和型号**
模拟器

**描述你的问题**
![image](https://user-images.githubusercontent.com/40593897/142170466-5038c973-9de9-436c-8d5f-dccfb858b15b.png)

**Comment by li-xiaojun** [comment]
@ehuiz 更新到最新版试试

**Comment by ehuiz** [comment]
不可以 一样的。 试的2.6.8

**Comment by li-xiaojun** [comment]
setBubbleBgColor()是传个color值，不是资源id，
