### ISSUE TITLE
asBottomList是否有方法设置“取消上面的那个分割线颜色”，若没有，能否下一版本更新呢（2.6.7）

### ISSUE THREAD

**Issue by androidHRTZ** [li-xiaojun/XPopup#861]
**XPopup版本**
如2.1.0

**手机系统和型号**
华为Mate20 Android 10

**描述你的问题**
最好能上代码截图和问题截图

**Comment by li-xiaojun** [comment]
@androidHRTZ  内置弹窗不增加特性了，如果要特殊逻辑，请自定义弹窗

**Comment by androidHRTZ** [comment]
谢谢您



发自我的iPhone


------------------ 原始邮件 ------------------
From: Jun ***@***.***&gt;
发送时间: 11/22/2021, 17:05
To: li-xiaojun/XPopup ***@***.***&gt;
抄送: androidHRTZ ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [li-xiaojun/XPopup] asBottomList是否有方法设置“取消上面的那个分割线颜色”，若没有，能否下一版本更新呢（2.6.7） (Issue #861)
