### ISSUE TITLE
查看大图内存溢出

### ISSUE THREAD

**Issue by XuHX** [li-xiaojun/XPopup#864]
**XPopup版本**
如2.1.0

**手机系统和型号**
华为Mate20 Android 10

**描述你的问题**
最好能上代码截图和问题截图
![1637737000(1)](https://user-images.githubusercontent.com/25903912/143189850-cb0657cd-0406-495e-908c-5f66a7478767.png)

**Comment by kokod21** [comment]
#853  用这个应该就行了
