### ISSUE TITLE
横竖屏切换时，位置会有段偏

### ISSUE THREAD

**Issue by zhou7126** [li-xiaojun/XPopup#865]
**XPopup版本**
2.6.7

**手机系统和型号**
realme GT   Android 11

**描述你的问题**
用github上最新的代码，修改了部分manifest：
    <application
        android:name=".XPopupApp"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme"
        android:usesCleartextTraffic="true">
        <meta-data
            android:name="android.max_aspect"
            android:value="2.4" />
        <meta-data
            android:name="android.notch_support"
            android:value="true" />

        <activity
            android:name="com.lxj.xpopupdemo.MainActivity"
            android:configChanges="keyboardHidden|orientation|screenSize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity
            android:name="com.lxj.xpopupdemo.DemoActivity"
            android:configChanges="keyboardHidden|orientation|screenSize" />

    </application>
效果截图：
![Screenshot_2021-11-25-17-39-35-23_477d484d467663db5954da3580389726](https://user-images.githubusercontent.com/41935398/143418513-5c967e8c-340b-4104-af10-ed86d8c3c302.jpg)
![Screenshot_2021-11-25-17-40-53-44_477d484d467663db5954da3580389726](https://user-images.githubusercontent.com/41935398/143418542-8dc3be75-7f0d-445c-a1f2-73a0edcbd12e.jpg)
![Screenshot_2021-11-25-17-41-29-46_477d484d467663db5954da3580389726](https://user-images.githubusercontent.com/41935398/143418554-c33611a5-775f-4181-b547-43467cdf1d6b.jpg)

![Screenshot_2021-11-25-17-19-52-72_477d484d467663db5954da3580389726](https://user-images.githubusercontent.com/41935398/143418563-4b9b6978-71b3-4a3a-b8a7-c92e4d6afe1d.jpg)

**Comment by zhou7126** [comment]
增加 .isViewMode(true) 保持一个方向弹出时就不偏了，但是在切换横、竖屏时，还是一样。

**Comment by crazyzjw** [comment]
横屏,底部会无法占满宽度...

**Comment by zjxuzhj** [comment]
> 增加 .isViewMode(true) 保持一个方向弹出时就不偏了，但是在切换横、竖屏时，还是一样。

就你说的对。我竟然没有悟到

**Comment by li-xiaojun** [comment]
@crazyzjw @zjxuzhj @zhou7126 更新到2.8.18 即可

**Comment by wangzhankai** [comment]
> @crazyzjw @zjxuzhj @zhou7126 更新到2.8.18 即可

我的也出现了竖屏切换到横屏，底部弹窗不会充满问题，但是我还不能升级到2.8.18或者2.9，最新版本会出现桌面小组件弹窗的时候桌面背景消失（可以看到桌面图标，就是没有背景，部分机型（华为居多））

**Comment by wangzhankai** [comment]
> @li-xiaojun 我的也出现了竖屏切换到横屏，底部弹窗不会充满问题，但是我还不能升级到2.8.18或者2.9，最新版本会出现桌面小组件弹窗的时候桌面背景消失（可以看到桌面图标，就是没有背景，部分机型（华为居多））
