### ISSUE TITLE
如何直接使用fragment

### ISSUE THREAD

**Issue by Alex861** [li-xiaojun/XPopup#866]
请问一下可以直接使用fragment吗？我看到demo里是通过viewPage使用的；本来想使用dialogFragment,但是发现dialogFragment各种不方便，用习惯了你这个弹框项目了

**Comment by Alex861** [comment]
我试着在xpopup的onCreate方法动态加入fragment,不知道这样写有没有什么不妥呢

**Comment by startong** [comment]
更新到最新版，有一个属性应该可以实现你的需求，我没试过，你可以试下
<img width="593" alt="企业微信截图_20211126165810" src="https://user-images.githubusercontent.com/27007471/143554417-866f2ecd-c2da-4baf-95e4-b2407681719e.png">

**Comment by li-xiaojun** [comment]
@Alex861 设置isViewMode(true)

**Comment by woshiluoyong** [comment]
> > 我试着在xpopup的onCreate方法动态加入fragment,不知道这样写有没有什么不妥呢
> 
> 这样不显示，有碰到嘛老哥
> 
> ```
> /**
>  * 房间消息弹窗 加载首页的第三个tab的内容
>  */
> @SuppressLint("ViewConstructor")
> class RoomMsgDialog(val activity: AppCompatActivity) : BottomPopupView(activity) {
> 
> 
>     override fun getPopupHeight(): Int {
>         return dp2px(495)
>     }
> 
>     // 返回自定义弹窗的布局
>     override fun getImplLayoutId(): Int {
>         return R.layout.dialog_room_msg
>     }
> 
>     override fun onCreate() {
>         super.onCreate()
>         activity.supportFragmentManager.beginTransaction()
>             .replace(R.id.fragment_container_view, MessageFragment())
>     }
> }
> ```
> 
> ```
> XPopup.Builder(appContext)
>                 .isDestroyOnDismiss(true)
>                 .dismissOnBackPressed(true)
>                 .dismissOnTouchOutside(true)
>                 .popupAnimation(PopupAnimation.TranslateAlphaFromBottom)
>                 .autoDismiss(true)
>                 .hasStatusBar(true)
>                 .statusBarBgColor(Color.TRANSPARENT)
>                 .navigationBarColor(Color.BLACK)
>                 .customHostLifecycle(lifecycle)
>                 .enableDrag(false)
>                 .hasShadowBg(false)
>                 .isViewMode(true)
>                 .asCustom(RoomMsgDialog(this@VoiceChatRoomActivity)).show()`
> ```
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
>     android:layout_width="match_parent"
>     android:background="@drawable/bg_item_room_bottom_seat_manager"
>     android:layout_height="match_parent">
> 
>     <androidx.fragment.app.FragmentContainerView
>         android:id="@+id/fragment_container_view"
>         android:layout_width="match_parent"
>         android:layout_height="match_parent" />
> </RelativeLayout>
> ```
> 
> <img alt="截屏2022-03-02 下午4 41 00" width="635" src="https://user-images.githubusercontent.com/24636051/156326070-6b3825c7-9e61-4d32-b932-70f7e8cd593b.png">

你上面的代码activity.supportFragmentManager.beginTransaction()
            .replace(R.id.fragment_container_view, MessageFragment())缺一句提交commitAllowingStateLoss(),要不然不会显示

**Comment by woshiluoyong** [comment]
感谢老哥的实例代码,要显示fragment核心总结:
1.显示
`
XPopup.Builder(context).isViewMode(true).asCustom(CommWebBottomPopup(fragmentActivity, "https://www.2345.com/?k726386446")).show()
`

2.代码
`
class CommWebBottomPopup(private val activity: FragmentActivity, private val loadWebUrl: String) : BottomPopupView(activity) {

    override fun getImplLayoutId(): Int = R.layout.view_common_web

    @SuppressLint("CommitTransaction")
    override fun onCreate() {
        super.onCreate()

        findViewById<View>(R.id.closeImgV).singleClick {
            dismiss()
        }

        activity.supportFragmentManager.beginTransaction().replace(R.id.contentFy, WebFragment().setUrl(loadWebUrl)).commitAllowingStateLoss()
    }

    override fun getInternalFragmentNames(): List<String> = arrayListOf(WebFragment::class.java.simpleName)
}
`

3.布局
`
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    app:radiusTopLeft="18dp"
    app:radiusTopRight="18dp"
    app:colorFill="#FF1E252B">

    <TextView
        android:id="@+id/hintTitleT"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginTop="20dp"
        android:layout_centerHorizontal="true"
        android:text="@string/title_dialog_vip_expired"
        android:textColor="@color/white"
        android:textSize="18sp"/>

    <ImageView
        android:id="@+id/closeImgV"
        android:layout_width="20dp"
        android:layout_height="20dp"
        android:layout_marginTop="10dp"
        android:layout_marginEnd="10dp"
        android:layout_alignParentEnd="true"
        android:src="@drawable/icon_dialog_close"/>

    <FrameLayout
        android:id="@+id/contentFy"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginTop="35dp"
        android:layout_below="@id/hintTitleT"/>
</RelativeLayout>
`
