### ISSUE TITLE
keyboardTagView造成页面异常

### ISSUE THREAD

**Issue by Vicent9920** [li-xiaojun/XPopup#868]
**XPopup版本**
2.5.15
**手机系统和型号**
三星Galaxy S9+ Android 10

**描述你的问题**
打开页面多次后，keyboardTagView会唤醒输入法，导致页面在无输入法的情况下，RecycleView的item宽度为0.
录屏文件放在阿里云盘了：https://www.aliyundrive.com/s/cYXhQNKrs44

**Comment by Vicent9920** [comment]
```Kotlin
mBinding.recyclerView.viewTreeObserver.addOnGlobalFocusChangeListener { oldFocus, newFocus ->
            oldFocus?.let { EasyLog.DEFAULT.e("CombinationActivity  oldFocus",oldFocus.tag?:"empty") }
            newFocus?.let { EasyLog.DEFAULT.e("CombinationActivity newFocus",newFocus.tag?:"empty") }

        }
```
日志：
CombinationActivity  oldFocus keyboardTagView
CombinationActivity newFocus keyboardTagView

**Comment by li-xiaojun** [comment]
用最新版试试
