### ISSUE TITLE
更新至2.6.8问题

### ISSUE THREAD

**Issue by zhuangjiahua** [li-xiaojun/XPopup#871]
**XPopup版本**
2.1.4 更新至 2.6.8 

**手机系统和型号**
华为荣耀V30 Android 10

**描述你的问题**
2.1.4版本FullScreenDialog有一个passClick方法，但2.6.8版本没有了，这个用什么代替？

**Comment by li-xiaojun** [comment]
事件传递由BasePopupView的passTouchThrought实现
