### ISSUE TITLE
dismissOnTouchOutside问题

### ISSUE THREAD

**Issue by kanshenmekan** [li-xiaojun/XPopup#874]
**XPopup版本**
如2.6.8

**手机系统和型号**
华为荣耀 Android 8.1

**描述你的问题**
dismissOnTouchOutside(false)的时候，按返回键关闭弹窗，没有动画，也不走onDismiss回调
，复用弹窗还会出现闪烁

**Comment by li-xiaojun** [comment]
@kanshenmekan 请运行下demo看看有没有问题，如果demo有问题，那基本确定是bug
