### ISSUE TITLE
java.lang.IllegalArgumentException  width and height must be > 0

### ISSUE THREAD

**Issue by po1xiao** [li-xiaojun/XPopup#875]
**XPopup版本**
2.5.18

**手机系统和型号**
vivo/FUNTOUCH Android 10

**描述你的问题**
java.lang.IllegalArgumentException width and height must be > 0
android.graphics.Bitmap.createBitmap(Bitmap.java:1139)
android.graphics.Bitmap.createBitmap(Bitmap.java:1106)
android.graphics.Bitmap.createBitmap(Bitmap.java:1056)
android.graphics.Bitmap.createBitmap(Bitmap.java:1017)
**com.lxj.xpopup.util.XPopupUtils.createBitmapDrawable(XPopupUtils.java:195)
com.lxj.xpopup.impl.InputConfirmPopupView$1.run(InputConfirmPopupView.java:52)**
android.os.Handler.handleCallback(Handler.java:883)
android.os.Handler.dispatchMessage(Handler.java:100)
android.os.Looper.loop(Looper.java:230)
android.app.ActivityThread.main(ActivityThread.java:7901)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

最新版本上我看这一段代码也没有加大于零判断。

**Comment by li-xiaojun** [comment]
@po1xiao 更新到2.7.0即可
