### ISSUE TITLE
2.6.8版本点击查看大图弹窗部分图片仍会旋转

### ISSUE THREAD

**Issue by androidjiajia** [li-xiaojun/XPopup#876]
**XPopup版本**
如2.6.8

**手机系统和型号**
小米、华为、一加都有该问题

**描述你的问题**
如这张图：http://test-yjk.oss-cn-chengdu.aliyuncs.com/APP/dynamic/picture/1637229940713.jpeg
在最新demo上也是旋转

**Comment by li-xiaojun** [comment]
@androidjiajia 更新到2.7.0即可
