### ISSUE TITLE
hasStatusBar方法描述有误且无效，如图，2.6.7版本

### ISSUE THREAD

**Issue by startong** [li-xiaojun/XPopup#878]
**XPopup版本**
2.6.7

**手机系统和型号**
华为nova6se Android 10 鸿蒙2.0

**描述你的问题**
1、hasStatusBar方法设置为false，在横屏的时候，打开继承自DrawerPopupView的弹框会显示出来状态栏，关闭弹框后状态栏消失

2、hasStatusBar方法设置为false，在横屏的时候，打开继承自CenterPopupView的弹框后状态栏会快速显示并快速消失回去

文档api的说明
注释是不是写错了
<img width="424" alt="企业微信截图_20211208163519" src="https://user-images.githubusercontent.com/27007471/145175854-602d117d-3627-4188-a975-53c8c4de9717.png">

我继承自DrawerPopupView的弹框
<img width="375" alt="企业微信截图_20211208163638" src="https://user-images.githubusercontent.com/27007471/145175958-873553d3-8e35-42c5-9494-5b394dee8570.png">
<img width="563" alt="企业微信截图_20211208163832" src="https://user-images.githubusercontent.com/27007471/145176035-df615d42-6552-49e2-ba62-3e27ca91373f.png">

**Comment by li-xiaojun** [comment]
你设置hasStatusBar(false)说明你的Activity应该也隐藏了状态栏，那么给弹窗设置isViewMode(true)即可，默认弹窗是dialog，和Activity不同window，所以在部分手机会有先显示再隐藏的闪烁效果。

**Comment by startong** [comment]
嗯嗯，isViewMode(true)确实是能解决问题的，但是为什么老版本（2.1.0）的hasStatusBar(false)是有效的，升级到2.6.7后就无效了呢
