### ISSUE TITLE
所有点击事件失效

### ISSUE THREAD

**Issue by iamGGboss** [li-xiaojun/XPopup#879]
**XPopup版本**
'com.github.li-xiaojun:XPopup:2.6.8'

**手机系统和型号**
华为荣耀v9

**描述你的问题**
经常出现弹窗口，感觉有透明图层盖住了界面，所有点击事件失效

      XPopup.Builder(context)
                                 .asCustom(bottomWebViewPopup.apply {
                                                    setData(data.name, data.url)
                                                })
                                                .show()

**Comment by iamGGboss** [comment]
我用三星手机测试也是一样。

**Comment by li-xiaojun** [comment]
你这个问题解决了吗，没有的话，截图发下你的布局和弹窗代码

**Comment by iamGGboss** [comment]
解决了，我是在doAfterDismiss里面做清空view数据的操作，但是应该是影响到动画的操作，导致遮罩层没有真正的移除，覆盖在了上面，我把doAfterDismiss里做得操作放到beforeDismiss里就好了
