### ISSUE TITLE
2.6.9和2.7.0无法弹出对话框

### ISSUE THREAD

**Issue by iamGGboss** [li-xiaojun/XPopup#880]
**XPopup版本**
如2.6.9 2.7.0

**手机系统和型号**
小米11 华为大部分手机 vIVO手机

**描述你的问题**
自定义弹窗无法弹出

**Comment by iamGGboss** [comment]
基本上所有手机都无法弹出

**Comment by li-xiaojun** [comment]
@iamGGboss 上代码啊，光说问题不上代码就是耍流氓

**Comment by iamGGboss** [comment]
private val mAgreePopUp by lazy {
        AgreePopup(this, object : AgreePopup.OnProtocolListener {

            override fun onAgree() {
                mViewModel.agreeProtocol()
            }

            override fun onReject() {
                finish()
            }
        })
    }


 XPopup.Builder(this)
            .dismissOnBackPressed(false)
            .dismissOnTouchOutside(false)
            .asCustom(mAgreePopUp)
            .show()

**Comment by po1xiao** [comment]
2.7.0上我也遇到了，回退到2.6.8就好了。
我是在启动后的第一个Activity（SplashActivity）的onCreate中创建了一个自定义dialog，据同事说，尝试延迟5秒就好了。
            new XPopup.Builder(this).dismissOnTouchOutside(false).dismissOnBackPressed(false)
                    .asCustom(new PrivacyDialog(this, new PrivacyDialog.OnChangeClickListener() {
                @Override
                public void onAgreementClick(@NotNull View v) {
                    PreferenceUtils.putBoolean(SplashActivity.this, Constants.PRIVACY_AGREE_STATUS, true);
                    initPermission();
                }

                @Override
                public void onDisagreeClick(@NotNull View v) {
                    finish();
                }
            })).show();

**Comment by AdminQQZ** [comment]
我也是遇到了

**Comment by ijustkeepmoving** [comment]
我也遇到了~~哎~~~

**Comment by li-xiaojun** [comment]
@ijustkeepmoving @AdminQQZ @iamGGboss @po1xiao 
已修复，更新到2.7.1

**Comment by AdminQQZ** [comment]
顶呱呱
