### ISSUE TITLE
建议代码修改

### ISSUE THREAD

**Issue by DuShuYuan** [li-xiaojun/XPopup#884]
addInnerContent方法
有的popup有，有的没有（PositionPopupView），有的protected有的final protected（FullScreenPopupView）
希望能统一一下，几个内置弹窗都加一下，用protected。

**Comment by li-xiaojun** [comment]
@DuShuYuan ok，下个版本修改

**Comment by li-xiaojun** [comment]
@DuShuYuan 更新到2.7.2即可
