### ISSUE TITLE
第一次打开内置有viewpager+fragment弹框，在当前pop里面再次触发弹出相同配置的pop内容不显示

### ISSUE THREAD

**Issue by daijunsheng** [li-xiaojun/XPopup#885]
**XPopup版本**
如2.5.8

**手机系统和型号**
oppo  reno

**描述你的问题**
第一次打开内置有viewpager+fragment弹框，在当前pop里面再次触发弹出相同配置的pop内容不显示，第一个pop已经关闭

**Comment by li-xiaojun** [comment]
更新到最新版本试试

**Comment by devzwy** [comment]
> 更新到最新版本试试

一样，只是显示了一次，第二次就不显示了。设置了isDestroy为true

**Comment by zdxiang** [comment]
我也遇到同样的问题。Activity+Framgent中，在fragment执行显示，第二次不显示，多次点击后又显示。接着又不显示。偶尔点击一次又显示。设置了isDestroy为true

**Comment by zdxiang** [comment]
> 我也遇到同样的问题。Activity+Framgent中，在fragment执行显示，第二次不显示，多次点击后又显示。接着又不显示。偶尔点击一次又显示。设置了isDestroy为true

我的问题已解决。经过实践，单独在Activity中显示也会出现这种情况，发现是由于使用了ViewBinding导致的，具体原因未往下探究。

**Comment by li-xiaojun** [comment]
@daijunsheng @devzwy isDestroy为false试试
