### ISSUE TITLE
部分vivo机型  吸附弹窗  位置会偏移一个状态栏的高度。

### ISSUE THREAD

**Issue by SinceJulyzzZ** [li-xiaojun/XPopup#887]
**XPopup版本**
如2.7.2

**手机系统和型号**
Vivo V1809A      Android 8

**描述你的问题**
吸附弹窗  位置会偏移一个状态栏的高度。
![573fa39b0fd4e7667b7cadb9a117dd4](https://user-images.githubusercontent.com/64911679/146858088-72de3ab0-254d-434c-9d3c-1f52f2190a86.jpg)

**Comment by SinceJulyzzZ** [comment]
使用最新2.7.2 依然如此。

**Comment by li-xiaojun** [comment]
@SinceJulyzzZ 可暂时使用isViewMode(true)解决
