### ISSUE TITLE
V1809A机型一个偏移状态高度的问题

### ISSUE THREAD

**Issue by hailiangcock** [li-xiaojun/XPopup#889]
**XPopup版本**
如2.7.3

**手机系统和型号**
vivo Y83A Android 8

**描述你的问题**
BottomPopupView 在最新版本2.7.3有向下的偏移量
![Screenshot_20220104_175510](https://user-images.githubusercontent.com/19505039/148042060-0f39c346-ed79-4c77-b167-221974289282.jpg)

这个问题跟FullScreenDialog里边判断添加的偏移量应该是一样的

**Comment by li-xiaojun** [comment]
@hailiangcock 试试2.7.5呢

**Comment by li-xiaojun** [comment]
@hailiangcock 奇怪，我用这个机型测试是没有问题的

**Comment by li-xiaojun** [comment]
@hailiangcock 试试最新版本，应该好了
