### ISSUE TITLE
版本更新日志记录

### ISSUE THREAD

**Issue by qiushui95** [li-xiaojun/XPopup#89]
我是从1.3.x开始用的，今天又来看一下，发现到1.6了，但是中间经历了这么多版本，每个版本有啥变化，我一概不知道，不利于更新，也不知道加了啥新功能。谢谢

**Comment by li-xiaojun** [comment]
尽量看下release的内容。
![QQ图片20190327100301](https://user-images.githubusercontent.com/4426715/55045071-8be6cd80-5077-11e9-8811-9702ff141f2c.png)

**Comment by qiushui95** [comment]
> 尽量看下release的内容。
> ![QQ图片20190327100301](https://user-images.githubusercontent.com/4426715/55045071-8be6cd80-5077-11e9-8811-9702ff141f2c.png)

不好意思  没看到
