### ISSUE TITLE
ClassCastException: android.view.ContextThemeWrapper cannot be cast to android.app.Activity

### ISSUE THREAD

**Issue by wyh123965** [li-xiaojun/XPopup#890]
**XPopup版本**
2.2.22

在AppCompatDialogFragment中使用FullScreenPopupView时，报错ClassCastException: android.view.ContextThemeWrapper cannot be cast to android.app.Activity

这里contentView的context是ContextThemeWrapper，所以是否能改为contentView.getContext().getBaseContext()

![image](https://user-images.githubusercontent.com/76555651/148172794-dbfa7f94-1c01-413f-9b3a-c9c83bd19ec3.png)
![image](https://user-images.githubusercontent.com/76555651/148173096-fbd568b6-05e1-4098-a1a5-191b4363698b.png)

**Comment by chenmingyin** [comment]
好家伙，我也碰到了

**Comment by li-xiaojun** [comment]
@chenmingyin @wyh123965 用最新版试试
