### ISSUE TITLE
BubbleAttachPopupView位置错误，recycleview 嵌套中对同一的itemview进行点击事件和长按事件的监听，弹出Popup显示位置不一致

### ISSUE THREAD

**Issue by nxnyk** [li-xiaojun/XPopup#891]
**XPopup版本**
如2.7.3

长按事件的PopupView显示位置正确，点击事件的PopupView显示的位置始终不对，存在较大的偏移，有的直接显示在左上角

**Comment by li-xiaojun** [comment]
@nxnyk 上报issue得说机型啊，不然没法改

**Comment by nxnyk** [comment]
> @nxnyk 上报issue得说机型啊，不然没法改

不好意思，忘写了，小米10s 安卓版本11

**Comment by li-xiaojun** [comment]
@nxnyk 更新到最新版本试试
