### ISSUE TITLE
Attach弹窗打开的情况下，点击弹窗外的EditText，无法自动打开软键盘

### ISSUE THREAD

**Issue by SinceJulyzzZ** [li-xiaojun/XPopup#892]
**XPopup版本**
如2.7.2

**手机系统和型号**
一加8T Android 10

**描述你的问题**
在Attach弹窗打开的情况下，点击弹窗外的edittext，无法自动打开软键盘，会有光标。

![image](https://user-images.githubusercontent.com/64911679/148344229-bba0e833-c9c0-416b-84ec-aea08d93906a.png)

**Comment by li-xiaojun** [comment]
isReuestFocus(false)
