### ISSUE TITLE
高度恢复bug

### ISSUE THREAD

**Issue by chengfan2017** [li-xiaojun/XPopup#895]
BottomPopupView 内部布局点击显示隐藏之后(无手动拖动)，会有一定情况被定在中间，需要手动调用doShowAnimation()到顶

**Comment by li-xiaojun** [comment]
用最新版试试

**Comment by chengfan2017** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by chengfan2017** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
