### ISSUE TITLE
Why can't I pull down the library?

### ISSUE THREAD

**Issue by zhangshuliang** [li-xiaojun/XPopup#896]
![image](https://user-images.githubusercontent.com/16489590/149689981-f3589747-3f19-4e71-b529-2d1a9fbbd2a2.png)

**Comment by zhangshuliang** [comment]
![image](https://user-images.githubusercontent.com/16489590/149690470-57e198a8-b5f3-4749-bf82-4eccb9f40de1.png)

**Comment by li-xiaojun** [comment]
网络问题
