### ISSUE TITLE
用华为pad进行图片浏览,图片会自动放大

### ISSUE THREAD

**Issue by XD-Z** [li-xiaojun/XPopup#897]
**XPopup版本**
如2.6.7
**手机系统和型号**
华为xrx-al19

**描述你的问题**
现在用demo的时候,横屏也有这种问题,想要横屏的时候,图片两边有黑边,中间图片全部显示出来
 //popup 显示图片加载
                            new XPopup.Builder(context)
                                    .isDestroyOnDismiss(true)
                                    .asImageViewer(viewHolder.img1, list.get(position).image, new SmartGlideImageLoader())
                                    .isInfinite(true)
                                    .isShowPlaceholder(true)
                                    .isShowSaveButton(false)
                                    .show();

**Comment by li-xiaojun** [comment]
更新到最新版本
