### ISSUE TITLE
使用BubbleAttachPopupView弹窗设置，阴影不显示，setBubbleShadowSize也无效

### ISSUE THREAD

**Issue by ChinaLike** [li-xiaojun/XPopup#898]
**XPopup版本**
2.7.5

**手机系统和型号**
OnePlus 6T Android 10

**描述你的问题**
使用BubbleAttachPopupView弹窗时，阴影不显示，或设置setBubbleShadowSize也无效
<img width="899" alt="QQ20220118-150801@2x" src="https://user-images.githubusercontent.com/19606225/149887871-4d13a557-fc5a-4e7f-a941-f1c7e8ffd030.png">
![mmexport1642489924325](https://user-images.githubusercontent.com/19606225/149888542-8de2db59-dbb9-4488-a13b-b597cac33c18.jpg)

**Comment by li-xiaojun** [comment]
@ChinaLike 更新到最新版试试

**Comment by li-xiaojun** [comment]
@ChinaLike 你没有设置shadowSize
