### ISSUE TITLE
BottomPopupView能否添加一个高度变化的回调

### ISSUE THREAD

**Issue by jin123d** [li-xiaojun/XPopup#899]
首先感谢作者提供的这个库。

**XPopup版本**
如2.7.4

**描述你的问题**
目前需要根据弹窗的高度做一些相应的动画，但是目前dialog的`beforeDismiss`是在动画结束完才执行。
如果`beforeDismiss`在`动画执行前`回调或者给出`高度回调`就会方便很多，谢谢。

**Comment by jin123d** [comment]
通过自定义动画实现

**Comment by liuhuilong2016** [comment]
> 首先感谢作者提供的这个库。
> 
> **XPopup版本** 如2.7.4
> 
> **描述你的问题** 目前需要根据弹窗的高度做一些相应的动画，但是目前dialog的`beforeDismiss`是在动画结束完才执行。 如果`beforeDismiss`在`动画执行前`回调或者给出`高度回调`就会方便很多，谢谢。

你是如何完成这效果的，我这里也需要他的高度来调整视频的高度

**Comment by jin123d** [comment]
> > 首先感谢作者提供的这个库。
> > **XPopup版本** 如2.7.4
> > **描述你的问题** 目前需要根据弹窗的高度做一些相应的动画，但是目前dialog的`beforeDismiss`是在动画结束完才执行。 如果`beforeDismiss`在`动画执行前`回调或者给出`高度回调`就会方便很多，谢谢。
> 
> 你是如何完成这效果的，我这里也需要他的高度来调整视频的高度

`XPopup.Builder(context).customAnimator(CustomTranslateAnimator(heightChange)) `

这个 自定义动画类

`CustomTranslateAnimator(val heightChange: ((Boolean, Float) -> Unit)? = null)`

中重写 `animateShow` 和 `animateDismiss`，在这两个方法中回调动画进度 `heightChange`，（最后再将进度计算为高度）


```
class CustomTranslateAnimator(val heightChange: ((Boolean, Float) -> Unit)? = null) :
    PopupAnimator() {
    var startTranslationX = 0f
    var startTranslationY = 0f
    var endTranslationX = 0f
    var endTranslationY = 0f
    var hasInit = false

    override fun initAnimator() {
        if (!hasInit) {
            endTranslationX = targetView.translationX
            endTranslationY = targetView.translationY
            // 设置起始坐标
            applyTranslation()
            startTranslationX = targetView.translationX
            startTranslationY = targetView.translationY
        }
    }

    private fun applyTranslation() {
        targetView.translationY =
            ((targetView.parent as View).measuredHeight - targetView.top).toFloat()
    }

    override fun animateShow() {
        val animator = targetView.animate().translationY(endTranslationY)
        animator.setInterpolator(FastOutSlowInInterpolator())
            .setDuration(300)
            .setUpdateListener {
                heightChange?.invoke(true, -it.animatedValue.toString().toFloat())
            }
            .withLayer().start()
    }

    override fun animateDismiss() {
        if (animating) return
        startTranslationY =
            ((targetView.parent as View).measuredHeight - targetView.top).toFloat()
        val animator = targetView.animate().translationY(startTranslationY)
        observerAnimator(
            animator.setInterpolator(FastOutSlowInInterpolator())
                .setUpdateListener {
                    heightChange?.invoke(false, it.animatedValue.toString().toFloat())
                }
                .setDuration((300 * .8).toLong())
                .withLayer()
        ).start()
    }
}
```

**Comment by liuhuilong2016** [comment]
目前已经不用此库完成效果了，使用官方库BottomSheetDialogFragment来使用了。反正效果就是要仿今日头条评论弹出，视频往上压缩，回弹视频恢复效果。XPopup目前没有开箱即用



在 2024-04-19 17:38:51，"jin123d" ***@***.***> 写道：

首先感谢作者提供的这个库。
XPopup版本 如2.7.4
描述你的问题 目前需要根据弹窗的高度做一些相应的动画，但是目前dialog的beforeDismiss是在动画结束完才执行。 如果beforeDismiss在动画执行前回调或者给出高度回调就会方便很多，谢谢。

你是如何完成这效果的，我这里也需要他的高度来调整视频的高度

XPopup.Builder(context).customAnimator(CustomTranslateAnimator(heightChange))

这个 自定义动画类

CustomTranslateAnimator(val heightChange: ((Boolean, Float) -> Unit)? = null)

中重写 animateShow 和 animateDismiss，在这两个方法中回调动画进度 heightChange，（最后再将进度计算为高度）

class CustomTranslateAnimator(val heightChange: ((Boolean, Float) -> Unit)? = null) :
    PopupAnimator() {
    var startTranslationX = 0f
    var startTranslationY = 0f
    var endTranslationX = 0f
    var endTranslationY = 0f
    var hasInit = false

    override fun initAnimator() {
        if (!hasInit) {
            endTranslationX = targetView.translationX
            endTranslationY = targetView.translationY
            // 设置起始坐标
            applyTranslation()
            startTranslationX = targetView.translationX
            startTranslationY = targetView.translationY
        }
    }

    private fun applyTranslation() {
        targetView.translationY =
            ((targetView.parent as View).measuredHeight - targetView.top).toFloat()
    }

    override fun animateShow() {
        val animator = targetView.animate().translationY(endTranslationY)
        animator.setInterpolator(FastOutSlowInInterpolator())
            .setDuration(300)
            .setUpdateListener {
                heightChange?.invoke(true, -it.animatedValue.toString().toFloat())
            }
            .withLayer().start()
    }

    override fun animateDismiss() {
        if (animating) return
        startTranslationY =
            ((targetView.parent as View).measuredHeight - targetView.top).toFloat()
        val animator = targetView.animate().translationY(startTranslationY)
        observerAnimator(
            animator.setInterpolator(FastOutSlowInInterpolator())
                .setUpdateListener {
                    heightChange?.invoke(false, it.animatedValue.toString().toFloat())
                }
                .setDuration((300 * .8).toLong())
                .withLayer()
        ).start()
    }
}
