### ISSUE TITLE
全面屏底部适配

### ISSUE THREAD

**Issue by parcool** [li-xiaojun/XPopup#9]
![image](https://user-images.githubusercontent.com/12092478/50389436-398acd80-0765-11e9-8c39-da9796b78c6b.png)
底部预留了虚拟导航栏的空间了，请适配一下全面屏哈。

**Comment by parcool** [comment]
另外，麻烦每次更新写上更新日志，谢谢了~

**Comment by parcool** [comment]
是几分钟前下载的你提供的这个蒲公英的地址的demo啊

**Comment by li-xiaojun** [comment]
@parcool 请说下手机型号和系统版本，可能是手机适配问题了，我用华为全面屏测试没有问题。

**Comment by parcool** [comment]
小米 mix 2s 9.0系统

**Comment by qiushui95** [comment]
我的mix 2s  9.0也是这样显示的

**Comment by li-xiaojun** [comment]
@qiushui95 @parcool 
感谢你们的建议，目前在1.0.2版本中已经适配小米MIX2，MIX2S以及华为系列全面屏，请下载Demo体验

**Comment by bluejuzz** [comment]
我的一加7也出现这个问题
