### ISSUE TITLE
作者你好，请问1.6.1怎么关闭asLoading对话框啊？ 在请求结束后手动关闭加载框，使用dismiss无效。

### ISSUE THREAD

**Issue by Geeouo** [li-xiaojun/XPopup#90]
BasePopView dialog = null;
@Override
                    public void onSubscribe(Disposable d) {
                        dialog = new XPopup.Builder(mContext).hasShadowBg(false).dismissOnTouchOutside(false).asLoading().show();
                    }

                    @Override
                    public void onNext(HttpResult<HotWordBean> value) {
                        ((GetWordTextView) spanView).dismissSelected();
                        if (dialog != null && dialog.isShow()) {
                            dialog.dismiss();
                            dialog = null;
                        }}

**Comment by li-xiaojun** [comment]
@Geeouo 
不要把dialog=null

**Comment by Geeouo** [comment]
> @Geeouo
> 不要把dialog=null

不行 我试过了  还是不行 不知道为什么  还有提供其他的什么方法取消加载框吗

**Comment by li-xiaojun** [comment]
@Geeouo 
你确定dismiss方法走了吗？

**Comment by li-xiaojun** [comment]
@Geeouo 
我这边怎么试都没问题，你确定你的onNext走了？

**Comment by Geeouo** [comment]
> @Geeouo
> 不要把dialog=null



> @Geeouo
> 我这边怎么试都没问题，你确定你的onNext走了？

打断点看了确定if判断为true走了dismiss执行了  但就是加载框没消失。 dismiss()下面还有加载数据的方法也确定数据加载出来了

**Comment by Geeouo** [comment]
> @Geeouo
> 我这边怎么试都没问题，你确定你的onNext走了？



> @Geeouo
> 不要把dialog=null
> 
> 
> @Geeouo
> 我这边怎么试都没问题，你确定你的onNext走了？
> 
> 打断点看了确定if判断为true走了dismiss执行了  但就是加载框没消失。 dismiss()下面还有加载数据的方法也确定数据加载出来了



> @Geeouo
> 我这边怎么试都没问题，你确定你的onNext走了？
@li-xiaojun 你好，你能提供一个标准的写法吗 在请求完成后手动取消加载框？

**Comment by Geeouo** [comment]
@li-xiaojun  作者你好，又试了一下，一个activity/Fragment中声明一个成员变量BasePopupView dialog1 = null 然后调用没问题。可以声明两个BasePopupView dialog1 = null，BasePopupView dialog2= null 调用dialog2.dismiss()时会报错dialog2空指针。

**Comment by 379119979** [comment]
在onNext中再次发起网络请求时，好像会遇到这种情况，应该时show了多个dialog

**Comment by Geeouo** [comment]
@

> 在onNext中再次发起网络请求时，好像会遇到这种情况，应该时show了多个dialog @li-xiaojun @Geeouo

@379119979 @li-xiaojun 按照我issue提供的写法一定发生dismiss()无效。我断点确定dismiss()方法执行了，追到里面四行代码就没再追了 版本要上线 已经退回到1.5.2了

**Comment by li-xiaojun** [comment]
@Geeouo 
如果你的onSubscribe执行多次，就会创建多个弹窗，之前弹的对象被后面创建的弹窗对象覆盖，所以你调用dismiss的时候，只能让当前的弹窗消失，被覆盖的弹窗无法消失。

看看你是否new了多个弹窗对象。

**Comment by Geeouo** [comment]
> @Geeouo
> 如果你的onSubscribe执行多次，就会创建多个弹窗，之前弹的对象被后面创建的弹窗对象覆盖，所以你调用dismiss的时候，只能让当前的弹窗消失，被覆盖的弹窗无法消失。
> 
> 看看你是否new了多个弹窗对象。

@li-xiaojun 好的  先mark一下  有时间研究一下  先切回到1.5.2赶进度了

**Comment by li-xiaojun** [comment]
@Geeouo 
我修复了一个在请求快速返回时弹窗无法关闭的bug，更新到1.6.3试试。

**Comment by Geeouo** [comment]
> @Geeouo
> 我修复了一个在请求快速返回时弹窗无法关闭的bug，更新到1.6.3试试。

@li-xiaojun 万分感谢 谢谢

**Comment by li-xiaojun** [comment]
@Geeouo 你的问题解决了吗

**Comment by Geeouo** [comment]
> @Geeouo 你的问题解决了吗

@li-xiaojun 晚些给你答复

**Comment by Geeouo** [comment]
@li-xiaojun  @379119979 切到1.6.4 问题解决。感谢

**Comment by li-xiaojun** [comment]
@Geeouo 
可以加qq群：783659607 来交流遇到的问题。

**Comment by Geeouo** [comment]
> @Geeouo
> 可以加qq群：783659607 来交流遇到的问题。

@li-xiaojun 好
