### ISSUE TITLE
关于show(),延迟10ms初始化问题

### ISSUE THREAD

**Issue by DNJusername** [li-xiaojun/XPopup#905]
**XPopup版本**
2.7.5

**手机系统和型号**
Android手机

**描述你的问题**
有时候会涉及到开放方法去初始化dialog里面的数据，看到源码上，只有在show()调用之后，才开始初始化布局，这就导致了如果我开放的方法里面涉及到了UI组件的话，会提示我UI组件没有初始化。我目前的解决办法是show()调用之后，延迟时间大于10ms，再去调用自定义弹窗开放的方法，但是有时候手机过卡还是什么原因，延迟时间太短也会报未初始化的异常。不知道大神你这边有没有什么好的建议和使用姿势

**Comment by li-xiaojun** [comment]
开放的方法是放在哪里执行的，如果放在onCreate执行应该是没有问题的；onCreate执行的时候，弹出的UI已经加载了

**Comment by DNJusername** [comment]
> 打开的方法是从哪里找到的，如果在onCreate执行时应该是没有问题的；onCreateExecute的时候，已经启动的UI加载了

我是在其它地方使用的时候，用popup对象去调用开放的方法，因为show有延迟，所以导致我用popup对象去调用方法的时候，会报没有初始化

**Comment by li-xiaojun** [comment]
@DNJusername 
在开放的方法内部做一些初始化判断；弹窗是有生命周期的，如果还没显示就调用方法，肯定会有问题；把弹窗想象为Fragment就好理解了。这里的延时10毫秒不影响的，去掉10毫秒还是有post的延时的。

你也可以做这样的判断，if(popup.isShow()) callYourMethod();
