### ISSUE TITLE
希望可以增加一个类似onBackPressed这样的api,在点击弹窗外部的时候做一个拦截

### ISSUE THREAD

**Issue by wlingf** [li-xiaojun/XPopup#908]
**XPopup版本**
2.7.5

**描述你的问题**
希望可以增加一个类似onBackPressed这样的api,在点击弹窗外部的时候做一个拦截，目前有需求是在弹窗消失的时候做挽留提示，如果在弹窗外部点击就没办法实现

**Comment by cwl1992** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
