### ISSUE TITLE
华为metapad pro适配问题

### ISSUE THREAD

**Issue by mishaoshuai** [li-xiaojun/XPopup#909]
底部带edittext的popup，有时候贴着输入法，有时候不贴，导致横屏时如果不贴就被输入法顶没了，竖屏情况下，edittext跑到屏幕中间，不贴着输入法，2.6.3

**Comment by mishaoshuai** [comment]
2.7.5试了也一样

**Comment by mishaoshuai** [comment]
试了demo没问题，是我的集成出问题了吗

**Comment by li-xiaojun** [comment]
看看文档，是不是手动设置Activity的softMode了

**Comment by mishaoshuai** [comment]
并没有

**Comment by mishaoshuai** [comment]
.isViewMode(false)
这样就ok了
