### ISSUE TITLE
在editText下方显示popuwindow时，显示在最顶部去了，而不是在下方

### ISSUE THREAD

**Issue by cc365774016** [li-xiaojun/XPopup#91]

**Comment by li-xiaojun** [comment]
截图。

**Comment by li-xiaojun** [comment]
@cc365774016 
改Bug已修复，更新到1.6.2。

**Comment by cc365774016** [comment]
现在OK了，atview这个方法能不能手动控制它的上下左右呢

**Comment by li-xiaojun** [comment]
@cc365774016 
目前还不支持，内部有一些算法来智能计算位置，不过这个想法挺不错，我后续加上这个功能吧。

**Comment by cc365774016** [comment]
好的，非常感谢。有没有交流群呢

**Comment by li-xiaojun** [comment]
@cc365774016 
![qqgroup](https://user-images.githubusercontent.com/4426715/55140663-971f2380-5173-11e9-8dde-747661c92110.png)
