### ISSUE TITLE
仅限交流（上下文强转问题），本人不能确定是否是XPop缺陷

### ISSUE THREAD

**Issue by SmallWinter** [li-xiaojun/XPopup#910]
**XPopup版本**
如2.7.5

**手机系统和型号**
OPPO Android 10

**描述你的问题**
首先感谢作者不辞辛劳封装这么好的库给大家使用，十分感谢！
问题如下：
上下文强转问题，报错如下：
![1645423541(1)](https://user-images.githubusercontent.com/8638180/154898414-a240bf6e-39b4-4e2b-8e88-bcebb2547614.png)
经debug定位到导致此问题所在位置:
![1645423624(1)](https://user-images.githubusercontent.com/8638180/154898561-571f9d8e-8a66-47ec-8a75-c814763dcc54.png)

说下出现这种情况的大概描述，继承自ImageViewerPopupView的一个pop（暂且称为A），在一个自定义view（暂且称为B）里面使用context传入pop（A），就出现这种现象了。

**Comment by SmallWinter** [comment]
补充：basePop里强转的地方还不少，所以复写此方法，并不能解决问题

**Comment by SmallWinter** [comment]
再次补充：找到问题所在，因为使用了appbarlayout包裹，获取的就是ContextThemeWrapper，不知道是否考虑后续兼容？

**Comment by li-xiaojun** [comment]
下个版本修复

**Comment by lhalcyon** [comment]
> 下个版本修复

大大,啥时候发上去呀.~

**Comment by li-xiaojun** [comment]
@lhalcyon @SmallWinter 更新到2.7.6即可

**Comment by SmallWinter** [comment]
感谢大佬
