### ISSUE TITLE
图片查看中页码指示器

### ISSUE THREAD

**Issue by YQcharlse** [li-xiaojun/XPopup#911]
**XPopup版本**
2.7.5
**描述你的问题**
ImageViewerPopupView 图片查看 中  tv_pager_indicator  页面指示器的颜色是否设置成 自定义颜色

**Comment by WillFreeman** [comment]
页码指示器和保存按钮，在遇到白底长图片时，会难以辨认。是否考虑有一个蒙层，适应各种底色。

**Comment by li-xiaojun** [comment]
可以自定义布局的，
