### ISSUE TITLE
底部弹窗，输入法软键盘弹出后切换到后台在回来的时候，软键盘隐藏，但是弹窗并没有掉下来

### ISSUE THREAD

**Issue by xhh1993** [li-xiaojun/XPopup#918]
**XPopup版本**
2.6.7

**手机系统和型号**
部分机型，如三星，部分华为等等，挺多的

**描述你的问题**
需要弹出软键盘的弹窗，切换到后台，再次返回时软键盘消失，但是弹窗并没有顶下来。导致软键盘的区域是空白的。本来应该在底部的弹窗悬浮在半空。挺多机型都能必现

**Comment by li-xiaojun** [comment]
试试demo有没有这个问题

**Comment by xhh1993** [comment]
![QQ图片20220308162651](https://user-images.githubusercontent.com/17424639/157196893-fb371545-ade7-4218-a1f2-e403ec687f22.jpg)
demo没有问题，但是demo里面的isViewMode(true)修改为isViewMode(false)大部分手机必现。但是isViewMode对于我而言有局限性，项目只能用isViewMode(false)的情况，大佬帮忙看看这个问题有修复的可能吗

**Comment by li-xiaojun** [comment]
@xhh1993 已修复。更新到2.8.2即可

**Comment by oudengding** [comment]
> @xhh1993 已修复。更新到2.8.2即可

最高不也才2.8.13吗？

**Comment by li-xiaojun** [comment]
> 

13比2大，有什么问题吗
