### ISSUE TITLE
dismissWith为什么是protected的

### ISSUE THREAD

**Issue by qiushui95** [li-xiaojun/XPopup#92]
在外面不能调用，不能实现消失再执行

**Comment by li-xiaojun** [comment]
@qiushui95 
下个版本修改。

**Comment by qiushui95** [comment]
> @qiushui95
> 下个版本修改。

大约什么时候  我现在项目需要这个。。。。

**Comment by li-xiaojun** [comment]
@qiushui95 
更新到1.6.2即可。

**Comment by qiushui95** [comment]
> @qiushui95
> 更新到1.6.2即可。

神速！谢谢
