### ISSUE TITLE
 android.view.WindowManager$BadTokenException

### ISSUE THREAD

**Issue by mm46468648** [li-xiaojun/XPopup#922]
**XPopup版本**
如com.lxj:xpopup:2.0.8-rc5

**手机系统和型号**
![image](https://user-images.githubusercontent.com/18639335/156973917-c89daa15-b731-48a2-ba47-65dc248ec3a1.png)

**描述你的问题**
在bugly上看到好多关于BasePopView的报错，可能是因为我在后台有弹出这种弹框的操作，但是我又不能保证我不在后台弹出，所有想请教一下看看有什么好的解决方式

报错信息如下：

# main(2)
android.view.WindowManager$BadTokenException
Unable to add window -- token android.os.BinderProxy@df52532 is not valid; is your activity running?
解析原始
1
android.view.ViewRootImpl.setView(ViewRootImpl.java:1255)
2
android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:420)
3
android.view.WindowManagerImpl.addView(WindowManagerImpl.java:110)
4
android.app.Dialog.show(Dialog.java:353)
5
com.lxj.xpopup.core.BasePopupView.s(BasePopupView.java:4)
6
com.lxj.xpopup.core.BasePopupView.i(BasePopupView.java:1)
7
com.lxj.xpopup.core.BasePopupView$b.run(BasePopupView.java:1)
8
android.os.Handler.handleCallback(Handler.java:938)
9
android.os.Handler.dispatchMessage(Handler.java:99)

**Comment by li-xiaojun** [comment]
更新到最新版本
