### ISSUE TITLE
isShow返回错误

### ISSUE THREAD

**Issue by iamGGboss** [li-xiaojun/XPopup#927]
**XPopup版本**
如2.7.6

判断isShow方法，返回了错误，弹窗在显示，但是isShow返回的是false

**Comment by iamGGboss** [comment]
2.7.5也有同样的问题，2.7.1正常，但是2.7.1全屏弹窗显示有点问题，就是他布局提前显示，然后动画之后再执行，导致看起来会闪一下。然后这个问题不是必现，有时候又是正常的

**Comment by CN-ZPH** [comment]
我测试  2.7.6没有问题 应该是你代码问题 主要 .asCustom(redPopup)这一行不要再new了 
  if (redPopup == null) {
                                    redPopup = new RedPopup(getContext());
                                }
                                if (!redPopup.isShow()) {
                                    new XPopup.Builder(getContext())
                                            .asCustom(redPopup)
                                            .show();
                                }

**Comment by iamGGboss** [comment]
> 我测试 2.7.6没有问题 应该是你代码问题 主要 .asCustom(redPopup)这一行不要再new了 if (redPopup == null) { redPopup = new RedPopup(getContext()); } if (!redPopup.isShow()) { new XPopup.Builder(getContext()) .asCustom(redPopup) .show(); }

并没有new，复用的缓存，而且这代码没有任何修改，老版本是没有任何问题的

**Comment by li-xiaojun** [comment]
弹窗相关代码贴下

**Comment by iamGGboss** [comment]
> 弹窗相关代码贴下

    private val mLoadingDialog by lazy {
        XPopup.Builder(this)
            .dismissOnTouchOutside(false)
            .dismissOnBackPressed(false)
            .asLoading(MyLang.getString("loading", R.string.loading), R.layout.dialog_loading)
    }

     override fun showLoading() {
        if (mLoadingDialog != null && !mLoadingDialog.isShow) {
            mLoadingDialog.show()
        }
    }

 override fun hideLoading() {
        if (mLoadingDialog != null && mLoadingDialog.isShow) {
            mLoadingDialog.smartDismiss()
        }
    }

**Comment by liubiaoren** [comment]
我也有这个问题，怎么处理？

**Comment by iamGGboss** [comment]
> 

降到2.7.2或者更早的版本

**Comment by li-xiaojun** [comment]
@iamGGboss @liubiaoren @CN-ZPH 更新到2.7.9即可
