### ISSUE TITLE
按下返回键后dialog自动关闭

### ISSUE THREAD

**Issue by diorslau** [li-xiaojun/XPopup#929]
**XPopup版本**
2.7.5

**手机系统和型号**
pda或者国外的一些机型，具体型号未知

**描述你的问题**
按下手机返回实体键后 弹出dialog后， 很大概率会自动关闭掉dialog，不知是不是机器的按键问题导致

**Comment by li-xiaojun** [comment]
设置 dismissOnBackPressed(false)即可
