### ISSUE TITLE
java.lang.NullPointerException Bitmap must not be null

### ISSUE THREAD

**Issue by po1xiao** [li-xiaojun/XPopup#931]
**XPopup版本**
2.7.6

**手机系统和型号**
Android 12,level 31
机型：小米 M2102J2SC

**描述你的问题**
线上崩溃，这个堆栈里没有我的代码，可否在SmartGlideImageLoader中做一下判断：
java.lang.NullPointerException Bitmap must not be null

com.bumptech.glide.load.engine.CallbackException:Unexpected exception thrown by non-Glide code
com.bumptech.glide.load.engine.EngineJob.callCallbackOnResourceReady(EngineJob.java:161)
......
Caused by:
java.lang.NullPointerException:Bitmap must not be null
java.util.Objects.requireNonNull(Objects.java:245)
com.davemorrissey.labs.subscaleview.ImageSource.cachedBitmap(ImageSource.java:154)
com.lxj.xpopup.util.SmartGlideImageLoader$1.onResourceReady(SmartGlideImageLoader.java:118)
com.lxj.xpopup.util.SmartGlideImageLoader$1.onResourceReady(SmartGlideImageLoader.java:67)
com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:639)
com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:578)
com.bumptech.glide.load.engine.EngineJob.callCallbackOnResourceReady(EngineJob.java:159)
com.bumptech.glide.load.engine.EngineJob$CallResourceReady.run(EngineJob.java:428)
android.os.Handler.handleCallback(Handler.java:938)
android.os.Handler.dispatchMessage(Handler.java:99)
android.os.Looper.loopOnce(Looper.java:210)
android.os.Looper.loop(Looper.java:299)
android.app.ActivityThread.main(ActivityThread.java:8087)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

**Comment by li-xiaojun** [comment]
@po1xiao  更新到2.7.8即可
