### ISSUE TITLE
全屏弹窗   下面遮挡不住

### ISSUE THREAD

**Issue by 865911246** [li-xiaojun/XPopup#932]
**XPopup版本**
1.8.10

**手机系统和型号**
红米  

**描述你的问题**
我设置的全屏弹窗    弹出后   最下面遮挡不住
![1](https://user-images.githubusercontent.com/102774140/161176185-47005941-d8f0-4fcf-95a6-aaea3035b824.png)
![2](https://user-images.githubusercontent.com/102774140/161176188-6a36e017-6204-40b9-966e-f328b52ce99d.png)
![3](https://user-images.githubusercontent.com/102774140/161176190-0ba3bb95-32ff-4844-9d64-c6ddafc1bf52.png)

ZuCaiGengDuoWanFaPopup  界面 布局是match_parent 

效果出来是这样的
![5](https://user-images.githubusercontent.com/102774140/161176727-ec1f8bb8-26b0-4daf-8d26-c96300e1fe7f.png)

**Comment by li-xiaojun** [comment]
更新版本
