### ISSUE TITLE
底部类型的List弹窗，在某些机型上向上偏移一段距离

### ISSUE THREAD

**Issue by goodluckier** [li-xiaojun/XPopup#933]
**XPopup版本**
如2.7.6

**手机系统和型号**
索尼 Xperia 1 Ⅱ

**描述你的问题**
用导航条时出现问题，小白条时正常。
代码和截屏如下，间隔高度好像是导航条高度。
是我代码配置错了吗，我测试了好几个是正常的，这是用户遇到的

![搜狗截图22年04月02日1424_1](https://user-images.githubusercontent.com/3511727/161370006-4e384412-d8a9-45b3-870a-adb62c513090.png)
![弹窗偏移](https://user-images.githubusercontent.com/3511727/161370087-ec1303d9-6615-45df-8d61-164d5480c774.png)

**Comment by li-xiaojun** [comment]
@goodluckier 看看最新版有没有这个问题
