### ISSUE TITLE
sqlite   rawQuery 报错

### ISSUE THREAD

**Issue by caochongsheng** [li-xiaojun/XPopup#934]
**XPopup版本**
所有版本

**手机系统和型号**
华为Mate20 Android 10

**描述你的问题**
引入库就报错
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.database.Cursor android.database.sqlite.SQLiteDatabase.rawQuery(java.lang.String, java.lang.String[])' on a null object reference

**Comment by dujianchi** [comment]
我特地下载了代码，这个库的代码里都没引用sqlite啊？

**Comment by caochongsheng** [comment]
库里是没有的， 但是我项目中有使用sqlite 会报错，删掉这个库就不报错，加上就报错



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月6日(星期三) 晚上6:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [li-xiaojun/XPopup] sqlite   rawQuery 报错 (Issue #934)





 
我特地下载了代码，这个库的代码里都没引用sqlite啊？

**Comment by caochongsheng** [comment]
你好是我项目里面有用到 sqliite&nbsp; 但是 已进入这个库 就会报错，去掉就不报错




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "li-xiaojun/XPopup"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月6日(星期三) 晚上6:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [li-xiaojun/XPopup] sqlite   rawQuery 报错 (Issue #934)





 
我特地下载了代码，这个库的代码里都没引用sqlite啊？

**Comment by MasterAlexXu** [comment]
用 room @caochongsheng

**Comment by li-xiaojun** [comment]
可能是编译问题，但这个问题肯定不是XPopup引起的，XPopup只是一个UI库，未关联任何sqlite相关代码
