### ISSUE TITLE
感觉显示比较迟钝

### ISSUE THREAD

**Issue by pj567** [li-xiaojun/XPopup#939]
**2.7.6**
在不使用框架时dialog显示和使用框架时dialog显示反应总比前者慢一拍

**Comment by li-xiaojun** [comment]
是不是动画时间造成了你的错觉，设置 .animationDuration(50)  试试 是否和你想要的效果一样，

**Comment by pj567** [comment]
这点小问题不知道会引起什么错，慢的问题我知道啥原因了，肯定是没有直接dialog反应快，全部的代码逻辑都了解得差不多了，挺牛的
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "li-xiaojun/XPopup"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月15日(星期五) 下午2:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [li-xiaojun/XPopup] 感觉显示比较迟钝 (Issue #939)





 
是不是动画时间造成了你的错觉，设置 .animationDuration(50)  试试 是否和你想要的效果一样，
