### ISSUE TITLE
初始化迟缓 show() 之后不能立即获取到其中元素

### ISSUE THREAD

**Issue by MasterAlexXu** [li-xiaojun/XPopup#940]
**XPopup版本**
2.4.9

**手机系统和型号**
华为 一加 8 pro  Android 11

**描述你的问题**
底部自定义弹出层 初始化 问题 在show() 后 获取不到 弹出层中的 progressBarV 元素  导致 空指针  在： onStart()  之后 立即  onChanged()
![微信截图_20220414143037](https://user-images.githubusercontent.com/90443578/163327340-b6f891f1-e1bd-4a2e-be17-0d88c1f19166.png)
![微信截图_20220414143126](https://user-images.githubusercontent.com/90443578/163327352-939dc0ac-3e30-4b57-80c3-9ab4751a23e8.png)
![微信截图_20220414143136](https://user-images.githubusercontent.com/90443578/163327354-65b1357e-d956-48ba-8905-fc8abdebed62.png)

**Comment by li-xiaojun** [comment]
UI是有生命周期的，记住这一点。Fragment和弹窗都是这样，show之后并不一定能获取到View，可以在弹窗的onCreated方法中执行相关方法，此时一定可以获取到View。

**Comment by MasterAlexXu** [comment]
我应该如何使用 这个回调 因为我在 popup.show() 之后不能立即拿到 progressBarV 以及 首次初始化popup时候并不会 onCreate() 只有在show() 之后 popup 才会创建 view 。 我的思路是这样的 先创建 popup 让我拿到其中View  然后再show() 这样就不会抛出空指针 但是我失败了，有关于底部popup 进度条变化的例子吗？感激不尽 谢谢

**Comment by MasterAlexXu** [comment]
如果只能在popup 的onCreate()中 执行相关 这是不合理的 比如异步的进度回调    您有什么更好的思路？比如我的进度从0-100更新完毕 但是popop才onCreate()  能不能先创建popup 不显示 让我获取其中的View 需要时候再显示 这样可以避免获取不到View 问题

**Comment by li-xiaojun** [comment]
@MasterAlexXu 
更新到2.7.7即可，已解决这个问题

**Comment by MasterAlexXu** [comment]
感激不尽

**Comment by XuXin007** [comment]
老哥 这个问题 我又拿不到了 以前还可以的，最近我又发现这个问题了
