### ISSUE TITLE
自定义底部弹出层 焦点问题 导致回收者视图RecyclerView无法滚动  

### ISSUE THREAD

**Issue by XuXin007** [li-xiaojun/XPopup#941]
自定义底部弹出层 导致回收者视图RecyclerView无法滚动   就是 extends BottomPopupView 的弹出层  'com.github.li-xiaojun:XPopup:2.4.9'  这个版本还可以滚动的     版本2.7.7就无法滚动了 网不好 其他版本没试过  谢谢

**Comment by MasterAlexXu** [comment]
不是弹出层里的，是弹出层下面的

**Comment by li-xiaojun** [comment]
isTouchThrough(true)
