### ISSUE TITLE
在onCreate里进行网络请求的loading会卡顿，有视频演示

### ISSUE THREAD

**Issue by JiangShuLiang** [li-xiaojun/XPopup#942]
**XPopup版本**
如2.7.7

**手机系统和型号**
红米k30s，android12

**描述你的问题**
自定义了一个popup，命名为A，在A的onCreate里初始化view后去请求接口数据，网络请求在onStart时有加入loading的弹窗（此处的loading用的也是xpopup的），但是使用起来，会发现loading有明显的0.5s左右的卡顿，详细见视频。

*注：loadingPopup对象是static的，网络请求得到的数据是用addView方式展示的。

https://user-images.githubusercontent.com/20485764/163914952-78ffacf4-f2f1-47ce-b1b8-892c8f5e2923.mp4

![微信图片_20220419113347](https://user-images.githubusercontent.com/20485764/163914988-2188c8ef-9942-4a19-8b5c-3e70f27a925f.png)

**Comment by li-xiaojun** [comment]
估计是addView造成的，试试将addView部分代码注释掉看看还卡顿不

**Comment by JiangShuLiang** [comment]
> 代码

确实，换成rv展示就不卡了，感谢回答
