### ISSUE TITLE
BottomPopupView设置背景颜色为透明色

### ISSUE THREAD

**Issue by woniu0936** [li-xiaojun/XPopup#944]
**XPopup版本**
2.7.6

**手机系统和型号**
小米 mix2s Android 10  MIUI 12.5.1

**描述你的问题**
`XPopup.Builder(this)
            .moveUpToKeyboard(false)  .enableDrag(false)
            .shadowBgColor(Color.TRANSPARENT)
            .isDestroyOnDismiss(true) 
            .dismissOnTouchOutside(false)
            .asCustom(bottomView)
            .show()`
这段代码是弹出一个底部出来的dialog，我想设置后面的半透明背景为全透明，使用`.shadowBgColor(Color.TRANSPARENT)`不起作用

**Comment by li-xiaojun** [comment]
直接hasShadowBg(false)即可

**Comment by woniu163** [comment]
收到，感谢
