### ISSUE TITLE
冲突报错

### ISSUE THREAD

**Issue by easywangzhe** [li-xiaojun/XPopup#950]
**XPopup版本**
如2.7.8

**描述你的问题**
最好能上代码截图和问题截图
项目里面使用了BottomNavigationViewEx这个控件，再集成xpopup就会报错，只能二选一不会报错
![QQ截图20220427153039](https://user-images.githubusercontent.com/9899467/165465769-59841ad3-e011-4638-acc6-21256ed9e9bb.png)

**Comment by cuipf-stey** [comment]
我也遇到了一样的问题，请问兄弟解决了吗？
