### ISSUE TITLE
app for token android.os.BinderProxy@be12cf1 has too many windows 20

### ISSUE THREAD

**Issue by mm46468648** [li-xiaojun/XPopup#951]
**XPopup版本**
如2.7.6

**手机系统和型号**
Android 10,level 29
V2057A

**描述你的问题**
bugly统计中看到好多这样的异常,完整日志如下

# main(2)
android.view.WindowManager$BadTokenException
Unable to add window -- app for token android.os.BinderProxy@a873044 has too many windows 20
解析原始
android.view.ViewRootImpl.setView(ViewRootImpl.java:1007)
android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:408)
android.view.WindowManagerImpl.addView(WindowManagerImpl.java:95)
android.app.Dialog.show(Dialog.java:377)
com.lxj.xpopup.core.BasePopupView.q(BasePopupView.java:26)
com.lxj.xpopup.core.BasePopupView.e(BasePopupView.java:1)
com.lxj.xpopup.core.BasePopupView$a.run(BasePopupView.java:1)
android.os.Handler.handleCallback(Handler.java:883)
android.os.Handler.dispatchMessage(Handler.java:100)
android.os.Looper.loop(Looper.java:230)
android.app.ActivityThread.main(ActivityThread.java:7880)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

**Comment by fuchengxin** [comment]
同上

**Comment by li-xiaojun** [comment]
@fuchengxin @mm46468648 更新到最新版本，最新版本尝试优化

**Comment by mm46468648** [comment]
> @fuchengxin @mm46468648 更新到最新版本，最新版本尝试优化

已更新最新版本，但是该报错还是存在

**Comment by WDevaloper** [comment]
这个问题解决了吗
