### ISSUE TITLE
内置弹窗弹出列表的时候可否加入设置文字不要单行显示，可以多行显示，也可以设置文字居左居中居右这样的

### ISSUE THREAD

**Issue by huaxuanHan** [li-xiaojun/XPopup#953]
**XPopup版本**
如2.7.9

**手机系统和型号**
一加8T Android12

**描述你的问题**
最好能上代码截图和问题截图

**Comment by li-xiaojun** [comment]
内置弹窗不在增加功能，需求太多样了，可以自己封装了。
