### ISSUE TITLE
在Dialog或者DialogFragment中弹出AttachPopupView位置偏移

### ISSUE THREAD

**Issue by songchuanyang** [li-xiaojun/XPopup#954]
**XPopup版本**
2.7.6

**描述你的问题**
原因是在PopupInfo中getAtViewRect方法导致的获取位置数据有问题
如果实在Dialog或者DialogFragment中弹出的话 使用getLocationOnScreen方法可以正常使用
建议新增属性或者方法支持一下这个获取位置的方法

**Comment by li-xiaojun** [comment]
截图我看看问题

**Comment by songchuanyang** [comment]
![image](https://user-images.githubusercontent.com/13843259/169628575-a92dfa02-69ae-4f95-b8b2-1d69c028f1da.png)

如果我重写倚靠逻辑以及
```
    public Rect getAtViewRect() {
        int[] locations = new int[2];
        popupInfo.atView.getLocationOnScreen(locations);
        return new Rect(locations[0], locations[1], locations[0] + popupInfo.atView.getMeasuredWidth(),
                locations[1] + popupInfo.atView.getMeasuredHeight());
    }
```
就可以解决问题

![image](https://user-images.githubusercontent.com/13843259/169628652-90669e92-fe06-41e2-aed4-bb3be8b0c6a2.png)

**Comment by li-xiaojun** [comment]
更新到2.8.3即可

**Comment by songchuanyang** [comment]
我查看到 为了  修复横屏时Attach系列弹窗位置不对的问题
