### ISSUE TITLE
BottomPopupView弹窗dissmiss后 输入法的弹起关闭异常

### ISSUE THREAD

**Issue by sanpark** [li-xiaojun/XPopup#957]
**XPopup版本**
2.6.7

**手机系统和型号**
华为Mate30 Android 10

**描述你的问题**
聊天界面@弹出人员列表BottomPopupView里面带有一个edittext搜索框。配置如下
`       .hasShadowBg(true)
                        .enableDrag(false)
                        .moveUpToKeyboard(false)
                        .autoFocusEditText(false)
                        .autoOpenSoftInput(false)`

现象：1.点击人员列表选择人员后，dismiss弹窗，会到聊天界面会弹出输入法，然后自动关闭，不知道为什么会出现
           2.如果是点击弹窗外部，就不会出现弹出输入法自动关闭的现象
尝试处理：加入.isRequestFocus(false)，聊天界面的输入法不会关闭，dismiss后输入法依然在。但是弹窗的edittext无法弹出输入法
请问 如果控制这个输入法的弹出和关闭？

**Comment by li-xiaojun** [comment]
@sanpark 更新到最新版本试试
