### ISSUE TITLE
notDismissWhenTouchInView()不起作用

### ISSUE THREAD

**Issue by xuqinghao1991** [li-xiaojun/XPopup#958]
**XPopup版本**
2.7.8

**手机系统和型号**
华为nova 4   Android 10

**描述你的问题**
搜索到https://github.com/li-xiaojun/XPopup/issues/798这个相同问题,使用版本2.5.11不会出现notDismissWhenTouchInView()不起作用问题
![Dingtalk_20220513152521](https://user-images.githubusercontent.com/32887962/168232830-c99170d7-c386-4d0c-9cdd-66dbdfd94adb.jpg)

**Comment by li-xiaojun** [comment]
@xuqinghao1991 更新到2.8.1即可
