### ISSUE TITLE
当手动设置状态栏和导航栏背景与字体颜色后，弹出框会改变此设置

### ISSUE THREAD

**Issue by a1782680475** [li-xiaojun/XPopup#960]
**XPopup版本**
如2.1.0
2.7.6
**手机系统和型号**
三星Note10+ Android 12（实际上所有机型都这样）

**描述你的问题**
最好能上代码截图和问题截图
![image](https://user-images.githubusercontent.com/32875468/168724089-d83c54cc-1cc4-4b70-8da9-c71c184ddc8a.png)
![image](https://user-images.githubusercontent.com/32875468/168724120-2ce7bee5-b79f-4e1c-afed-d0a7df304d09.png)

**Comment by 18363853135** [comment]
最新版本 这个bug还是存在  解决了 提供下思路
