### ISSUE TITLE
DrawerPopupView高度为wrap_content，位置默认是顶部，怎么改为在底部？

### ISSUE THREAD

**Issue by leestars** [li-xiaojun/XPopup#961]
**XPopup版本**
2.7.6

**手机系统和型号**
google pixel 3 Android 12

**描述你的问题**
![Screenshot_20220520-154002](https://user-images.githubusercontent.com/15726885/169483679-74ab0edb-029c-490a-a617-7e61e4ca2c10.png)

**Comment by li-xiaojun** [comment]
你再弹出的布局设置下gravity
