### ISSUE TITLE
内置弹窗快速点击问题

### ISSUE THREAD

**Issue by oudengding** [li-xiaojun/XPopup#962]
如ConfirmPopupView弹窗，如果快速点击会出现问题（背景慢慢变黑），希望作者对于内置弹窗能加一个是否拦截快速点击的开关字段

**Comment by li-xiaojun** [comment]
你是弹了多个弹窗吧？这种重复开启弹窗的逻辑需要自己处理，类似的问题有重复点击多次网络请求，开启多个Activity。
做下事件节流

**Comment by appdev** [comment]
同样遇到了这个问题，点击弹窗关闭当前弹窗同时打开一个新的弹窗，如果慢慢点，没问题，但是如果快速点会有这个问题。
有个疑问是，快速点击的时候 为什么 dismiss 不生效？
