### ISSUE TITLE
列表item过长attach弹窗显示异常

### ISSUE THREAD

**Issue by princekin-f** [li-xiaojun/XPopup#964]
**XPopup版本**
如2.8.0

- 在列表中使用AttachPopupView，如果item高度超过列表高度，显示不完全，或者无法显示。

**Comment by li-xiaojun** [comment]
那就更换个目标View啊，

**Comment by princekin-f** [comment]
> 那就更换个目标View啊，

是这么处理的，需要自己计算上下空间是否足够，并设置一个固定的锚点view。
- 建议空间不足时，直接置顶或者置底。
