### ISSUE TITLE
平板自定义AttachPopupView宽度设置无效果

### ISSUE THREAD

**Issue by Elex92** [li-xiaojun/XPopup#966]
**XPopup版本**
2.8.0

**手机系统和型号**
华为平板SCM-AL09 鸿蒙系统 横屏模式

**描述你的问题**
![image](https://user-images.githubusercontent.com/16713043/170622556-a2864bf8-626a-4bf3-a6be-f78729ffe4d2.png)
XPopup.Builder(context)
                .hasStatusBar(false)
                .hasShadowBg(false)
                .dismissOnTouchOutside(isDismissOnTouchOutside)
                .dismissOnBackPressed(isDismissOnBackPressed)
                .maxWidth(DisplayUtil.getScreenWidth(context))
                .popupWidth(DisplayUtil.getScreenWidth(context))
                .offsetX(-(DisplayUtil.getScreenWidth(context) * 0.08).toInt())
                .moveUpToKeyboard(moveUpToKeyboard)
                .atView(atView)
                .asCustom(this)
                .show()
maxWidth和popupWidth都设置了屏幕宽度，可是弹窗永远就只有这么大，请问是什么原因。谢谢

**Comment by li-xiaojun** [comment]
我试了下是没问题的，你弹窗的代码和布局的代码贴下

**Comment by Elex92** [comment]
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:app="http://schemas.android.com/apk/res-auto">

    <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_width="match_parent"
        android:layout_height="200dp"
        android:background="@color/color3CAFA3">
        <androidx.appcompat.widget.AppCompatTextView
            android:layout_width="3000dp"
            android:layout_height="match_parent"
            android:text="1111111"
            android:textColor="@color/colorFFFFFF"
            android:textSize="@dimen/sp_40"/>

    </LinearLayout>


</layout>

**Comment by Elex92** [comment]
class ChatRoomFilterPopup (context: Context) : BaseShadowPopupView<PopupChatRoomBinding>(context) {

    override fun getLayoutId(): Int = R.layout.popup_chat_room

    override fun initView() {


    }


}

inline fun showFilterPopup(
        context: Context,
        atView: View,
        isDismissOnTouchOutside: Boolean = true,
        dialog: ChatRoomFilterPopup.() -> Unit
) {
    ChatRoomFilterPopup(context).apply(dialog).showT(atView,isDismissOnTouchOutside, isDismissOnTouchOutside)
}

**Comment by Elex92** [comment]
abstract class BaseShadowPopupView<B : ViewDataBinding>(context: Context) : BubbleAttachPopupView(context) {

    protected lateinit var mBinding: B
    abstract fun getLayoutId(): Int
    abstract fun initView()
    override fun getImplLayoutId(): Int {
        return getLayoutId()
    }

    override fun initPopupContent() {
        super.initPopupContent()
        mBinding = DataBindingUtil.bind(bubbleContainer[0])!!
        initView()
        setArrowWidth(XPopupUtils.dp2px(context,40F))
        setArrowHeight(XPopupUtils.dp2px(context,40F))
        setArrowRadius(XPopupUtils.dp2px(context,20F))
        setBubbleBgColor(Color.WHITE)
        setBubbleShadowColor(Color.parseColor("#333CAFA3"))
    }



    fun showT(
        atView: View,
        isDismissOnTouchOutside: Boolean = true,
        isDismissOnBackPressed: Boolean = true,
        moveUpToKeyboard: Boolean = true
    ) {
        XPopup.Builder(context)
                .hasStatusBar(false)
                .hasShadowBg(false)
                .dismissOnTouchOutside(isDismissOnTouchOutside)
                .dismissOnBackPressed(isDismissOnBackPressed)
                .popupWidth(DisplayUtil.getScreenWidth(context))
                .maxWidth(DisplayUtil.getScreenWidth(context))
                .offsetX((DisplayUtil.getScreenWidth(context) * 0.08).toInt())
                .moveUpToKeyboard(moveUpToKeyboard)
                .atView(atView)
                .asCustom(this)
                .show()
    }

}

**Comment by li-xiaojun** [comment]
@Elex92 把initPopupContent的代码移到onCrate中试试
