### ISSUE TITLE
在某些设备上输入弹窗布局出现异常

### ISSUE THREAD

**Issue by liujson** [li-xiaojun/XPopup#968]
**XPopup版本**
2.8.0

**手机系统和型号**
rk3399 
Android 7.1.2
Physical size: 1920x1080
Physical density: 160

**描述你的问题**
布局错乱
![image](https://user-images.githubusercontent.com/35724447/170820925-e4b764eb-24b0-47cc-8767-ee76baad2743.png)

**Comment by li-xiaojun** [comment]
更新到2.8.3，应该好了
