### ISSUE TITLE
执行关闭动画，view高度不正确

### ISSUE THREAD

**Issue by limuyang2** [li-xiaojun/XPopup#97]
对于`PartShadowPopupView`下拉菜单类型的弹窗。当弹窗里的view布局发生变化时，例如（显示了一个view，高度增加），关闭时的动画滑动范围就不正常了。
`TranslateAnimator`中，应该在`animateDismiss`关闭方法中，重新获取下view的高度

**Comment by li-xiaojun** [comment]
@limuyang2
我抽空修复这个问题

**Comment by li-xiaojun** [comment]
@limuyang2 
更新到1.6.5，问题已修复。
