### ISSUE TITLE
BottomPopupView   isThreeDrag无效，底部弹出先向上滑，触发滑动事件逻辑，无法立即向下滑动

### ISSUE THREAD

**Issue by Dirtyshushu** [li-xiaojun/XPopup#970]
**XPopup版本**
如2.8.2

**手机系统和型号**
华为Mate20 Android 10

isThreeDrag无效不知道是不是这个功能一直没有支持
看代码是SmartDragLayout的state更新异常，导致触摸事件直接返回了
向下滑动异常大概也是post的runnable更新状态异常

**Comment by Fomovet** [comment]
+1

**Comment by li-xiaojun** [comment]
更新到最新版本
