### ISSUE TITLE
-BubbleAttachPopupView空指针问题

### ISSUE THREAD

**Issue by billdizl** [li-xiaojun/XPopup#975]
**XPopup版本**
2.8.2

**手机系统和型号**
设备
品牌：samsung
型号：Galaxy J2
屏幕方向： 纵向
可用 RAM： 275.52 MB
可用磁盘空间： 428.72 MB

**描述你的问题**
问题一:
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'boolean com.lxj.xpopup.core.PopupInfo.isCenterHorizontal' on a null object reference
       at com.lxj.xpopup.core.BubbleAttachPopupView$3.run(BubbleAttachPopupView.java:208)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6816)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1565)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1453)

问题二:
Fatal Exception: java.lang.NullPointerException
Attempt to read from field 'android.graphics.PointF com.lxj.xpopup.core.PopupInfo.touchPoint' on a null object reference
com.lxj.xpopup.core.BubbleAttachPopupView.doAttach (BubbleAttachPopupView.java:82)

代码如下:XPopup.Builder(mContext) //                        .isCenterHorizontal(true)
                    .isDestroyOnDismiss(true) //对于只使用一次的弹窗，推荐设置这个
                    .atView(mView)
                    .isViewMode(true)
                    .hasShadowBg(false) // 去掉半透明背景
                    .offsetX(XPopupUtils.dp2px(mContext, offsetX))
                    .offsetY(XPopupUtils.dp2px(mContext, offsetY))
                    .asCustom(
                        ViewBubbleTipPhotoAttachPopup(
                            mContext,
                            tipText, tipTitle
                        ) //                                .setArrowOffset(-XPopupUtils.dp2px(getContext(), 40))  //气泡箭头偏移
                            //                                .setBubbleBgColor(Color.RED)  //气泡背景
                            .setArrowWidth(XPopupUtils.dp2px(mContext, 5f))
                            .setArrowHeight(
                                XPopupUtils.dp2px(
                                    mContext,
                                    6f
                                )
                            ) //                                .setBubbleRadius(100)
                            .setArrowRadius(XPopupUtils.dp2px(mContext, 3f))
                    )
                    .show()

**Comment by li-xiaojun** [comment]
@HouQiang0903 @billdizl 更新到2.8.4即可
