### ISSUE TITLE
XPopupUtils 可以优化下吗?

### ISSUE THREAD

**Issue by luoxiong94** [li-xiaojun/XPopup#976]
**XPopup版本**
如2.8.3

**手机系统和型号**
华为Mate20 Android 10

**描述你的问题**
XPopupUtils 类的moveUpToKeyboardInternal方法中,  能把 pv instanceof CenterPopupView  改成 pv  instanceof A接口吗?
让 CenterPopupView  实现A 接口,  这样我们自定义的CenterView也能支持走到这个方法, 如果自定义的pw 不走moveUpToKeyboardInternal方法, 输入框移动不上去,

**Comment by li-xiaojun** [comment]
你自定义的centerView继承 CenterPopupView即可；难不成你是继承BasePopupView自己搞的？

**Comment by luoxiong94** [comment]
是的, 我是继承 BasePopupView 来实现的, 把 CenterPopupView 里面的代码拿出来了, 因为我们布局是基于databinding写的, 想封装下, 减少布局层次.
