### ISSUE TITLE
XPopup.Builder.hasStatusBar属性并且其为false状态栏有一瞬间的隐藏动画

### ISSUE THREAD

**Issue by extfff** [li-xiaojun/XPopup#977]
**XPopup版本**
2.8.3

Andorid版本：10

**描述你的问题**
1、配置主工程代码AppTheme，添加属性<item name="android:windowFullscreen">true</item>
2、观察未设置isViewMode(true)的dialog并且设置了hasStatusBar(false)的表现，

结果：
通知栏会有一个隐藏动作而不是一直不存在通知栏

**Comment by li-xiaojun** [comment]
试试最新版本

**Comment by liangrk** [comment]
最新版本实测不行, 真机p30, 雷电模拟器也可以复现
上方代码clone代码尝试, 晚点试试行不行

> 试试最新版本
