### ISSUE TITLE
自定义Popup初始化后，使用自己写的setData，执行却会在Oncreate之后

### ISSUE THREAD

**Issue by midfisher2** [li-xiaojun/XPopup#978]
**XPopup版本**
2.6.6

**手机系统和型号**
OPPO手机 Android 9

**描述你的问题**
![image](https://user-images.githubusercontent.com/94035285/173995456-8cfcafa5-630b-4a68-9f00-32a74d1a474d.png)
自定义popup，在Oncreate回调内进行控件初始化及相关集合初始化
调用代码时如下
![image](https://user-images.githubusercontent.com/94035285/173995675-ce33c65d-42f7-43b9-8ced-1191a01a7584.png)
setdata会在Oncreate之前执行，这是为什么，另外为啥自己初始化popup的时候不会回调oncreate
![image](https://user-images.githubusercontent.com/94035285/173995761-cb40a157-0aeb-4721-ac10-72f472348c8c.png)

**Comment by li-xiaojun** [comment]
@midfisher2 更新到最新版本
