### ISSUE TITLE
使用dialog模式下的弹框,弹框向下偏移了

### ISSUE THREAD

**Issue by jackma11** [li-xiaojun/XPopup#979]
**XPopup版本**
如2.8.3

**手机系统和型号**
vivo Y93s(V1818CA)   Android 8.1.0

**描述你的问题**
使用dialog模式下的弹框,弹框向下偏移了,使用view模式就是正常的

![image](https://user-images.githubusercontent.com/51396482/174009623-29d1c537-5113-442e-ac9e-ffc0d0fd01c3.png)
![image](https://user-images.githubusercontent.com/51396482/174009663-c79e8579-7081-4a1e-b8d0-f7f760f3174f.png)
![image](https://user-images.githubusercontent.com/51396482/174009681-74082f9b-2def-4169-baa7-6731850fe0d6.png)

**Comment by li-xiaojun** [comment]
@jackma11 试试2.8.2是不是也是这样

**Comment by jackma11** [comment]
![image](https://user-images.githubusercontent.com/51396482/174282803-1d1d60b8-4e59-40e5-af6b-0313d88ad4aa.png)


一样的

**Comment by li-xiaojun** [comment]
@jackma11 只有Attach弹窗这样吗，试试Bottom弹窗会不会下移

**Comment by jackma11** [comment]
https://user-images.githubusercontent.com/51396482/174971992-8ad0a3f6-d48b-45b0-b563-a0fd31322ca7.mp4

**Comment by li-xiaojun** [comment]
@jackma11 方便加qq吗，我没有这个机型，帮忙测试下，我的qq： 16167479

**Comment by jackma11** [comment]
结案！手机型号是V1818CA
![TKK_$O3NG AS{67QSVI}C3W](https://user-images.githubusercontent.com/51396482/175888987-163f2a03-9d5b-4530-a590-4e923f7a7d01.png)
