### ISSUE TITLE
继承了CenterPopupView，没有居中，会偏左，请问是打开方式不正确么

### ISSUE THREAD

**Issue by hope320** [li-xiaojun/XPopup#98]

**Comment by li-xiaojun** [comment]
@hope320 
第一，先确定我的Demo有没有问题，如果没有问题那一般就是你写的有问题。
第二，如果你写的有问题，尽量贴个截图和代码，不要一句话描述现象，因为这些现象一般不会发生，只描述现象我很难定位问题所在。
