### ISSUE TITLE
自定义Bottom类型的弹窗经常出现无法弹出全部布局的问题

### ISSUE THREAD

**Issue by RiceRichhonour** [li-xiaojun/XPopup#982]
**XPopup版本**
如2.7.6

**手机系统和型号**
测试手机均可重现，比如华为mate30pro  oppo reno5pro+

**描述你的问题**

自定义Bottom类型的弹窗经常出现无法弹出全部布局。

只弹出部分的弹窗。

![0557B5A045FDFEE2AC1F303FB11D9EB9](https://user-images.githubusercontent.com/26269539/174751607-224a0ec4-cfb6-4ff8-abb2-bc11dee9a133.jpg)

代码和布局如下：

如果外层布局写死高度，此问题不会重现

`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
      xmlns:android="http://schemas.android.com/apk/res/android"
      android:orientation="vertical"
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      android:background="@color/color_primary"
      >

    <RelativeLayout
        android:layout_marginTop="30dp"
        android:paddingBottom="15dp"
        android:layout_marginLeft="46dp"
        android:layout_marginRight="46dp"
        android:background="@drawable/bg_coins_good_buy"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <ImageView
            android:id="@+id/iv_good"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_centerInParent="true"
            android:layout_margin="45dp"
            android:padding="1dp"
            android:src="@drawable/flower" />

    </RelativeLayout>

    <TextView
        android:id="@+id/tv_good_name"
        android:layout_marginTop="20dp"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:gravity="center"
        android:text="鲜花"
        android:textSize="15sp"
        android:textColor="@color/coin_text_color" />

    <RelativeLayout
        android:id="@+id/device_layout"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center"
        android:layout_marginTop="20dp">

        <ImageView
            android:id="@+id/iv_coins"
            android:layout_width="16dp"
            android:layout_height="16dp"
            android:layout_marginLeft="10dp"
            android:layout_marginTop="4dp"
            android:layout_toRightOf="@+id/tv_comment"
            android:src="@drawable/my_total_coin" />

        <TextView
            android:id="@+id/tv_good_price"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginLeft="4dp"
            android:layout_toRightOf="@+id/iv_coins"
            android:text="100"
            android:textColor="@color/color_primary_day_orange2"
            android:textSize="16sp" />

    </RelativeLayout>

    <RelativeLayout
        android:layout_marginTop="20dp"
        android:background="@drawable/shape_good_buy"
        android:layout_gravity="center"
        android:layout_width="92dp"
        android:layout_height="24dp">

        <TextView
            android:id="@+id/reduce_num"
            android:text="-"
            android:padding="2dp"
            android:textSize="15sp"
            android:layout_marginLeft="5dp"
            android:textColor="@color/normal_text_color"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"/>

        <View
            android:id="@+id/divider"
            android:layout_width="1dp"
            android:layout_height="match_parent"
            android:layout_marginLeft="23dp"
            android:background="@color/normal_text_gray_color" />

        <TextView
            android:id="@+id/tv_num"
            android:text="1"
            android:layout_centerInParent="true"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"/>

        <TextView
            android:text="+"
            android:id="@+id/add_num"
            android:textSize="15sp"
            android:padding="2dp"
            android:layout_alignParentRight="true"
            android:layout_marginRight="5dp"
            android:textColor="@color/normal_text_color"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"/>
        <View
            android:layout_height="match_parent"
            android:layout_width="1dp"
            android:layout_marginRight="23dp"
            android:layout_alignParentRight="true"
            android:background="@color/normal_text_gray_color"/>

    </RelativeLayout>

    <TextView
        android:id="@+id/tv_good_detail"
        android:layout_marginTop="20dp"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:gravity="center"
        android:text="送给你欣赏的他/她吧！"
        android:textSize="13sp"
        android:textColor="@color/normal_text_gray_color" />

    <TextView
        android:layout_marginTop="20dp"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:gravity="center"
        android:text="购买即同意《快科技商城用户协议》"
        android:textSize="10sp"
        android:textColor="@color/comment_smalltextcolor" />

     <RelativeLayout
         android:layout_marginTop="20dp"
         android:paddingBottom="30dp"
         android:layout_width="match_parent"
         android:layout_height="wrap_content">

         <TextView
             android:id="@+id/bt_cancle"
             android:gravity="center"
             android:layout_width="wrap_content"
             android:layout_height="42dp"
             android:layout_marginLeft="22dp"
             android:background="@drawable/button_cancle_buy"
             android:paddingLeft="40dp"
             android:paddingRight="40dp"
             android:text="取消购买"
             android:textColor="@color/coins_cancle_text_color" />

         <TextView
             android:id="@+id/bt_buy"
             android:layout_width="wrap_content"
             android:layout_height="42dp"
             android:gravity="center"
             android:layout_alignParentRight="true"
             android:layout_marginLeft="22dp"
             android:layout_marginRight="22dp"
             android:background="@drawable/button_buy"
             android:paddingLeft="40dp"
             android:paddingRight="40dp"
             android:text="确定购买"
             android:textColor="@color/my_coins_white_text_color" />

     </RelativeLayout>

</LinearLayout>`

      XPopup.Builder(this@ActivityCoinsMain)
                            .hasShadowBg(true)
                            .isLightStatusBar(false)
                            .asCustom(CustomPopup(this@ActivityCoinsMain,pList,p2))
                            .show()

**Comment by RiceRichhonour** [comment]
非必现，但是出现几率很高

**Comment by li-xiaojun** [comment]
@RiceRichhonour 试试demo在你手机上有这个问题不
