### ISSUE TITLE
优化问题

### ISSUE THREAD

**Issue by jiming-mao** [li-xiaojun/XPopup#983]
**XPopup版本**
2.8.4

**手机系统和型号**
所有手机

**描述你的问题**
能否把BottomPopupView与PartShadowPopupView中的contentView设置成成员变量给子类调用，这样就可以在子类中使用ViewDataBinding，十分感谢

**Comment by li-xiaojun** [comment]
@jiming-mao WIKI中有写如何使用databinding：
```
//DataBinding 在 onCreate 调用
binding = DataBindingUtil.bind(getPopupImplView());

//ViewBinding
binding = XXXBinding.bind(getPopupImplView());
```

**Comment by jiming-mao** [comment]
谢谢回复

**Comment by yzgt** [comment]
按照这个写法报错了啊, 资源找不到
