### ISSUE TITLE
LoadingPopupView不显示加载中信息

### ISSUE THREAD

**Issue by cjcj125125** [li-xiaojun/XPopup#984]
**XPopup版本**
2.8.5

**手机系统和型号**
OPPO K5 Android 11

**描述你的问题**
再最新版demo中使用内置LoadingPopupView，先创建后show()不会出现提示文字，如下图所示：
![微信截图_20220623162222](https://user-images.githubusercontent.com/20206579/175253075-56afed1c-ad5c-4641-a9b0-45f1d3bc96a5.png)
![微信图片_20220623162551](https://user-images.githubusercontent.com/20206579/175253104-d9bf048d-7810-46a9-b9fd-c9a4ac4182ae.jpg)

**Comment by li-xiaojun** [comment]
@cjcj125125 更新到2.8.6即可
