### ISSUE TITLE
偶尔会爆空指针

### ISSUE THREAD

**Issue by CCTV-11** [li-xiaojun/XPopup#985]
**XPopup版本**
2.2.23

**手机系统和型号**
华为Mate20 Android 10

**描述你的问题**

[#1002 java.lang.NullPointerException](https://bugly.qq.com/v2/crash-reporting/crashes/824d03d2f7/1002?pid=1)
Attempt to read from field 'boolean com.lxj.xpopup.core.PopupInfo.enableShowWhenAppBackground' on a null object reference
com.lxj.xpopup.core.FullScreenDialog.onCreate(FullScreenDialog.java:32)

**Comment by li-xiaojun** [comment]
@CCTV-11 更新版本
