### ISSUE TITLE
底部弹窗如何让软键盘跟随EditText

### ISSUE THREAD

**Issue by 858902548** [li-xiaojun/XPopup#986]
**XPopup版本**
2.8.4

**手机系统和型号**
OPPO K9   android 12

**描述你的问题**
自定义底部弹窗BottomPopupView中有多个EditText,如何让软键盘弹出的时候，既不遮盖弹窗，也不会把弹窗顶上去，而是跟随EditText

**Comment by li-xiaojun** [comment]
@858902548 禁用弹窗的上移，然后自己做滚动

**Comment by 858902548** [comment]
使用全屏弹窗可以了
