### ISSUE TITLE
自定义xpop

### ISSUE THREAD

**Issue by jasonSuzhow** [li-xiaojun/XPopup#99]
![image](https://user-images.githubusercontent.com/13963143/55319093-c18c1c00-54a6-11e9-93e3-8c92e8bd6152.png)
我想实现图中效果, 应该怎么改啊

**Comment by li-xiaojun** [comment]
@jasonSuzhow 
继承AttachPopupView自定义个弹窗，这些布局和图片需要你自己写。

**Comment by jasonSuzhow** [comment]
> @jasonSuzhow
> 继承AttachPopupView自定义个弹窗，这些布局和图片需要你自己写。

好的, 老哥 稳

**Comment by jasonSuzhow** [comment]
> 需要

![image](https://user-images.githubusercontent.com/13963143/55373672-80444c80-5538-11e9-8fd1-420f15a49cbf.png)
请问一下, 我这个该在哪里设置啊

**Comment by li-xiaojun** [comment]
你自定义弹窗了，逻辑和数据都在你自定义的弹窗中写。你可以在自己的弹窗中放一个RecyclerView去实现。

**Comment by jasonSuzhow** [comment]
那这个不是必须的把
![image](https://user-images.githubusercontent.com/13963143/55374586-8daf0600-553b-11e9-9c72-1f9ec15c6015.png)

**Comment by li-xiaojun** [comment]
@jasonSuzhow 
这个不是用写，只需正常写你的布局即可，就像写Activity的布局一样。

**Comment by jasonSuzhow** [comment]
> @jasonSuzhow
> 这个不是用写，只需正常写你的布局即可，就像写Activity的布局一样。

好的, 谢谢 已解决
