### ISSUE TITLE
从2.8.8版本开始，ImageViewerPopupView界面中按返回键无法返回。

### ISSUE THREAD

**Issue by po1xiao** [li-xiaojun/XPopup#990]
**XPopup版本**
2.8.8

**手机系统和型号**
荣耀50 Android 12/华为p30 pro 鸿蒙2.0

**描述你的问题**
从2.8.8版本开始，ImageViewerPopupView界面中按返回键无法返回。如果想要退出，只能杀死重进。

**Comment by li-xiaojun** [comment]
@po1xiao 更新到2.8.11即可
