### ISSUE TITLE
返回键拦截失效

### ISSUE THREAD

**Issue by qiushui95** [li-xiaojun/XPopup#991]
**XPopup版本**
最新版本

**手机系统和型号**
所有

**描述你的问题**
https://github.com/li-xiaojun/XPopup/blob/b4dae7663cc1efcdf5b43ee9cefb74ae01d0f0b5/app/src/main/java/com/lxj/xpopupdemo/fragment/QuickStartDemo.java#L295
新插入一行使用ViewMode会使返回键拦截失效
isViewMode(true)

**Comment by li-xiaojun** [comment]
什么机型，我这边复现不了

**Comment by qiushui95** [comment]
雷电模拟器

**Comment by li-xiaojun** [comment]
模拟器就算了，用真机
