### ISSUE TITLE
Caused by java.lang.NullPointerException

### ISSUE THREAD

**Issue by billdizl** [li-xiaojun/XPopup#993]
**XPopup版本**
2.8.11

**手机系统和型号**
设备
品牌：HUAWEI
型号：JNY-LX1
屏幕方向： 纵向
可用 RAM： 3.12 GB
可用磁盘空间： 12.28 GB
操作系统
版本：Android 10
屏幕方向： 纵向
是否已取得 root 权限：否
崩溃
日期：2022年7月7日 09:13:01
应用版本：3.13.62 (445)

**描述你的问题**
Fatal Exception: java.lang.RuntimeException
Unable to destroy activity {xxxx.xxxx.view.activity.CurrencyChangeActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Handler.removeCallbacks(java.lang.Runnable)' on a null object reference
Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'void android.os.Handler.removeCallbacks(java.lang.Runnable)' on a null object reference
com.lxj.xpopup.core.BasePopupView.dismiss (BasePopupView.java:605)
com.chiquedoll.chiquedoll.view.activity.BaseActivity.onDestroy (BaseActivity.java:278)
com.chiquedoll.chiquedoll.view.activity.RxActivity.onDestroy (RxActivity.java:84)
android.app.Activity.performDestroy (Activity.java:8478)
android.app.Instrumentation.callActivityOnDestroy (Instrumentation.java:1355)
android.app.ActivityThread.performDestroyActivity (ActivityThread.java:5863)
android.app.ActivityThread.handleDestroyActivity (ActivityThread.java:5908)
android.app.servertransaction.DestroyActivityItem.execute (DestroyActivityItem.java:44)

代码如下:
这个是BaseActivity中的 每个activity都继承自BaseActivity 

    @Override
    protected void onDestroy() {
        super.onDestroy();
        if (loadingPopupView != null) {
          loadingPopupView.dismiss();
           loadingPopupView = null;
       }
    }

**Comment by li-xiaojun** [comment]
把 loadingPopupView = null; 去掉

**Comment by billdizl** [comment]
无效,      if (fullDiscountBottomDialog == null) {
            fullDiscountBottomDialog = XPopup.Builder(this@ProductActivity)
                .customHostLifecycle(lifecycle)
                .dismissOnTouchOutside(true)
                .isViewMode(true) //开启View实现
                .isDestroyOnDismiss(false)
                .asCustom(AllDiscountBootomDialog(this@ProductActivity))
        }
        fullDiscountBottomDialog?.show()

在ondestory的时候调用 if(fullDiscountBottomDialog!=null){
fullDiscountBottomDialog?.dissmiss()}  这样子也是崩溃的

**Comment by li-xiaojun** [comment]
onDestroy无需调用dismiss，自动会dismiss

**Comment by billdizl** [comment]
其实按照onDestroy中 if (loadingPopupView != null) {
      loadingPopupView.dismiss();
       loadingPopupView = null;
   }加上loadingPopupView = null;也没问题的,主要是因为你在   implementation 'com.github.li-xiaojun:XPopup:2.8.10'版本的时候处理了  然后就导致我这种写法崩溃,if (loadingPopupView != null) {
      loadingPopupView.dismiss();
       loadingPopupView = null;
    这种写法难道不规范吗?  我看好多其他控件这种写法也是没问题的

**Comment by jin123d** [comment]
同样发现 ` handler.removeCallbacksAndMessages(null);`，onDetachedFromWindow多次被调用。

在

` public void onDestroy() {
        onDetachedFromWindow();
        detachFromHost();
        destroy();
    }`
中会先调用一次`onDetachedFromWindow`，然后再destroy中` if(dialog.isShowing()) dialog.dismiss();`中又会触发一次`onDetachedFromWindow`，第二次触发时`handler`已经为null

**Comment by li-xiaojun** [comment]
@jin123d @billdizl 更新到2.8.12即可
