### ISSUE TITLE
软键盘交互问题

### ISSUE THREAD

**Issue by jiming-mao** [li-xiaojun/XPopup#994]
**XPopup版本**
2.8.6之后的所有版本

**手机系统和型号**
红米Note 7 Pro

**描述你的问题**
在demo中点击测试输入框不关闭软键盘后不管弹出什么弹框就会出现关闭之前的弹框显示一个新的软键盘出来

**Comment by jin123d** [comment]
我这边的问题不知道和你这个是不是一个现象。
--------------------------------------
如果界面有个Edittext输入法也是打开的。
此时show弹窗后就出现 弹窗跑到输入法上方（正常应该是输入法关闭）。

`com.lxj.xpopup.core.FullScreenDialog#onWindowFocusChanged`方法中会把键盘弹出来。

https://github.com/li-xiaojun/XPopup/blob/a6ce44908de7123e30143b40dc72b494bcc76f45/library/src/main/java/com/lxj/xpopup/core/FullScreenDialog.java#L201-L208

**Comment by jiming-mao** [comment]
是这样的，如果调用弹框之前关闭软键盘就不会弹出了

**Comment by li-xiaojun** [comment]
@jiming-mao 我复现不出来，如果可以的话。录个视频发到群里，或者加我qq：16167479 我帮你看看

**Comment by jiming-mao** [comment]
只要提前关闭当前的输入框弹出的软键盘就不会出现，不关闭当前输入框的软键盘，就会出现这样的现象，我现在处理的就是把当前软键盘关闭就没问题了
![image](https://user-images.githubusercontent.com/30363027/178398196-9ff2ce28-3173-4b8e-ac3d-35f31e137dee.png)
ji就是这行代码导致的

**Comment by li-xiaojun** [comment]
@jin123d @jiming-mao 更新到2.8.13试试

**Comment by jiming-mao** [comment]
完美解决，十分感谢
