### ISSUE TITLE
ImageViewerPopupView无法加载bmp格式图片

### ISSUE THREAD

**Issue by Yangqingchun** [li-xiaojun/XPopup#995]
**XPopup版本**
2.8.11

**手机系统和型号**
Android 12

**描述你的问题**
打开bmp格式图片时，加载不出来

报错日志如下
![EGL UN6H8VL@CQ}$(S_(VKD](https://user-images.githubusercontent.com/33993115/178139956-693be5da-58d9-4f14-a99d-0c1978dd6f25.jpg)

**Comment by li-xiaojun** [comment]
不是我的锅，只能用new SmartGlideImageLoader(true) , 传false的话走的是`[subsampling-scale-image-view](https://github.com/davemorrissey/subsampling-scale-image-view)`他本身不支持
