### ISSUE TITLE
弹窗里面嵌入视频播放器，全屏时候显示不正确

### ISSUE THREAD

**Issue by guozhiqiang123** [li-xiaojun/XPopup#997]
**XPopup版本**
2.8.12

**手机系统和型号**
华为Mate20 Android 10

**描述你的问题**
最![截图_选择区域_20220712192327](https://user-images.githubusercontent.com/20378988/178478992-c824dbad-5044-48f6-8f20-9e4bfed6eecc.png)
全屏后：
![截图_选择区域_20220712193014](https://user-images.githubusercontent.com/20378988/178480160-680fc899-d064-4fd2-9d4a-fff445691129.png)

**Comment by li-xiaojun** [comment]
你全屏那一层是dialog还是activity？或者试试isViewMode(true)
