### ISSUE TITLE
屏中屏的时候弹窗的时候会弹出键盘问题

### ISSUE THREAD

**Issue by huimieni** [li-xiaojun/XPopup#998]
**XPopup版本**
如2.8.12

**手机系统和型号**
华为Mate40 pro 鸿蒙os2

**描述你的问题**
屏中屏的时候弹窗的时候会弹出键盘，全屏的时候没问题，加了isrequestfocus false不会弹出但是返回也监听不到了

**Comment by li-xiaojun** [comment]
@huimieni 更新到2.8.13即可
